INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(CHEMICALSET_SYMBOLS_DIR) \
	$(CHEMICALSET_TAGS_DIR) \
#	$(CHEMICALSET_MARKS_DIR) \
#	$(CHEMICALSET_DATABASES_DIR) \
#	$(CHEMICALSET_INTERFACES_DIR) \
 