INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(UNITS_DIR) \
	$(MEASURE_DIR) \
	$(READEE_DIR) \
	$(CONTEXTSET_DIR) \
	$(COORDINATESET_SYMBOLS_DIR) \
	$(COORDINATESET_TAGS_DIR) \
	$(COORDINATESET_ENVELOPES_DIR) \
	$(PARAMETERSET_ENVELOPES_DIR) \
	$(PARAMETERSET_SYMBOLS_DIR) \
	$(PARAMETERSET_TAGS_DIR) \
 