LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(UNITS_DIR) \
	$(MEASURE_DIR) \
	$(READEE_DIR) \
	$(QUANTUM_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_LEXER_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_COOSER_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(COORDINATESET_SYMBOLS_DIR) \
	$(COORDINATESET_TAGS_DIR) \
	$(COORDINATESET_BUILDER_TREES_DIR) \
	$(COORDINATESET_CONTAINERS_DIR) \
	$(COORDINATESET_VALUES_DIR) \
	$(SKELETONSET_SYMBOLS_DIR) \
	$(SKELETONSET_TAGS_DIR) \
	$(SKELETONSET_BUILDER_TREES_DIR) \
	$(SKELETONSET_CONTAINERS_DIR) \
	$(SKELETONSET_VALUES_DIR) \
 