INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(DATABASESET_COMMON_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1FIGURESET_LEXER_DIR) \
	$(DB1FIGURESET_SYMBOLS_DIR) \
	$(DB1FIGURESET_PARSER_DIR) \
	$(DB1FIGURESET_TAGS_DIR) \
	$(DB1FIGURESET_BUILDER_TREES_DIR) \
	$(ELEMENTARYSET_SYMBOLS_DIR) \
	$(ELEMENTARYSET_TAGS_DIR) \
	$(ELEMENTARYSET_DATABASES_DIR) \
	$(FIGURESET_SYMBOLS_DIR) \
	$(FIGURESET_TAGS_DIR) \
 