FILES_GENERAL_ML := \
Database_filename_by_category_trail_provider_u_naturalset.ml \
Database_record_list_by_category_trail_provider_u_naturalset_symbol.ml \
Word_word_string_triplet_list_by_category_trail_provider_u_naturalset_symbol.ml \
Word_word_string_triplet_list_by_domain_trail_provider_u_naturalset.ml \
Entity_basename_kind_basename_righthandside_string_triplet_list_by_category_trail_provider_u_naturalset_symbol.ml \
Entity_basename_lefthandside_list_by_category_trail_provider_u_naturalset_symbol.ml \
Entity_basename_righthandside_list_by_category_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_lefthandside_list_by_category_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_kind_basename_righthandside_string_triplet_list_by_category_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_righthandside_string_doublet_list_by_category_trail_provider_u_naturalset_symbol.ml \
Constructor_root_basename_by_domain_trail_provider_u_naturalset.ml \
# Constructor_basename_lefthandside_string_doublet_list_by_category_trail_provider_u_naturalset_symbol.ml \
# Constructor_basename_righthandside_string_doublet_list_by_category_trail_provider_u_naturalset_symbol.ml \
  
FILES_GENERAL_FORMULA_ML := \
Database_record_list_by_category_trail_provider_u_naturalset_formula.ml \
Word_word_string_triplet_list_by_category_trail_provider_u_naturalset_formula.ml \
Constructor_basename_righthandside_string_doublet_list_by_category_trail_provider_u_naturalset_formula.ml \
Constructor_basename_lefthandside_string_doublet_list_by_category_trail_provider_u_naturalset_formula.ml \

FILES_GENERAL_FORMULA_LIST_ML := \
Entity_basename_kind_basename_righthandside_string_triplet_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Entity_basename_lefthandside_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Entity_basename_righthandside_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Constructor_basename_lefthandside_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Constructor_basename_kind_basename_righthandside_string_triplet_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Constructor_basename_righthandside_string_doublet_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Database_record_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Word_word_string_triplet_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Constructor_basename_righthandside_string_doublet_list_by_category_trail_provider_u_naturalset_formula_list.ml \
Constructor_basename_lefthandside_string_doublet_list_by_category_trail_provider_u_naturalset_formula_list.ml \
 
FILES_CONSTRUCTOR_NOTLEAF_ML := \
Constructor_notleaf_basename_list_by_domain_trail_provider_u_naturalset.ml \
Constructor_notleaf_basename_righthandside_string_doublet_list_by_domain_trail_provider_u_naturalset.ml \
Righthandside_string_by_constructor_notleaf_trail_provider_u_naturalset.ml \
Constructor_basename_list_by_constructor_notleaf_trail_provider_u_naturalset.ml \
 
FILES_CONSTRUCTOR_NODE_ML := \
Constructor_node_basename_list_by_domain_trail_provider_u_naturalset.ml \
# Constructor_node_basename_righthandside_string_doublet_list_by_domain_trail_provider_u_naturalset.ml
# Kind_name_constructor_node_basename_doublet_list_by_domain_trail_provider_u_naturalset.ml \
# Kind_name_by_constructor_node_trail_provider_u_naturalset.ml \
# Constructor_node_basename_list_by_domain_trail_provider_u_naturalset.ml \
# Builder_basename_list_by_domain_trail_provider_u_naturalset.ml \
 
FILES_CONSTRUCTOR_LEAF_ML := \
Constructor_leaf_basename_datastructure_basename_doublet_list_by_domain_trail_provider_u_naturalset_list.ml \
Constructor_leaf_basename_kind_basename_righthandside_string_triplet_list_by_domain_trail_provider_u_naturalset.ml \
Constructor_leaf_basename_list_by_domain_trail_provider_u_naturalset.ml \
Constructor_leaf_basename_righthandside_string_doublet_list_by_domain_trail_provider_u_naturalset.ml \
Righthandside_string_by_constructor_leaf_trail_provider_u_naturalset_list.ml \

FILES_DATASTRUCTURE_ML := \
Datastructure_basename_by_constructor_leaf_trail_provider_u_naturalset_list.ml \
 
FILES_CONSTRUCTOR_SYMBOL_ML := \
Righthandside_string_list_by_category_trail_provider_u_naturalset_symbol.ml \
Righthandside_string_by_constructor_notleaf_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_list_by_constructor_notleaf_trail_provider_u_naturalset.ml \
Constructor_basename_list_by_constructor_notleaf_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_list_by_constructor_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_list_by_domain_trail_provider_u_naturalset_symbol.ml \
Constructor_basename_list_by_domain_trail_provider_u_naturalset.ml \

FILES_KIND_ML := \
Kind_basename_list_by_category_trail_provider_u_naturalset.ml \
Kind_name_by_constructor_notleaf_trail_provider_u_naturalset.ml \

FILES_BUILDER_ML := \
Constructor_leaf_basename_righthandside_string_doublet_list_by_domain_trail_provider_u_naturalset.ml \
Constructor_leaf_basename_list_by_domain_trail_provider_u_naturalset.ml \
Constructor_leaf_basename_datastructure_basename_doublet_list_by_domain_trail_provider_u_naturalset.ml \
Builder_root_basename_list_by_domain_trail_provider_u_naturalset.ml \
# Kind_basename_constructor_leaf_basename_doublet_list_by_domain_trail_provider_u_naturalset.ml \
# Kind_basename_by_constructor_leaf_trail_provider_u_naturalset.ml \

FILES_BUILDER_FORMULA_ML := \
Righthandside_string_list_by_category_trail_provider_u_naturalset_formula.ml \
Righthandside_string_by_constructor_leaf_trail_provider_u_naturalset_formula.ml \
Datastructure_basename_by_constructor_leaf_trail_provider_u_naturalset_formula.ml \
Datastructure_basename_builder_basename_list_doublet_by_constructor_leaf_trail_provider_u_naturalset_formula.ml \
Builder_basename_list_by_constructor_leaf_trail_provider_u_naturalset_formula.ml \

FILES_BUILDER_LIST_ML := \
Entity_basic_basename_list_by_domain_trail_provider_u_naturalset_list.ml \
Builder_basename_list_by_constructor_leaf_trail_provider_u_naturalset_list.ml \
Builder_root_basename_list_by_domain_trail_provider_u_naturalset_list.ml \
Datastructure_basename_builder_basename_list_doublet_by_constructor_leaf_trail_provider_u_naturalset_list.ml \
# Righthandside_string_list_by_category_trail_provider_u_naturalset_formula_list.ml \
# Righthandside_string_by_constructor_leaf_trail_provider_u_naturalset_formula_list.ml \
# Datastructure_basename_by_constructor_leaf_trail_provider_u_naturalset_formula_list.ml \
# Datastructure_basename_builder_basename_list_doublet_by_constructor_leaf_trail_provider_u_naturalset_formula_list.ml \
# Builder_basename_list_by_constructor_leaf_trail_provider_u_naturalset_formula_list.ml \

FILES_CONSTRUCTOR_TREE_ML := \
Constructor_basename_tree_by_domain_trail_provider_u_naturalset.ml \
 
UNITARY_TESTS_FILES_NATURALSET_ML := \
$(FILES_CONSTRUCTOR_TREE_ML) \
# $(FILES_GENERAL_ML) \
# $(FILES_BUILDER_LIST_ML) \
# $(FILES_CONSTRUCTOR_NODE_ML) \
# $(FILES_CONSTRUCTOR_NOTLEAF_ML) \
# $(FILES_CONSTRUCTOR_LEAF_ML) \
# $(FILES_DATASTRUCTURE_ML) \
# $(FILES_BUILDER_ML) \
# $(FILES_BUILDER_LIST_ML) \
# $(FILES_CONSTRUCTOR_SYMBOL_ML) \
# $(FILES_KIND_ML) \
# $(FILES_BUILDER_FORMULA_ML) \
# $(FILES_GENERAL_SYMBOL_ML) \
# $(FILES_GENERAL_FORMULA_LIST_ML) \
# $(FILES_GENERAL_FORMULA_ML) \



 
