LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
        $(GENERATORSET_SYMBOLS_DIR) \
        $(GENERATORSET_DATABASES_DIR) \
        $(GENERATORSET_DATABASES_ADB_DIR) \
        $(GENERATORSET_INTERFACES_DIR) \
        $(GENERATORSET_TAGS_DIR) \
        $(GENERATORSET_FORMULAS_DIR) \
	$(realpath ..) \
    