#!/bin/bash

ledit -x -h ./.toplevel-history ocaml \
-I $BAS \
-I $FIL \
-I $DAT \
-I $COMS \
-I $CONS \
-I $DGTR/adb \
-I $SGTR \
-I $TGTR \
-I $IGTR \
-I $FGTR \
-I ../ \
unix.cma str.cma \
$BAS/basics.cma \
$FIL/files.cma \
$DAT/datastructures.cma \
$COMS/commonset.cma \
$CONS/contextset.cma \
$DGTR/adb/adb.cma \
$SGTR/generatorset_symbols.cma \
$TGTR/generatorset_tags.cma \
$IGTR/generatorset_interfaces.cma \
$FGTR/generatorset_formulas.cma \
$VGTR/generatorset_values.cma \
 

