NATURALSET_SYMBOL_ML := \
Camlline_value_u_naturalset_symbol_naturalset_upgrading.ml \
Camlline_value_u_naturalset_symbol_triangle_abbreviating.ml \
Camlline_value_u_naturalset_symbol_triangle_typing.ml \
Camlline_value_u_naturalset_symbol_vector_upgrading.ml \
Camlparagraph_endmarked_type_value_u_naturalset_symbol_triangle_isoceles_typing.ml \
Item_value_u_naturalset_symbol_naturalset_abbreviating.ml \
Item_value_u_naturalset_symbol_naturalset_upgrading.ml \
Item_value_u_naturalset_symbol_naturalset_making.ml \
Item_value_u_naturalset_symbol_triangle_isoceles_abbreviating.ml \
Item_value_u_naturalset_symbol_triangle_isoceles_naming.ml \
Item_value_u_naturalset_symbol_triangle_isoceles_typing.ml \
Item_value_u_naturalset_symbol_triangle_isoceles_upgrading.ml \
Item_value_u_naturalset_symbol_triangle_typing.ml \
Item_value_u_naturalset_symbol_triangle_upgrading.ml \
Usagefile_value_u_naturalset_symbol_naturalset_type_alone.ml \
Usagefile_value_u_naturalset_symbol_naturalset_value_alone.ml \
Usagefile_value_u_naturalset_symbol_triangle_isoceles_type_alone.ml \
Usagefile_value_u_naturalset_symbol_triangle_isoceles_value_alone.ml \
Usagefile_value_u_naturalset_symbol_triangle_type_alone.ml \

NATURALSET_FORMULA_ML := \
Usagefile_value_u_naturalset_formula_mp3_elementary_stream_value_alone.ml \
Usagefile_value_u_naturalset_formula_metadata_id3_value_alone.ml \
Usagefile_value_u_naturalset_formula_mp3_layout_tag_value_alone.ml \
# Camlline_value_u_naturalset_formula_naturalset_typing.ml \
# Camlline_value_u_naturalset_formula_triangle_typing.ml \
#  \
# Item_value_u_naturalset_symbol_triangle_isoceles_making.ml \
# camlline_datastructure_camltype_value_u_naturalset_symbol_triangle_isoceles_typing.ml \
 
DO_NATURALSET_SYMBOL_ML := \
Do_naturalset_symbols_files_mli_mk.ml \
Do_naturalset_symbols_tv.ml \

DO_NATURALSET_TAG_ML := \
Do_naturalset_tags_files_mli_mk.ml \
Do_naturalset_tags_tv.ml \
 
DO_NATURALSET_FORMULA_ML := \
Do_naturalset_formulas_files_mli_mk.ml \
Do_naturalset_formulas_tv.ml \

FILES_INACTIVE := \

UNITARY_TESTS_FILES_NATURALSET_ML := \
$(DO_NATURALSET_SYMBOL_ML) \
$(DO_NATURALSET_FORMULA_ML) \
# $(DO_NATURALSET_TAG_ML) \
# $(NATURALSET_SYMBOL_ML) \
