NWCHEM_LEXER_T_MLI :=  \
  Nwchemdata_parser_variable_symbol_t.mli \
  Nwchemdata_parser_symbol_symbol_t.mli \
  Nwchemdata_parser_keyword_symbol_t.mli \
  Nwchemdata_parser_hashline_symbol_t.mli \
    Nwchemdata_parser_basic_word_uppercase_symbol_t.mli \
     Nwchemdata_parser_basic_word_numeric_positive_symbol_t.mli \
     Nwchemdata_parser_basic_word_numeric_negative_symbol_t.mli \
    Nwchemdata_parser_basic_word_numeric_symbol_t.mli \
    Nwchemdata_parser_basic_word_lowercase_symbol_t.mli \
    Nwchemdata_parser_basic_word_capitalized_symbol_t.mli \
    Nwchemdata_parser_basic_word_anycase_symbol_t.mli \
   Nwchemdata_parser_basic_word_symbol_t.mli \
     Nwchemdata_parser_basic_character_mark_singled_symbol_t.mli \
     Nwchemdata_parser_basic_character_mark_coupled_symbol_t.mli \
    Nwchemdata_parser_basic_character_mark_symbol_t.mli \
    Nwchemdata_parser_basic_character_alphabetic_symbol_t.mli \
   Nwchemdata_parser_basic_character_symbol_t.mli \
  Nwchemdata_parser_basic_symbol_t.mli \
 Nwchemdata_parser_symbol_t.mli \
