type elementary_border_parameter_aopef_coefficient_belt = (Elementary_border_parameter_aopef_coefficient_tag_t.elementary_border_parameter_aopef_coefficient_tag, Measure_actual_length_t.measure_actual_length) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_parameter_aopef_coefficient measure_actual_length *)
(* using ./template_belt_as_doublet_border_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:04 (UTC+0200) *)

