(** {3 Elementary_context_envelope_v} *)

(** {6 Documenting_for_envelope} *)

let documentation () = 
  [
   "Current : VELE:Elementary_context_envelope_v";
   "Needs : VELE:Envelopee_v";
   "Needs : VELE:Elementary_border_envelope_v";
   "Needs : FELE:Elementary_context_container_v";
   "Needed-by: ";
   "What-is-it : it is the Envelope for Elementary_context";
   "How-is-it-done: ";
]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Border_as_list from Database} *)

let border_as_list_of_tag tag_eco =
  Elementary_context_container_v.border_as_list tag_eco
;;
  
let border_of_tag tag_eco =
  border_as_list_of_tag tag_eco
;;

(** {6 Envelope as Envelopee list} *)

let envelope_of_tag tag_eco =
  let bor_l = border_as_list_of_tag tag_eco in
  List_v.map
    Elementary_border_envelope_v.envelopee_of_tag
    bor_l
;;

(** {6 Readee} *)

let readee_list_of_tag tag_eco =
  let env = envelope_of_tag tag_eco in
  List.map Envelopee_v.readee_off_envelopee env
;;

(** {6 Measure_actual} *)

let measure_actual_list_of_tag tag_eco =
  let rea = readee_list_of_tag tag_eco in
  List.map Readee_v.measure_actual_off_readee rea
;;

(** {6 Float} *)

let float_list_of_tag tag_eco  =
  let mea_l = measure_actual_list_of_tag tag_eco in
  List.map Measure_actual_v.float_off_measure_actual mea_l
;;

(** {6 Units} *)

let elementary_fence_units_actual_symbol_list_of_tag tag_eco =
  let mea_l = measure_actual_list_of_tag tag_eco in
  List.map Measure_actual_v.elementary_fence_units_actual_symbol_off_measure_actual mea_l 
;;

(** {6 Text} *)
(*
let text_of_tag tag_eco =
  let bor_l = border_as_list_of_tag tag_eco in
  List_v.name Elementary_border_envelope_v.text_of_tag bor_l
;;
*)
(** {6 Naming} *)

let name env_eco =
  List_v.name Elementary_border_envelope_v.name env_eco
;;

let longname env_eco =
  List_v.name Elementary_border_envelope_v.longname env_eco
;;

(* generated by ./do_envelope_as_list_context_bud_measure_units_float_v.sh elementary_context eco *)
(* using ./template_envelope_as_list_context_bud_measure_units_float_v.ml *)
(* Done on mardi 24 mai 2016, 17:35:59 (UTC+0200) *)

