(** {3 Elementary_fence_units_actual_none_belt_v} *)

(** {6 Documenting_for_belt} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_units_actual_none_belt_v";
   "Needs : DELE:Measure_actual_by_elementary_fence_units_actual_tag_provider_v";
   "Needs : DELE:Measure_canonical_by_elementary_fence_units_actual_tag_provider_v";
   "Needed-by: ";
   "What-is-it : it is its own Tag coupled with a Measure_none)";
   "How-is-it-done: ";
]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Extraction from Database : Measure} *)

let measure_actual_of_tag tag_ean =
  let tag_ean = Tag_v.map_entity
      Elementary_fence_units_actual_symbol_v.elementary_fence_units_actual_symbol_of_elementary_fence_units_actual_none_symbol
      tag_ean
  in
  Measure_actual_by_elementary_fence_units_actual_tag_provider_v.provide 
    tag_ean 
;;

let measure_actual_none_of_tag tag_ean =
  let mea_act = measure_actual_of_tag tag_ean in
  Measure_actual_none_v.measure_actual_none_off_measure_actual mea_act
;;

let measure_canonical_of_tag_of_calculation_name tag_ean nam_cal =
  let mea_act = measure_actual_of_tag tag_ean in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal
;;

(** {6 Belt} *)

let belt_of_tag tag_ean =
  let mle = measure_actual_none_of_tag tag_ean in
  Doublet_v.make tag_ean mle
;;

(** {6 Extracting Measure off Belt} *)

let measure_actual_none_off_belt bel_ean =
  Doublet_v.right_off_doublet bel_ean
;;

let measure_actual_off_belt bel_ean =
  let mea_ano = measure_actual_none_off_belt bel_ean in
  Measure_actual_none_v.measure_actual_of_measure_actual_none mea_ano
;;

let measure_actual_list_off_belt bel_ean =
  let mea_act = measure_actual_off_belt bel_ean in
  [mea_act]
;;

let measure_canonical_off_belt_of_calculation_name bel_ean nam_cal =
  let mea_act = measure_actual_off_belt bel_ean in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal 
;;

let measure_canonical_list_off_belt_of_calculation_name bel_ean nam_cal =
  let mea_can = measure_canonical_off_belt_of_calculation_name bel_ean nam_cal in
  [mea_can]
;;

(** {6 Readee : a Generalization of Measure} *)

let readee_off_belt bel_ean =
  let mea_act = measure_actual_off_belt bel_ean in
  Readee_v.readee_of_measure_actual mea_act
;;

let readee_of_tag tag_ean =
  let bel_ean = belt_of_tag tag_ean in
  readee_off_belt bel_ean 
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_ean =
  let rea = readee_off_belt bel_ean in
  [rea]
;;

let closure_of_tag tag_ean =
  let bel_ean = belt_of_tag tag_ean in
  closure_off_belt bel_ean
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_ean =
  let plu_ean = readee_of_tag tag_ean in
  Doublet_v.make tag_ean plu_ean
;;

(** {6 Float} *)

let float_of_tag tag_ean  =
  let mno = measure_actual_none_of_tag tag_ean in
  Measure_actual_none_v.float_off_measure_actual_none mno 
;;

(** {6 Units} *)

let elementary_fence_units_actual_none_tag_of_tag tag_ean =
  let mno = measure_actual_none_of_tag tag_ean in
  Measure_actual_none_v.elementary_fence_units_actual_none_symbol_off_measure_actual_none mno
;;

(** {6 Text} *)

let text_of_tag tag_ean =
  let (flo, sym_ean) = measure_actual_none_of_tag tag_ean in
  Format.sprintf "none %f %s" flo ( Elementary_fence_units_actual_none_symbol_v.name sym_ean)
;;

(** {6 Naming} *)

let name bel_ean =
  Doublet_v.name Elementary_fence_units_actual_none_tag_v.name Measure_actual_none_v.name bel_ean
;;

let string_off bel_ean =
  Doublet_v.name Elementary_fence_units_actual_none_tag_v.string_off Measure_actual_none_v.string_off bel_ean
;;

let longname bel_ean =
  Doublet_v.name Elementary_fence_units_actual_none_tag_v.longname Measure_actual_none_v.longname bel_ean
;;

let fullname bel_ean =
  Doublet_v.name Elementary_fence_units_actual_none_tag_v.fullname Measure_actual_none_v.fullname bel_ean
;;


(* generated by ./do_belt_as_doublet_fence_units_actual_branch_1sibling_2beltee_v.sh elementary_fence_units_actual none ean unitless mno *)
(* using ./template_belt_as_doublet_fence_units_actual_branch_1sibling_2beltee_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:06 (UTC+0200) *)

