(** {3 Elementary_border_parameter_aopef_exponent_belt_v} *)

(** {6 Documenting_for_belt} *)

let documentation () = 
  [
   "Current : VELE:Elementary_border_parameter_aopef_exponent_belt_v";
   "Needs : TELE:Thup_tag_v";
   "Needs : VELE:Elementary_border_parameter_aopef_exponent_container_v";
   "Needed-by: ";
   "What-is-it : it is a belt of a Bud Type as a Doublet of its own Tag and a Measure";
   "Remark : no Bridge in Elementary Domain";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Coercing Up Tag} *)

let coerce_up_tag tag_eae =
  Tag_v.map_entity 
    Elementary_border_symbol_v.elementary_border_symbol_of_elementary_border_parameter_aopef_exponent_symbol 
    tag_eae
;;

(** {6 Border as list of itself} *)

let border_of_tag tag_eae =
  [coerce_up_tag tag_eae]
;;

(** {6 Extraction from Database : Measure_actual} *)

let measure_actual_length_of_tag tag_eae =
  let tag_fal = 
    Elementary_border_parameter_aopef_exponent_container_v.container_of_tag 
      tag_eae
  in
  Elementary_fence_units_actual_length_belt_v.measure_actual_length_of_tag tag_fal
;;

(** {6 Measure_actual} *)

let measure_actual_of_tag tag_eae =
  let msr = measure_actual_length_of_tag tag_eae in
  Measure_actual_length_v.measure_actual_of_measure_actual_length msr
;;

let measure_canonical_of_tag_of_calculation_name tag_eae nam_cal =
  let mea = measure_actual_of_tag tag_eae in
  Measure_actual_v.measure_canonical_of_measure_actual_of_calculation_name mea nam_cal
;;

(** {6 Belt} *)

let belt_of_tag tag_eae =
  let msr = measure_actual_length_of_tag tag_eae in
  Doublet_v.make tag_eae msr
;;

(** {6 Extracting Measure_actual off Belt} *)

let measure_actual_length_off_belt bel_eae =
  Doublet_v.right_off_doublet bel_eae
;;

let measure_actual_off_belt bel_eae =
  let msr = measure_actual_length_off_belt bel_eae in
  Measure_actual_length_v.measure_actual_of_measure_actual_length msr
;;

let measure_actual_list_off_belt bel_eae =
  let mea = measure_actual_off_belt bel_eae in
  [mea]
;;

let measure_canonical_off_belt_of_calculation_name bel_eae nam_cal =
  let mea = measure_actual_off_belt bel_eae in
  Measure_actual_v.measure_canonical_of_measure_actual_of_calculation_name mea nam_cal
;;

let measure_canonical_list_off_belt_of_calculation_name bel_eae nam_cal =
  let can_mea = measure_canonical_off_belt_of_calculation_name bel_eae nam_cal in
  [can_mea]
;;

(** {6 Readee : a Generalization of Measure_actual} *)

let readee_off_belt bel_eae =
  let mea = measure_actual_off_belt bel_eae in
  Readee_v.readee_of_measure_actual mea
;;

let readee_of_tag tag_eae =
  let bel_eae = belt_of_tag tag_eae in
  readee_off_belt bel_eae 
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_eae =
  let rea = readee_off_belt bel_eae in
  [rea]
;;

let closure_of_tag tag_eae =
  let bel_eae = belt_of_tag tag_eae in
  closure_off_belt bel_eae
;;

(** {6 Float} *)

let float_of_tag tag_eae  =
  let mle = measure_actual_length_of_tag tag_eae in
  Measure_actual_length_v.float_off_measure_actual_length mle 
;;

(** {6 Elementary_fence_units_actual} *)

let elementary_fence_units_actual_tag_of_tag tag_eae =
  let mle = measure_actual_length_of_tag tag_eae in
  Measure_actual_length_v.elementary_fence_units_actual_length_symbol_off_measure_actual_length mle
;;

(** {6 Text} *)

let text_of_tag tag_eae =
  let (flo, sym_eae) = measure_actual_length_of_tag tag_eae in
  Format.sprintf "length %f %s" flo ( Elementary_fence_units_actual_length_symbol_v.name sym_eae)
;;

(** {6 Naming_for_belt} *)

let name bel_eae =
  Doublet_v.name 
    Elementary_border_parameter_aopef_exponent_tag_v.name
    Measure_actual_length_v.name
    bel_eae
;;

let longname bel_eae =
  Format.sprintf "Elementary_border_parameter_aopef_exponent_belt_t.%s" (String.capitalize (name bel_eae))
;;


(* generated by ./do_belt_as_doublet_border_bud_1sibling_1units_2beltee_v.sh elementary_border_parameter_aopef epa exponent eae elementary_fence_units_actual efa length fal mle *)
(* using ./template_belt_as_doublet_border_bud_1sibling_1units_2beltee_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:11 (UTC+0200) *)

