(** {3 Elementary_fence_units_canonical_classical_belt_v} *)

(** {6 Documenting_for_belt} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_units_canonical_classical_belt_v";
   "Needs : DELE:Measure_by_elementary_fence_units_canonical_tag_provider_v";
   "Needed-by: ";
   "What-is-it : it is its own Tag coupled with a Measure_canonical_classical)";
   "How-is-it-done: ";
]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Extraction from Database : Measure} *)

let measure_canonical_of_tag tag_ecc =
  let tag_euc = Tag_v.map_entity
      Elementary_fence_units_canonical_symbol_v.elementary_fence_units_canonical_symbol_of_elementary_fence_units_canonical_classical_symbol
      tag_ecc
  in
  Measure_canonical_by_elementary_fence_units_canonical_tag_provider_v.provide 
    tag_euc
;;

let measure_canonical_classical_of_tag tag_ecq =
  let mea_can = measure_canonical_of_tag tag_ecq in
  Measure_canonical_classical_v.measure_canonical_classical_off_measure_canonical mea_can
;;

let measure_actual_of_tag tag_ecc =
  let mea_can = measure_canonical_of_tag tag_ecc in
  Measure_actual_v.measure_actual_of_measure_canonical mea_can
;;

(** {6 Belt} *)

let belt_of_tag tag_ecc =
  let mle = measure_canonical_classical_of_tag tag_ecc in
  Doublet_v.make tag_ecc mle
;;

(** {6 Extracting Measure_actual off Belt} *)

let measure_canonical_classical_off_belt bel_ecc =
  Doublet_v.right_off_doublet bel_ecc
;;

let measure_canonical_off_belt bel_ecc =
  let mea_len = measure_canonical_classical_off_belt bel_ecc in
  Measure_canonical_classical_v.measure_canonical_of_measure_canonical_classical mea_len
;;

let measure_canonical_list_off_belt bel_ecc =
  let mea = measure_canonical_off_belt bel_ecc in
  [mea]
;;

let measure_actual_off_belt bel_ecc =
  let mea_can = measure_canonical_off_belt bel_ecc in
  Measure_actual_v.measure_actual_of_measure_canonical mea_can
;;

let measure_actual_off_belt bel_ecc =
  let mea_can = measure_canonical_off_belt bel_ecc in
  Measure_actual_v.measure_actual_of_measure_canonical mea_can
;;

let measure_actual_list_off_belt_of_calculation_name bel_ecc nam_cal =
  let mea = measure_actual_off_belt bel_ecc in
  [mea]
;;

(** {6 Readee : a Generalization of Measure_actual} *)

let readee_off_belt bel_ecc =
  let mea_act = measure_actual_off_belt bel_ecc in
  Readee_v.readee_of_measure_actual mea_act
;;

let readee_of_tag tag_ecc =
  let bel_ecc = belt_of_tag tag_ecc in
  readee_off_belt bel_ecc 
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_ecc =
  let rea = readee_off_belt bel_ecc in
  [rea]
;;

let closure_of_tag tag_ecc =
  let bel_ecc = belt_of_tag tag_ecc in
  closure_off_belt bel_ecc
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_ecc =
  let plu_ecc = readee_of_tag tag_ecc in
  Doublet_v.make tag_ecc plu_ecc
;;

(** {6 Float} *)

let float_of_tag tag_ecc  =
  let mcc = measure_canonical_classical_of_tag tag_ecc in
  Measure_canonical_classical_v.float_off_measure_canonical_classical mcc 
;;

(** {6 Units} *)

let elementary_fence_units_canonical_classical_tag_of_tag tag_ecc =
  let mcc = measure_canonical_classical_of_tag tag_ecc in
  Measure_canonical_classical_v.elementary_fence_units_canonical_classical_symbol_off_measure_canonical_classical mcc
;;

(** {6 Text} *)

let text_of_tag tag_ecc =
  let (flo, sym_ecc) = measure_canonical_classical_of_tag tag_ecc in
  Format.sprintf "classical %f %s" flo ( Elementary_fence_units_canonical_classical_symbol_v.name sym_ecc)
;;

(** {6 Naming} *)

let name bel_ecc =
  Doublet_v.name Elementary_fence_units_canonical_classical_tag_v.name Measure_canonical_classical_v.name bel_ecc
;;

let string_off bel_ecc =
  Doublet_v.name Elementary_fence_units_canonical_classical_tag_v.string_off Measure_canonical_classical_v.string_off bel_ecc
;;

let longname bel_ecc =
  Doublet_v.name Elementary_fence_units_canonical_classical_tag_v.longname Measure_canonical_classical_v.longname bel_ecc
;;

let fullname bel_ecc =
  Doublet_v.name Elementary_fence_units_canonical_classical_tag_v.fullname Measure_canonical_classical_v.fullname bel_ecc
;;




(* generated by ./do_belt_as_doublet_fence_units_canonical_branch_9sibling_2beltee_v.sh elementary_fence_units_canonical classical ecc canonical_classical_action_kilocalorie_second canonical_classical_angle_radian canonical_classical_charge_coulomb canonical_classical_energy_kilocalorie canonical_classical_length_angstrom canonical_classical_mass_electron_mass canonical_classical_temperature_kelvin canonical_classical_time_femtosecond canonical_classical_none mcc *)
(* using ./template_belt_as_doublet_fence_units_canonical_branch_9sibling_2beltee_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:06 (UTC+0200) *)

