type elementary_body_parameter_tuple_aopef_envelope = Envelopee_t.envelopee list;;

(* generated by ./do_envelope_as_list_t.sh elementary_body_parameter_tuple_aopef *)
(* using ./template_envelope_as_list_t.ml *)
(* Done on lundi 14 mars 2016, 10:18:20 (UTC+0100) *)

