(** {3 Elementary_fence_basic_integer_belt_v} *)

(** {6 Documenting} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_basic_integer_belt_v";
   "What-is-it : it is a Tag coupled with a Readee_basic_integer";
   "Remark: it is analogous to Elementary_fence_units_actual_action_belt_v";
   "Remark: where fence_units_action is replaced by fence_basic_integer";
   "Remark: where measure_action (readee_units) is replaced by readee_basic_integer";
 ]
;;

(** {6 Naming} *)

let name bel_ebi =
  Doublet_v.name Elementary_fence_basic_integer_tag_v.name Readee_basic_integer_v.name bel_ebi
;;

let string_off bel_ebi =
  Doublet_v.name Elementary_fence_basic_integer_tag_v.string_off Readee_basic_integer_v.string_off bel_ebi
;;

let longname bel_ebi =
  Doublet_v.name Elementary_fence_basic_integer_tag_v.longname Readee_basic_integer_v.longname bel_ebi
;;

let fullname bel_ebi =
  Doublet_v.name Elementary_fence_basic_integer_tag_v.fullname Readee_basic_integer_v.fullname bel_ebi
;;

(** {6 Extraction from Database : Readee_basic_integer} *)

let readee_of_tag tag_ebi =
  let tag_efe = Tag_v.map_entity
      Elementary_fence_symbol_v.elementary_fence_symbol_of_elementary_fence_basic_integer_symbol
      tag_ebi
  in
  Readee_by_elementary_fence_tag_provider_v.provide 
    tag_efe
;;

let readee_basic_integer_of_tag tag_ebi =
  let rea = readee_of_tag tag_ebi in
  Readee_v.readee_basic_integer_off_readee rea
;;

(** {6 Tagged_measure Triplet} *)

let belt_of_tag tag_ebi =
  let pbs = readee_basic_integer_of_tag tag_ebi in
  Doublet_v.make tag_ebi pbs
;;

let tagged_readee_basic_integer_doublet_of_tag tag_ebi =
  let pbs = readee_basic_integer_of_tag tag_ebi in
  Doublet_v.make tag_ebi pbs
;;

(** {6 Extracting Readee off Belt} *)

let readee_basic_integer_off_belt bel_ebi =
  Doublet_v.right_off_doublet bel_ebi
;;

let readee_basic_off_belt bel_ebi =
  let pbs = readee_basic_integer_off_belt bel_ebi in
  Readee_basic_v.readee_basic_of_readee_basic_integer pbs
;;

let readee_off_belt bel_ebi =
  let pba = readee_basic_off_belt bel_ebi in
  Readee_v.readee_of_readee_basic pba
;;

let readee_list_off_belt bel_ebi =
  let rea = readee_off_belt bel_ebi in
  [rea]
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_ebi =
  let rea = readee_off_belt bel_ebi in
  [rea]
;;

let closure_of_tag tag_ebi =
  let bel_ebi = belt_of_tag tag_ebi in
  closure_off_belt bel_ebi
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_ebi =
  let plu_ebi = readee_of_tag tag_ebi in
  Doublet_v.make tag_ebi plu_ebi
;;

(** {6 String} *)

let string_of_tag tag_ebi  =
  let pbs = readee_basic_integer_of_tag tag_ebi in
  Readee_basic_integer_v.string_off pbs 
;;

(** {6 Integer} *)

let integer_of_tag tag_ebi  =
  let pbs = readee_basic_integer_of_tag tag_ebi in
  Readee_basic_integer_v.integer_off pbs 
;;

(** {6 Basic} *)

let elementary_fence_basic_integer_symbol_of_tag tag_ebi =
  Tag_v.entity_off_tag tag_ebi
;;

let elementary_fence_basic_integer_symbol_off_belt bel_ebi =
  let tag_ebi = Doublet_v.left_off_doublet bel_ebi in
  elementary_fence_basic_integer_symbol_of_tag tag_ebi
;;

(** {6 Text} *)

let text_of_tag tag_ebi =
  let str = string_of_tag tag_ebi in
  Format.sprintf "integer %s" str
;;

(* generated by ./do_belt_as_doublet_fence_basic_stalk_v.sh elementary_fence_basic integer *)
(* using ./template_belt_as_doublet_fence_basic_stalk_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:07 (UTC+0200) *)
