type elementary_fence_units_actual_length_belt = (Elementary_fence_units_actual_length_tag_t.elementary_fence_units_actual_length_tag, Measure_actual_length_t.measure_actual_length) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_length measure_actual_length *)
(* using ./template_belt_as_doublet_fence_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:02 (UTC+0200) *)

