type elementary_fence_basic_integer_belt = (Elementary_fence_basic_integer_tag_t.elementary_fence_basic_integer_tag, Readee_basic_integer_t.readee_basic_integer) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_integer readee_basic_integer *)
(* using ./template_belt_as_doublet_fence_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:02 (UTC+0200) *)

