type elementary_border_parameter_aopef_envelope = Envelopee_t.envelopee list;;

(* generated by ./do_envelope_as_list_t.sh elementary_border_parameter_aopef *)
(* using ./template_envelope_as_list_t.ml *)
(* Done on lundi 14 mars 2016, 10:18:18 (UTC+0100) *)

