type elementary_context_domain_envelope = Envelopee_t.envelopee list;;

(* generated by ./do_envelope_as_list_t.sh elementary_context_domain *)
(* using ./template_envelope_as_list_t.ml *)
(* Done on lundi 14 mars 2016, 10:18:20 (UTC+0100) *)

