type elementary_fence_units_canonical_classical_belt = (Elementary_fence_units_canonical_classical_tag_t.elementary_fence_units_canonical_classical_tag, Measure_canonical_classical_t.measure_canonical_classical) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_canonical_classical measure_canonical_classical *)
(* using ./template_belt_as_doublet_fence_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:02 (UTC+0200) *)

