type elementary_border_coordinate_heterogeneous_polar_rho_envelope = Envelopee_t.envelopee list;;

(* generated by ./do_envelope_as_list_t.sh elementary_border_coordinate_heterogeneous_polar_rho *)
(* using ./template_envelope_as_list_t.ml *)
(* Done on lundi 14 mars 2016, 10:18:19 (UTC+0100) *)

