(** {3 Elementary_fence_basic_belt_t} *)


(** {6 Typing_for_belt} *)

type elementary_fence_basic_belt =
  | Elementary_fence_basic_boolean_belt of Elementary_fence_basic_boolean_belt_t.elementary_fence_basic_boolean_belt
  | Elementary_fence_basic_float_belt of Elementary_fence_basic_float_belt_t.elementary_fence_basic_float_belt
  | Elementary_fence_basic_integer_belt of Elementary_fence_basic_integer_belt_t.elementary_fence_basic_integer_belt
  | Elementary_fence_basic_string_belt of Elementary_fence_basic_string_belt_t.elementary_fence_basic_string_belt
;;


(** Elementary_fence_basic_belt_t at 11:53:10 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_belt_from_symbol_this_t.sh elementary_fence_basic *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_fence_basic_symbol_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:02 (UTC+0200) *)
