(** {3 Elementary_fence_units_actual_charge_belt_v} *)

(** {6 Documenting_for_belt} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_units_actual_charge_belt_v";
   "Needs : DELE:Measure_actual_by_elementary_fence_units_actual_tag_provider_v";
   "Needs : DELE:Measure_canonical_by_elementary_fence_units_actual_tag_provider_v";
   "Needed-by: ";
   "What-is-it : it is its own Tag coupled with a Measure_charge)";
   "How-is-it-done: ";
]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Extraction from Database : Measure} *)

let measure_actual_of_tag tag_eac =
  let tag_eac = Tag_v.map_entity
      Elementary_fence_units_actual_symbol_v.elementary_fence_units_actual_symbol_of_elementary_fence_units_actual_charge_symbol
      tag_eac
  in
  Measure_actual_by_elementary_fence_units_actual_tag_provider_v.provide 
    tag_eac 
;;

let measure_actual_charge_of_tag tag_eac =
  let mea_act = measure_actual_of_tag tag_eac in
  Measure_actual_charge_v.measure_actual_charge_off_measure_actual mea_act
;;

let measure_canonical_of_tag_of_calculation_name tag_eac nam_cal =
  let mea_act = measure_actual_of_tag tag_eac in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal
;;

(** {6 Belt} *)

let belt_of_tag tag_eac =
  let mle = measure_actual_charge_of_tag tag_eac in
  Doublet_v.make tag_eac mle
;;

(** {6 Extracting Measure off Belt} *)

let measure_actual_charge_off_belt bel_eac =
  Doublet_v.right_off_doublet bel_eac
;;

let measure_actual_off_belt bel_eac =
  let mea_ano = measure_actual_charge_off_belt bel_eac in
  Measure_actual_charge_v.measure_actual_of_measure_actual_charge mea_ano
;;

let measure_actual_list_off_belt bel_eac =
  let mea_act = measure_actual_off_belt bel_eac in
  [mea_act]
;;

let measure_canonical_off_belt_of_calculation_name bel_eac nam_cal =
  let mea_act = measure_actual_off_belt bel_eac in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal 
;;

let measure_canonical_list_off_belt_of_calculation_name bel_eac nam_cal =
  let mea_can = measure_canonical_off_belt_of_calculation_name bel_eac nam_cal in
  [mea_can]
;;

(** {6 Readee : a Generalization of Measure} *)

let readee_off_belt bel_eac =
  let mea_act = measure_actual_off_belt bel_eac in
  Readee_v.readee_of_measure_actual mea_act
;;

let readee_of_tag tag_eac =
  let bel_eac = belt_of_tag tag_eac in
  readee_off_belt bel_eac 
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_eac =
  let rea = readee_off_belt bel_eac in
  [rea]
;;

let closure_of_tag tag_eac =
  let bel_eac = belt_of_tag tag_eac in
  closure_off_belt bel_eac
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_eac =
  let plu_eac = readee_of_tag tag_eac in
  Doublet_v.make tag_eac plu_eac
;;

(** {6 Float} *)

let float_of_tag tag_eac  =
  let mno = measure_actual_charge_of_tag tag_eac in
  Measure_actual_charge_v.float_off_measure_actual_charge mno 
;;

(** {6 Units} *)

let elementary_fence_units_actual_charge_tag_of_tag tag_eac =
  let mno = measure_actual_charge_of_tag tag_eac in
  Measure_actual_charge_v.elementary_fence_units_actual_charge_symbol_off_measure_actual_charge mno
;;

(** {6 Text} *)

let text_of_tag tag_eac =
  let (flo, sym_eac) = measure_actual_charge_of_tag tag_eac in
  Format.sprintf "charge %f %s" flo ( Elementary_fence_units_actual_charge_symbol_v.name sym_eac)
;;

(** {6 Naming} *)

let name bel_eac =
  Doublet_v.name Elementary_fence_units_actual_charge_tag_v.name Measure_actual_charge_v.name bel_eac
;;

let string_off bel_eac =
  Doublet_v.name Elementary_fence_units_actual_charge_tag_v.string_off Measure_actual_charge_v.string_off bel_eac
;;

let longname bel_eac =
  Doublet_v.name Elementary_fence_units_actual_charge_tag_v.longname Measure_actual_charge_v.longname bel_eac
;;

let fullname bel_eac =
  Doublet_v.name Elementary_fence_units_actual_charge_tag_v.fullname Measure_actual_charge_v.fullname bel_eac
;;


(* generated by ./do_belt_as_doublet_fence_units_actual_branch_2sibling_2beltee_v.sh elementary_fence_units_actual charge eac coulomb electron_charge mch *)
(* using ./template_belt_as_doublet_fence_units_actual_branch_2sibling_2beltee_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:05 (UTC+0200) *)

