(** {3 Elementary_fence_basic_boolean_belt_v} *)

(** {6 Documenting} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_basic_boolean_belt_v";
   "What-is-it : it is a Tag coupled with a Readee_basic_boolean";
   "Remark: it is analogous to Elementary_fence_units_actual_action_belt_v";
   "Remark: where fence_units_action is replaced by fence_basic_boolean";
   "Remark: where measure_action (readee_units) is replaced by readee_basic_boolean";
 ]
;;

(** {6 Naming} *)

let name bel_ebb =
  Doublet_v.name Elementary_fence_basic_boolean_tag_v.name Readee_basic_boolean_v.name bel_ebb
;;

let string_off bel_ebb =
  Doublet_v.name Elementary_fence_basic_boolean_tag_v.string_off Readee_basic_boolean_v.string_off bel_ebb
;;

let longname bel_ebb =
  Doublet_v.name Elementary_fence_basic_boolean_tag_v.longname Readee_basic_boolean_v.longname bel_ebb
;;

let fullname bel_ebb =
  Doublet_v.name Elementary_fence_basic_boolean_tag_v.fullname Readee_basic_boolean_v.fullname bel_ebb
;;

(** {6 Extraction from Database : Readee_basic_boolean} *)

let readee_of_tag tag_ebb =
  let tag_efe = Tag_v.map_entity
      Elementary_fence_symbol_v.elementary_fence_symbol_of_elementary_fence_basic_boolean_symbol
      tag_ebb
  in
  Readee_by_elementary_fence_tag_provider_v.provide 
    tag_efe
;;

let readee_basic_boolean_of_tag tag_ebb =
  let rea = readee_of_tag tag_ebb in
  Readee_v.readee_basic_boolean_off_readee rea
;;

(** {6 Tagged_measure Triplet} *)

let belt_of_tag tag_ebb =
  let pbs = readee_basic_boolean_of_tag tag_ebb in
  Doublet_v.make tag_ebb pbs
;;

let tagged_readee_basic_boolean_doublet_of_tag tag_ebb =
  let pbs = readee_basic_boolean_of_tag tag_ebb in
  Doublet_v.make tag_ebb pbs
;;

(** {6 Extracting Readee off Belt} *)

let readee_basic_boolean_off_belt bel_ebb =
  Doublet_v.right_off_doublet bel_ebb
;;

let readee_basic_off_belt bel_ebb =
  let pbs = readee_basic_boolean_off_belt bel_ebb in
  Readee_basic_v.readee_basic_of_readee_basic_boolean pbs
;;

let readee_off_belt bel_ebb =
  let pba = readee_basic_off_belt bel_ebb in
  Readee_v.readee_of_readee_basic pba
;;

let readee_list_off_belt bel_ebb =
  let rea = readee_off_belt bel_ebb in
  [rea]
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_ebb =
  let rea = readee_off_belt bel_ebb in
  [rea]
;;

let closure_of_tag tag_ebb =
  let bel_ebb = belt_of_tag tag_ebb in
  closure_off_belt bel_ebb
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_ebb =
  let plu_ebb = readee_of_tag tag_ebb in
  Doublet_v.make tag_ebb plu_ebb
;;

(** {6 String} *)

let string_of_tag tag_ebb  =
  let pbs = readee_basic_boolean_of_tag tag_ebb in
  Readee_basic_boolean_v.string_off pbs 
;;

(** {6 Boolean} *)

let boolean_of_tag tag_ebb  =
  let pbs = readee_basic_boolean_of_tag tag_ebb in
  Readee_basic_boolean_v.boolean_off pbs 
;;

(** {6 Basic} *)

let elementary_fence_basic_boolean_symbol_of_tag tag_ebb =
  Tag_v.entity_off_tag tag_ebb
;;

let elementary_fence_basic_boolean_symbol_off_belt bel_ebb =
  let tag_ebb = Doublet_v.left_off_doublet bel_ebb in
  elementary_fence_basic_boolean_symbol_of_tag tag_ebb
;;

(** {6 Text} *)

let text_of_tag tag_ebb =
  let str = string_of_tag tag_ebb in
  Format.sprintf "boolean %s" str
;;

(* generated by ./do_belt_as_doublet_fence_basic_stalk_v.sh elementary_fence_basic boolean *)
(* using ./template_belt_as_doublet_fence_basic_stalk_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:07 (UTC+0200) *)
