type elementary_border_coordinate_heterogeneous_cylindrical_phi_belt = (Elementary_border_coordinate_heterogeneous_cylindrical_phi_tag_t.elementary_border_coordinate_heterogeneous_cylindrical_phi_tag, Measure_actual_angle_t.measure_actual_angle) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_phi measure_actual_angle *)
(* using ./template_belt_as_doublet_border_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:03 (UTC+0200) *)

