(** {3 Elementary_fence_units_actual_length_belt_v} *)

(** {6 Documenting_for_belt} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_units_actual_length_belt_v";
   "Needs : DELE:Measure_actual_by_elementary_fence_units_actual_tag_provider_v";
   "Needs : DELE:Measure_canonical_by_elementary_fence_units_actual_tag_provider_v";
   "Needed-by: ";
   "What-is-it : it is its own Tag coupled with a Measure_length)";
   "How-is-it-done: ";
]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Extraction from Database : Measure} *)

let measure_actual_of_tag tag_eal =
  let tag_eal = Tag_v.map_entity
      Elementary_fence_units_actual_symbol_v.elementary_fence_units_actual_symbol_of_elementary_fence_units_actual_length_symbol
      tag_eal
  in
  Measure_actual_by_elementary_fence_units_actual_tag_provider_v.provide 
    tag_eal 
;;

let measure_actual_length_of_tag tag_eal =
  let mea_act = measure_actual_of_tag tag_eal in
  Measure_actual_length_v.measure_actual_length_off_measure_actual mea_act
;;

let measure_canonical_of_tag_of_calculation_name tag_eal nam_cal =
  let mea_act = measure_actual_of_tag tag_eal in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal
;;

(** {6 Belt} *)

let belt_of_tag tag_eal =
  let mle = measure_actual_length_of_tag tag_eal in
  Doublet_v.make tag_eal mle
;;

(** {6 Extracting Measure off Belt} *)

let measure_actual_length_off_belt bel_eal =
  Doublet_v.right_off_doublet bel_eal
;;

let measure_actual_off_belt bel_eal =
  let mea_ano = measure_actual_length_off_belt bel_eal in
  Measure_actual_length_v.measure_actual_of_measure_actual_length mea_ano
;;

let measure_actual_list_off_belt bel_eal =
  let mea_act = measure_actual_off_belt bel_eal in
  [mea_act]
;;

let measure_canonical_off_belt_of_calculation_name bel_eal nam_cal =
  let mea_act = measure_actual_off_belt bel_eal in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal 
;;

let measure_canonical_list_off_belt_of_calculation_name bel_eal nam_cal =
  let mea_can = measure_canonical_off_belt_of_calculation_name bel_eal nam_cal in
  [mea_can]
;;

(** {6 Readee : a Generalization of Measure} *)

let readee_off_belt bel_eal =
  let mea_act = measure_actual_off_belt bel_eal in
  Readee_v.readee_of_measure_actual mea_act
;;

let readee_of_tag tag_eal =
  let bel_eal = belt_of_tag tag_eal in
  readee_off_belt bel_eal 
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_eal =
  let rea = readee_off_belt bel_eal in
  [rea]
;;

let closure_of_tag tag_eal =
  let bel_eal = belt_of_tag tag_eal in
  closure_off_belt bel_eal
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_eal =
  let plu_eal = readee_of_tag tag_eal in
  Doublet_v.make tag_eal plu_eal
;;

(** {6 Float} *)

let float_of_tag tag_eal  =
  let mno = measure_actual_length_of_tag tag_eal in
  Measure_actual_length_v.float_off_measure_actual_length mno 
;;

(** {6 Units} *)

let elementary_fence_units_actual_length_tag_of_tag tag_eal =
  let mno = measure_actual_length_of_tag tag_eal in
  Measure_actual_length_v.elementary_fence_units_actual_length_symbol_off_measure_actual_length mno
;;

(** {6 Text} *)

let text_of_tag tag_eal =
  let (flo, sym_eal) = measure_actual_length_of_tag tag_eal in
  Format.sprintf "length %f %s" flo ( Elementary_fence_units_actual_length_symbol_v.name sym_eal)
;;

(** {6 Naming} *)

let name bel_eal =
  Doublet_v.name Elementary_fence_units_actual_length_tag_v.name Measure_actual_length_v.name bel_eal
;;

let string_off bel_eal =
  Doublet_v.name Elementary_fence_units_actual_length_tag_v.string_off Measure_actual_length_v.string_off bel_eal
;;

let longname bel_eal =
  Doublet_v.name Elementary_fence_units_actual_length_tag_v.longname Measure_actual_length_v.longname bel_eal
;;

let fullname bel_eal =
  Doublet_v.name Elementary_fence_units_actual_length_tag_v.fullname Measure_actual_length_v.fullname bel_eal
;;


(* generated by ./do_belt_as_doublet_fence_units_actual_branch_13sibling_2beltee_v.sh elementary_fence_units_actual length eal angstrom bohr centimeter decameter decimeter foot inch kilometer light_year meter millimeter nanometer yard mle *)
(* using ./template_belt_as_doublet_fence_units_actual_branch_13sibling_2beltee_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:05 (UTC+0200) *)

