(** {3 Elementary_fence_units_actual_angle_belt_v} *)

(** {6 Documenting_for_belt} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_units_actual_angle_belt_v";
   "Needs : DELE:Measure_actual_by_elementary_fence_units_actual_tag_provider_v";
   "Needs : DELE:Measure_canonical_by_elementary_fence_units_actual_tag_provider_v";
   "Needed-by: ";
   "What-is-it : it is its own Tag coupled with a Measure_angle)";
   "How-is-it-done: ";
]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Extraction from Database : Measure} *)

let measure_actual_of_tag tag_eaa =
  let tag_eaa = Tag_v.map_entity
      Elementary_fence_units_actual_symbol_v.elementary_fence_units_actual_symbol_of_elementary_fence_units_actual_angle_symbol
      tag_eaa
  in
  Measure_actual_by_elementary_fence_units_actual_tag_provider_v.provide 
    tag_eaa 
;;

let measure_actual_angle_of_tag tag_eaa =
  let mea_act = measure_actual_of_tag tag_eaa in
  Measure_actual_angle_v.measure_actual_angle_off_measure_actual mea_act
;;

let measure_canonical_of_tag_of_calculation_name tag_eaa nam_cal =
  let mea_act = measure_actual_of_tag tag_eaa in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal
;;

(** {6 Belt} *)

let belt_of_tag tag_eaa =
  let mle = measure_actual_angle_of_tag tag_eaa in
  Doublet_v.make tag_eaa mle
;;

(** {6 Extracting Measure off Belt} *)

let measure_actual_angle_off_belt bel_eaa =
  Doublet_v.right_off_doublet bel_eaa
;;

let measure_actual_off_belt bel_eaa =
  let mea_ano = measure_actual_angle_off_belt bel_eaa in
  Measure_actual_angle_v.measure_actual_of_measure_actual_angle mea_ano
;;

let measure_actual_list_off_belt bel_eaa =
  let mea_act = measure_actual_off_belt bel_eaa in
  [mea_act]
;;

let measure_canonical_off_belt_of_calculation_name bel_eaa nam_cal =
  let mea_act = measure_actual_off_belt bel_eaa in
  Measure_canonical_v.measure_canonical_of_measure_actual_of_calculation_name mea_act nam_cal 
;;

let measure_canonical_list_off_belt_of_calculation_name bel_eaa nam_cal =
  let mea_can = measure_canonical_off_belt_of_calculation_name bel_eaa nam_cal in
  [mea_can]
;;

(** {6 Readee : a Generalization of Measure} *)

let readee_off_belt bel_eaa =
  let mea_act = measure_actual_off_belt bel_eaa in
  Readee_v.readee_of_measure_actual mea_act
;;

let readee_of_tag tag_eaa =
  let bel_eaa = belt_of_tag tag_eaa in
  readee_off_belt bel_eaa 
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_eaa =
  let rea = readee_off_belt bel_eaa in
  [rea]
;;

let closure_of_tag tag_eaa =
  let bel_eaa = belt_of_tag tag_eaa in
  closure_off_belt bel_eaa
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_eaa =
  let plu_eaa = readee_of_tag tag_eaa in
  Doublet_v.make tag_eaa plu_eaa
;;

(** {6 Float} *)

let float_of_tag tag_eaa  =
  let mno = measure_actual_angle_of_tag tag_eaa in
  Measure_actual_angle_v.float_off_measure_actual_angle mno 
;;

(** {6 Units} *)

let elementary_fence_units_actual_angle_tag_of_tag tag_eaa =
  let mno = measure_actual_angle_of_tag tag_eaa in
  Measure_actual_angle_v.elementary_fence_units_actual_angle_symbol_off_measure_actual_angle mno
;;

(** {6 Text} *)

let text_of_tag tag_eaa =
  let (flo, sym_eaa) = measure_actual_angle_of_tag tag_eaa in
  Format.sprintf "angle %f %s" flo ( Elementary_fence_units_actual_angle_symbol_v.name sym_eaa)
;;

(** {6 Naming} *)

let name bel_eaa =
  Doublet_v.name Elementary_fence_units_actual_angle_tag_v.name Measure_actual_angle_v.name bel_eaa
;;

let string_off bel_eaa =
  Doublet_v.name Elementary_fence_units_actual_angle_tag_v.string_off Measure_actual_angle_v.string_off bel_eaa
;;

let longname bel_eaa =
  Doublet_v.name Elementary_fence_units_actual_angle_tag_v.longname Measure_actual_angle_v.longname bel_eaa
;;

let fullname bel_eaa =
  Doublet_v.name Elementary_fence_units_actual_angle_tag_v.fullname Measure_actual_angle_v.fullname bel_eaa
;;


(* generated by ./do_belt_as_doublet_fence_units_actual_branch_2sibling_2beltee_v.sh elementary_fence_units_actual angle eaa degree radian man *)
(* using ./template_belt_as_doublet_fence_units_actual_branch_2sibling_2beltee_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:05 (UTC+0200) *)

