(** {3 Elementary_fence_units_actual_belt_t} *)


(** {6 Typing_for_belt} *)

type elementary_fence_units_actual_belt =
  | Elementary_fence_units_actual_action_belt of Elementary_fence_units_actual_action_belt_t.elementary_fence_units_actual_action_belt
  | Elementary_fence_units_actual_angle_belt of Elementary_fence_units_actual_angle_belt_t.elementary_fence_units_actual_angle_belt
  | Elementary_fence_units_actual_charge_belt of Elementary_fence_units_actual_charge_belt_t.elementary_fence_units_actual_charge_belt
  | Elementary_fence_units_actual_energy_belt of Elementary_fence_units_actual_energy_belt_t.elementary_fence_units_actual_energy_belt
  | Elementary_fence_units_actual_length_belt of Elementary_fence_units_actual_length_belt_t.elementary_fence_units_actual_length_belt
  | Elementary_fence_units_actual_mass_belt of Elementary_fence_units_actual_mass_belt_t.elementary_fence_units_actual_mass_belt
  | Elementary_fence_units_actual_temperature_belt of Elementary_fence_units_actual_temperature_belt_t.elementary_fence_units_actual_temperature_belt
  | Elementary_fence_units_actual_time_belt of Elementary_fence_units_actual_time_belt_t.elementary_fence_units_actual_time_belt
  | Elementary_fence_units_actual_none_belt of Elementary_fence_units_actual_none_belt_t.elementary_fence_units_actual_none_belt
;;


(** Elementary_fence_units_actual_belt_t at 11:53:17 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_belt_from_symbol_this_t.sh elementary_fence_units_actual *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_fence_units_actual_symbol_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:03 (UTC+0200) *)
