type elementary_fence_basic_string_belt = (Elementary_fence_basic_string_tag_t.elementary_fence_basic_string_tag, Readee_basic_string_t.readee_basic_string) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_string readee_basic_string *)
(* using ./template_belt_as_doublet_fence_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:02 (UTC+0200) *)

