type elementary_fence_basic_boolean_belt = (Elementary_fence_basic_boolean_tag_t.elementary_fence_basic_boolean_tag, Readee_basic_boolean_t.readee_basic_boolean) Doublet_t.doublet;;

(* generated by ./do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_boolean readee_basic_boolean *)
(* using ./template_belt_as_doublet_fence_bud_2beltee_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:01 (UTC+0200) *)

