(** {3 Elementary_fence_basic_string_belt_v} *)

(** {6 Documenting} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_basic_string_belt_v";
   "What-is-it : it is a Tag coupled with a Readee_basic_string";
   "Remark: it is analogous to Elementary_fence_units_actual_action_belt_v";
   "Remark: where fence_units_action is replaced by fence_basic_string";
   "Remark: where measure_action (readee_units) is replaced by readee_basic_string";
 ]
;;

(** {6 Naming} *)

let name bel_ebs =
  Doublet_v.name Elementary_fence_basic_string_tag_v.name Readee_basic_string_v.name bel_ebs
;;

let string_off bel_ebs =
  Doublet_v.name Elementary_fence_basic_string_tag_v.string_off Readee_basic_string_v.string_off bel_ebs
;;

let longname bel_ebs =
  Doublet_v.name Elementary_fence_basic_string_tag_v.longname Readee_basic_string_v.longname bel_ebs
;;

let fullname bel_ebs =
  Doublet_v.name Elementary_fence_basic_string_tag_v.fullname Readee_basic_string_v.fullname bel_ebs
;;

(** {6 Extraction from Database : Readee_basic_string} *)

let readee_of_tag tag_ebs =
  let tag_efe = Tag_v.map_entity
      Elementary_fence_symbol_v.elementary_fence_symbol_of_elementary_fence_basic_string_symbol
      tag_ebs
  in
  Readee_by_elementary_fence_tag_provider_v.provide 
    tag_efe
;;

let readee_basic_string_of_tag tag_ebs =
  let rea = readee_of_tag tag_ebs in
  Readee_v.readee_basic_string_off_readee rea
;;

(** {6 Tagged_measure Triplet} *)

let belt_of_tag tag_ebs =
  let pbs = readee_basic_string_of_tag tag_ebs in
  Doublet_v.make tag_ebs pbs
;;

let tagged_readee_basic_string_doublet_of_tag tag_ebs =
  let pbs = readee_basic_string_of_tag tag_ebs in
  Doublet_v.make tag_ebs pbs
;;

(** {6 Extracting Readee off Belt} *)

let readee_basic_string_off_belt bel_ebs =
  Doublet_v.right_off_doublet bel_ebs
;;

let readee_basic_off_belt bel_ebs =
  let pbs = readee_basic_string_off_belt bel_ebs in
  Readee_basic_v.readee_basic_of_readee_basic_string pbs
;;

let readee_off_belt bel_ebs =
  let pba = readee_basic_off_belt bel_ebs in
  Readee_v.readee_of_readee_basic pba
;;

let readee_list_off_belt bel_ebs =
  let rea = readee_off_belt bel_ebs in
  [rea]
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_ebs =
  let rea = readee_off_belt bel_ebs in
  [rea]
;;

let closure_of_tag tag_ebs =
  let bel_ebs = belt_of_tag tag_ebs in
  closure_off_belt bel_ebs
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_ebs =
  let plu_ebs = readee_of_tag tag_ebs in
  Doublet_v.make tag_ebs plu_ebs
;;

(** {6 String} *)

let string_of_tag tag_ebs  =
  let pbs = readee_basic_string_of_tag tag_ebs in
  Readee_basic_string_v.string_off pbs 
;;

(** {6 String} *)

let string_of_tag tag_ebs  =
  let pbs = readee_basic_string_of_tag tag_ebs in
  Readee_basic_string_v.string_off pbs 
;;

(** {6 Basic} *)

let elementary_fence_basic_string_symbol_of_tag tag_ebs =
  Tag_v.entity_off_tag tag_ebs
;;

let elementary_fence_basic_string_symbol_off_belt bel_ebs =
  let tag_ebs = Doublet_v.left_off_doublet bel_ebs in
  elementary_fence_basic_string_symbol_of_tag tag_ebs
;;

(** {6 Text} *)

let text_of_tag tag_ebs =
  let str = string_of_tag tag_ebs in
  Format.sprintf "string %s" str
;;

(* generated by ./do_belt_as_doublet_fence_basic_stalk_v.sh elementary_fence_basic string *)
(* using ./template_belt_as_doublet_fence_basic_stalk_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:07 (UTC+0200) *)
