(** {3 Elementary_border_parameter_ecppef_belt_t} *)


(** {6 Typing_for_belt} *)

type elementary_border_parameter_ecppef_belt =
  | Elementary_border_parameter_ecppef_coefficient_belt of Elementary_border_parameter_ecppef_coefficient_belt_t.elementary_border_parameter_ecppef_coefficient_belt
  | Elementary_border_parameter_ecppef_exponent_belt of Elementary_border_parameter_ecppef_exponent_belt_t.elementary_border_parameter_ecppef_exponent_belt
;;


(** Elementary_border_parameter_ecppef_belt_t at 11:53:4 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_belt_from_symbol_this_t.sh elementary_border_parameter_ecppef *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_border_parameter_ecppef_symbol_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:04 (UTC+0200) *)
