(** {3 Elementary_fence_basic_float_belt_v} *)

(** {6 Documenting} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_basic_float_belt_v";
   "What-is-it : it is a Tag coupled with a Readee_basic_float";
   "Remark: it is analogous to Elementary_fence_units_actual_action_belt_v";
   "Remark: where fence_units_action is replaced by fence_basic_float";
   "Remark: where measure_action (readee_units) is replaced by readee_basic_float";
 ]
;;

(** {6 Naming} *)

let name bel_ebf =
  Doublet_v.name Elementary_fence_basic_float_tag_v.name Readee_basic_float_v.name bel_ebf
;;

let string_off bel_ebf =
  Doublet_v.name Elementary_fence_basic_float_tag_v.string_off Readee_basic_float_v.string_off bel_ebf
;;

let longname bel_ebf =
  Doublet_v.name Elementary_fence_basic_float_tag_v.longname Readee_basic_float_v.longname bel_ebf
;;

let fullname bel_ebf =
  Doublet_v.name Elementary_fence_basic_float_tag_v.fullname Readee_basic_float_v.fullname bel_ebf
;;

(** {6 Extraction from Database : Readee_basic_float} *)

let readee_of_tag tag_ebf =
  let tag_efe = Tag_v.map_entity
      Elementary_fence_symbol_v.elementary_fence_symbol_of_elementary_fence_basic_float_symbol
      tag_ebf
  in
  Readee_by_elementary_fence_tag_provider_v.provide 
    tag_efe
;;

let readee_basic_float_of_tag tag_ebf =
  let rea = readee_of_tag tag_ebf in
  Readee_v.readee_basic_float_off_readee rea
;;

(** {6 Tagged_measure Triplet} *)

let belt_of_tag tag_ebf =
  let pbs = readee_basic_float_of_tag tag_ebf in
  Doublet_v.make tag_ebf pbs
;;

let tagged_readee_basic_float_doublet_of_tag tag_ebf =
  let pbs = readee_basic_float_of_tag tag_ebf in
  Doublet_v.make tag_ebf pbs
;;

(** {6 Extracting Readee off Belt} *)

let readee_basic_float_off_belt bel_ebf =
  Doublet_v.right_off_doublet bel_ebf
;;

let readee_basic_off_belt bel_ebf =
  let pbs = readee_basic_float_off_belt bel_ebf in
  Readee_basic_v.readee_basic_of_readee_basic_float pbs
;;

let readee_off_belt bel_ebf =
  let pba = readee_basic_off_belt bel_ebf in
  Readee_v.readee_of_readee_basic pba
;;

let readee_list_off_belt bel_ebf =
  let rea = readee_off_belt bel_ebf in
  [rea]
;;

(** {6 Closure : list of Readee} *)

let closure_off_belt bel_ebf =
  let rea = readee_off_belt bel_ebf in
  [rea]
;;

let closure_of_tag tag_ebf =
  let bel_ebf = belt_of_tag tag_ebf in
  closure_off_belt bel_ebf
;;

(** {6 Tagged_readee Doublet} *)

let tagged_readee_doublet_of_tag tag_ebf =
  let plu_ebf = readee_of_tag tag_ebf in
  Doublet_v.make tag_ebf plu_ebf
;;

(** {6 String} *)

let string_of_tag tag_ebf  =
  let pbs = readee_basic_float_of_tag tag_ebf in
  Readee_basic_float_v.string_off pbs 
;;

(** {6 Float} *)

let float_of_tag tag_ebf  =
  let pbs = readee_basic_float_of_tag tag_ebf in
  Readee_basic_float_v.float_off pbs 
;;

(** {6 Basic} *)

let elementary_fence_basic_float_symbol_of_tag tag_ebf =
  Tag_v.entity_off_tag tag_ebf
;;

let elementary_fence_basic_float_symbol_off_belt bel_ebf =
  let tag_ebf = Doublet_v.left_off_doublet bel_ebf in
  elementary_fence_basic_float_symbol_of_tag tag_ebf
;;

(** {6 Text} *)

let text_of_tag tag_ebf =
  let str = string_of_tag tag_ebf in
  Format.sprintf "float %s" str
;;

(* generated by ./do_belt_as_doublet_fence_basic_stalk_v.sh elementary_fence_basic float *)
(* using ./template_belt_as_doublet_fence_basic_stalk_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:07 (UTC+0200) *)
