(** {3 Elementary_fence_belt_v} *)

(** {6 Documenting} *)

let documentation () = 
  [
   "Current : VELE:Elementary_fence_belt_v";
   "Needs : VELE:Elementary_fence_basic_belt_v";
   "Needs : VELE:Elementary_fence_color_belt_v";
   "Needs : VELE:Elementary_fence_units_belt_v";
   "Needed-by :";
   "What-is-it : Up_coercion of Belt type as Symbol type up_coercion";
 ]
;;

(** {6 Naming} *)

let name = function
  | Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb ->
      (Elementary_fence_basic_belt_v.name bel_efb)
	
  | Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc ->
      (Elementary_fence_color_belt_v.name bel_efc)

  | Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa ->
      (Elementary_fence_units_belt_v.name bel_efa)
;;

let string_off = function
  | Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb ->
      (Elementary_fence_basic_belt_v.string_off bel_efb)
	
  | Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc ->
      (Elementary_fence_color_belt_v.string_off bel_efc)

  | Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa ->
      (Elementary_fence_units_belt_v.string_off bel_efa)
;;

let longname = function
  | Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb ->
      (Elementary_fence_basic_belt_v.longname bel_efb)
	
  | Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc ->
      (Elementary_fence_color_belt_v.longname bel_efc)

  | Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa ->
      (Elementary_fence_units_belt_v.longname bel_efa)
;;

let fullname = function
  | Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb ->
      (Elementary_fence_basic_belt_v.fullname bel_efb)
	
  | Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc ->
      (Elementary_fence_color_belt_v.fullname bel_efc)

  | Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa ->
      (Elementary_fence_units_belt_v.fullname bel_efa)
;;

(** {6 Coercing up} *)

let elementary_fence_belt_of_basic_belt bel_efb =
  Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb 
;;

let elementary_fence_belt_of_color_belt bel_efc =
  Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc 
;;

let elementary_fence_belt_of_units_belt bel_efa =
  Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa 
;;

(** {6 Coercing down} *)

let basic_belt_off_elementary_fence_belt = function
  | Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb -> bel_efb
  | _ -> failwith "Not_a_basic:Elementary_fence_belt.Elementary_fence_basic_belt_off_elementary_fence_belt"
;;

let color_belt_off_elementary_fence_belt = function
  | Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc -> bel_efc
  | _ -> failwith "Not_a_color:Elementary_fence_belt.Elementary_fence_color_belt_off_elementary_fence_belt"
;;

let units_belt_off_elementary_fence_belt = function
  | Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa -> bel_efa
  | _ -> failwith "Not_a_units:Elementary_fence_belt.units_belt_off_elementary_fence_belt"
;;

(** {6 Belt} *)

let belt_of_tag tag_efe =
  let soi_efe = Tag_v.sole_index_off_tag tag_efe in
  let sym_efe = Tag_v.entity_off_tag tag_efe in
  match sym_efe with
  | Elementary_fence_symbol_t.Elementary_fence_basic_symbol sym_efb ->
      let tag_efb = Tag_v.make sym_efb soi_efe in
      Elementary_fence_belt_t.Elementary_fence_basic_belt
	(Elementary_fence_basic_belt_v.belt_of_tag tag_efb)

  | Elementary_fence_symbol_t.Elementary_fence_color_symbol sym_efc ->
      let tag_efc = Tag_v.make sym_efc soi_efe in
      Elementary_fence_belt_t.Elementary_fence_color_belt
	(Elementary_fence_color_belt_v.belt_of_tag tag_efc)

  | Elementary_fence_symbol_t.Elementary_fence_units_symbol sym_efa ->
      let tag_efa = Tag_v.make sym_efa soi_efe in
      Elementary_fence_belt_t.Elementary_fence_units_belt
	(Elementary_fence_units_belt_v.belt_of_tag tag_efa)
;;

(** {6 Readee : a Generalization of Readee_basic} *)

let readee_off_belt = function
  | Elementary_fence_belt_t.Elementary_fence_basic_belt bel_efb ->
      (Elementary_fence_basic_belt_v.readee_off_belt bel_efb)
	
  | Elementary_fence_belt_t.Elementary_fence_color_belt bel_efc ->
      (Elementary_fence_color_belt_v.readee_off_belt bel_efc)

  | Elementary_fence_belt_t.Elementary_fence_units_belt bel_efa ->
      (Elementary_fence_units_belt_v.readee_off_belt bel_efa)
;;

(** {6 Closure} *)

let closure_off_belt bel_efe =
  let rea = readee_off_belt bel_efe in
  [rea]
;;

let closure_of_tag tag_efe =
  let bel_efe = belt_of_tag tag_efe in
  closure_off_belt bel_efe
;;

(* generated by ./do_belt_as_fence_trunc_3sibling_v.sh elementary_fence efe basic efb color efc units efa *)
(* using ./template_belt_as_fence_trunc_3sibling_v.ml *)
(* Done on mardi 24 mai 2016, 16:43:08 (UTC+0200) *)

