(** {3 Elementary_fence_units_belt_t} *)


(** {6 Typing_for_belt} *)

type elementary_fence_units_belt =
  | Elementary_fence_units_actual_belt of Elementary_fence_units_actual_belt_t.elementary_fence_units_actual_belt
  | Elementary_fence_units_canonical_belt of Elementary_fence_units_canonical_belt_t.elementary_fence_units_canonical_belt
;;


(** Elementary_fence_units_belt_t at 11:53:16 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_belt_from_symbol_this_t.sh elementary_fence_units *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_fence_units_symbol_t.ml *)
(* Done on lundi 23 mai 2016, 08:05:03 (UTC+0200) *)
