INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(DB1POINTSDATASET_CONTAINERS_DIR) \
	$(NWCHEMDATASET_SYMBOLS_DIR) \
	$(NWCHEMDATASET_TAGS_DIR) \
	$(NWCHEMDATASET_BUILDER_TREES_DIR) \
	$(NWCHEMDATASET_CONTAINERS_DIR) \
  