LOCALINPUT_T_MLI :=  \
     Localinput_set_fence_variable_name_operator_symbol_t.mli \
      Localinput_set_fence_variable_name_entity_target_symbol_t.mli \
      Localinput_set_fence_variable_name_entity_implicit_symbol_t.mli \
      Localinput_set_fence_variable_name_entity_external_symbol_t.mli \
     Localinput_set_fence_variable_name_entity_symbol_t.mli \
     Localinput_set_fence_variable_name_context_symbol_t.mli \
    Localinput_set_fence_variable_name_symbol_t.mli \
     Localinput_set_fence_variable_kind_operator_symbol_t.mli \
      Localinput_set_fence_variable_kind_entity_target_symbol_t.mli \
      Localinput_set_fence_variable_kind_entity_implicit_symbol_t.mli \
      Localinput_set_fence_variable_kind_entity_external_symbol_t.mli \
     Localinput_set_fence_variable_kind_entity_symbol_t.mli \
     Localinput_set_fence_variable_kind_context_symbol_t.mli \
    Localinput_set_fence_variable_kind_symbol_t.mli \
      Localinput_set_fence_keyword_word_units_symbol_t.mli \
      Localinput_set_fence_keyword_word_type_symbol_t.mli \
      Localinput_set_fence_keyword_word_statistics_symbol_t.mli \
      Localinput_set_fence_keyword_word_sector_symbol_t.mli \
      Localinput_set_fence_keyword_word_operator_symbol_t.mli \
      Localinput_set_fence_keyword_word_operation_symbol_t.mli \
      Localinput_set_fence_keyword_word_ondomain_symbol_t.mli \
      Localinput_set_fence_keyword_word_name_symbol_t.mli \
      Localinput_set_fence_keyword_word_module_symbol_t.mli \
      Localinput_set_fence_keyword_word_file_symbol_t.mli \
      Localinput_set_fence_keyword_word_external_context_symbol_t.mli \
      Localinput_set_fence_keyword_word_end_symbol_t.mli \
      Localinput_set_fence_keyword_word_domain_symbol_t.mli \
      Localinput_set_fence_keyword_word_debug_symbol_t.mli \
      Localinput_set_fence_keyword_word_databox_symbol_t.mli \
      Localinput_set_fence_keyword_word_database_symbol_t.mli \
      Localinput_set_fence_keyword_word_cpu_symbol_t.mli \
      Localinput_set_fence_keyword_word_context_symbol_t.mli \
      Localinput_set_fence_keyword_word_cofactor_entity_symbol_t.mli \
      Localinput_set_fence_keyword_word_cofactor_basic_symbol_t.mli \
      Localinput_set_fence_keyword_word_cofactor_symbol_t.mli \
      Localinput_set_fence_keyword_word_category_symbol_t.mli \
     Localinput_set_fence_keyword_word_symbol_t.mli \
      Localinput_set_fence_keyword_variable_kind_target_symbol_t.mli \
      Localinput_set_fence_keyword_variable_kind_operator_symbol_t.mli \
      Localinput_set_fence_keyword_variable_kind_external_symbol_t.mli \
      Localinput_set_fence_keyword_variable_kind_context_symbol_t.mli \
     Localinput_set_fence_keyword_variable_kind_symbol_t.mli \
      Localinput_set_fence_keyword_command_write_symbol_t.mli \
      Localinput_set_fence_keyword_command_title_symbol_t.mli \
      Localinput_set_fence_keyword_command_stop_symbol_t.mli \
      Localinput_set_fence_keyword_command_set_symbol_t.mli \
      Localinput_set_fence_keyword_command_read_symbol_t.mli \
      Localinput_set_fence_keyword_command_print_symbol_t.mli \
      Localinput_set_fence_keyword_command_define_symbol_t.mli \
     Localinput_set_fence_keyword_command_symbol_t.mli \
    Localinput_set_fence_keyword_symbol_t.mli \
     Localinput_set_fence_cell_target_operator_symbol_t.mli \
     Localinput_set_fence_cell_target_operand_symbol_t.mli \
     Localinput_set_fence_cell_operation_symbol_t.mli \
     Localinput_set_fence_cell_ondomain_symbol_t.mli \
     Localinput_set_fence_cell_module_symbol_t.mli \
     Localinput_set_fence_cell_function_symbol_t.mli \
     Localinput_set_fence_cell_file_symbol_t.mli \
     Localinput_set_fence_cell_external_variable_symbol_t.mli \
     Localinput_set_fence_cell_external_name_symbol_t.mli \
     Localinput_set_fence_cell_external_context_symbol_t.mli \
     Localinput_set_fence_cell_domain_symbol_t.mli \
     Localinput_set_fence_cell_databox_symbol_t.mli \
     Localinput_set_fence_cell_database_symbol_t.mli \
     Localinput_set_fence_cell_sector_symbol_t.mli \
     Localinput_set_fence_cell_context_symbol_t.mli \
     Localinput_set_fence_cell_cofactor_entity_symbol_t.mli \
     Localinput_set_fence_cell_cofactor_basic_symbol_t.mli \
     Localinput_set_fence_cell_category_symbol_t.mli \
    Localinput_set_fence_cell_symbol_t.mli \
     Localinput_set_fence_basic_word_uppercase_symbol_t.mli \
     Localinput_set_fence_basic_word_lowercase_symbol_t.mli \
     Localinput_set_fence_basic_word_capitalized_symbol_t.mli \
     Localinput_set_fence_basic_word_anycase_symbol_t.mli \
    Localinput_set_fence_basic_word_symbol_t.mli \
     Localinput_set_fence_basic_integer_symbol_t.mli \
     Localinput_set_fence_basic_float_symbol_t.mli \
    Localinput_set_fence_basic_numerical_symbol_t.mli \
   Localinput_set_fence_symbol_t.mli \
     Localinput_set_body_list_variable_type_symbol_t.mli \
     Localinput_set_body_list_variable_name_external_symbol_t.mli \
    Localinput_set_body_list_symbol_t.mli \
      Localinput_set_body_handle_variable_target_symbol_t.mli \
      Localinput_set_body_handle_variable_operator_symbol_t.mli \
      Localinput_set_body_handle_variable_external_symbol_t.mli \
      Localinput_set_body_handle_variable_context_symbol_t.mli \
     Localinput_set_body_handle_variable_kind_symbol_t.mli \
       Localinput_set_body_handle_command_tounit_write_symbol_t.mli \
       Localinput_set_body_handle_command_tounit_print_symbol_t.mli \
      Localinput_set_body_handle_command_tounit_symbol_t.mli \
       Localinput_set_body_handle_command_creation_title_symbol_t.mli \
       Localinput_set_body_handle_command_creation_set_symbol_t.mli \
       Localinput_set_body_handle_command_creation_read_symbol_t.mli \
       Localinput_set_body_handle_command_creation_define_symbol_t.mli \
      Localinput_set_body_handle_command_creation_symbol_t.mli \
     Localinput_set_body_handle_command_symbol_t.mli \
     Localinput_set_body_handle_cofactor_symbol_t.mli \
    Localinput_set_body_handle_symbol_t.mli \
     Localinput_set_body_box_units_symbol_t.mli \
     Localinput_set_body_box_type_symbol_t.mli \
    Localinput_set_body_box_symbol_t.mli \
     Localinput_set_body_block_write_symbol_t.mli \
     Localinput_set_body_block_variable_target_symbol_t.mli \
     Localinput_set_body_block_variable_operator_symbol_t.mli \
     Localinput_set_body_block_variable_external_symbol_t.mli \
     Localinput_set_body_block_variable_context_symbol_t.mli \
     Localinput_set_body_block_title_symbol_t.mli \
     Localinput_set_body_block_set_alternative_symbol_t.mli \
     Localinput_set_body_block_set_symbol_t.mli \
     Localinput_set_body_block_read_symbol_t.mli \
     Localinput_set_body_block_print_symbol_t.mli \
     Localinput_set_body_block_cofactor_symbol_t.mli \
     Localinput_set_body_block_define_symbol_t.mli \
    Localinput_set_body_block_symbol_t.mli \
   Localinput_set_body_symbol_t.mli \
  Localinput_set_symbol_t.mli \
   Localinput_context_sector_symbol_t.mli \
   Localinput_context_inputbox_symbol_t.mli \
   Localinput_context_inputbase_symbol_t.mli \
   Localinput_context_domain_symbol_t.mli \
  Localinput_context_symbol_t.mli \
 Localinput_symbol_t.mli \
