(** {3 Localinput_set_fence_cell_symbol_t} *)


(** {6 Typing_for_symbol} *)

type localinput_set_fence_cell_symbol =
  | Localinput_set_fence_cell_category_symbol of Localinput_set_fence_cell_category_symbol_t.localinput_set_fence_cell_category_symbol
  | Localinput_set_fence_cell_cofactor_basic_symbol of Localinput_set_fence_cell_cofactor_basic_symbol_t.localinput_set_fence_cell_cofactor_basic_symbol
  | Localinput_set_fence_cell_cofactor_entity_symbol of Localinput_set_fence_cell_cofactor_entity_symbol_t.localinput_set_fence_cell_cofactor_entity_symbol
  | Localinput_set_fence_cell_context_symbol of Localinput_set_fence_cell_context_symbol_t.localinput_set_fence_cell_context_symbol
  | Localinput_set_fence_cell_sector_symbol of Localinput_set_fence_cell_sector_symbol_t.localinput_set_fence_cell_sector_symbol
  | Localinput_set_fence_cell_database_symbol of Localinput_set_fence_cell_database_symbol_t.localinput_set_fence_cell_database_symbol
  | Localinput_set_fence_cell_databox_symbol of Localinput_set_fence_cell_databox_symbol_t.localinput_set_fence_cell_databox_symbol
  | Localinput_set_fence_cell_domain_symbol of Localinput_set_fence_cell_domain_symbol_t.localinput_set_fence_cell_domain_symbol
  | Localinput_set_fence_cell_external_context_symbol of Localinput_set_fence_cell_external_context_symbol_t.localinput_set_fence_cell_external_context_symbol
  | Localinput_set_fence_cell_external_name_symbol of Localinput_set_fence_cell_external_name_symbol_t.localinput_set_fence_cell_external_name_symbol
  | Localinput_set_fence_cell_external_variable_symbol of Localinput_set_fence_cell_external_variable_symbol_t.localinput_set_fence_cell_external_variable_symbol
  | Localinput_set_fence_cell_file_symbol of Localinput_set_fence_cell_file_symbol_t.localinput_set_fence_cell_file_symbol
  | Localinput_set_fence_cell_function_symbol of Localinput_set_fence_cell_function_symbol_t.localinput_set_fence_cell_function_symbol
  | Localinput_set_fence_cell_module_symbol of Localinput_set_fence_cell_module_symbol_t.localinput_set_fence_cell_module_symbol
  | Localinput_set_fence_cell_ondomain_symbol of Localinput_set_fence_cell_ondomain_symbol_t.localinput_set_fence_cell_ondomain_symbol
  | Localinput_set_fence_cell_operation_symbol of Localinput_set_fence_cell_operation_symbol_t.localinput_set_fence_cell_operation_symbol
  | Localinput_set_fence_cell_target_operand_symbol of Localinput_set_fence_cell_target_operand_symbol_t.localinput_set_fence_cell_target_operand_symbol
  | Localinput_set_fence_cell_target_operator_symbol of Localinput_set_fence_cell_target_operator_symbol_t.localinput_set_fence_cell_target_operator_symbol
;;


(** Localinput_set_fence_cell_symbol_t at 11:18:56 on 15 May 2017. created by version v2.4 of generator *)



