(** {3 Localinput_set_body_handle_command_creation_symbol_t} *)


(** {6 Typing_for_symbol} *)

type localinput_set_body_handle_command_creation_symbol =
  | Localinput_set_body_handle_command_creation_define_symbol of Localinput_set_body_handle_command_creation_define_symbol_t.localinput_set_body_handle_command_creation_define_symbol
  | Localinput_set_body_handle_command_creation_read_symbol of Localinput_set_body_handle_command_creation_read_symbol_t.localinput_set_body_handle_command_creation_read_symbol
  | Localinput_set_body_handle_command_creation_set_symbol of Localinput_set_body_handle_command_creation_set_symbol_t.localinput_set_body_handle_command_creation_set_symbol
  | Localinput_set_body_handle_command_creation_title_symbol of Localinput_set_body_handle_command_creation_title_symbol_t.localinput_set_body_handle_command_creation_title_symbol
;;


(** Localinput_set_body_handle_command_creation_symbol_t at 11:17:53 on 15 May 2017. created by version v2.4 of generator *)



