(** {3 Localinput_set_body_block_symbol_t} *)


(** {6 Typing_for_symbol} *)

type localinput_set_body_block_symbol =
  | Localinput_set_body_block_define_symbol of Localinput_set_body_block_define_symbol_t.localinput_set_body_block_define_symbol
  | Localinput_set_body_block_cofactor_symbol of Localinput_set_body_block_cofactor_symbol_t.localinput_set_body_block_cofactor_symbol
  | Localinput_set_body_block_print_symbol of Localinput_set_body_block_print_symbol_t.localinput_set_body_block_print_symbol
  | Localinput_set_body_block_read_symbol of Localinput_set_body_block_read_symbol_t.localinput_set_body_block_read_symbol
  | Localinput_set_body_block_set_symbol of Localinput_set_body_block_set_symbol_t.localinput_set_body_block_set_symbol
  | Localinput_set_body_block_set_alternative_symbol of Localinput_set_body_block_set_alternative_symbol_t.localinput_set_body_block_set_alternative_symbol
  | Localinput_set_body_block_title_symbol of Localinput_set_body_block_title_symbol_t.localinput_set_body_block_title_symbol
  | Localinput_set_body_block_variable_context_symbol of Localinput_set_body_block_variable_context_symbol_t.localinput_set_body_block_variable_context_symbol
  | Localinput_set_body_block_variable_external_symbol of Localinput_set_body_block_variable_external_symbol_t.localinput_set_body_block_variable_external_symbol
  | Localinput_set_body_block_variable_operator_symbol of Localinput_set_body_block_variable_operator_symbol_t.localinput_set_body_block_variable_operator_symbol
  | Localinput_set_body_block_variable_target_symbol of Localinput_set_body_block_variable_target_symbol_t.localinput_set_body_block_variable_target_symbol
  | Localinput_set_body_block_write_symbol of Localinput_set_body_block_write_symbol_t.localinput_set_body_block_write_symbol
;;


(** Localinput_set_body_block_symbol_t at 11:17:31 on 15 May 2017. created by version v2.4 of generator *)



