(** {3 Localinput_set_fence_keyword_word_symbol_t} *)


(** {6 Typing_for_symbol} *)

type localinput_set_fence_keyword_word_symbol =
  | Localinput_set_fence_keyword_word_category_symbol of Localinput_set_fence_keyword_word_category_symbol_t.localinput_set_fence_keyword_word_category_symbol
  | Localinput_set_fence_keyword_word_cofactor_symbol of Localinput_set_fence_keyword_word_cofactor_symbol_t.localinput_set_fence_keyword_word_cofactor_symbol
  | Localinput_set_fence_keyword_word_cofactor_basic_symbol of Localinput_set_fence_keyword_word_cofactor_basic_symbol_t.localinput_set_fence_keyword_word_cofactor_basic_symbol
  | Localinput_set_fence_keyword_word_cofactor_entity_symbol of Localinput_set_fence_keyword_word_cofactor_entity_symbol_t.localinput_set_fence_keyword_word_cofactor_entity_symbol
  | Localinput_set_fence_keyword_word_context_symbol of Localinput_set_fence_keyword_word_context_symbol_t.localinput_set_fence_keyword_word_context_symbol
  | Localinput_set_fence_keyword_word_cpu_symbol of Localinput_set_fence_keyword_word_cpu_symbol_t.localinput_set_fence_keyword_word_cpu_symbol
  | Localinput_set_fence_keyword_word_database_symbol of Localinput_set_fence_keyword_word_database_symbol_t.localinput_set_fence_keyword_word_database_symbol
  | Localinput_set_fence_keyword_word_databox_symbol of Localinput_set_fence_keyword_word_databox_symbol_t.localinput_set_fence_keyword_word_databox_symbol
  | Localinput_set_fence_keyword_word_debug_symbol of Localinput_set_fence_keyword_word_debug_symbol_t.localinput_set_fence_keyword_word_debug_symbol
  | Localinput_set_fence_keyword_word_domain_symbol of Localinput_set_fence_keyword_word_domain_symbol_t.localinput_set_fence_keyword_word_domain_symbol
  | Localinput_set_fence_keyword_word_end_symbol of Localinput_set_fence_keyword_word_end_symbol_t.localinput_set_fence_keyword_word_end_symbol
  | Localinput_set_fence_keyword_word_external_context_symbol of Localinput_set_fence_keyword_word_external_context_symbol_t.localinput_set_fence_keyword_word_external_context_symbol
  | Localinput_set_fence_keyword_word_file_symbol of Localinput_set_fence_keyword_word_file_symbol_t.localinput_set_fence_keyword_word_file_symbol
  | Localinput_set_fence_keyword_word_module_symbol of Localinput_set_fence_keyword_word_module_symbol_t.localinput_set_fence_keyword_word_module_symbol
  | Localinput_set_fence_keyword_word_name_symbol of Localinput_set_fence_keyword_word_name_symbol_t.localinput_set_fence_keyword_word_name_symbol
  | Localinput_set_fence_keyword_word_ondomain_symbol of Localinput_set_fence_keyword_word_ondomain_symbol_t.localinput_set_fence_keyword_word_ondomain_symbol
  | Localinput_set_fence_keyword_word_operation_symbol of Localinput_set_fence_keyword_word_operation_symbol_t.localinput_set_fence_keyword_word_operation_symbol
  | Localinput_set_fence_keyword_word_operator_symbol of Localinput_set_fence_keyword_word_operator_symbol_t.localinput_set_fence_keyword_word_operator_symbol
  | Localinput_set_fence_keyword_word_sector_symbol of Localinput_set_fence_keyword_word_sector_symbol_t.localinput_set_fence_keyword_word_sector_symbol
  | Localinput_set_fence_keyword_word_statistics_symbol of Localinput_set_fence_keyword_word_statistics_symbol_t.localinput_set_fence_keyword_word_statistics_symbol
  | Localinput_set_fence_keyword_word_type_symbol of Localinput_set_fence_keyword_word_type_symbol_t.localinput_set_fence_keyword_word_type_symbol
  | Localinput_set_fence_keyword_word_units_symbol of Localinput_set_fence_keyword_word_units_symbol_t.localinput_set_fence_keyword_word_units_symbol
;;


(** Localinput_set_fence_keyword_word_symbol_t at 11:19:52 on 15 May 2017. created by version v2.4 of generator *)



