INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(DATABASESET_COMMON_DIR) \
	$(DATABASESET_DB1_DIR) \
	$(ELEMENTARYSET_SYMBOLS_DIR) \
	$(ELEMENTARYSET_TAGS_DIR) \
	$(ELEMENTARYSET_DATABASES_DIR) \
	$(ELEMENTARYSET_CONTAINERS_DIR) \
	$(ELEMENTARYSET_VALUES_DIR) \
	$(ELEMENTARYSET_PROPERTIES_DIR) \
  


