PROPERTY_T_MLI :=  \
     Property_target_body_implicit_tounit_symbol_t.mli \
    Property_target_body_implicit_symbol_t.mli \
   Property_target_body_symbol_t.mli \
  Property_target_symbol_t.mli \
     Property_operator_fence_tounit_write_symbol_t.mli \
     Property_operator_fence_tounit_print_symbol_t.mli \
    Property_operator_fence_tounit_symbol_t.mli \
     Property_operator_fence_creation_tobasic_symbol_t.mli \
     Property_operator_fence_creation_tomeasure_symbol_t.mli \
     Property_operator_fence_creation_toentity_symbol_t.mli \
    Property_operator_fence_creation_symbol_t.mli \
   Property_operator_fence_symbol_t.mli \
  Property_operator_symbol_t.mli \
    Property_operand_fence_external_symbol_t.mli \
   Property_operand_fence_symbol_t.mli \
     Property_operand_body_target_measured_symbol_t.mli \
     Property_operand_body_target_created_symbol_t.mli \
     Property_operand_body_target_calculated_symbol_t.mli \
    Property_operand_body_target_symbol_t.mli \
   Property_operand_body_symbol_t.mli \
  Property_operand_symbol_t.mli \
   Property_context_inputbox_symbol_t.mli \
   Property_context_inputbase_symbol_t.mli \
   Property_context_domain_symbol_t.mli \
   Property_context_sector_symbol_t.mli \
  Property_context_symbol_t.mli \
    Property_command_body_trace_symbol_t.mli \
    Property_command_body_title_symbol_t.mli \
    Property_command_body_set_symbol_t.mli \
    Property_command_body_debug_symbol_t.mli \
   Property_command_body_symbol_t.mli \
  Property_command_symbol_t.mli \
 Property_symbol_t.mli \
