#!/bin/bash
# generates Frames_directories.mk

echo "# this file has been generated by $0"
echo "# inside setup directory"
echo 'FRAMES_DIR := $(SETUP_DIR)/frames'

echo "# inside frames directory"
echo ""
echo "# specific directories"
echo 'include $(MAK)/Frames_general_directories.mk'
echo 'GENERATOR_DIR := $(FRAMES_DIR)/generator'
echo ""
echo "# sets directories as defined in Active_sets.sh"
for set in `${FRA}/Active_sets.sh`
do
echo "include ${MAK}/Frames_${set}_directories.mk"
done
echo ""
echo "# all nodes "
echo -n 'NODE_LIST := $(SETUP_DIR) $(FRAMES_DIR) $(GENERAL_DIR) $(GENERATOR_DIR)' 
for set in `${FRA}/Active_sets.sh`
do
    SET=`echo $set | tr a-z A-Z`
    echo " \$(${SET}_DIR)" 
done

