# ghostset directories

GHOSTSET_DATABASES_DIR := $(GHOSTSET_DIR)/ghostset_databases
GHOSTSET_DATABASES_DB1_DIR := $(GHOSTSET_DATABASES_DIR)/db1
GHOSTSET_DATABASES_DB2_DIR := $(GHOSTSET_DATABASES_DIR)/db2
GHOSTSET_DATABASES_COMMON_DIR := $(GHOSTSET_DATABASES_DIR)/common
GHOSTSET_CONTAINERS_DIR := $(GHOSTSET_DIR)/ghostset_containers
GHOSTSET_BUILDER_TREES_DIR := $(GHOSTSET_DIR)/ghostset_builder_trees
GHOSTSET_PROPERTIES_DIR := $(GHOSTSET_DIR)/ghostset_properties
GHOSTSET_SYMBOLS_DIR := $(GHOSTSET_DIR)/ghostset_symbols
GHOSTSET_TAGS_DIR := $(GHOSTSET_DIR)/ghostset_tags
GHOSTSET_VALUES_DIR := $(GHOSTSET_DIR)/ghostset_values


