# db2geometry directories

DB2GEOMETRYDATASET_LEXER_DIR := $(DB2GEOMETRYDATASET_DIR)/db2geometrydataset_lexer
DB2GEOMETRYDATASET_SYMBOLS_DIR := $(DB2GEOMETRYDATASET_DIR)/db2geometrydataset_symbols
DB2GEOMETRYDATASET_TAGS_DIR := $(DB2GEOMETRYDATASET_DIR)/db2geometrydataset_tags
DB2GEOMETRYDATASET_PARSER_DIR := $(DB2GEOMETRYDATASET_DIR)/db2geometrydataset_parser
DB2GEOMETRYDATASET_BUILDER_TREES_DIR := $(DB2GEOMETRYDATASET_DIR)/db2geometrydataset_builder_trees


