# kind = "node" (has code subdirectories) in Makefile for these directories :

NODE_LIST := \
	$(CHEMICALDATA_DIR) \
	$(CHEMICALSET_DIR) \
	$(COORDINATESET_DIR) \
	$(DB1POINTSDATASET_DIR) \
	$(DB2GEOMETRYDATASET_DIR) \
	$(ELEMENTARYSET_DIR) \
	$(EXTERNALSECTOR_DIR) \
	$(FIGUREDATA_DIR) \
	$(FIGURESET_DIR) \
	$(FRAMES_DIR) \
	$(GENERALSECTOR_DIR) \
	$(GENERATORSECTOR_DIR) \
	$(GENERATORSET_DIR) \
	$(GLOBALSET_DIR) \
	$(LOCALINPUTSET_DIR) \
	$(MUSICSET_DIR) \
	$(NATURALSET_DIR) \
	$(NWCHEMDATASET_DIR) \
	$(PARAMETERSET_DIR) \
	$(PROPERTYSET_DIR) \
	$(SETUP_DIR) \
	$(SKELETONDATA_DIR) \
	$(SKELETONSET_DIR) \

#	$(OPERATORSET_DIR) \
#	$(GHOSTSET_DIR)  not a Node
#	$(COMMONSET_DIR)  not a Node
#	$(CONTEXTSET_DIR)  not a Node

