# coordinateset directories

COORDINATESET_BUILDER_TREES_DIR := $(COORDINATESET_DIR)/coordinateset_builder_trees
COORDINATESET_DATABASES_DIR := $(COORDINATESET_DIR)/coordinateset_databases
COORDINATESET_CONTAINERS_DIR := $(COORDINATESET_DIR)/coordinateset_containers
COORDINATESET_SYMBOLS_DIR := $(COORDINATESET_DIR)/coordinateset_symbols
COORDINATESET_TAGS_DIR := $(COORDINATESET_DIR)/coordinateset_tags
COORDINATESET_READEES_DIR := $(COORDINATESET_DIR)/coordinateset_readees
COORDINATESET_ENVELOPES_DIR := $(COORDINATESET_DIR)/coordinateset_envelopes
COORDINATESET_OPERATIONS_DIR := $(COORDINATESET_DIR)/coordinateset_operations
COORDINATESET_VALUES_DIR := $(COORDINATESET_DIR)/coordinateset_values


