# inside generalsector directory

BASICS_DIR := $(GENERALSECTOR_DIR)/basics
DATASTRUCTURES_DIR := $(GENERALSECTOR_DIR)/datastructures
FILES_DIR := $(GENERALSECTOR_DIR)/files
FUNCTIONS_DIR := $(GENERALSECTOR_DIR)/functions
INTEGRALS_DIR := $(GENERALSECTOR_DIR)/integrals
LINEARALGEBRA_DIR := $(GENERALSECTOR_DIR)/linearalgebra
MISCELLANEOUS_DIR := $(GENERALSECTOR_DIR)/miscellaneous
MEASURE_DIR := $(GENERALSECTOR_DIR)/measure
POLYNOMIALS_DIR := $(GENERALSECTOR_DIR)/polynomials
QUANTUM_DIR := $(GENERALSECTOR_DIR)/quantum
READEE_DIR := $(GENERALSECTOR_DIR)/readee
SYMBOLSGENERAL_DIR := $(GENERALSECTOR_DIR)/symbolsgeneral
UNITS_DIR := $(GENERALSECTOR_DIR)/units

