# elementaryset directories content

ELEMENTARYSET_BUILDER_TREES_DIR := $(ELEMENTARYSET_DIR)/elementaryset_builder_trees
ELEMENTARYSET_CONTAINERS_DIR := $(ELEMENTARYSET_DIR)/elementaryset_containers
ELEMENTARYSET_DATABASES_DIR := $(ELEMENTARYSET_DIR)/elementaryset_databases
ELEMENTARYSET_ENVELOPES_DIR := $(ELEMENTARYSET_DIR)/elementaryset_envelopes
ELEMENTARYSET_SYMBOLS_DIR := $(ELEMENTARYSET_DIR)/elementaryset_symbols
ELEMENTARYSET_TAGS_DIR := $(ELEMENTARYSET_DIR)/elementaryset_tags
ELEMENTARYSET_BELTS_DIR := $(ELEMENTARYSET_DIR)/elementaryset_belts
ELEMENTARYSET_VALUES_DIR := $(ELEMENTARYSET_DIR)/elementaryset_values

