#

ENTRYSECTOR_DIR := $(FRAMES_DIR)/entrysector
EXTERNALSECTOR_DIR := $(FRAMES_DIR)/externalsector
GENERALSECTOR_DIR := $(FRAMES_DIR)/generalsector
GENERATORSECTOR_DIR := $(FRAMES_DIR)/generatorsector
INTERNALSECTOR_DIR := $(FRAMES_DIR)/internalsector
PRODUCTSECTOR_DIR := $(FRAMES_DIR)/productsector

