# musicset directories

MUSICSET_DATABASES_DIR := $(MUSICSET_DIR)/musicset_databases
MUSICSET_DATABASES_DB1_DIR := $(MUSICSET_DATABASES_DIR)/db1
MUSICSET_DATABASES_DB2_DIR := $(MUSICSET_DATABASES_DIR)/db2
MUSICSET_DATABASES_COMMON_DIR := $(MUSICSET_DATABASES_DIR)/common
MUSICSET_CONTAINERS_DIR := $(MUSICSET_DIR)/musicset_containers
MUSICSET_BUILDER_TREES_DIR := $(MUSICSET_DIR)/musicset_builder_trees
MUSICSET_SYMBOLS_DIR := $(MUSICSET_DIR)/musicset_symbols
MUSICSET_TAGS_DIR := $(MUSICSET_DIR)/musicset_tags
MUSICSET_VALUES_DIR := $(MUSICSET_DIR)/musicset_values




