# generatorset directories

GENERATORSET_DATABASES_DIR := $(GENERATORSET_DIR)/generatorset_databases
GENERATORSET_FORMULAS_DIR := $(GENERATORSET_DIR)/generatorset_formulas
GENERATORSET_INTERFACES_DIR := $(GENERATORSET_DIR)/generatorset_interfaces
GENERATORSET_SYMBOLS_DIR := $(GENERATORSET_DIR)/generatorset_symbols
GENERATORSET_TAGS_DIR := $(GENERATORSET_DIR)/generatorset_tags
GENERATORSET_VALUES_DIR := $(GENERATORSET_DIR)/generatorset_values

GENERATORSET_DATABASES_ADB_DIR := $(GENERATORSET_DATABASES_DIR)/adb
