# molpro directories

MOLPRODATASET_LEXER_DIR := $(MOLPRODATASET_DIR)/molprodataset_lexer
MOLPRODATASET_SYMBOLS_DIR := $(MOLPRODATASET_DIR)/molprodataset_symbols
MOLPRODATASET_TAGS_DIR := $(MOLPRODATASET_DIR)/molprodataset_tags
MOLPRODATASET_PARSER_DIR := $(MOLPRODATASET_DIR)/molprodataset_parser
MOLPRODATASET_BUILDER_TREES_DIR := $(MOLPRODATASET_DIR)/molprodataset_builder_trees


