# localinputset directories

LOCALINPUTSET_COMMON_DIR := $(LOCALINPUTSET_DIR)/localinputset_common
LOCALINPUTSET_CONTAINERS_DIR := $(LOCALINPUTSET_DIR)/localinputset_containers
LOCALINPUTSET_LEXICAL_ANALYSIS_DIR := $(LOCALINPUTSET_DIR)/localinputset_lexical_analysis
LOCALINPUTSET_LEXER_DIR := $(LOCALINPUTSET_DIR)/localinputset_lexer
LOCALINPUTSET_PARSER_DIR := $(LOCALINPUTSET_DIR)/localinputset_parser
LOCALINPUTSET_BUILDER_TREES_DIR := $(LOCALINPUTSET_DIR)/localinputset_builder_trees
LOCALINPUTSET_SYMBOLS_DIR := $(LOCALINPUTSET_DIR)/localinputset_symbols
LOCALINPUTSET_TAGS_DIR := $(LOCALINPUTSET_DIR)/localinputset_tags
LOCALINPUTSET_VALUES_DIR := $(LOCALINPUTSET_DIR)/localinputset_values
LOCALINPUTSET_VARIABLES_DIR := $(LOCALINPUTSET_DIR)/localinputset_variables



