# db1points directories

DB1POINTSDATASET_LEXER_DIR := $(DB1POINTSDATASET_DIR)/db1pointsdataset_lexer
DB1POINTSDATASET_SYMBOLS_DIR := $(DB1POINTSDATASET_DIR)/db1pointsdataset_symbols
DB1POINTSDATASET_TAGS_DIR := $(DB1POINTSDATASET_DIR)/db1pointsdataset_tags
DB1POINTSDATASET_PARSER_DIR := $(DB1POINTSDATASET_DIR)/db1pointsdataset_parser
DB1POINTSDATASET_BUILDER_TREES_DIR := $(DB1POINTSDATASET_DIR)/db1pointsdataset_builder_trees


