# generatorset directories

CHEMICALSET_DATABASES_DIR := $(CHEMICALSET_DIR)/chemicalset_databases
CHEMICALSET_CONTAINERS_DIR := $(CHEMICALSET_DIR)/chemicalset_containers
CHEMICALSET_BUILDER_TREES_DIR := $(CHEMICALSET_DIR)/chemicalset_builder_trees
CHEMICALSET_MARKS_DIR := $(CHEMICALSET_DIR)/chemicalset_marks
CHEMICALSET_SYMBOLS_DIR := $(CHEMICALSET_DIR)/chemicalset_symbols
CHEMICALSET_TAGS_DIR := $(CHEMICALSET_DIR)/chemicalset_tags
CHEMICALSET_VALUES_DIR := $(CHEMICALSET_DIR)/chemicalset_values

# databases dir alien local pdb
CHEMICALSET_DATABASES_ADB_DIR := $(CHEMICALSET_DATABASES_DIR)/adb
CHEMICALSET_DATABASES_LDB_DIR := $(CHEMICALSET_DATABASES_DIR)/ldb
CHEMICALSET_DATABASES_PDB_DIR := $(CHEMICALSET_DATABASES_DIR)/pdb


