INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(UNITS_DIR) \
	$(MEASURE_DIR) \
	$(CONTEXTSET_DIR) \
	$(NWCHEMDATASET_SYMBOLS_DIR) \
	$(NWCHEMDATASET_PARSER_DIR) \
	$(NWCHEMDATASET_TAGS_DIR) \
  



