#!/bin/bash

# The sub-directories where we run a configure script.
SUB_DIRECTORIES="musicset_symbols musicset_tags musicset_formulas"

# The directory where we just configure .depend and .depend-rebuild.
CURRENT_AND_TEST=". unitary_tests"

# created by /code/sources/ocaml_top/setup/utilities/do_configure_local_no_sub_directory.sh > configure_local
