(** {3 Elementary_fence_coordinate_homogeneous_cartesian_symbol_t} *)


(** {6 Typing_for_symbol} *)

type elementary_fence_coordinate_homogeneous_cartesian_symbol =
  | Elementary_fence_coordinate_homogeneous_cartesian_x_symbol of Elementary_fence_coordinate_homogeneous_cartesian_x_symbol_t.elementary_fence_coordinate_homogeneous_cartesian_x_symbol
  | Elementary_fence_coordinate_homogeneous_cartesian_y_symbol of Elementary_fence_coordinate_homogeneous_cartesian_y_symbol_t.elementary_fence_coordinate_homogeneous_cartesian_y_symbol
  | Elementary_fence_coordinate_homogeneous_cartesian_z_symbol of Elementary_fence_coordinate_homogeneous_cartesian_z_symbol_t.elementary_fence_coordinate_homogeneous_cartesian_z_symbol
;;


(** Elementary_fence_coordinate_homogeneous_cartesian_symbol_t at 9:52:28 on 27 Sep 2016. created by version v2.4 of generator *)



