(** {3 Elementary_fence_coordinate_heterogeneous_spherical_symbol_t} *)


(** {6 Typing_for_symbol} *)

type elementary_fence_coordinate_heterogeneous_spherical_symbol =
  | Elementary_fence_coordinate_heterogeneous_spherical_rho_symbol of Elementary_fence_coordinate_heterogeneous_spherical_rho_symbol_t.elementary_fence_coordinate_heterogeneous_spherical_rho_symbol
  | Elementary_fence_coordinate_heterogeneous_spherical_phi_symbol of Elementary_fence_coordinate_heterogeneous_spherical_phi_symbol_t.elementary_fence_coordinate_heterogeneous_spherical_phi_symbol
  | Elementary_fence_coordinate_heterogeneous_spherical_theta_symbol of Elementary_fence_coordinate_heterogeneous_spherical_theta_symbol_t.elementary_fence_coordinate_heterogeneous_spherical_theta_symbol
;;


(** Elementary_fence_coordinate_heterogeneous_spherical_symbol_t at 9:52:20 on 27 Sep 2016. created by version v2.4 of generator *)



