ELEMENTARY_T_MLI :=  \
     Elementary_fence_parameter_ecppef_exponent_symbol_t.mli \
     Elementary_fence_parameter_ecppef_coefficient_symbol_t.mli \
    Elementary_fence_parameter_ecppef_symbol_t.mli \
     Elementary_fence_parameter_aopef_exponent_symbol_t.mli \
     Elementary_fence_parameter_aopef_coefficient_symbol_t.mli \
    Elementary_fence_parameter_aopef_symbol_t.mli \
   Elementary_fence_parameter_symbol_t.mli \
      Elementary_fence_coordinate_homogeneous_planar_y_symbol_t.mli \
      Elementary_fence_coordinate_homogeneous_planar_x_symbol_t.mli \
     Elementary_fence_coordinate_homogeneous_planar_symbol_t.mli \
      Elementary_fence_coordinate_homogeneous_linear_x_symbol_t.mli \
     Elementary_fence_coordinate_homogeneous_linear_symbol_t.mli \
      Elementary_fence_coordinate_homogeneous_cartesian_z_symbol_t.mli \
      Elementary_fence_coordinate_homogeneous_cartesian_y_symbol_t.mli \
      Elementary_fence_coordinate_homogeneous_cartesian_x_symbol_t.mli \
     Elementary_fence_coordinate_homogeneous_cartesian_symbol_t.mli \
    Elementary_fence_coordinate_homogeneous_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_spherical_theta_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_spherical_phi_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_spherical_rho_symbol_t.mli \
     Elementary_fence_coordinate_heterogeneous_spherical_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_polar_theta_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_polar_rho_symbol_t.mli \
     Elementary_fence_coordinate_heterogeneous_polar_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_cylindrical_zed_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_cylindrical_phi_symbol_t.mli \
      Elementary_fence_coordinate_heterogeneous_cylindrical_rho_symbol_t.mli \
     Elementary_fence_coordinate_heterogeneous_cylindrical_symbol_t.mli \
    Elementary_fence_coordinate_heterogeneous_symbol_t.mli \
   Elementary_fence_coordinate_symbol_t.mli \
  Elementary_fence_symbol_t.mli \
   Elementary_context_sector_symbol_t.mli \
   Elementary_context_domain_symbol_t.mli \
   Elementary_context_databox_symbol_t.mli \
   Elementary_context_database_symbol_t.mli \
  Elementary_context_symbol_t.mli \
    Elementary_body_parameter_tuple_ecppef_symbol_t.mli \
    Elementary_body_parameter_tuple_aopef_symbol_t.mli \
   Elementary_body_parameter_tuple_symbol_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_planar_symbol_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_linear_symbol_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_cartesian_symbol_t.mli \
    Elementary_body_coordinate_tuple_homogeneous_symbol_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_spherical_symbol_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_polar_symbol_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_cylindrical_symbol_t.mli \
    Elementary_body_coordinate_tuple_heterogeneous_symbol_t.mli \
   Elementary_body_coordinate_tuple_symbol_t.mli \
  Elementary_body_symbol_t.mli \
 Elementary_symbol_t.mli \
