type camlline_for_tag_datastructure_camltype_formula =
  | Camlline_for_tag_datastructure_camltype_uno_formula of Camlline_for_tag_datastructure_camltype_uno_formula_t.camlline_for_tag_datastructure_camltype_uno_formula
  | Camlline_for_tag_datastructure_camltype_duo_formula of Camlline_for_tag_datastructure_camltype_duo_formula_t.camlline_for_tag_datastructure_camltype_duo_formula
;;

