type camlline_for_tag_duo_current_top_formula =
  | Let_tag_ec_equal_tag_vdot_make_ec_symbol_sym_ac_soi_at_in of Entity_tag_t.entity_tag list
  | Tag_vdot_map_left_et_symbol_vdot_ec_symbol_off_et_symbol_tag_at of Entity_tag_t.entity_tag list
  | Tag_vdot_map_left_et_symbol_vdot_et_symbol_of_ec_symbol_tag_ac of Entity_tag_t.entity_tag list
  | Tag_vdot_map_left_et_symbol_vdot_is_ec_symbol_off_et_symbol_tag_at of Entity_tag_t.entity_tag list
;;
