type camlline_for_formula_uno_formula =
  | Camlline_for_formula_uno_builder_formula of Camlline_for_formula_uno_builder_formula_t.camlline_for_formula_uno_builder_formula
  | Camlline_for_formula_uno_data_formula of Camlline_for_formula_uno_data_formula_t.camlline_for_formula_uno_data_formula
  | Camlline_for_formula_uno_main_formula of Camlline_for_formula_uno_main_formula_t.camlline_for_formula_uno_main_formula
  | Camlline_for_formula_uno_son_formula of Camlline_for_formula_uno_son_formula_t.camlline_for_formula_uno_son_formula
  | Camlline_for_formula_uno_top_formula of Camlline_for_formula_uno_top_formula_t.camlline_for_formula_uno_top_formula
;;

