type camlline_for_any_uno_camltype_formula =
  | Camlline_for_any_uno_camltype_son_bare_formula of Camlline_for_any_uno_camltype_son_bare_formula_t.camlline_for_any_uno_camltype_son_bare_formula
  | Camlline_for_any_uno_camltype_son_notleaf_formula of Camlline_for_any_uno_camltype_son_notleaf_formula_t.camlline_for_any_uno_camltype_son_notleaf_formula
  | Camlline_for_any_uno_camltype_son_ofstring_formula of Camlline_for_any_uno_camltype_son_ofstring_formula_t.camlline_for_any_uno_camltype_son_ofstring_formula
  | Camlline_for_any_uno_camltype_top_formula of Camlline_for_any_uno_camltype_top_formula_t.camlline_for_any_uno_camltype_top_formula
;;
