(** {6 Typing} *)

type camlline_for_symbol_uno_formula =
  | Camlline_for_symbol_uno_builder_formula of Camlline_for_symbol_uno_builder_formula_t.camlline_for_symbol_uno_builder_formula
  | Camlline_for_symbol_uno_current_formula of Camlline_for_symbol_uno_current_formula_t.camlline_for_symbol_uno_current_formula
  | Camlline_for_symbol_uno_son_formula of Camlline_for_symbol_uno_son_formula_t.camlline_for_symbol_uno_son_formula
  | Camlline_for_symbol_uno_top_formula of Camlline_for_symbol_uno_top_formula_t.camlline_for_symbol_uno_top_formula
;;
