(** {6 Typing_for_formula} *)

type camlline_for_formula_trio_formula =
  | Camlline_for_formula_trio_son_top_builder_formula of Camlline_for_formula_trio_son_top_builder_formula_t.camlline_for_formula_trio_son_top_builder_formula
  | Camlline_for_formula_trio_son_top_data_formula of Camlline_for_formula_trio_son_top_data_formula_t.camlline_for_formula_trio_son_top_data_formula
  | Camlline_for_formula_trio_top_builder_data_formula of Camlline_for_formula_trio_top_builder_data_formula_t.camlline_for_formula_trio_top_builder_data_formula
  | Camlline_for_formula_trio_top_main_builder_formula of Camlline_for_formula_trio_top_main_builder_formula_t.camlline_for_formula_trio_top_main_builder_formula
;;
