type camlline_for_formula_duo_localset_data_formula =
  | Let_dss_of_sym_equal_localset_symbol_vdot_localset_symbol_of_ed_symbol_in of Entity_tag_t.entity_tag list  
  | List_dot_iter2_localset_symbol_by_sole_index_register_vdot_store_soi_ad_l_dss_ad_l_semicolon of Entity_tag_t.entity_tag list  
;;
