type camlline_for_any_duo_formula =
  | Camlline_for_any_duo_current_son_formula of Camlline_for_any_duo_current_son_formula_t.camlline_for_any_duo_current_son_formula
  | Camlline_for_any_duo_current_top_formula of Camlline_for_any_duo_current_top_formula_t.camlline_for_any_duo_current_top_formula
  | Camlline_for_any_duo_datastructure_formula of Camlline_for_any_duo_datastructure_formula_t.camlline_for_any_duo_datastructure_formula
  | Camlline_for_any_duo_son_top_bare_formula of Camlline_for_any_duo_son_top_bare_formula_t.camlline_for_any_duo_son_top_bare_formula
  | Camlline_for_any_duo_son_top_ofstring_formula of Camlline_for_any_duo_son_top_ofstring_formula_t.camlline_for_any_duo_son_top_ofstring_formula
  | Camlline_for_any_duo_son_top_notleaf_formula of Camlline_for_any_duo_son_top_notleaf_formula_t.camlline_for_any_duo_son_top_notleaf_formula
  | Camlline_for_any_duo_top_main_formula of Camlline_for_any_duo_top_main_formula_t.camlline_for_any_duo_top_main_formula
;;
