type camlline_for_symbol_uno_top_formula =
  | Et_symbol_vdot_name_sym_at of Entity_tag_t.entity_tag list
  | Et_symbol_vdot_string_off_sym_at of Entity_tag_t.entity_tag list
  | Let_et_symbol_equal_et_symbol_tdot_et of Entity_tag_t.entity_tag list
  | Let_sym_at_equal_tag_vdot_symbol_off_tag_tag_at_in of Entity_tag_t.entity_tag list
  | Pipe_et_symbol_tdot_et_symbol_arrow_string of Entity_tag_t.entity_tag list
  | Failwith_not_a_et_symbol_make of Entity_tag_t.entity_tag list
  | Failwith_not_a_et_symbol_name of Entity_tag_t.entity_tag list
  | Failwith_not_a_et_symbol_string_off of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_bare_et_symbol_make of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_bare_et_symbol_name of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_bare_et_symbol_string_off of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_notleaf_et_symbol_make of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_notleaf_et_symbol_name of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_notleaf_et_symbol_string_off of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_ofstring_et_symbol_make of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_ofstring_et_symbol_name of Entity_tag_t.entity_tag list
  | Failwith_not_a_topson_ofstring_et_symbol_string_off of Entity_tag_t.entity_tag list
  | Let_sym_at_equal_et_symbol_vdot_make_nam_at_s_in of Entity_tag_t.entity_tag list
  | Let_underscore_print_error_make_et_of_string_of_string of Entity_tag_t.entity_tag list
  | Let_underscore_print_error_name_et_of_string_of_string of Entity_tag_t.entity_tag list
  | Let_underscore_print_error_string_off_et_of_string_of_string of Entity_tag_t.entity_tag list
  | Print_fatal_error_make_et_of_string_of_string of Entity_tag_t.entity_tag list
  | Print_fatal_error_name_et_of_string_of_string of Entity_tag_t.entity_tag list
  | Print_fatal_error_string_off_et_of_string_of_string of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_bare_et_symbol_arrow_make of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_bare_et_symbol_arrow_name of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_bare_et_symbol_arrow_string_off of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_notleaf_et_symbol_arrow_make of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_notleaf_et_symbol_arrow_name of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_notleaf_et_symbol_arrow_string_off of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_ofstring_et_symbol_arrow_make of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_ofstring_et_symbol_arrow_name of Entity_tag_t.entity_tag list
  | With_failure_not_a_topson_ofstring_et_symbol_arrow_string_off of Entity_tag_t.entity_tag list
  | Match_sym_at_with of Entity_tag_t.entity_tag list
;;
