type camlline_for_formula_formula =
  | Camlline_for_formula_datastructure_formula of Camlline_for_formula_datastructure_formula_t.camlline_for_formula_datastructure_formula
  | Camlline_for_formula_duo_formula of Camlline_for_formula_duo_formula_t.camlline_for_formula_duo_formula
  | Camlline_for_formula_trio_formula of Camlline_for_formula_trio_formula_t.camlline_for_formula_trio_formula
  | Camlline_for_formula_uno_formula of Camlline_for_formula_uno_formula_t.camlline_for_formula_uno_formula
;;

