type camlline_for_formula_duo_main_builder_formula =
  | Let_sym_ab_l_equal_eb_symbol_list_by_em_tag_provider_vdot_provide_tag_am_in of Entity_tag_t.entity_tag list
  | One_lpar_list_dot_length_sym_ab_l_rpar_soi_am_in of Entity_tag_t.entity_tag list
;;
