type camlline_for_formula_duo_formula =
  | Camlline_for_formula_duo_builder_data_formula of Camlline_for_formula_duo_builder_data_formula_t.camlline_for_formula_duo_builder_data_formula
  | Camlline_for_formula_duo_localset_builder_formula of Camlline_for_formula_duo_localset_builder_formula_t.camlline_for_formula_duo_localset_builder_formula
  | Camlline_for_formula_duo_localset_data_formula of Camlline_for_formula_duo_localset_data_formula_t.camlline_for_formula_duo_localset_data_formula
  | Camlline_for_formula_duo_main_builder_formula of Camlline_for_formula_duo_main_builder_formula_t.camlline_for_formula_duo_main_builder_formula
  | Camlline_for_formula_duo_main_data_formula of Camlline_for_formula_duo_main_data_formula_t.camlline_for_formula_duo_main_data_formula

  | Camlline_for_formula_duo_son_builder_formula of Camlline_for_formula_duo_son_builder_formula_t.camlline_for_formula_duo_son_builder_formula
  | Camlline_for_formula_duo_son_data_formula of Camlline_for_formula_duo_son_data_formula_t.camlline_for_formula_duo_son_data_formula
  | Camlline_for_formula_duo_son_main_formula of Camlline_for_formula_duo_son_main_formula_t.camlline_for_formula_duo_son_main_formula
  | Camlline_for_formula_duo_son_top_formula of Camlline_for_formula_duo_son_top_formula_t.camlline_for_formula_duo_son_top_formula
  | Camlline_for_formula_duo_top_builder_formula of Camlline_for_formula_duo_top_builder_formula_t.camlline_for_formula_duo_top_builder_formula
  | Camlline_for_formula_duo_top_data_formula of Camlline_for_formula_duo_top_data_formula_t.camlline_for_formula_duo_top_data_formula
  | Camlline_for_formula_duo_top_main_formula of Camlline_for_formula_duo_top_main_formula_t.camlline_for_formula_duo_top_main_formula
;;

