type camlline_for_formula_duo_main_data_formula =
  | Let_sym_ad_l_equal_ed_symbol_list_by_em_tag_provider_vdot_provide_tag_am_in of Entity_tag_t.entity_tag list
  | One_lpar_list_dot_length_sym_ad_l_rpar_soi_am_in of Entity_tag_t.entity_tag list
;;
