(** {6 Typing} *)

type camlline_for_symbol_uno_son_formula =
  | Camlline_for_symbol_uno_son_bare_formula of Camlline_for_symbol_uno_son_bare_formula_t.camlline_for_symbol_uno_son_bare_formula
  | Camlline_for_symbol_uno_son_ofstring_formula of Camlline_for_symbol_uno_son_ofstring_formula_t.camlline_for_symbol_uno_son_ofstring_formula
  | Camlline_for_symbol_uno_son_notleaf_formula of Camlline_for_symbol_uno_son_notleaf_formula_t.camlline_for_symbol_uno_son_notleaf_formula
;;

