type camlline_for_formula_datastructure_formula =
  | Camlline_for_formula_datastructure_uno_formula of Camlline_for_formula_datastructure_uno_formula_t.camlline_for_formula_datastructure_uno_formula
  | Camlline_for_formula_datastructure_duo_formula of Camlline_for_formula_datastructure_duo_formula_t.camlline_for_formula_datastructure_duo_formula
  | Camlline_for_formula_datastructure_trio_formula of Camlline_for_formula_datastructure_trio_formula_t.camlline_for_formula_datastructure_trio_formula
;;

