type camlline_for_tag_datastructure_function_make_formula =
  | Camlline_for_tag_datastructure_function_make_uno_formula of Camlline_for_tag_datastructure_function_make_uno_formula_t.camlline_for_tag_datastructure_function_make_uno_formula
  | Camlline_for_tag_datastructure_function_make_duo_formula of Camlline_for_tag_datastructure_function_make_duo_formula_t.camlline_for_tag_datastructure_function_make_duo_formula
  | Camlline_for_tag_datastructure_function_make_trio_formula of Camlline_for_tag_datastructure_function_make_trio_formula_t.camlline_for_tag_datastructure_function_make_trio_formula
;;
