GROUP_T_MLI := \
    Group_for_symbol_footer_top_formula_t.mli \
   Group_for_symbol_footer_formula_t.mli \
    Group_for_symbol_body_current_son_top_formula_t.mli \
    Group_for_symbol_body_son_top_formula_t.mli \
    Group_for_symbol_body_son_formula_t.mli \
    Group_for_symbol_body_top_formula_t.mli \
   Group_for_symbol_body_formula_t.mli \
    Group_for_symbol_header_son_top_formula_t.mli \
    Group_for_symbol_header_son_formula_t.mli \
    Group_for_symbol_header_current_top_formula_t.mli \
    Group_for_symbol_header_current_son_top_formula_t.mli \
    Group_for_symbol_header_constant_formula_t.mli \
   Group_for_symbol_header_formula_t.mli \
  Group_for_symbol_formula_t.mli \
    Group_for_formula_header_top_main_formula_t.mli \
    Group_for_formula_header_top_data_formula_t.mli \
    Group_for_formula_header_top_builder_formula_t.mli \
    Group_for_formula_header_constant_formula_t.mli \
   Group_for_formula_header_formula_t.mli \
     Group_for_formula_body_top_main_formula_t.mli \
     Group_for_formula_body_top_data_formula_t.mli \
     Group_for_formula_body_top_builder_data_formula_t.mli \
     Group_for_formula_body_top_builder_formula_t.mli \
     Group_for_formula_body_top_alone_formula_t.mli \
    Group_for_formula_body_top_formula_t.mli \
     Group_for_formula_body_son_top_main_builder_formula_t.mli \
     Group_for_formula_body_son_top_main_formula_t.mli \
     Group_for_formula_body_son_top_data_formula_t.mli \
     Group_for_formula_body_son_top_builder_formula_t.mli \
     Group_for_formula_body_son_top_formula_t.mli \
     Group_for_formula_body_son_builder_formula_t.mli \
    Group_for_formula_body_son_formula_t.mli \
    Group_for_formula_body_main_data_formula_t.mli \
    Group_for_formula_body_main_builder_formula_t.mli \
    Group_for_formula_body_localset_builder_formula_t.mli \
    Group_for_formula_body_localset_data_formula_t.mli \
    Group_for_formula_body_data_alone_formula_t.mli \
    Group_for_formula_body_builder_data_formula_t.mli \
    Group_for_formula_body_builder_alone_formula_t.mli \
   Group_for_formula_body_formula_t.mli \
  Group_for_formula_formula_t.mli \
   Group_for_any_footer_formula_t.mli \
    Group_for_any_body_top_main_formula_t.mli \
    Group_for_any_body_top_formula_t.mli \
    Group_for_any_body_son_formula_t.mli \
   Group_for_any_body_formula_t.mli \
    Group_for_any_header_top_formula_t.mli \
    Group_for_any_header_constant_formula_t.mli \
   Group_for_any_header_formula_t.mli \
  Group_for_any_formula_t.mli \
 Group_formula_t.mli \

