type group_for_formula_body_builder_formula =
  | Group_for_formula_body_builder_alone_formula of Group_for_formula_body_builder_alone_formula_t.group_for_formula_body_builder_alone_formula
  | Group_for_formula_body_data_alone_formula of Group_for_formula_body_data_alone_formula_t.group_for_formula_body_data_alone_formula
  | Group_for_formula_body_builder_data_formula of Group_for_formula_body_builder_data_formula_t.group_for_formula_body_builder_data_formula
;;

