type group_for_formula_header_formula =
  | Group_for_formula_header_constant_formula of Group_for_formula_header_constant_formula_t.group_for_formula_header_constant_formula
  | Group_for_formula_header_top_builder_formula of Group_for_formula_header_top_builder_formula_t.group_for_formula_header_top_builder_formula
  | Group_for_formula_header_top_data_formula of Group_for_formula_header_top_data_formula_t.group_for_formula_header_top_data_formula
  | Group_for_formula_header_top_main_formula of Group_for_formula_header_top_main_formula_t.group_for_formula_header_top_main_formula
;;
