type group_for_formula_body_top_formula =
  | Group_for_formula_body_top_alone_formula of Group_for_formula_body_top_alone_formula_t.group_for_formula_body_top_alone_formula
  | Group_for_formula_body_top_builder_formula of Group_for_formula_body_top_builder_formula_t.group_for_formula_body_top_builder_formula
  | Group_for_formula_body_top_builder_data_formula of Group_for_formula_body_top_builder_data_formula_t.group_for_formula_body_top_builder_data_formula
  | Group_for_formula_body_top_data_formula of Group_for_formula_body_top_data_formula_t.group_for_formula_body_top_data_formula
  | Group_for_formula_body_top_main_formula of Group_for_formula_body_top_main_formula_t.group_for_formula_body_top_main_formula
;;
