type group_for_formula_body_formula =
  | Group_for_formula_body_builder_alone_formula of Group_for_formula_body_builder_alone_formula_t.group_for_formula_body_builder_alone_formula
  | Group_for_formula_body_builder_data_formula of Group_for_formula_body_builder_data_formula_t.group_for_formula_body_builder_data_formula
  | Group_for_formula_body_data_alone_formula of Group_for_formula_body_data_alone_formula_t.group_for_formula_body_data_alone_formula
  | Group_for_formula_body_localset_builder_formula of Group_for_formula_body_localset_builder_formula_t.group_for_formula_body_localset_builder_formula
  | Group_for_formula_body_localset_data_formula of Group_for_formula_body_localset_data_formula_t.group_for_formula_body_localset_data_formula
  | Group_for_formula_body_main_builder_formula of Group_for_formula_body_main_builder_formula_t.group_for_formula_body_main_builder_formula
  | Group_for_formula_body_main_data_formula of Group_for_formula_body_main_data_formula_t.group_for_formula_body_main_data_formula
  | Group_for_formula_body_son_formula of Group_for_formula_body_son_formula_t.group_for_formula_body_son_formula
  | Group_for_formula_body_top_formula of Group_for_formula_body_top_formula_t.group_for_formula_body_top_formula
;;

