type group_for_formula_body_son_formula =
  | Group_for_formula_body_son_builder_formula of Group_for_formula_body_son_builder_formula_t.group_for_formula_body_son_builder_formula
  | Group_for_formula_body_son_top_formula of Group_for_formula_body_son_top_formula_t.group_for_formula_body_son_top_formula
  | Group_for_formula_body_son_top_builder_formula of Group_for_formula_body_son_top_builder_formula_t.group_for_formula_body_son_top_builder_formula
  | Group_for_formula_body_son_top_data_formula of Group_for_formula_body_son_top_data_formula_t.group_for_formula_body_son_top_data_formula
  | Group_for_formula_body_son_top_main_formula of Group_for_formula_body_son_top_main_formula_t.group_for_formula_body_son_top_main_formula
  | Group_for_formula_body_son_top_main_builder_formula of Group_for_formula_body_son_top_main_builder_formula_t.group_for_formula_body_son_top_main_builder_formula

;;
