type group_for_formula_formula =
  | Group_for_formula_body_formula of Group_for_formula_body_formula_t.group_for_formula_body_formula
  | Group_for_formula_header_formula of Group_for_formula_header_formula_t.group_for_formula_header_formula

;;
