(** {6 Typing} *)

type item_for_symbol_formula =
  | Item_for_symbol_each_grandson_bare_formula of Item_for_symbol_each_grandson_bare_formula_t.item_for_symbol_each_grandson_bare_formula
  | Item_for_symbol_each_grandson_notleaf_formula of Item_for_symbol_each_grandson_notleaf_formula_t.item_for_symbol_each_grandson_notleaf_formula
  | Item_for_symbol_each_grandson_ofstring_formula of Item_for_symbol_each_grandson_ofstring_formula_t.item_for_symbol_each_grandson_ofstring_formula
  | Item_for_symbol_each_topson_bare_formula of Item_for_symbol_each_topson_bare_formula_t.item_for_symbol_each_topson_bare_formula
  | Item_for_symbol_each_topson_notleaf_formula of Item_for_symbol_each_topson_notleaf_formula_t.item_for_symbol_each_topson_notleaf_formula
  | Item_for_symbol_each_topson_ofstring_formula of Item_for_symbol_each_topson_ofstring_formula_t.item_for_symbol_each_topson_ofstring_formula
  | Item_for_symbol_only_top_formula of Item_for_symbol_only_top_formula_t.item_for_symbol_only_top_formula
  | Item_for_symbol_by_group_topsons_formula of Item_for_symbol_by_group_topsons_formula_t.item_for_symbol_by_group_topsons_formula
;;




