type section_for_formula_body_formula =
  | Section_for_formula_body_builder_data_formula of Section_for_formula_body_builder_data_formula_t.section_for_formula_body_builder_data_formula
  | Section_for_formula_body_localset_builder_formula of Section_for_formula_body_localset_builder_formula_t.section_for_formula_body_localset_builder_formula
  | Section_for_formula_body_localset_data_formula of Section_for_formula_body_localset_data_formula_t.section_for_formula_body_localset_data_formula
  | Section_for_formula_body_son_builder_formula of Section_for_formula_body_son_builder_formula_t.section_for_formula_body_son_builder_formula
  | Section_for_formula_body_son_top_formula of Section_for_formula_body_son_top_formula_t.section_for_formula_body_son_top_formula
  | Section_for_formula_body_son_top_builder_formula of Section_for_formula_body_son_top_builder_formula_t.section_for_formula_body_son_top_builder_formula
  | Section_for_formula_body_son_top_data_formula of Section_for_formula_body_son_top_data_formula_t.section_for_formula_body_son_top_data_formula
  | Section_for_formula_body_son_top_main_formula of Section_for_formula_body_son_top_main_formula_t.section_for_formula_body_son_top_main_formula
  | Section_for_formula_body_son_top_main_builder_formula of Section_for_formula_body_son_top_main_builder_formula_t.section_for_formula_body_son_top_main_builder_formula
  | Section_for_formula_body_top_formula of Section_for_formula_body_top_formula_t.section_for_formula_body_top_formula
  | Section_for_formula_body_top_builder_formula of Section_for_formula_body_top_builder_formula_t.section_for_formula_body_top_builder_formula
  | Section_for_formula_body_top_builder_data_formula of Section_for_formula_body_top_builder_data_formula_t.section_for_formula_body_top_builder_data_formula
  | Section_for_formula_body_top_data_formula of Section_for_formula_body_top_data_formula_t.section_for_formula_body_top_data_formula
  | Section_for_formula_body_top_main_builder_formula of Section_for_formula_body_top_main_builder_formula_t.section_for_formula_body_top_main_builder_formula
  | Section_for_formula_body_top_main_data_formula of Section_for_formula_body_top_main_data_formula_t.section_for_formula_body_top_main_data_formula
;;

