type section_for_formula_formula =
  | Section_for_formula_body_formula of Section_for_formula_body_formula_t.section_for_formula_body_formula
  | Section_for_formula_header_formula of Section_for_formula_header_formula_t.section_for_formula_header_formula
;;

