type section_for_formula_header_formula =
  | Section_for_formula_header_constant_formula of Section_for_formula_header_constant_formula_t.section_for_formula_header_constant_formula
  | Section_for_formula_header_top_builder_formula of Section_for_formula_header_top_builder_formula_t.section_for_formula_header_top_builder_formula

  | Section_for_formula_header_top_data_formula of Section_for_formula_header_top_data_formula_t.section_for_formula_header_top_data_formula

  | Section_for_formula_header_top_main_formula of Section_for_formula_header_top_main_formula_t.section_for_formula_header_top_main_formula
;;
