type coordinate_set_fence_homogeneous_cartesian_y_container = Coordinate_set_fence_homogeneous_cartesian_y_tag_t.coordinate_set_fence_homogeneous_cartesian_y_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_1containee_t.sh coordinate_set_fence_homogeneous_cartesian_y  *)
(* using template_container_as_uno_fence_bud_1containee_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:44 (UTC+0100) *)

