type coordinate_set_fence_heterogeneous_cylindrical_phi_container = Coordinate_set_fence_heterogeneous_cylindrical_phi_tag_t.coordinate_set_fence_heterogeneous_cylindrical_phi_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_1containee_t.sh coordinate_set_fence_heterogeneous_cylindrical_phi  *)
(* using template_container_as_uno_fence_bud_1containee_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:44 (UTC+0100) *)

