type coordinate_set_body_tuple_homogeneous_linear_container = Coordinate_set_fence_homogeneous_linear_x_tag_t.coordinate_set_fence_homogeneous_linear_x_tag Singlet_t.singlet;;

(* generated by ./do_container_as_singlet_body_bud_1containee_t.sh coordinate_set_body_tuple_homogeneous_linear coordinate_set_fence_homogeneous_linear_x *)
(* using ./template_container_as_singlet_body_bud_1containee_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:45 (UTC+0100) *)

