type coordinate_context_sector_container = Coordinate_context_domain_tag_t.coordinate_context_domain_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh coordinate_context_sector coordinate_context_domain *)
(* using template_container_as_list_context_bud_1containee_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:45 (UTC+0100) *)

