(** {3 Coordinate_set_fence_heterogeneous_container_t} *)


(** {6 Typing_for_container} *)

type coordinate_set_fence_heterogeneous_container =
  | Coordinate_set_fence_heterogeneous_cylindrical_container of Coordinate_set_fence_heterogeneous_cylindrical_container_t.coordinate_set_fence_heterogeneous_cylindrical_container
  | Coordinate_set_fence_heterogeneous_polar_container of Coordinate_set_fence_heterogeneous_polar_container_t.coordinate_set_fence_heterogeneous_polar_container
  | Coordinate_set_fence_heterogeneous_spherical_container of Coordinate_set_fence_heterogeneous_spherical_container_t.coordinate_set_fence_heterogeneous_spherical_container
;;


(** Coordinate_set_fence_heterogeneous_container_t at 11:33:3 on 14 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh coordinate_set_fence_heterogeneous *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/coordinateset/coordinateset_symbols/Coordinate_set_fence_heterogeneous_symbol_t.ml *)
(* adding supplement_coordinate_set_fence_heterogeneous_container_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:46 (UTC+0100) *)
