(** {3 Coordinate_container_t} *)


(** {6 Typing_for_container} *)

type coordinate_container =
  | Coordinate_context_container of Coordinate_context_container_t.coordinate_context_container
  | Coordinate_set_container of Coordinate_set_container_t.coordinate_set_container
;;


(** Coordinate_container_t at 11:32:59 on 14 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh coordinate *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/coordinateset/coordinateset_symbols/Coordinate_symbol_t.ml *)
(* adding supplement_coordinate_container_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:47 (UTC+0100) *)
