(** {3 Coordinate_context_container_t} *)


(** {6 Typing_for_container} *)

type coordinate_context_container =
  | Coordinate_context_database_container of Coordinate_context_database_container_t.coordinate_context_database_container
  | Coordinate_context_databox_container of Coordinate_context_databox_container_t.coordinate_context_databox_container
  | Coordinate_context_domain_container of Coordinate_context_domain_container_t.coordinate_context_domain_container
  | Coordinate_context_sector_container of Coordinate_context_sector_container_t.coordinate_context_sector_container
;;


(** Coordinate_context_container_t at 11:32:59 on 14 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh coordinate_context *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/coordinateset/coordinateset_symbols/Coordinate_context_symbol_t.ml *)
(* adding supplement_coordinate_context_container_t.ml *)
(* Done on vendredi 16 décembre 2016, 15:34:45 (UTC+0100) *)
