DB1FIGURE_LEXER_T_MLI :=  \
    Db1pointsdata_lexer_token_units_length_symbol_t.mli \
    Db1pointsdata_lexer_token_units_angle_symbol_t.mli \
   Db1pointsdata_lexer_token_units_symbol_t.mli \
    Db1pointsdata_lexer_token_figure_kind_symbol_t.mli \
   Db1pointsdata_lexer_token_figure_symbol_t.mli \
  Db1pointsdata_lexer_token_symbol_t.mli \
   Db1pointsdata_lexer_keyword_figure_symbol_t.mli \
    Db1pointsdata_lexer_keyword_coordinates_units_symbol_t.mli \
   Db1pointsdata_lexer_keyword_coordinates_symbol_t.mli \
   Db1pointsdata_lexer_keyword_character_symbol_t.mli \
  Db1pointsdata_lexer_keyword_symbol_t.mli \
    Db1pointsdata_lexer_basic_word_uppercase_symbol_t.mli \
    Db1pointsdata_lexer_basic_word_lowercase_symbol_t.mli \
    Db1pointsdata_lexer_basic_word_capitalized_symbol_t.mli \
    Db1pointsdata_lexer_basic_word_anycase_symbol_t.mli \
   Db1pointsdata_lexer_basic_word_symbol_t.mli \
   Db1pointsdata_lexer_basic_string_symbol_t.mli \
   Db1pointsdata_lexer_basic_float_symbol_t.mli \
  Db1pointsdata_lexer_basic_symbol_t.mli \
 Db1pointsdata_lexer_symbol_t.mli \
