INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(PROPERTYSET_SYMBOLS_DIR) \
	$(PROPERTYSET_TAGS_DIR) \
	$(PROPERTYSET_BUILDER_TREES_DIR) \
 