(** {3 Property_operand_body_target_container_t} *)


(** {6 Typing_for_container} *)

type property_operand_body_target_container =
  | Property_operand_body_target_calculated_container of Property_operand_body_target_calculated_container_t.property_operand_body_target_calculated_container
  | Property_operand_body_target_created_container of Property_operand_body_target_created_container_t.property_operand_body_target_created_container
  | Property_operand_body_target_measured_container of Property_operand_body_target_measured_container_t.property_operand_body_target_measured_container
;;


(** Property_operand_body_target_container_t at 10:48:29 on 19 Mar 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh property_operand_body_target *)
(* using /keep/sources/ocaml_top/setup/frames/productsector/propertyset/propertyset_symbols/Property_operand_body_target_symbol_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:06 (UTC+0200) *)
