(** {3 Property_command_body_title_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FPRO:Property_command_body_title_container_v";
   "Needs : FPRO:Property_operand_fence_external_tag_v";
   "Needs : FPRO:Property_son_tag_list_by_property_father_tag_provider_v";
   "Needs : BPRO:Property_fence_by_property_tag_provider_v";
   "Remark : Container is Property_operand_fence_external_tag Singlet";
   "Remark : Containee_1 is Property_operand_fence_external is also Containee_up";
   "Remark : Builders are Property";
   "Definition : a Builder (for an Entity of a Domain) is a son of its Builder-Subtree";
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a Building is the same Datastructure as Container filled with Builders"; 
   "What-is-it : it is a Body Bud Singlet of Property_operand_fence_external_tag";
   "Author : François Colonna 21 mai 2017 at 08:24:27+01:00";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name con_pct =
  Singlet_v.name 
    Property_operand_fence_external_tag_v.name
    con_pct
;;

let string_off con_pct =
  Singlet_v.name 
    Property_operand_fence_external_tag_v.string_off
    con_pct
;;

let longname con_pct =
  Singlet_v.name 
    Property_operand_fence_external_tag_v.longname
    con_pct
;;

let fullname con_pct =
  Singlet_v.name 
    Property_operand_fence_external_tag_v.fullname
    con_pct
;;

(** {6 Builders} *)

(** {9 Builder Tag list} *)

let builder_tag_list_of_tag tag_pct =
  let tag_pro = Property_command_body_title_tag_v.property_tag_of_property_command_body_title_tag tag_pct in
  Property_son_tag_list_by_property_father_tag_provider_v.provide
    tag_pro
;;

(** {9 Builder Tag Datastructures} *)

let builder_tag_uno_of_tag tag_pct =
  let tag_pro_l = builder_tag_list_of_tag tag_pct in
  Uno_v.uno_of_list tag_pro_l
;;

(** {9 Builder Tag Tuple} *)

let builder_tag_tuple_of_tag tag_pct =
  let tag_pro_u = builder_tag_uno_of_tag tag_pct in
  Tuple_v.tuple_of_uno tag_pro_u
;;

(** {9 Building as Builder Tag uno} *)

let building_of_tag tag_pct =
  builder_tag_uno_of_tag tag_pct
;;

(** {6 Container} *)

(** {9 Coercing Up Containee_up Tag to Builder Tag} *)

let builder_tag_of_containee_1_tag tag_pce =
  Tag_v.map_entity 
    Property_symbol_v.property_symbol_of_property_operand_fence_external_symbol
    tag_pce
;;

(** {9 Coercing Down Builder Tag to Containee_1 Tag} *)

let containee_1_tag_off_builder_tag tag_pro =
  Tag_v.map_entity 
    Property_symbol_v.property_operand_fence_external_symbol_off_property_symbol
    tag_pro
;;

(** {9 Containee_1 Tag list} *)

let containee_1_tag_list_of_tag tag_pct =
  let tag_pro_l = builder_tag_list_of_tag tag_pct in
  List.map containee_1_tag_off_builder_tag tag_pro_l 
;;

(** {9 Containee_1 Tag Uno} *)

let containee_1_tag_uno_of_tag tag_pct =
  let tag_pro_u = builder_tag_uno_of_tag tag_pct in
  Uno_v.map containee_1_tag_off_builder_tag tag_pro_u
;;

(** {9 Container_of_tag : Containee Datastructure} *)

let containee_1_of_tag tag_pct =
  let tag_pce_u = containee_1_tag_uno_of_tag tag_pct in
  Uno_v.element_off_uno tag_pce_u
;;

let container_of_tag tag_pct =
  let tag_pce = containee_1_of_tag tag_pct in
  Singlet_v.make tag_pce
;;

(** {6 Fence *)

let fence_as_list_of_tag tag_pct =
  let tag_pro = Property_command_body_title_tag_v.property_tag_of_property_command_body_title_tag tag_pct in
  Property_fence_by_property_tag_provider_v.provide tag_pro
;;

let fence_as_uno_of_tag tag_pct =
  let fen_pct = fence_as_list_of_tag tag_pct in
  Uno_v.uno_of_list fen_pct
;;

let fence_as_tuple_of_tag tag_pct =
  let fen_l = fence_as_list_of_tag tag_pct in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_pct =
  let fen_l = fence_as_list_of_tag tag_pct in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_singlet_body_bud_1containee_v.sh property_command_body_title pct property_operand_fence_external pce *)
(* using template_container_as_singlet_body_bud_1containee_v.ml *)
(* Done on dimanche 21 mai 2017, 10:59:59 (UTC+0200) *)
