(** {3 Property_operator_fence_tounit_write_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FPRO:Property_operator_fence_tounit_write_container_v";
   "Needs : BPRO:Property_any_category_by_sole_index_extractor_v";
   "Needs : BPRO:Property_fence_by_property_tag_provider_v";
   "Needed-by: ";
   "Definition : a Builder (for an Entity of a Domain) is a son of its B-Tree i.e. Coerced Up";
   "Definition : a Builder of a fence Container is its own Tag Coerced Up";
   "Builder_tag : Property_tag";
   "Definition : a Building is the same Datastructure as a Container but filled with Builders"; 
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : the Containee Tag of a fence Container is its own Tag";
   "Containee_tag : Property_operator_fence_tounit_write_tag";
   "Definition : the Fence is the Tag list (Coerced Up) of the Leaf Entities of the B-Tree of any Entity";
   "Fence : Property_tag list";
   "Definition : a Bud type is a Stem type with only one constructor of string";
   "What-is-it: it is a container of a Fence Bud Type as a Uno of Property_operator_fence_tounit_write_tag (i.e. Property_operator_fence_tounit_write_tag)";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Coercing Up Tag} *)

let builder_tag_of_containee_tag tag_ptw =
  Tag_v.map_entity 
    Property_symbol_v.property_symbol_of_property_operator_fence_tounit_write_symbol 
    tag_ptw
;;

(** {6 Coercing Down Tag} *)

let containee_tag_off_builder_tag tag_pro =
  Tag_v.map_entity
    Property_symbol_v.property_operator_fence_tounit_write_symbol_off_property_symbol
    tag_pro
;;

(** {6 Builder Tag Datastructures : Building} *)

let building_of_tag tag_ptw =
  let tag_pro = builder_tag_of_containee_tag tag_ptw in
  Uno_v.make tag_pro
;;

let builder_tag_uno tag_ptw =
  building_of_tag tag_ptw
;;

let builder_tag_list_of_tag tag_ptw =
  let tag_pro = builder_tag_of_containee_tag tag_ptw in
  [tag_pro]
;;

let builder_tag_tuple_of_tag tag_ptw =
  let bug = building_of_tag tag_ptw in
  Tuple_v.tuple_of_uno bug
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_ptw =
  Uno_v.make tag_ptw
;;

(** {6 Fence list *)

let fence_as_list_of_tag tag_ptw =
  let tag_pro = builder_tag_of_containee_tag tag_ptw in
  Property_fence_by_property_tag_provider_v.provide tag_pro
;;

let fence_as_tuple_of_tag tag_ptw =
  let fen_l = fence_as_list_of_tag tag_ptw in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_ptw =
  let fen_l = fence_as_list_of_tag tag_ptw in
  Tuple_list_v.make fen_l
;;

(** {6 Naming_for_container} *)

let name con_ptw =
  Uno_v.name 
    Property_operator_fence_tounit_write_tag_v.name
    con_ptw
;;

let string_off con_ptw =
  Uno_v.name 
    Property_operator_fence_tounit_write_tag_v.string_off
    con_ptw
;;

let longname con_ptw =
  Uno_v.name 
    Property_operator_fence_tounit_write_tag_v.longname
    con_ptw
;;

let fullname con_ptw =
  Uno_v.name 
    Property_operator_fence_tounit_write_tag_v.fullname
    con_ptw
;;


(* generated by ./do_container_as_uno_fence_bud_0containee_v.sh property_operator_fence_tounit_write ptw *)
(* using ./template_container_as_uno_fence_bud_0containee_v.ml *)
(* Done on dimanche 21 mai 2017, 10:59:58 (UTC+0200) *)
