type property_context_inputbase_container = Property_context_inputbox_tag_t.property_context_inputbox_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh property_context_inputbase property_context_inputbox *)
(* using template_container_as_list_context_bud_1containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:03 (UTC+0200) *)

