type property_context_sector_container = Property_context_domain_tag_t.property_context_domain_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh property_context_sector property_context_domain *)
(* using template_container_as_list_context_bud_1containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:02 (UTC+0200) *)

