type property_operator_fence_tounit_write_container = Property_operator_fence_tounit_write_tag_t.property_operator_fence_tounit_write_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_0containee_t.sh property_operator_fence_tounit_write *)
(* using template_container_as_uno_fence_bud_0containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:02 (UTC+0200) *)

