type property_target_body_implicit_tounit_container = (Property_operator_fence_tounit_tag_t.property_operator_fence_tounit_tag, Property_operand_tag_t.property_operand_tag) Doublet_t.doublet;;

(* generated by ./do_container_as_doublet_body_bud_2containee_t.sh property_target_body_implicit_tounit property_operator_fence_tounit property_operand  *)
(* using template_container_as_doublet_body_bud_2containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:05 (UTC+0200) *)

