type property_operand_body_target_created_container = (Property_operator_fence_creation_toentity_tag_t.property_operator_fence_creation_toentity_tag, Property_operand_tag_t.property_operand_tag) Doublet_t.doublet;;

(* generated by ./do_container_as_doublet_body_bud_2containee_t.sh property_operand_body_target_created property_operator_fence_creation_toentity property_operand  *)
(* using template_container_as_doublet_body_bud_2containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:05 (UTC+0200) *)

