type property_command_body_set_container = Property_command_body_tag_t.property_command_body_tag Singlet_t.singlet;;

(* generated by ./do_container_as_singlet_body_bud_1containee_t.sh property_command_body  *)
(* using ./template_container_as_singlet_body_bud_1containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:03 (UTC+0200) *)

