(** {3 Property_operator_fence_creation_container_t} *)


(** {6 Typing_for_container} *)

type property_operator_fence_creation_container =
  | Property_operator_fence_creation_toentity_container of Property_operator_fence_creation_toentity_container_t.property_operator_fence_creation_toentity_container
  | Property_operator_fence_creation_tomeasure_container of Property_operator_fence_creation_tomeasure_container_t.property_operator_fence_creation_tomeasure_container
  | Property_operator_fence_creation_tobasic_container of Property_operator_fence_creation_tobasic_container_t.property_operator_fence_creation_tobasic_container
;;


(** Property_operator_fence_creation_container_t at 10:48:33 on 19 Mar 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh property_operator_fence_creation *)
(* using /keep/sources/ocaml_top/setup/frames/productsector/propertyset/propertyset_symbols/Property_operator_fence_creation_symbol_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:06 (UTC+0200) *)
