type property_command_body_debug_container = Property_operand_fence_external_tag_t.property_operand_fence_external_tag Duo_t.duo;;

(* generated by ./do_container_as_duo_body_bud_1containee_t.sh property_command_body_debug property_operand_fence_external  *)
(* using template_container_as_duo_body_bud_1containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:03 (UTC+0200) *)

