(** {3 Property_command_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FPRO:Property_command_container_v";
   "Needs : FPRO:Property_command_body_container_v";
   "Needs : DPRO:Property_fence_by_property_tag_provider_v";
   "Needed-by: ";
   "Remark : Container is _tag Singlet";
   "Remark : Containee_1 is  is also Containee_up";
   "Remark : Builders are Property";
   "Definition : a Builder (for an Entity of a Domain) is a son of its Builder-Subtree";
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a Building is the same Datastructure as Container filled with Builders"; 
   "Author : François Colonna 21 mai 2017 at 10:14:15+01:00";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name = function
  | Property_command_container_t.Property_command_body_container con_pcb ->
      (Property_command_body_container_v.name con_pcb)
;;

let string_off = function
  | Property_command_container_t.Property_command_body_container con_pcb ->
      (Property_command_body_container_v.string_off con_pcb)
;;

let longname = function
  | Property_command_container_t.Property_command_body_container con_pcb ->
      (Property_command_body_container_v.longname con_pcb)
;;

let fullname = function
  | Property_command_container_t.Property_command_body_container con_pcb ->
      (Property_command_body_container_v.fullname con_pcb)
;;

(** {6 Coercing Tag} *)

(** {6 Builders} *)

(** {9 Builder Tag list} *)

let builder_tag_list_of_tag tag_pco =
  let (sym_pco, soi_pco) = tag_pco in
  match sym_pco with
  | Property_command_symbol_t.Property_command_body_symbol sym_pcb ->
      let tag_pcb = Tag_v.make sym_pcb soi_pco in
      Property_command_body_container_v.builder_tag_list_of_tag tag_pcb
;;

(** {9 Builder Tag Tuple} *)

let builder_tag_tuple_of_tag tag_pco =
  let (sym_pco, soi_pco) = tag_pco in
  match sym_pco with
  | Property_command_symbol_t.Property_command_body_symbol sym_pcb ->
      let tag_pcb = Tag_v.make sym_pcb soi_pco in
      Property_command_body_container_v.builder_tag_tuple_of_tag tag_pcb
;;

(** {9 Building as Builder Tag tuple} *)

let building_of_tag tag_pco =
  builder_tag_tuple_of_tag tag_pco
;;

(** {6 Container} *)

let container_of_tag tag_pco =
  let (sym_pco, soi_pco) = tag_pco in
  match sym_pco with
  | Property_command_symbol_t.Property_command_body_symbol sym_pcb ->
      let tag_pcb = Tag_v.make sym_pcb soi_pco in
      let con_pcb = Property_command_body_container_v.container_of_tag tag_pcb in
      Property_command_container_t.Property_command_body_container con_pcb
;;

(** {6 Fence *)

let fence_as_list_of_tag tag_pco =
  let tag_pro = Property_command_tag_v.property_tag_of_property_command_tag tag_pco in
  Property_fence_by_property_tag_provider_v.provide tag_pro
;;

let fence_as_tuple_of_tag tag_pco =
  let fen_l = fence_as_list_of_tag tag_pco in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_pco =
  let fen_l = fence_as_list_of_tag tag_pco in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_tuple_body_trunc_1sibling_0containee_v.sh property_command pco property_command_body pcb *)
(* using template_container_as_tuple_body_trunc_1sibling_0containee_v.ml *)
(* Done on dimanche 21 mai 2017, 11:00:03 (UTC+0200) *)
