(** {3 Property_command_body_debug_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FPRO:Property_command_body_debug_container_v";
   "Needs : FPRO:Property_operand_fence_external_tag_v";
   "Needs : FPRO:Property_son_tag_list_by_property_father_tag_provider_v";
   "Needs : BPRO:Property_fence_by_property_tag_provider_v";
   "Remark : Container is Property_operand_fence_external_tag Duo";
   "Remark : Containee_1 is Property_operand_fence_external is also Containee_up";
   "Remark : Builders are Property";
   "Definition : a Builder (for an Entity of a Domain) is a son of its Builder-Subtree";
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a Building is the same Datastructure as Container filled with Builders"; 
   "What-is-it : it is a Body Bud Duo of Property_operand_fence_external_tag";
   "Author : François Colonna 21 mai 2017 at 08:24:27+01:00";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name con_pcd =
  Duo_v.name 
    Property_operand_fence_external_tag_v.name
    con_pcd
;;

let string_off con_pcd =
  Duo_v.name 
    Property_operand_fence_external_tag_v.string_off
    con_pcd
;;

let longname con_pcd =
  Duo_v.name 
    Property_operand_fence_external_tag_v.longname
    con_pcd
;;

let fullname con_pcd =
  Duo_v.name 
    Property_operand_fence_external_tag_v.fullname
    con_pcd
;;

(** {6 Coercing Up Tag} *)

let coerce_up_tag tag_pcd =
  Tag_v.map_entity 
    Property_symbol_v.property_symbol_of_property_command_body_debug_symbol 
    tag_pcd
;;

(** {6 Builders} *)

(** {9 Builder Tag list} *)

let builder_tag_list_of_tag tag_pcd =
  let tag_pro = coerce_up_tag tag_pcd in
  Property_son_tag_list_by_property_father_tag_provider_v.provide
    tag_pro
;;

(** {9 Builder Tag Datastructures} *)

let builder_tag_duo_of_tag tag_pcd =
  let tag_bui_l = builder_tag_list_of_tag tag_pcd in
  Duo_v.duo_of_list tag_bui_l
;;

(** {9 Builder Tag Tuple} *)

let builder_tag_tuple_of_tag tag_pcd =
  let tag_bui_d = builder_tag_duo_of_tag tag_pcd in
  Tuple_v.tuple_of_duo tag_bui_d
;;

(** {9 Building as Builder Tag duo} *)

let building_of_tag tag_pcd =
  builder_tag_duo_of_tag tag_pcd
;;

(** {6 Container} *)

(** {9 Coercing Up Containee_up Tag to Builder Tag} *)

let builder_tag_of_containee_1_tag tag_poe =
  Tag_v.map_entity 
    Property_symbol_v.property_symbol_of_property_operand_fence_external_symbol
    tag_poe
;;

(** {9 Coercing Down Builder Tag to Containee_1 Tag} *)

let containee_1_tag_off_builder_tag tag_bui =
  Tag_v.map_entity 
    Property_symbol_v.property_operand_fence_external_symbol_off_property_symbol
    tag_bui
;;

(** {9 Containee_1 Tag list} *)

let containee_1_tag_list_of_tag tag_pcd =
  let tag_bui_l = builder_tag_list_of_tag tag_pcd in
  List.map containee_1_tag_off_builder_tag tag_bui_l 
;;

(** {9 Containee_1 Tag Duo} *)

let containee_1_tag_duo_of_tag tag_pcd =
  let tag_poe_l = containee_1_tag_list_of_tag tag_pcd in
  Duo_v.duo_of_list tag_poe_l
;;

(** {9 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_pcd =
  let tag_pro_l = builder_tag_list_of_tag tag_pcd in
  let tag_poe_l = List.map containee_1_tag_off_builder_tag tag_pro_l in
  Duo_v.duo_of_list tag_poe_l
;;

(** {9 Extracting Containees off Tag} *)

let containee_as_operator_tag tag_pcd =
  let con_pcd = container_of_tag tag_pcd in
  Duo_v.first_off_duo con_pcd
;;

let containee_as_operand_tag tag_pcd =
  let con_pcd = container_of_tag tag_pcd in
  Duo_v.second_off_duo con_pcd
;;

(** {6 Fence *)

let fence_as_list_of_tag tag_pcd =
  let tag_pro = coerce_up_tag tag_pcd in
  Property_fence_by_property_tag_provider_v.provide tag_pro
;;

let fence_as_duo_of_tag tag_pcd =
  let fen_pcd = fence_as_list_of_tag tag_pcd in
  Duo_v.duo_of_list fen_pcd
;;

let fence_as_tuple_of_tag tag_pcd =
  let fen_l = fence_as_list_of_tag tag_pcd in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_pcd =
  let fen_l = fence_as_list_of_tag tag_pcd in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_duo_body_bud_1containee_v.sh property_command_body_debug pcd property_operand_fence_external poe *)
(* using template_container_as_duo_body_bud_1containee_v.ml *)
(* Done on dimanche 21 mai 2017, 10:59:58 (UTC+0200) *)
