type property_operand_fence_external_container = Property_operand_fence_external_tag_t.property_operand_fence_external_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_0containee_t.sh property_operand_fence_external *)
(* using template_container_as_uno_fence_bud_0containee_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:00 (UTC+0200) *)

