(** {3 Property_operator_fence_container_t} *)


(** {6 Typing_for_container} *)

type property_operator_fence_container =
  | Property_operator_fence_creation_container of Property_operator_fence_creation_container_t.property_operator_fence_creation_container
  | Property_operator_fence_tounit_container of Property_operator_fence_tounit_container_t.property_operator_fence_tounit_container
;;


(** Property_operator_fence_container_t at 10:48:32 on 19 Mar 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh property_operator_fence *)
(* using /keep/sources/ocaml_top/setup/frames/productsector/propertyset/propertyset_symbols/Property_operator_fence_symbol_t.ml *)
(* Done on dimanche 21 mai 2017, 10:54:06 (UTC+0200) *)
