FROM_FILES_V_ML := \
Basicname_database_by_figure_context_databox_tag_provider_u_any.ml \
Basicname_databox_by_figure_context_databox_tag_provider_u_any.ml \
Basicname_databox_n_basicname_database_by_figure_context_databox_tag_provider_u_any.ml \
Basicname_figure_by_figure_set_fence_tag_provider_u_any.ml \
Coordinate_set_body_tuple_string_off_by_figure_set_fence_tag_provider_u_any.ml \
Figure_any_category_by_sole_index_extractor_u_any.ml \
Figure_as_context_database_tag_by_basicname_database_provider_u_any.ml \
Figure_as_context_databox_tag_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_as_context_domain_tag_by_unit_provider_u_any.ml \
Figure_as_context_sector_tag_by_unit_provider_u_any.ml \
Figure_as_context_tag_quatuor_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_basicname_databox_by_any_sole_index_provider_u_any.ml \
Figure_basicname_domain_by_unit_provider_u_any.ml \
Figure_basicname_quatuor_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_basicname_sector_by_unit_provider_u_any.ml \
Figure_bridge_by_figure_set_fence_tag_provider_u_any.ml \
Figure_context_database_tag_by_basicname_database_provider_u_any.ml \
Figure_context_databox_sole_index_by_any_sole_index_provider_u_any.ml \
Figure_context_databox_symbol_by_any_sole_index_provider_u_any.ml \
Figure_context_databox_tag_by_any_sole_index_provider_u_any.ml \
Figure_context_databox_tag_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_context_domain_tag_by_unit_provider_u_any.ml \
Figure_context_sector_tag_by_unit_provider_u_any.ml \
Figure_context_tag_quadruplet_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_fence_by_figure_tag_provider_u_any.ml \
Figure_name_by_figure_set_fence_tag_provider_u_any.ml \
Figure_set_fence_tag_list_by_figure_tag_provider_u_any.ml \
Figure_set_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Figure_son_tag_list_by_figure_father_tag_provider_u_any.ml \
Figure_symbol_by_sole_index_provider_u_any.ml \
Figure_symbol_from_db1pointsdata_symbol_translations_u_any.ml \
Figure_symbol_subtree_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_any.ml \
Figure_tag_all_list_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_tag_all_list_by_figure_context_databox_tag_provider_u_any.ml \
Figure_tag_subtree_by_figure_tag_provider_u_any.ml \
Figure_tag_tree_by_basicname_databox_n_basicname_database_provider_u_any.ml \
Figure_tag_tree_by_figure_context_databox_tag_provider_u_any.ml \

FROM_FILES_U_ML := \
Figure_any_category_by_sole_index_extractor_u_cc_pvtz.ml \
Figure_as_symbol_subtree_by_basicname_databox_n_basicname_database_provider_u_point_a.ml \
Figure_as_symbol_subtree_by_basicname_databox_n_basicname_database_provider_u_segment_s.ml \
Figure_set_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_u_segment_bc.ml \
Figure_symbol_subtree_by_basicname_databox_n_basicname_database_provider_u_segment_bc.ml \
Figure_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_u_segment_bc.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_cc_pvtz.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_lanl2dz_analysis.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_lanl2dz_cpu.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_lanl2dz.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_try_ao_analysis.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_try_ao.ml \
Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_try_ao_trace.ml \
Figure_tag_all_list_by_basicname_databox_n_basicname_database_provider_u_try_ao.ml \
Figure_tag_all_list_by_figure_context_databox_tag_provider_u_try_ao.ml \
Figure_tag_subtree_by_figure_tag_provider_u_lanl2dz.ml \
Figure_tag_tree_by_basicname_databox_n_basicname_database_provider_u_cc_pvtz.ml \
Figure_tag_tree_by_basicname_databox_n_basicname_database_provider_u_segment_bc.ml \
Figure_tag_tree_by_basicname_databox_n_basicname_database_provider_u_try_ao.ml \
Figure_tag_tree_by_figure_context_databox_tag_provider_u_lanl2dz_analysis.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
$(FROM_FILES_U_ML) \

