LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(QUANTUM_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_LEXER_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_PARSER_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(FIGURESET_SYMBOLS_DIR) \
	$(FIGURESET_TAGS_DIR) \
	$(FIGURESET_BUILDER_TREES_DIR) \
 