#!/bin/bash

alias ins="cd $INS"
alias exs="cd $EXS"
alias prs="cd $PRS"
alias figs="cd $FIGS"
alias sfig="cd $SFIG"
alias bfig="cd $BFIG"
alias ffig="cd $FFIG"
alias skes="cd $SKES"
alias bske="cd $BSKE"
alias sske="cd $SSKE"
alias nwc="cd $NWC"
alias nwcs="cd $NWCS"
alias bnwc="cd $BNWC"
alias snwc="cd $SNWC"
alias pars="cd $PARS"
alias bpar="cd $BPAR"
alias vpar="cd $VPAR"
alias pros="cd $PROS"
alias fpro="cd $FPRO"
