val molecule_aminoacid_regular_symbol_of_molecule_aminoacid_regular_olc_symbol :
  Molecule_aminoacid_regular_olc_symbol_t.molecule_aminoacid_regular_olc_symbol ->
    Molecule_aminoacid_regular_symbol_t.molecule_aminoacid_regular_symbol
;;

val molecule_aminoacid_regular_olc_symbol_of_char :
  char ->
    Molecule_aminoacid_regular_olc_symbol_t.molecule_aminoacid_regular_olc_symbol
;;

val molecule_aminoacid_regular_olc_symbol_of_string :
  string ->
    Molecule_aminoacid_regular_olc_symbol_t.molecule_aminoacid_regular_olc_symbol
;;

