  
MEASURES_T_MLI := \
Measure_canonical_quantum_t.mli \
Measure_canonical_classical_t.mli \
Measure_canonical_t.mli \
 \
Measure_actual_none_t.mli \
Measure_actual_time_t.mli \
Measure_actual_temperature_t.mli \
Measure_actual_mass_t.mli \
Measure_actual_length_t.mli \
Measure_actual_energy_t.mli \
Measure_actual_charge_t.mli \
Measure_actual_angle_t.mli \
Measure_actual_action_t.mli \
Measure_actual_t.mli \
 \
Measure_t.mli \
 
MEASURES_U_ML := $(subst _t.mli,_u_any.ml,$(MEASURES_T_MLI)) 
MEASURES_TV_MLI := $(MEASURES_T_MLI) $(MEASURES_U_ML)
 
READEES_T_MLI := \
Readee_basic_string_t.mli \
Readee_basic_float_t.mli \
Readee_basic_integer_t.mli \
Readee_basic_boolean_t.mli \
Readee_basic_t.mli \
Readee_t.mli \
 
READEES_U_ML := $(subst _t,_v,$(READEES_T_MLI)) 
READEES_TV_MLI := $(READEES_T_MLI) $(READEES_U_ML)
 
CLOSURES_T_MLI := \
Closure_color_t.mli \
Closure_basic_t.mli \
Closure_units_t.mli \
Closure_t.mli \
 
CLOSURES_U_ML := $(subst _t,_v,$(CLOSURES_T_MLI)) 
CLOSURES_TV_MLI := $(CLOSURES_T_MLI) $(CLOSURES_U_ML)
 
CONTEXT_SKELETON_U_ML := \
Elementary_context_databox_skeletondata_tag_by_databox_name_n_database_name_provider_u_any.ml \
Elementary_as_context_databox_skeletondata_tag_by_databox_name_n_database_name_provider_u_any.ml \
  
CONTEXT_FIGURE_U_ML := \
Elementary_context_databox_figuredata_tag_by_databox_name_n_database_name_provider_u_any.ml \
Elementary_as_context_databox_figuredata_tag_by_databox_name_n_database_name_provider_u_any.ml \
 
CONTEXT_TAGS_U_ML := \
Elementary_context_domain_sole_index_by_unit_provider_u_any.ml \
Elementary_as_context_domain_tag_by_unit_provider_u_any.ml \
Elementary_context_domain_tag_by_unit_provider_u_any.ml \
 \
Elementary_as_context_database_tag_by_database_name_provider_u_any.ml \
Elementary_context_database_tag_by_database_name_provider_u_any.ml \
 \
Elementary_as_context_databox_tag_by_databox_name_n_database_name_provider_u_any.ml \
Elementary_context_databox_tag_by_databox_name_n_database_name_provider_u_any.ml \
Databox_name_n_database_name_by_elementary_context_databox_tag_provider_u_any.ml \
  
TRANSLATORS_FROM_DB1POINTSDATASET_U_ML := \
Elementary_symbol_from_db1pointsdata_tag_translations_u_any.ml \
Elementary_as_body_coordinate_tuple_symbol_subtree_from_db1pointsdata_as_body_sequence_float_tag_subtree_translator_u_any.ml \
 
TRANSLATORS_FROM_NWCHEMDATASET_U_ML := \
Elementary_string_off_list_by_nwchem_body_node_aoset_numerical_values_string_off_list_translator_u_any.ml \
Elementary_aopef_name_n_nwchem_aopef_name_list_by_nwchem_body_node_as_aoset_onecenter_block_tag_translator_u_any.ml \
Elementary_aopef_name_n_nwchem_aopef_name_list_by_center_name_provider_u_any.ml \
 
SUBTREES_NWCHEMDATASET_U_ML := \
Elementary_as_context_tag_trio_by_nwchem_context_databox_tag_provider_u_any.ml \
Elementary_symbol_subtree_by_nwchem_context_databox_tag_provider_u_any.ml \
  
TREES_NWCHEMDATASET_U_ML := \
Elementary_tag_tree_by_nwchem_context_databox_tag_provider_u_any.ml \
 
SUBTREES_DB1POINTSDATASET_U_ML := \
Elementary_as_context_tag_trio_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Elementary_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
  
TREES_DB1POINTSDATASET_U_ML := \
Elementary_tag_tree_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
 
TREES_U_ML := \
Elementary_tag_tree_by_elementary_context_databox_figuredata_tag_provider_u_any.ml \
Elementary_tag_tree_by_elementary_context_databox_skeletondata_tag_provider_u_any.ml \
Elementary_tag_tree_by_elementary_context_databox_tag_provider_u_any.ml \
Elementary_tag_tree_by_databox_name_n_database_name_provider_u_any.ml \
 
INTERFACES_U_ML := \
Elementary_tag_all_list_by_elementary_context_databox_figuredata_tag_provider_u_any.ml \
Elementary_tag_all_list_by_elementary_context_databox_skeletondata_tag_provider_u_any.ml \
Elementary_tag_all_list_by_databox_name_n_database_name_provider_u_any.ml \
Elementary_tag_all_list_by_elementary_context_databox_tag_provider_u_any.ml \
 
EXTRACTORS_U_ML := \
Databox_name_n_database_name_by_sole_index_provider_u_any.ml \
Elementary_symbol_by_sole_index_provider_u_any.ml \
Elementary_any_category_by_sole_index_extractor_u_any.ml \
Elementary_context_databox_tag_by_elementary_tag_provider_u_any.ml \
Elementary_as_context_databox_tag_by_elementary_tag_provider_u_any.ml \
Databox_name_n_database_name_by_elementary_tag_provider_u_any.ml \
Elementary_tag_subtree_by_elementary_tag_provider_u_any.ml \
Elementary_son_tag_list_by_elementary_father_tag_provider_u_any.ml \
 
FENCE_U_ML := \
Elementary_fence_by_elementary_tag_provider_u_any.ml \
 
BORDER_U_ML := \
Elementary_border_by_elementary_tag_provider_u_any.ml \
 
PROVIDERS_EXTRA_U_ML := \
Measure_actual_by_elementary_fence_units_actual_tag_provider_u_any.ml \
Measure_by_elementary_fence_units_actual_tag_provider_u_any.ml \
Measure_canonical_by_calculation_name_n_elementary_fence_units_actual_tag_provider_u_any.ml \
Measure_by_elementary_fence_units_canonical_tag_provider_u_any.ml \
Measure_canonical_by_elementary_fence_units_canonical_tag_provider_u_any.ml \
Measure_canonical_list_by_calculation_name_n_elementary_fence_units_actual_tag_provider_u_any.ml \
Measure_by_elementary_fence_units_tag_provider_u_any.ml \
Measure_actual_by_elementary_fence_units_tag_provider_u_any.ml \
 \
Readee_basic_by_elementary_fence_basic_tag_provider_u_any.ml \
Readee_by_elementary_fence_tag_provider_u_any.ml \
 
BORDER_COORDINATES_U_ML := \
Elementary_border_coordinate_tag_border_by_elementary_tag_provider_u_any.ml \
Elementary_body_coordinate_tuple_tag_border_by_elementary_tag_provider_u_any.ml \
 
BORDER_PARAMETERS_U_ML := \
Elementary_border_parameter_tag_border_by_elementary_tag_provider_u_any.ml \
Elementary_body_parameter_tuple_tag_border_by_elementary_tag_provider_u_any.ml \
Elementary_border_parameter_aopef_coefficient_n_elementary_border_parameter_aopef_exponent_tag_doublet_by_skeleton_field_border_centered_aopef_single_scaled_tag_provider_u_any.ml \

FROM_FILES_MLI := \
 \
$(MEASURES_TV_MLI) \
$(READEES_TV_MLI) \
$(CLOSURES_TV_MLI) \
#  \
# $(CONTEXT_SKELETON_U_ML) \
# $(CONTEXT_FIGURE_U_ML) \
# $(CONTEXT_TAGS_U_ML) \
# $(TRANSLATORS_FROM_NWCHEMDATASET_U_ML) \
# $(SUBTREES_NWCHEMDATASET_U_ML) \
# $(TREES_NWCHEMDATASET_U_ML) \
# $(TRANSLATORS_FROM_DB1POINTSDATASET_U_ML) \
# $(SUBTREES_DB1POINTSDATASET_U_ML) \
# $(TREES_DB1POINTSDATASET_U_ML) \
# $(TREES_U_ML) \
# $(INTERFACES_U_ML) \
# $(EXTRACTORS_U_ML) \
# $(FENCE_U_ML) \
# $(BORDER_U_ML) \
# $(PROVIDERS_EXTRA_U_ML) \

# $(BORDER_COORDINATES_U_ML) \
# $(BORDER_PARAMETERS_U_ML) \


EXTRA_FILES_ML := \
Boundary_u.ml \
Elementary_aopef_name_n_nwchem_aopef_name_list_by_center_name_provider_u_test_ao.ml \
Elementary_aopef_name_n_nwchem_aopef_name_list_from_nwchem_body_node_as_aoset_onecenter_block_tag_translator_u_cc_pvtz.ml \
Elementary_as_body_coordinate_tuple_symbol_subtree_from_db1figure_as_body_sequence_float_tag_subtree_translator_u_point_a.ml \
Elementary_as_body_coordinate_tuple_symbol_subtree_from_db1figure_as_body_sequence_float_tag_subtree_translator_u_segment_s.ml \
Elementary_as_context_tag_trio_by_db1figure_context_databox_tag_provider_u_test_ao.ml \
Elementary_as_context_tag_trio_by_nwchem_context_databox_tag_provider_u_nwchem_lanl2dz.ml \
Elementary_as_units_symbol_leaf_list_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
Elementary_body_coordinate_tuple_tag_border_by_elementary_tag_provider_u.ml \
Elementary_border_by_elementary_tag_provider_u.ml \
Elementary_border_by_elementary_tag_provider_u_test_ao.ml \
Elementary_context_databox_figuredata_tag_by_database_name_n_databox_name_provider_u_triangle_isoright.ml \
Elementary_context_databox_tag_by_database_name_n_databox_name_provider_u_triangle_isoright.ml \
Elementary_fence_by_elementary_tag_provider_u_test_ao.ml \
Elementary_fence_units_actual_tag_fence_by_elementary_tag_provider_u.ml \
Elementary_string_off_list_from_nwchem_body_node_aoset_numerical_values_string_off_list_translator_u_test_ao.ml \
Elementary_symbol_by_db1figure_tag_translator_u_point_a.ml \
Elementary_symbol_subtree_by_db1figure_context_databox_tag_provider_u_point_a.ml \
Elementary_symbol_subtree_by_db1figure_context_databox_tag_provider_u_segment_s.ml \
Elementary_symbol_subtree_by_nwchem_context_databox_tag_provider_u_cc_pvtz.ml \
Elementary_symbol_subtree_by_nwchem_context_databox_tag_provider_u_lanl2dz.ml \
Elementary_symbol_tree_by_elementary_createdby_tag_provider_u_coordinate_tuple_print.ml \
Elementary_symbol_tree_by_input_fullnameoffile_provider_u_coordinate_tuple_print.ml \
Elementary_symbol_tree_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
Elementary_symbol_tree_by_input_fullnameoffile_provider_u_print_homothety_n_translation_point_t.ml \
Elementary_tag_all_list_by_database_name_n_databox_name_provider_u_point_a.ml \
Elementary_tag_all_list_by_elementary_createdby_tag_provider_u_coordinate_tuple_print.ml \
Elementary_tag_all_list_by_elementary_createdby_tag_provider_u_point_homothety_n_translation.ml \
Elementary_tag_subtree_by_elementary_createdby_tag_provider_u_coordinate_tuple_print.ml \
Elementary_tag_subtree_by_elementary_tag_provider_u.ml \
Elementary_tag_tree_by_database_name_n_databox_name_provider_u_point_a.ml \
Elementary_tag_tree_by_database_name_provider_u_nwchem.ml \
Elementary_tag_tree_by_db1figure_context_databox_tag_provider_u_point_a.ml \
Elementary_tag_tree_by_elementary_createdby_tag_provider_u_coordinate_tuple_print.ml \
Elementary_tag_tree_by_input_fullnameoffile_provider_u_coordinate_tuple_print.ml \
Elementary_tag_tree_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
Elementary_tag_tree_by_nwchem_context_databox_tag_provider_u_nwchem_lanl2dz.ml \
Measure_actual_by_elementary_fence_units_actual_tag_provider_u_point_a.ml \
Measure_by_elementary_fence_units_actual_tag_provider_u_point_a.ml \
Measure_by_elementary_fence_units_actual_tag_provider_u_test_ao.ml \
Measure_canonical_by_elementary_fence_units_actual_tag_provider_u_point_a.ml \
Measure_canonical_by_elementary_fence_units_canonical_tag_provider_u_point_a.ml \
Measure_length_u_test_ao.ml \
Measure_u_test_ao.ml \


UNITARY_TESTS_FILES_ML := \
$(EXTRA_FILES_ML) \
$(FROM_FILES_MLI) \

