FILES_MLI := \
Local_database_fullnameofdirectory_list_by_domain_tag_register_v.mli \
Local_database_nameofdirectory_list_by_domain_tag_register_v.mli \
 \
Local_database_fullnameofdirectory_list_by_domain_tag_provider_v.mli \
Local_database_nameofdirectory_list_by_domain_tag_provider_v.mli \
  