REGISTERS_V_MLI := \
Databox_name_n_database_name_by_elementary_context_databox_tag_register_v.mli \
Elementary_creation_module_name_by_sole_index_register_v.mli \
Elementary_fence_by_elementary_tag_register_v.mli \
Elementary_son_tag_list_by_elementary_father_tag_register_v.mli \
Elementary_symbol_by_sole_index_register_v.mli \
Elementary_tag_all_list_by_databox_name_n_database_name_register_v.mli \
Elementary_tag_all_list_by_elementary_context_databox_tag_register_v.mli \
Elementary_tag_subtree_by_elementary_tag_register_v.mli \
Elementary_tag_tree_by_databox_name_n_database_name_register_v.mli \
Elementary_tag_tree_by_elementary_context_databox_tag_register_v.mli \
  
CONTEXT_NAME_BY_UNIT_V_MLI := \
Elementary_context_sector_name_by_unit_provider_v.mli \
Elementary_context_domain_name_by_unit_provider_v.mli \
 
CONTEXT_TAG_BY_UNIT_V_MLI := \
Elementary_context_sector_tag_by_unit_provider_v.mli \
Elementary_as_context_sector_tag_by_unit_provider_v.mli \
 \
Elementary_context_domain_tag_by_unit_provider_v.mli \
Elementary_as_context_domain_tag_by_unit_provider_v.mli \
 
CHECK_CONTEXT_NAME_CONSISTENCY_V_MLI := \
Check_consistency_by_databox_name_n_database_name_provider_v.mli \
Check_consistency_by_elementary_context_name_quatuor_provider_v.mli \
 \
Elementary_context_name_quatuor_by_databox_name_n_database_name_provider_v.mli \
 
CONTEXT_TAG_BY_DATABOX_NAME_N_DATABASE_NAME_V_MLI := \
Elementary_context_database_tag_by_database_name_provider_v.mli \
Elementary_as_context_database_tag_by_database_name_provider_v.mli \
 \
Elementary_context_databox_tag_by_databox_name_n_database_name_provider_v.mli \
Elementary_as_context_databox_tag_by_databox_name_n_database_name_provider_v.mli \
 \
Elementary_context_tag_quadruplet_by_databox_name_n_database_name_provider_v.mli \
Elementary_as_context_tag_quatuor_by_databox_name_n_database_name_provider_v.mli \
 \
Database_name_by_elementary_context_databox_tag_provider_v.mli \
Databox_name_n_database_name_by_elementary_context_databox_tag_provider_v.mli \
 
TRANSLATION_FROM_NWCHEMDATA_V_MLI := \
Elementary_string_off_list_by_nwchemdata_body_node_aoset_numerical_values_string_off_list_translator_v.mli \

TRANSLATION_FROM_DB1POINTSDATA_V_MLI := \
Elementary_as_body_coordinate_tuple_symbol_subtree_by_vertex_name_n_databox_name_provider_v.mli \
Elementary_as_body_coordinate_tuple_symbol_subtree_list_by_db1pointsdata_context_databox_name_provider_v.mli \
 
SYMBOL_SUBTREE_BY_CONTEXT_NAME_V_MLI := \
Elementary_symbol_subtree_by_db1pointsdata_context_databox_name_provider_v.mli \
Elementary_symbol_subtree_by_nwchemdata_context_databox_name_provider_v.mli \
Elementary_symbol_subtree_by_databox_name_n_database_name_provider_v.mli \
  
TAG_TREE_V_MLI := \
Elementary_tag_tree_by_databox_name_n_database_name_provider_v.mli \
Elementary_tag_tree_by_elementary_context_databox_tag_provider_v.mli \
 
INTERFACES_V_MLI := \
Elementary_tag_all_list_by_databox_name_n_database_name_provider_v.mli \
Elementary_tag_all_list_by_elementary_context_databox_tag_provider_v.mli \
 
EXTRACTORS_V_MLI := \
Elementary_symbol_by_sole_index_register_filler_v.mli \
Elementary_symbol_by_sole_index_provider_v.mli \
Elementary_any_category_by_sole_index_extractor_v.mli \
Elementary_son_tag_list_by_elementary_father_tag_provider_v.mli \
Elementary_tag_subtree_by_elementary_tag_provider_v.mli \
 
FENCE_V_MLI := \
Elementary_fence_by_elementary_tag_provider_v.mli \
 
FILES_MLI := \
$(REGISTERS_V_MLI) \
$(CONTEXT_NAME_BY_UNIT_V_MLI) \
$(CONTEXT_TAG_BY_UNIT_V_MLI) \
$(CHECK_CONTEXT_NAME_CONSISTENCY_V_MLI) \
$(CONTEXT_TAG_BY_DATABOX_NAME_N_DATABASE_NAME_V_MLI) \
$(TRANSLATION_FROM_NWCHEMDATA_V_MLI) \
$(TRANSLATION_FROM_DB1POINTSDATA_V_MLI) \
$(SYMBOL_SUBTREE_BY_CONTEXT_NAME_V_MLI) \
$(TAG_TREE_V_MLI) \
$(INTERFACES_V_MLI) \
$(EXTRACTORS_V_MLI) \
$(FENCE_V_MLI) \
