FILES_MLI := \
Db2figurefigurefigure_entity_tag_tree_by_db2figure_entity_local_database_tag_register_v.mli \
Db2figurefigurefigure_entity_tag_tree_by_db2figure_entity_local_database_tag_provider_v.mli \
 