INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(QUANTUM_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_PARSER_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(COORDINATESET_SYMBOLS_DIR) \
	$(COORDINATESET_TAGS_DIR) \
	$(COORDINATESET_BUILDER_TREES_DIR) \
  



