(** {3 A Data for a field in a DBREF Record of a Pdb file.} *)

type dbref_fieldpdb_data =
  | Empty_1 of string (* 7-7 *)
  | Dbref_id of string (* 8-11 *)
  | Empty_2 of string (* 12-12 *)
  | Dbref_chain_id of char (* 13-13 *)
  | Empty_3 of string (* 14-14 *)
  | Dbref_pdb_sequence_segment_initial_sequence_number of int (* 15-18 *)
  | Dbref_pdb_sequence_segment_initial_insertion_code of char (* 19-19 *)
  | Empty_4 of string (* 20-20 *)
  | Dbref_pdb_sequence_segment_final_sequence_number of int (* 21-24 *)
  | Dbref_pdb_sequence_segment_final_insertion_code of char (* 25-25 *)
  | Empty_5 of string (* 26-26 *)
  | Dbref_sequence_database_name of string (* 27-32 *)
  | Empty_6 of string (* 33-33 *)
  | Dbref_sequence_database_accession_code of string (* 34-41 *)
  | Empty_7 of string (* 42-42 *)
  | Dbref_sequence_database_identification_code of string (* 43-54 *)
  | Empty_8 of string (* 55-55 *)
  | Dbref_database_segment_initial_sequence_number of int (* 56-60 *)
  | Dbref_database_segment_initial_insertion_code of char (* 61-61 *)
  | Empty_9 of string (* 62-62 *)
  | Dbref_database_segment_final_sequence_number of int (* 63-67 *)
  | Dbref_database_segment_final_residue_insertion_code of char (* 68-68 *)
  | Empty_10 of string (* 68-80 *)
;;
(** created by ./do_some_fieldpdp_data_t Dbref Dfs 18 May 2010. *)
