modify_string.pl Afd_t Atom_fieldpdb_data_t *.ml
modify_string.pl Afd_v Atom_fieldpdb_data_v *.ml
modify_string.pl Afs_t Atom_fieldpdb_symbol_t *.ml
modify_string.pl Anfd_t Anisou_fieldpdb_data_t *.ml
modify_string.pl Anfd_v Anisou_fieldpdb_data_v *.ml
modify_string.pl Anfs_t Anisou_fieldpdb_symbol_t *.ml
modify_string.pl Anfs_v Anisou_fieldpdb_symbol_v *.ml
modify_string.pl Aos_t Aminoacid_olc_symbol_t *.ml
modify_string.pl Aps_t Atompdb_symbol_t *.ml
modify_string.pl Aps_v Atompdb_symbol_v *.ml
modify_string.pl Ard_t Atom_recordpdb_data_t *.ml
modify_string.pl Ark_t Atom_recordpdb_keypdb_t *.ml
modify_string.pl Ark_v Atom_recordpdb_keypdb_v *.ml
modify_string.pl Arm_t Atom_recordpdb_markerpdb_t *.ml
modify_string.pl Arm_t Seqres_packpdb_markerpdb_t *.ml
modify_string.pl Arm_v Atom_recordpdb_markerpdb_v *.ml
modify_string.pl Atfd_v Atom_fieldpdb_data_v *.ml
modify_string.pl Atfs_t Atom_fieldpdb_symbol_t *.ml
modify_string.pl Atfs_v Atom_fieldpdb_symbol_v *.ml
modify_string.pl Atfv_t Atom_fieldpdb_values_t *.ml
modify_string.pl Ats_t Atom_symbol_t *.ml
modify_string.pl Ats_v Aminoacid_tlc_symbol_v *.ml
modify_string.pl Bpm_t Block_packpdb_markerpdb_t *.ml
modify_string.pl Bps_t Bookkeeping_clusterpdb_symbol_t *.ml
modify_string.pl Cal_t Capped_list_t *.ml
modify_string.pl Cal_v Capped_list_v *.ml
modify_string.pl Cfd_v Cispep_fieldpdb_data_v *.ml
modify_string.pl Cfs_t Cispep_fieldpdb_symbol_t *.ml
modify_string.pl Cfs_v Cispep_fieldpdb_symbol_v *.ml
modify_string.pl Cifd_t Cispep_fieldpdb_data_t *.ml
modify_string.pl Cifs_t Cispep_fieldpdb_symbol_t *.ml
modify_string.pl Cpd_v Clusterpdb_data_v *.ml
modify_string.pl Cpk_t Clusterpdb_keypdb_t *.ml
modify_string.pl Cpk_v Clusterpdb_keypdb_v *.ml
modify_string.pl Cps_t Clusterpdb_symbol_t *.ml
modify_string.pl Cps_v Clusterpdb_symbol_v *.ml
modify_string.pl Crps_t Crystallographic_clusterpdb_symbol_t *.ml
modify_string.pl Csp_t Chain_sequencepdb_t *.ml
modify_string.pl Csp_v Chain_sequencepdb_v *.ml
modify_string.pl Ctps_t Coordinate_transformation_clusterpdb_symbol_t *.ml
modify_string.pl D1fd_t Dbref1_fieldpdb_data_t *.ml
modify_string.pl D1fd_v Dbref1_fieldpdb_data_v *.ml
modify_string.pl D1fs_t Dbref1_fieldpdb_symbol_t *.ml
modify_string.pl D1fs_v Dbref1_fieldpdb_symbol_v *.ml
modify_string.pl D2fd_t Dbref2_fieldpdb_data_t *.ml
modify_string.pl D2fd_v Dbref2_fieldpdb_data_v *.ml
modify_string.pl D2fs_t Dbref2_fieldpdb_symbol_t *.ml
modify_string.pl D2fs_v Dbref2_fieldpdb_symbol_v *.ml
modify_string.pl Dbl_t Doublet_t *.ml
modify_string.pl Dbl_v Doublet_v *.ml
modify_string.pl Dfd_t Dbref_fieldpdb_data_t *.ml
modify_string.pl Dfd_v Dbref_fieldpdb_data_v *.ml
modify_string.pl Dfs_t Dbref_fieldpdb_symbol_t *.ml
modify_string.pl Dfs_v Dbref_fieldpdb_symbol_v *.ml
modify_string.pl Drd_t Dbref_recordpdb_data_t *.ml
modify_string.pl Drsf_v Dbref_recordpdb_symbol_formula_v *.ml
modify_string.pl Epd_v Entrypdb_data_v *.ml
modify_string.pl Epd_v Entrypdb_data_v *.ml
modify_string.pl Epk_t Entrypdb_keypdb_t *.ml
modify_string.pl Eps_t Entrypdb_symbol_t *.ml
modify_string.pl Eps_v Entrypdb_symbol_v *.ml
modify_string.pl Eps_v Entrypdb_symbol_v *.ml
modify_string.pl Esf_t Entrypdb_symbol_formula_t *.ml
modify_string.pl Fio_v Fileio_v *.ml
modify_string.pl Fln_v Filename_p *.ml
modify_string.pl Fpk_t Fragment_packpdb_keypdb_t *.ml
modify_string.pl Fpm_t Fragment_packpdb_markerpdb_t *.ml
modify_string.pl Fps_t Fieldpdb_symbol_t *.ml
modify_string.pl Fps_v Fieldpdb_symbol_v *.ml
modify_string.pl Fpt_v Fieldpdb_tools_v *.ml
modify_string.pl Frs_v Fragment_symbol_v *.ml
modify_string.pl Fsf_v Fragment_symbol_formula_v *.ml
modify_string.pl Hafd_v Hetatm_fieldpdb_data_v *.ml
modify_string.pl Hafs_t Hetatm_fieldpdb_symbol_t *.ml
modify_string.pl Hafs_v Hetatm_fieldpdb_symbol_v *.ml
modify_string.pl Hdfs_t Header_fieldpdb_symbol_t *.ml
modify_string.pl Hdfs_v Header_fieldpdb_symbol_v *.ml
modify_string.pl Hlfd_t Helix_fieldpdb_data_t *.ml
modify_string.pl Hlfd_v Helix_fieldpdb_data_v *.ml
modify_string.pl Hlfs_t Helix_fieldpdb_symbol_t *.ml
modify_string.pl Hlfs_v Helix_fieldpdb_symbol_v *.ml
modify_string.pl Hps_t Hetatmpdb_symbol_t *.ml
modify_string.pl Hps_t Heterogen_clusterpdb_symbol_t *.ml
modify_string.pl Hps_v Hetatmpdb_symbol_v *.ml
modify_string.pl Hrd_t Header_recordpdb_data_t *.ml
modify_string.pl Hrd_t Hetatm_recordpdb_data_t *.ml
modify_string.pl Hrk_t Hetatm_recordpdb_keypdb_t *.ml
modify_string.pl Hrk_v Hetatm_recordpdb_keypdb_v *.ml
modify_string.pl Hrm_t Hetatm_recordpdb_markerpdb_t *.ml
modify_string.pl Hrm_v Hetatm_recordpdb_markerpdb_v *.ml
modify_string.pl Hrsf_v Header_recordpdb_symbol_formula_v *.ml
modify_string.pl Htfd_v Het_fieldpdb_data_v *.ml
modify_string.pl Htfs_t Het_fieldpdb_symbol_t *.ml
modify_string.pl Htfs_v Het_fieldpdb_symbol_v *.ml
modify_string.pl Lfd_t Link_fieldpdb_data_t *.ml
modify_string.pl Lfd_t Linl_fieldpdb_data_t *.ml
modify_string.pl Lfd_v Link_fieldpdb_data_v *.ml
modify_string.pl Lfs_t Link_fieldpdb_symbol_t *.ml
modify_string.pl Lfs_t Linl_fieldpdb_symbol_t *.ml
modify_string.pl Lst_v List_v *.ml
modify_string.pl Mfd_t Modres_fieldpdb_data_t *.ml
modify_string.pl Mfd_v Modres_fieldpdb_data_v *.ml
modify_string.pl Mfs_t Modres_fieldpdb_symbol_t *.ml
modify_string.pl Mns_v Mendeleev_symbol_v *.ml
modify_string.pl Mpd_v Molecule_packpdb_data_v *.ml
modify_string.pl Mpk_t Molecule_packpdb_keypdb_t *.ml
modify_string.pl Mpk_v Molecule_packpdb_keypdb_v *.ml
modify_string.pl Mpm_t Molecule_packpdb_markerpdb_t *.ml
modify_string.pl Mpm_v Molecule_packpdb_markerpdb_v *.ml
modify_string.pl Mps_t Moleculepdb_symbol_t *.ml
modify_string.pl Mps_v Moleculepdb_symbol_v *.ml
modify_string.pl Ord_p Ordinal_p *.ml
modify_string.pl Ppd_v Packpdb_data_v *.ml
modify_string.pl Ppk_t Packpdb_keypdb_t *.ml
modify_string.pl Ppk_t Packpdb_markerpdb_t *.ml
modify_string.pl Ppk_v Packpdb_keypdb_v *.ml
modify_string.pl Ppm_t Packpdb_markerpdb_t *.ml
modify_string.pl Ppm_v Packpdb_markerpdb_v *.ml
modify_string.pl Pps_t Packpdb_symbol_t *.ml
modify_string.pl Pps_v Packpdb_symbol_v *.ml
modify_string.pl Psp_t Protein_sequencepdb_t *.ml
modify_string.pl Reg_v Register_v *.ml
modify_string.pl Rns_t Residuepdb_symbol_t *.ml
modify_string.pl Rpd_v Residue_packpdb_data_v *.ml
modify_string.pl Rpk_t Recordpdb_keypdb_t *.ml
modify_string.pl Rpk_t Residue_packpdb_keypdb_t *.ml
modify_string.pl Rpk_v Residue_packpdb_keypdb_v *.ml
modify_string.pl Rpm_t Residue_packpdb_markerpdb_t *.ml
modify_string.pl Rpm_v Residue_packpdb_markerpdb_v *.ml
modify_string.pl Safd_t Seqadv_fieldpdb_data_t *.ml
modify_string.pl Safd_v Seqadv_fieldpdb_data_v *.ml
modify_string.pl Safs_t Seqadv_fieldpdb_symbol_t *.ml
modify_string.pl Safs_v Seqadv_fieldpdb_symbol_v *.ml
modify_string.pl Sbfd_t Ssbond_fieldpdb_data_t *.ml
modify_string.pl Sbfd_v Ssbond_fieldpdb_data_v *.ml
modify_string.pl Sbfs_t Ssbond_fieldpdb_symbol_t *.ml
modify_string.pl Sbfs_v Ssbond_fieldpdb_symbol_v *.ml
modify_string.pl Sfd_t Seqres_fieldpdb_data_t *.ml
modify_string.pl Sfd_v Seqres_fieldpdb_data_v *.ml
modify_string.pl Sfs_t Seqres_fieldpdb_symbol_t *.ml
modify_string.pl Sfs_v Seqres_fieldpdb_symbol_v *.ml
modify_string.pl Shfd_t Sheet_fieldpdb_data_t *.ml
modify_string.pl Shfd_v Sheet_fieldpdb_data_v *.ml
modify_string.pl Shfs_t Sheet_fieldpdb_symbol_t *.ml
modify_string.pl Shfs_v Sheet_fieldpdb_symbol_v *.ml
modify_string.pl Sifd_t Site_fieldpdb_data_t *.ml
modify_string.pl Sifd_v Site_fieldpdb_data_v *.ml
modify_string.pl Sifs_t Site_fieldpdb_symbol_t *.ml
modify_string.pl Sifs_v Site_fieldpdb_symbol_v *.ml
modify_string.pl Spk_t Sidechain_packpdb_keypdb_t *.ml
modify_string.pl Spm_t Sidechain_packpdb_markerpdb_t *.ml
modify_string.pl Sps_t Sectionpdb_symbol_t *.ml
modify_string.pl Sps_v Sectionpdb_symbol_v *.ml
modify_string.pl Sqcd_v Seqres_clusterpdb_data_v *.ml
modify_string.pl Sqfd_t Seqres_fieldpdb_data_t *.ml
modify_string.pl Sqfd_v Seqres_fieldpdb_data_v *.ml
modify_string.pl Sqfs_t Seqres_fieldpdb_symbol_t *.ml
modify_string.pl Sqfs_v Seqres_fieldpdb_symbol_v *.ml
modify_string.pl Sqpd_v Seqres_packpdb_data_v *.ml
modify_string.pl Srd_t Seqres_recordpdb_data_t *.ml
modify_string.pl Srfs_t Seqres_fieldpdb_symbol_t *.ml
modify_string.pl Srfs_v Seqres_fieldpdb_symbol_v *.ml
modify_string.pl Srsf_v Seqres_recordpdb_symbol_formula_v *.ml
modify_string.pl Ssf_v Sectionpdb_symbol_formula_v *.ml
modify_string.pl Ssf_v Sidegroup_symbol_formula_v *.ml
modify_string.pl Ssps_t Secondary_structure_clusterpdb_symbol_t *.ml
modify_string.pl Str_v String_v *.ml
modify_string.pl Tfd_t Ter_fieldpdb_data_t *.ml
modify_string.pl Tfd_v Ter_fieldpdb_data_v *.ml
modify_string.pl Tfs_t Ter_fieldpdb_symbol_t *.ml
modify_string.pl Tfs_v Ter_fieldpdb_symbol_v *.ml
modify_string.pl Tkp_t Tokenpdb_t *.ml
modify_string.pl Tks_t Tokenpdb_symbol_t *.ml
modify_string.pl Trd_t Ter_recordpdb_data_t *.ml
modify_string.pl Trp_t Triplet_t *.ml
modify_string.pl Trp_v Triplet_v *.ml
modify_string.pl Trsf_v Ter_recordpdb_symbol_formula_v *.ml
modify_string.pl Tsps_t Title_section_clusterpdb_symbol_t *.ml
 