(** {3 A Data for a field in a SEQADV Record of a Pdb file.} *)

type seqadv_fieldpdb_data =
  | Empty_1 of string (* 7-7 *)
  | Seqadv_id of string (* 8-11 *)
  | Empty_2 of string (* 12-12 *)
  | Seqadv_residue_name of string (* 13-15 *)
  | Empty_3 of string (* 16-16 *)
  | Seqadv_chain_id of char (* 17-17 *)
  | Empty_4 of string (* 18-18 *)
  | Seqadv_sequence_number of string (* 19-22 *)
  | Seqadv_insertion_code of char (* 23-23 *)
  | Empty_5 of string (* 24-24 *)
  | Seqadv_database of string (* 25-28 *)
  | Empty_6 of string (* 29-29 *)
  | Seqadv_sequence_databse_accession_number of int (* 30-38 *)
  | Empty_7 of string (* 39-39 *)
  | Seqadv_sequence_databse_residue_name of string (* 40-42 *)
  | Empty_8 of string (* 43-43 *)
  | Seqadv_sequence_databse_sequence_number of int (* 44-48 *)
  | Empty_9 of string (* 49-49 *)
  | Seqadv_conflict_description of string (* 50-70 *)
  | Empty_10 of string (* 71-80 *)
;;
(** created by ./do_some_fieldpdp_data_t Seqadv Safs 18 May 2010. *)
