(** {3 A Data for a field in a SHEET Record of a Pdb file.} *)

type sheet_fieldpdb_data =
  | Empty_1 of string (* 7-7 *)
  | Sheet_strand_number of int (* 8-10 *)
  | Empty_2 of string (* 11-11 *)
  | Sheet_id of string (* 12-14 *)
  | Sheet_strand_count of int (* 15-16 *)
  | Sheet_initial_residue_name of string (* 18-20 *)
  | Empty_3 of string (* 21-21 *)
  | Sheet_initial_residue_chain_id of char (* 22-22 *)
  | Empty_4 of string (* 21-21 *)
  | Sheet_initial_residue_sequence_number of int (* 23-26 *)
  | Sheet_initial_residue_insertion_code of char (* 27-27 *)
  | Empty_5 of string (* 28-28 *)
  | Sheet_final_residue_name of string (* 29-31 *)
  | Empty_6 of string (* 32-32 *)
  | Sheet_final_residue_chain_id of char (* 33-33 *)
  | Empty_7 of string (* 33-33 *)
  | Sheet_final_residue_sequence_number of int (* 34-37 *)
  | Sheet_final_residue_insertion_code of char (* 38-38 *)
  | Sheet_sense of int (* 39-40 *)
  | Empty_8 of string (* 41-41 *)
  | Sheet_current_strand_atom_name of string (* 42-45 *)
  | Sheet_current_strand_residue_name of string (* 46-48 *)
  | Empty_9 of string (* 49-49 *)
  | Sheet_current_strand_chain_id of char (* 50-50 *)
  | Sheet_current_strand_residue_sequence_number of int (* 51-54 *)
  | Sheet_current_strand_residue_inserion_code of char (* 55-55 *)
  | Empty_10 of string (* 56-56 *)
  | Sheet_previous_strand_atom_name of string (* 57-60 *)
  | Sheet_previous_strand_residue_name of string (* 61-63 *)
  | Empty_11 of string (* 64-64 *)
  | Sheet_previous_strand_chain_id of char (* 65-65 *)
  | Sheet_previous_strand_residue_sequence_number of int (* 66-69 *)
  | Sheet_previous_strand_residue_inserion_code of char (* 70-70 *)
  | Empty_12 of string (* 71-80 *)
;;
(** created by ./do_some_fieldpdp_data_t Sheet Shfs 18 May 2010. *)
