(** {3 A Data for a field in a SITE Record of a Pdb file.} *)

type site_fieldpdb_data =
  | Site_sequence_number of int (* 8-10 *)
  | Empty_1 of string (* 11-11 *)
  | Site_name of string (* 12-14 *)
  | Empty_2 of string (* 15-15 *)
  | Site_residue_count of int (* 16-17 *)
  | Empty_3 of string (* 18-18 *)
  | Site_first_residue_name of string (* 19-21 *)
  | Empty_4 of string (* 22-22 *)
  | Site_first_residue_chain_id of char (* 23-23 *)
  | Site_first_residue_sequence_number of int (* 24-27 *)
  | Site_first_residue_insertion_code of char (* 28-28 *)
  | Empty_5 of string (* 29-29 *)
  | Site_second_residue_name of string (* 30-32 *)
  | Empty_6 of string (* 33-33 *)
  | Site_second_residue_chain_id of char (* 34-34 *)
  | Site_second_residue_sequence_number of int (* 35-38 *)
  | Site_second_residue_insertion_code of char (* 39-39 *)
  | Empty_7 of string (* 40-40 *)
  | Site_third_residue_name of string (* 41-43 *)
  | Empty_8 of string (* 44-44 *)
  | Site_third_residue_chain_id of char (* 45-45 *)
  | Site_third_residue_sequence_number of int (* 46-49 *)
  | Site_third_residue_insertion_code of char (* 50-50 *)
  | Empty_9 of string (* 51-51 *)
  | Site_fourth_residue_name of string (* 52-54 *)
  | Empty_10 of string (* 55-55 *)
  | Site_fourth_residue_chain_id of char (* 56-56 *)
  | Site_fourth_residue_sequence_number of int (* 57-60 *)
  | Site_fourth_residue_insertion_code of char (* 61-61 *)
  | Empty_11 of string (* 62-80 *)
;;
(** created by ./do_some_fieldpdp_data_t Site Sifs 18 May 2010. *)
