FROM_FILES_V_ML := \
Coordinate_container_u_any.ml \
Coordinate_context_container_u_any.ml \
Coordinate_context_database_container_u_any.ml \
Coordinate_context_databox_container_u_any.ml \
Coordinate_context_domain_container_u_any.ml \
Coordinate_context_sector_container_u_any.ml \
Coordinate_set_body_container_u_any.ml \
Coordinate_set_body_tuple_container_u_any.ml \
Coordinate_set_body_tuple_heterogeneous_container_u_any.ml \
Coordinate_set_body_tuple_heterogeneous_cylindrical_container_u_any.ml \
Coordinate_set_body_tuple_heterogeneous_polar_container_u_any.ml \
Coordinate_set_body_tuple_heterogeneous_spherical_container_u_any.ml \
Coordinate_set_body_tuple_homogeneous_cartesian_container_u_any.ml \
Coordinate_set_body_tuple_homogeneous_container_u_any.ml \
Coordinate_set_body_tuple_homogeneous_linear_container_u_any.ml \
Coordinate_set_body_tuple_homogeneous_planar_container_u_any.ml \
Coordinate_set_container_u_any.ml \
Coordinate_set_fence_container_u_any.ml \
Coordinate_set_fence_heterogeneous_container_u_any.ml \
Coordinate_set_fence_heterogeneous_cylindrical_container_u_any.ml \
Coordinate_set_fence_heterogeneous_cylindrical_phi_container_u_any.ml \
Coordinate_set_fence_heterogeneous_cylindrical_rho_container_u_any.ml \
Coordinate_set_fence_heterogeneous_cylindrical_zed_container_u_any.ml \
Coordinate_set_fence_heterogeneous_polar_container_u_any.ml \
Coordinate_set_fence_heterogeneous_polar_rho_container_u_any.ml \
Coordinate_set_fence_heterogeneous_polar_theta_container_u_any.ml \
Coordinate_set_fence_heterogeneous_spherical_container_u_any.ml \
Coordinate_set_fence_heterogeneous_spherical_phi_container_u_any.ml \
Coordinate_set_fence_heterogeneous_spherical_rho_container_u_any.ml \
Coordinate_set_fence_heterogeneous_spherical_theta_container_u_any.ml \
Coordinate_set_fence_homogeneous_cartesian_container_u_any.ml \
Coordinate_set_fence_homogeneous_cartesian_x_container_u_any.ml \
Coordinate_set_fence_homogeneous_cartesian_y_container_u_any.ml \
Coordinate_set_fence_homogeneous_cartesian_z_container_u_any.ml \
Coordinate_set_fence_homogeneous_container_u_any.ml \
Coordinate_set_fence_homogeneous_linear_container_u_any.ml \
Coordinate_set_fence_homogeneous_linear_x_container_u_any.ml \
Coordinate_set_fence_homogeneous_planar_container_u_any.ml \
Coordinate_set_fence_homogeneous_planar_x_container_u_any.ml \
Coordinate_set_fence_homogeneous_planar_y_container_u_any.ml \

FROM_FILES_U_ML := \
Coordinate_set_body_tuple_container_u_point_a.ml \
Coordinate_set_body_tuple_heterogeneous_cylindrical_container_u_cc_pvtz.ml \
Coordinate_set_body_tuple_heterogeneous_cylindrical_container_u_point_a.ml \
Coordinate_set_fence_container_u_point_a.ml \
Coordinate_set_fence_container_u_test_ao.ml \
Coordinate_set_fence_heterogeneous_cylindrical_coefficient_container_u_point_a.ml \
Coordinate_set_fence_heterogeneous_cylindrical_container_u_lanl2dz.ml \
Coordinate_set_fence_heterogeneous_cylindrical_container_u_point_a.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
$(FROM_FILES_U_ML) \

