FILES_MLI:= \
Coordinate_symbol_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
Coordinate_tag_by_basicname_variable_external_n_basicname_inputbox_register_v.mli \
Coordinate_tag_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
 \
Figure_symbol_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
Figure_tag_by_basicname_variable_external_n_basicname_inputbox_register_v.mli \
Figure_tag_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
 \
Parameter_symbol_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
Parameter_tag_by_basicname_variable_external_n_basicname_inputbox_register_v.mli \
Parameter_tag_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
 \
Skeleton_symbol_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
Skeleton_tag_by_basicname_variable_external_n_basicname_inputbox_register_v.mli \
Skeleton_tag_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
 \
Elementary_envelopee_tuple_list_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
Measured_float_tuple_list_by_basicname_variable_external_n_basicname_inputbox_provider_v.mli \
Measured_float_tuple_by_basicname_cofactor_entity_n_basicname_inputbox_provider_v.mli \
 
