(** {3 Localinput_lexer_basic_word_doublequoted_symbol_t} *)


(** {6 Typing_for_symbol} *)

type localinput_lexer_basic_word_doublequoted_symbol =
  | Localinput_lexer_basic_word_doublequoted_anycase_symbol of Localinput_lexer_basic_word_doublequoted_anycase_symbol_t.localinput_lexer_basic_word_doublequoted_anycase_symbol
  | Localinput_lexer_basic_word_doublequoted_capitalized_symbol of Localinput_lexer_basic_word_doublequoted_capitalized_symbol_t.localinput_lexer_basic_word_doublequoted_capitalized_symbol
  | Localinput_lexer_basic_word_doublequoted_lowercase_symbol of Localinput_lexer_basic_word_doublequoted_lowercase_symbol_t.localinput_lexer_basic_word_doublequoted_lowercase_symbol
  | Localinput_lexer_basic_word_doublequoted_uppercase_symbol of Localinput_lexer_basic_word_doublequoted_uppercase_symbol_t.localinput_lexer_basic_word_doublequoted_uppercase_symbol
;;


(** Localinput_lexer_basic_word_doublequoted_symbol_t at 12:10:54 on 22 Mar 2017. created by version v2.4 of generator *)



