(** {3 Localinput_lexer_keyword_nextstringed_symbol_t} *)


(** {6 Typing_for_symbol} *)

type localinput_lexer_keyword_nextstringed_symbol =
  | Localinput_lexer_keyword_nextstringed_category_symbol of Localinput_lexer_keyword_nextstringed_category_symbol_t.localinput_lexer_keyword_nextstringed_category_symbol
  | Localinput_lexer_keyword_nextstringed_database_symbol of Localinput_lexer_keyword_nextstringed_database_symbol_t.localinput_lexer_keyword_nextstringed_database_symbol
  | Localinput_lexer_keyword_nextstringed_databox_symbol of Localinput_lexer_keyword_nextstringed_databox_symbol_t.localinput_lexer_keyword_nextstringed_databox_symbol
  | Localinput_lexer_keyword_nextstringed_domain_symbol of Localinput_lexer_keyword_nextstringed_domain_symbol_t.localinput_lexer_keyword_nextstringed_domain_symbol
  | Localinput_lexer_keyword_nextstringed_external_name_symbol of Localinput_lexer_keyword_nextstringed_external_name_symbol_t.localinput_lexer_keyword_nextstringed_external_name_symbol
  | Localinput_lexer_keyword_nextstringed_file_symbol of Localinput_lexer_keyword_nextstringed_file_symbol_t.localinput_lexer_keyword_nextstringed_file_symbol
  | Localinput_lexer_keyword_nextstringed_function_symbol of Localinput_lexer_keyword_nextstringed_function_symbol_t.localinput_lexer_keyword_nextstringed_function_symbol
  | Localinput_lexer_keyword_nextstringed_module_symbol of Localinput_lexer_keyword_nextstringed_module_symbol_t.localinput_lexer_keyword_nextstringed_module_symbol
  | Localinput_lexer_keyword_nextstringed_ondomain_symbol of Localinput_lexer_keyword_nextstringed_ondomain_symbol_t.localinput_lexer_keyword_nextstringed_ondomain_symbol
  | Localinput_lexer_keyword_nextstringed_operation_symbol of Localinput_lexer_keyword_nextstringed_operation_symbol_t.localinput_lexer_keyword_nextstringed_operation_symbol
  | Localinput_lexer_keyword_nextstringed_sector_symbol of Localinput_lexer_keyword_nextstringed_sector_symbol_t.localinput_lexer_keyword_nextstringed_sector_symbol
;;


(** Localinput_lexer_keyword_nextstringed_symbol_t at 12:11:19 on 22 Mar 2017. created by version v2.4 of generator *)



