FROM_FILES_V_ML := \
Check_consistency_by_databox_name_n_database_name_provider_u_any.ml \
Check_consistency_by_parameter_context_name_quatuor_provider_u_any.ml \
Database_name_by_any_sole_index_provider_u_any.ml \
Database_name_by_parameter_context_databox_tag_provider_u_any.ml \
Databox_name_by_any_sole_index_provider_u_any.ml \
Databox_name_n_database_name_by_parameter_context_databox_tag_provider_u_any.ml \
Nwchemdata_as_set_body_node_aoset_numericalvalues_tag_by_parameter_set_body_tuple_aopef_tag_provider_u_any.ml \
Nwchemdata_set_body_node_aoset_numericalvalues_string_off_by_parameter_set_body_tuple_aopef_tag_provider_u_any.ml \
Nwchemdata_set_body_node_aoset_numericalvalues_string_off_by_parameter_set_body_tuple_aopef_tag_string_off_provider_u_any.ml \
Nwchemdata_set_body_node_aoset_numericalvalues_tag_by_parameter_set_body_tuple_aopef_tag_provider_u_any.ml \
Parameter_any_category_by_sole_index_extractor_u_any.ml \
Parameter_as_context_database_tag_by_database_name_provider_u_any.ml \
Parameter_as_context_databox_tag_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_as_context_domain_tag_by_unit_provider_u_any.ml \
Parameter_as_context_sector_tag_by_unit_provider_u_any.ml \
Parameter_as_context_tag_quatuor_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_context_database_sole_index_by_any_sole_index_provider_u_any.ml \
Parameter_context_database_tag_by_database_name_provider_u_any.ml \
Parameter_context_databox_name_by_any_sole_index_provider_u_any.ml \
Parameter_context_databox_sole_index_by_any_sole_index_provider_u_any.ml \
Parameter_context_databox_symbol_by_any_sole_index_provider_u_any.ml \
Parameter_context_databox_tag_by_any_sole_index_provider_u_any.ml \
Parameter_context_databox_tag_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_context_domain_name_by_unit_provider_u_any.ml \
Parameter_context_domain_tag_by_unit_provider_u_any.ml \
Parameter_context_name_quatuor_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_context_sector_name_by_unit_provider_u_any.ml \
Parameter_context_sector_tag_by_unit_provider_u_any.ml \
Parameter_context_tag_quadruplet_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_fence_by_parameter_tag_provider_u_any.ml \
Parameter_son_tag_list_by_parameter_father_tag_provider_u_any.ml \
Parameter_string_off_by_nwchemdata_set_body_node_aoset_numericalvalues_string_off_provider_u_any.ml \
Parameter_string_off_list_by_nwchemdata_set_body_node_aoset_numericalvalues_string_off_list_translator_u_any.ml \
Parameter_symbol_by_sole_index_provider_u_any.ml \
Parameter_symbol_subtree_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_symbol_subtree_by_nwchemdata_context_databox_name_provider_u_any.ml \
Parameter_symbol_subtree_by_parameter_context_databox_tag_provider_u_any.ml \
Parameter_tag_all_list_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_tag_all_list_by_parameter_context_databox_tag_provider_u_any.ml \
Parameter_tag_subtree_by_parameter_tag_provider_u_any.ml \
Parameter_tag_tree_by_databox_name_n_database_name_provider_u_any.ml \
Parameter_tag_tree_by_parameter_context_databox_tag_provider_u_any.ml \

FROM_FILES_U_ML := \
Nwchemdata_set_body_node_aoset_numericalvalues_tag_by_parameter_set_body_tuple_aopef_tag_provider_u_cc_pvtz.ml \
Parameter_context_domain_name_by_unit_provider_u_lanl2dz.ml \
Parameter_son_tag_list_by_parameter_father_tag_provider_u_lanl2dz.ml \
Parameter_symbol_subtree_by_parameter_context_databox_tag_provider_u_lanl2dz.ml \
Parameter_tag_all_list_by_parameter_context_databox_tag_provider_u_lanl2dz.ml \
Parameter_tag_tree_by_parameter_context_databox_tag_provider_u_cc_pvtz_analysis_tree.ml \
Parameter_tag_tree_by_parameter_context_databox_tag_provider_u_lanl2dz_analysis_list.ml \
Parameter_tag_tree_by_parameter_context_databox_tag_provider_u_lanl2dz_analysis.ml \
Parameter_tag_tree_by_parameter_context_databox_tag_provider_u_lanl2dz_analysis_tree.ml \
Parameter_tag_tree_by_parameter_context_databox_tag_provider_u_lanl2dz.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
#$(FROM_FILES_U_ML) \

