CONTAINERS_T_MLI :=  \
     Skeleton_set_fence_periodic_wavelet_container_t.mli \
     Skeleton_set_fence_periodic_blochwave_container_t.mli \
    Skeleton_set_fence_periodic_container_t.mli \
     Skeleton_set_fence_centered_ecppef_container_t.mli \
     Skeleton_set_fence_centered_aopef_container_t.mli \
    Skeleton_set_fence_centered_container_t.mli \
   Skeleton_set_fence_container_t.mli \
     Skeleton_set_body_periodic_waveletset_container_t.mli \
     Skeleton_set_body_periodic_blochwaveset_container_t.mli \
    Skeleton_set_body_periodic_container_t.mli \
     Skeleton_set_body_centered_ecppefset_container_t.mli \
      Skeleton_set_body_centered_aopefset_shellordinal_container_t.mli \
      Skeleton_set_body_centered_aopefset_shellsymmetry_container_t.mli \
      Skeleton_set_body_centered_aopefset_onecenter_container_t.mli \
      Skeleton_set_body_centered_aopefset_anycenter_container_t.mli \
     Skeleton_set_body_centered_aopefset_container_t.mli \
    Skeleton_set_body_centered_container_t.mli \
   Skeleton_set_body_container_t.mli \
  Skeleton_set_container_t.mli \
   Skeleton_context_databox_container_t.mli \
   Skeleton_context_database_container_t.mli \
   Skeleton_context_domain_container_t.mli \
   Skeleton_context_sector_container_t.mli \
  Skeleton_context_container_t.mli \
 Skeleton_container_t.mli \
