SKELETON_T_MLI :=  \
     Skeleton_set_fence_periodic_wavelet_symbol_t.mli \
     Skeleton_set_fence_periodic_blochwave_symbol_t.mli \
    Skeleton_set_fence_periodic_symbol_t.mli \
     Skeleton_set_fence_centered_ecppef_symbol_t.mli \
     Skeleton_set_fence_centered_aopef_symbol_t.mli \
    Skeleton_set_fence_centered_symbol_t.mli \
   Skeleton_set_fence_symbol_t.mli \
     Skeleton_set_body_periodic_waveletset_symbol_t.mli \
     Skeleton_set_body_periodic_blochwaveset_symbol_t.mli \
    Skeleton_set_body_periodic_symbol_t.mli \
     Skeleton_set_body_centered_ecppefset_symbol_t.mli \
      Skeleton_set_body_centered_aopefset_shellordinal_symbol_t.mli \
      Skeleton_set_body_centered_aopefset_shellsymmetry_symbol_t.mli \
      Skeleton_set_body_centered_aopefset_onecenter_symbol_t.mli \
      Skeleton_set_body_centered_aopefset_anycenter_symbol_t.mli \
     Skeleton_set_body_centered_aopefset_symbol_t.mli \
    Skeleton_set_body_centered_symbol_t.mli \
   Skeleton_set_body_symbol_t.mli \
  Skeleton_set_symbol_t.mli \
   Skeleton_context_databox_symbol_t.mli \
   Skeleton_context_database_symbol_t.mli \
   Skeleton_context_domain_symbol_t.mli \
   Skeleton_context_sector_symbol_t.mli \
  Skeleton_context_symbol_t.mli \
 Skeleton_symbol_t.mli \
