INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(SKELETONSET_SYMBOLS_DIR) \
	$(SKELETONSET_TAGS_DIR) \
	$(SKELETONSET_BUILDER_TREES_DIR) \
	$(SKELETONSET_CONTAINERS_DIR) \
  