(** {3 Skeleton_fence_centered_aopef_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FSKE:Skeleton_fence_centered_aopef_container_v";
   "Needs : FSKE:Skeleton_fence_centered_aopef_tag_v";
   "Needs : DSKE:Skeleton_any_category_by_sole_index_extractor_v";
   "Needs : DSKE:Skeleton_fence_by_skeleton_tag_provider_v";
   "Needed-by: ";
   "Definition : a Builder (for an Entity of a Domain) is a son its Builder-Subtree";
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a Building is the Datastructure of the Builders of an Entity (Container with Builders)"; 
   "Definition : a Trunc type has only constructors of constructor";
   "Definition : a Branch type has only constructors of nothing";
   "Definition : a Stem type has only constructor of string";
   "Definition : a Bud type is a Stem type with only one constructor of string";
   "What-is-it: it is a container of a Fence Bud Type as a Uno of Skeleton_fence_centered_aopef_tag (i.e. Skeleton_fence_centered_aopef_tag)";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name con_pca =
  Uno_v.name 
    Skeleton_fence_centered_aopef_tag_v.name
    con_pca
;;

let string_off con_pca =
  Uno_v.name 
    Skeleton_fence_centered_aopef_tag_v.string_off
    con_pca
;;

let longname con_pca =
  Uno_v.name 
    Skeleton_fence_centered_aopef_tag_v.longname
    con_pca
;;

let fullname con_pca =
  Uno_v.name 
    Skeleton_fence_centered_aopef_tag_v.fullname
    con_pca
;;

(** {6 Coercing Up Tag} *)

let builder_tag_of_containee_tag tag_pca =
  Tag_v.map_entity 
    Skeleton_symbol_v.skeleton_symbol_of_skeleton_fence_centered_aopef_symbol 
    tag_pca
;;

(** {6 Coercing Down Tag} *)

let containee_tag_off_builder_tag tag_ske =
  Tag_v.map_entity
    Skeleton_symbol_v.skeleton_fence_centered_aopef_symbol_off_skeleton_symbol
    tag_ske
;;

(** {6 Builder Tag Datastructures : Building} *)

let building_of_tag tag_pca =
  let tag_ske = builder_tag_of_containee_tag tag_pca in
  Uno_v.make tag_ske
;;

let builder_tag_uno tag_pca =
  building_of_tag tag_pca
;;

let builder_tag_list_of_tag tag_pca =
  let tag_ske = builder_tag_of_containee_tag tag_pca in
  [tag_ske]
;;

let builder_tag_tuple_of_tag tag_pca =
  let bug = building_of_tag tag_pca in
  Tuple_v.tuple_of_uno bug
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_pca =
  Uno_v.make tag_pca
;;

(** {6 Fence list *)

let fence_as_list_of_tag tag_pca =
  let tag_ske = builder_tag_of_containee_tag tag_pca in
  Skeleton_fence_by_skeleton_tag_provider_v.provide tag_ske
;;

let fence_as_tuple_of_tag tag_pca =
  let fen_l = fence_as_list_of_tag tag_pca in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_pca =
  let fen_l = fence_as_list_of_tag tag_pca in
  Tuple_list_v.make fen_l
;;


(* generated by ./do_container_as_uno_fence_bud_v.sh skeleton_fence_centered_aopef pca *)
(* using ./template_container_as_uno_fence_bud_v.ml *)
(* Done on mardi 3 janvier 2017, 17:58:09 (UTC+0100) *)
