(** {3 Skeleton_set_fence_centered_container_t} *)


(** {6 Typing_for_container} *)

type skeleton_set_fence_centered_container =
  | Skeleton_set_fence_centered_aopef_container of Skeleton_set_fence_centered_aopef_container_t.skeleton_set_fence_centered_aopef_container
  | Skeleton_set_fence_centered_ecppef_container of Skeleton_set_fence_centered_ecppef_container_t.skeleton_set_fence_centered_ecppef_container
;;


(** Skeleton_set_fence_centered_container_t at 14:13:16 on 5 Jan 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh skeleton_set_fence_centered *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/skeletonset/skeletonset_symbols/Skeleton_set_fence_centered_symbol_t.ml *)
(* Done on jeudi 5 janvier 2017, 19:03:02 (UTC+0100) *)
