(** {3 Skeleton_set_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FSKE:Skeleton_set_container_v";
   "Needs : FSKE:Skeleton_set_fence_tag_v";
   "Needs : FSKE:Skeleton_set_body_container_v";
   "Needs : FSKE:Skeleton_set_fence_container_v";
   "Needs : DSKE:Skeleton_any_category_by_sole_index_extractor_v";
   "Needs : DSKE:Skeleton_fence_by_skeleton_tag_provider_v";
   "Needed-by: ";
   "What-is-it : Up_coercion to Skeleton_set type from Skeleton_set_sibext_1 ...sibext_2";
   "What-is-it : it is a Body container as a Tuple of Skeleton_set_fence and thus a List Skeleton_set_fence Tag";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name = function
  | Skeleton_set_container_t.Skeleton_set_body_container con_ssb ->
      (Skeleton_set_body_container_v.name con_ssb)
        
  | Skeleton_set_container_t.Skeleton_set_fence_container con_ssf ->
      (Skeleton_set_fence_container_v.name con_ssf)
;;

let string_off = function
  | Skeleton_set_container_t.Skeleton_set_body_container con_ssb ->
      (Skeleton_set_body_container_v.string_off con_ssb)
        
  | Skeleton_set_container_t.Skeleton_set_fence_container con_ssf ->
      (Skeleton_set_fence_container_v.string_off con_ssf)
;;

let longname = function
  | Skeleton_set_container_t.Skeleton_set_body_container con_ssb ->
      (Skeleton_set_body_container_v.longname con_ssb)
        
  | Skeleton_set_container_t.Skeleton_set_fence_container con_ssf ->
      (Skeleton_set_fence_container_v.longname con_ssf)
;;

let fullname = function
  | Skeleton_set_container_t.Skeleton_set_body_container con_ssb ->
      (Skeleton_set_body_container_v.fullname con_ssb)
        
  | Skeleton_set_container_t.Skeleton_set_fence_container con_ssf ->
      (Skeleton_set_fence_container_v.fullname con_ssf)
;;

(** {6 Coercing Tag} *)

(** {9 Coercing Up Tag} *)

let coerce_up_tag tag_fse =
  Tag_v.map_entity 
    Skeleton_symbol_v.skeleton_symbol_of_skeleton_set_symbol 
    tag_fse
;;

(** {9 Coercing Down Builder to Containee} *)

let containee_tag_off_builder_tag tag_ske =
  Tag_v.map_entity
    Skeleton_symbol_v.skeleton_set_fence_symbol_off_skeleton_symbol
    tag_ske
;;

(** {9 Coercing Up Containee_up to Builder} *)

let builder_tag_of_containee_tag tag_cnu =
  Tag_v.map_entity 
    Skeleton_symbol_v.skeleton_symbol_of_skeleton_set_fence_symbol
    tag_cnu
;;

(** {6 Builders} *)

(** {9 Builder Tag list} *)

let builder_tag_list_of_tag tag_fse =
  let (sym_fse, soi_fse) = tag_fse in
  match sym_fse with
  | Skeleton_set_symbol_t.Skeleton_set_body_symbol sym_ssb ->
      let tag_ssb = Tag_v.make sym_ssb soi_fse in
      Skeleton_set_body_container_v.builder_tag_list_of_tag tag_ssb

  | Skeleton_set_symbol_t.Skeleton_set_fence_symbol sym_ssf ->
      let tag_ssf = Tag_v.make sym_ssf soi_fse in
      Skeleton_set_fence_container_v.builder_tag_list_of_tag tag_ssf
;;

(** {9 Builder Tag Tuple} *)

let builder_tag_tuple tag_fse =
  let tag_bui_l = builder_tag_list_of_tag tag_fse in
  Tuple_v.tuple_of_list tag_bui_l
;;

(** {9 Building as Builder Tag tuple} *)

let building_of_tag tag_fse =
  builder_tag_list_of_tag tag_fse
;;

(** {6 Container} *)

let containee_tag_list_of_tag tag_fse =
  let tag_bui_l = builder_tag_list_of_tag tag_fse in
  List.map containee_tag_off_builder_tag tag_bui_l
;;

(** {6 Fence *)

let fence_as_list tag_fse =
  let tag_ske = coerce_up_tag tag_fse in
  Skeleton_fence_by_skeleton_tag_provider_v.provide tag_ske
;;

let fence_as_tuple tag_fse =
  let fen_l = fence_as_list tag_fse in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list tag_fse =
  let fen_l = fence_as_list tag_fse in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_tuple_body_stem_2sibling_1containee_v.sh skeleton_set fse body ssb fence ssf skeleton_set_fence ssf skeleton_set_fence ssf *)
(* using ./template_container_as_tuple_body_stem_2sibling_1containee_v.ml *)
(* done on mardi 3 janvier 2017, 15:37:09 (UTC+0100) *)

