(** {3 Skeleton_set_body_centered_aopefset_container_t} *)


(** {6 Typing_for_container} *)

type skeleton_set_body_centered_aopefset_container =
  | Skeleton_set_body_centered_aopefset_onecenter_container of Skeleton_set_body_centered_aopefset_onecenter_container_t.skeleton_set_body_centered_aopefset_onecenter_container
  | Skeleton_set_body_centered_aopefset_anycenter_container of Skeleton_set_body_centered_aopefset_anycenter_container_t.skeleton_set_body_centered_aopefset_anycenter_container
  | Skeleton_set_body_centered_aopefset_shellsymmetry_container of Skeleton_set_body_centered_aopefset_shellsymmetry_container_t.skeleton_set_body_centered_aopefset_shellsymmetry_container
  | Skeleton_set_body_centered_aopefset_shellordinal_container of Skeleton_set_body_centered_aopefset_shellordinal_container_t.skeleton_set_body_centered_aopefset_shellordinal_container
;;


(** Skeleton_set_body_centered_aopefset_container_t at 14:13:13 on 5 Jan 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh skeleton_set_body_centered_aopefset *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/skeletonset/skeletonset_symbols/Skeleton_set_body_centered_aopefset_symbol_t.ml *)
(* Done on jeudi 5 janvier 2017, 19:03:02 (UTC+0100) *)
