(** {3 Skeleton_set_fence_centered_aopef_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FSKE:Skeleton_set_fence_centered_aopef_container_v";
   "Needs : BSKE:Skeleton_any_category_by_sole_index_extractor_v";
   "Needs : BSKE:Skeleton_fence_by_skeleton_tag_provider_v";
   "Needed-by: ";
   "Definition : a Builder (for an Entity of a Domain) is a son of its B-Tree i.e. Coerced Up";
   "Definition : a Builder of a fence Container is its own Tag Coerced Up";
   "Builder_tag : Skeleton_tag";
   "Definition : a Building is the same Datastructure as a Container but filled with Builders"; 
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : the Containee Tag of a fence Container is its own Tag";
   "Containee_tag : Skeleton_set_fence_centered_aopef_tag";
   "Definition : the Fence is the Tag list (Coerced Up) of the Leaf Entities of the B-Tree of any Entity";
   "Fence : Skeleton_tag list";
   "Definition : a Bud type is a Stem type with only one constructor of string";
   "What-is-it: it is a container of a Fence Bud Type as a Uno of Skeleton_set_fence_centered_aopef_tag (i.e. Skeleton_set_fence_centered_aopef_tag)";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Coercing Up Tag} *)

let builder_tag_of_containee_tag tag_sca =
  Tag_v.map_entity 
    Skeleton_symbol_v.skeleton_symbol_of_skeleton_set_fence_centered_aopef_symbol 
    tag_sca
;;

(** {6 Coercing Down Tag} *)

let containee_tag_off_builder_tag tag_ske =
  Tag_v.map_entity
    Skeleton_symbol_v.skeleton_set_fence_centered_aopef_symbol_off_skeleton_symbol
    tag_ske
;;

(** {6 Builder Tag Datastructures : Building} *)

let building_of_tag tag_sca =
  let tag_ske = builder_tag_of_containee_tag tag_sca in
  Uno_v.make tag_ske
;;

let builder_tag_uno tag_sca =
  building_of_tag tag_sca
;;

let builder_tag_list_of_tag tag_sca =
  let tag_ske = builder_tag_of_containee_tag tag_sca in
  [tag_ske]
;;

let builder_tag_tuple_of_tag tag_sca =
  let bug = building_of_tag tag_sca in
  Tuple_v.tuple_of_uno bug
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_sca =
  Uno_v.make tag_sca
;;

(** {6 Fence list *)

let fence_as_list_of_tag tag_sca =
  let tag_ske = builder_tag_of_containee_tag tag_sca in
  Skeleton_fence_by_skeleton_tag_provider_v.provide tag_ske
;;

let fence_as_tuple_of_tag tag_sca =
  let fen_l = fence_as_list_of_tag tag_sca in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_sca =
  let fen_l = fence_as_list_of_tag tag_sca in
  Tuple_list_v.make fen_l
;;

(** {6 Naming_for_container} *)

let name con_sca =
  Uno_v.name 
    Skeleton_set_fence_centered_aopef_tag_v.name
    con_sca
;;

let string_off con_sca =
  Uno_v.name 
    Skeleton_set_fence_centered_aopef_tag_v.string_off
    con_sca
;;

let longname con_sca =
  Uno_v.name 
    Skeleton_set_fence_centered_aopef_tag_v.longname
    con_sca
;;

let fullname con_sca =
  Uno_v.name 
    Skeleton_set_fence_centered_aopef_tag_v.fullname
    con_sca
;;


(* generated by ./do_container_as_uno_fence_bud_0containee_v.sh skeleton_set_fence_centered_aopef sca *)
(* using ./template_container_as_uno_fence_bud_0containee_v.ml *)
(* Done on jeudi 5 janvier 2017, 19:38:46 (UTC+0100) *)
