(** {3 Skeleton_context_container_t} *)


(** {6 Typing_for_container} *)

type skeleton_context_container =
  | Skeleton_context_database_container of Skeleton_context_database_container_t.skeleton_context_database_container
  | Skeleton_context_databox_container of Skeleton_context_databox_container_t.skeleton_context_databox_container
  | Skeleton_context_domain_container of Skeleton_context_domain_container_t.skeleton_context_domain_container
  | Skeleton_context_sector_container of Skeleton_context_sector_container_t.skeleton_context_sector_container
;;


(** Skeleton_context_container_t at 14:13:12 on 5 Jan 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh skeleton_context *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/skeletonset/skeletonset_symbols/Skeleton_context_symbol_t.ml *)
(* Done on jeudi 5 janvier 2017, 19:03:02 (UTC+0100) *)
