(** {3 Skeleton_set_container_t} *)


(** {6 Typing_for_container} *)

type skeleton_set_container =
  | Skeleton_set_body_container of Skeleton_set_body_container_t.skeleton_set_body_container
  | Skeleton_set_fence_container of Skeleton_set_fence_container_t.skeleton_set_fence_container
;;


(** Skeleton_set_container_t at 14:13:12 on 5 Jan 2017. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh skeleton_set *)
(* using /keep/sources/ocaml_top/setup/frames/internalsector/skeletonset/skeletonset_symbols/Skeleton_set_symbol_t.ml *)
(* Done on jeudi 5 janvier 2017, 19:03:02 (UTC+0100) *)
