(** {3 Skeleton_body_centered_aopefset_shellordinal_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FSKE:Skeleton_body_centered_aopefset_shellordinal_container_v";
   "Needs : FSKE:Skeleton_fence_centered_aopef_tag_v";
   "Needs : DSKE:Skeleton_any_category_by_sole_index_extractor_v";
   "Needs : DSKE:Skeleton_fence_by_skeleton_tag_provider_v";
   "Needed-by: ";
   "Definition : a Builder (for an Entity of a Domain) is a son its Builder-Subtree";
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a Building is the Datastructure of the Builders of an Entity (Container with Builders)"; 
   "Definition : a Trunc type has only constructors of constructor";
   "Definition : a Branch type has only constructors of nothing";
   "Definition : a Stem type has only constructor of string";
   "Definition : a Bud type is a Stem type with only one constructor of string";
   "What-is-it : it is a container of a Bud Type as a List of Skeleton_fence_centered_aopef_tag";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name con_sso =
  List_v.name 
    Skeleton_fence_centered_aopef_tag_v.name
    con_sso
;;

let string_off con_sso =
  List_v.name 
    Skeleton_fence_centered_aopef_tag_v.string_off
    con_sso
;;

let longname con_sso =
  List_v.name 
    Skeleton_fence_centered_aopef_tag_v.longname
    con_sso
;;

let fullname con_sso =
  List_v.name 
    Skeleton_fence_centered_aopef_tag_v.fullname
    con_sso
;;

(** {6 Coercing Up Tag} *)

let coerce_up_of_tag tag_sso =
  Tag_v.map_entity 
    Skeleton_symbol_v.skeleton_symbol_of_skeleton_body_centered_aopefset_shellordinal_symbol 
    tag_sso
;;

(** {6 Coercing Down Containee} *)

let containee_tag_off_builder_tag tag_ske =
  Tag_v.map_entity
    Skeleton_symbol_v.skeleton_fence_centered_aopef_symbol_off_skeleton_symbol
    tag_ske
;;

(** {6 Building as Builder Tag list} *)

let building_of_tag tag_sso =
  let tag_ske = coerce_up_of_tag tag_sso in
  Son_skeleton_tag_list_by_father_skeleton_tag_provider_v.provide tag_ske
;;

(** {6 Builder Tag Datastructures} *)

let builder_tag_list_of_tag tag_sso =
  building_of_tag tag_sso
;;

let builder_tag_tuple_of_tag tag_sso =
  let tag_bui_l = builder_tag_list_of_tag tag_sso in
  Tuple_v.tuple_of_list tag_bui_l
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_sso =
  let bug = building_of_tag tag_sso in
  List.map (* Coerce Down *)
    containee_tag_off_builder_tag
    bug
;;

(** {6 Containee Tag Datastructures} *)

let containee_tag_list_of_tag tag_sso =
  container_of_tag tag_sso
;;

let containee_tag_tuple tag_sso =
  let tag_cne_l = containee_tag_list_of_tag tag_sso in
  Tuple_v.tuple_of_list tag_cne_l
;;

(** {6 Fence list *)

let fence_as_list_of_tag tag_sso =
  let tag_ske = coerce_up_of_tag tag_sso in
  Skeleton_fence_by_skeleton_tag_provider_v.provide tag_ske
;;

let fence_as_tuple_of_tag tag_sso =
  let tag_cne_t = containee_tag_tuple tag_sso in
  Tuple_v.map
    Skeleton_fence_centered_aopef_container_v.fence_as_list_of_tag
    tag_cne_t
;;

let fence_as_tuple_list_of_tag tag_sso =
  let tag_cne_l = containee_tag_list_of_tag tag_sso in
  List_v.map
    Skeleton_fence_centered_aopef_container_v.fence_as_tuple_of_tag
    tag_cne_l
;;


(* generated by ./do_container_as_list_body_bud_1containee_v.sh skeleton_body_centered_aopefset_shellordinal sso skeleton_fence_centered_aopef sca *)
(* using ./template_container_as_list_body_bud_1containee_v.ml *)
(* Done on mardi 3 janvier 2017, 17:54:00 (UTC+0100) *)

