(** {3 Skeleton_set_fence_periodic_wavelet_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FSKE:Skeleton_set_fence_periodic_wavelet_container_v";
   "Needs : BSKE:Skeleton_any_category_by_sole_index_extractor_v";
   "Needs : BSKE:Skeleton_fence_by_skeleton_tag_provider_v";
   "Needed-by: ";
   "Definition : a Builder (for an Entity of a Domain) is a son of its B-Tree i.e. Coerced Up";
   "Definition : a Builder of a fence Container is its own Tag Coerced Up";
   "Builder_tag : Skeleton_tag";
   "Definition : a Building is the same Datastructure as a Container but filled with Builders"; 
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : the Containee Tag of a fence Container is its own Tag";
   "Containee_tag : Skeleton_set_fence_periodic_wavelet_tag";
   "Definition : the Fence is the Tag list (Coerced Up) of the Leaf Entities of the B-Tree of any Entity";
   "Fence : Skeleton_tag list";
   "Definition : a Bud type is a Stem type with only one constructor of string";
   "What-is-it: it is a container of a Fence Bud Type as a Uno of Skeleton_set_fence_periodic_wavelet_tag (i.e. Skeleton_set_fence_periodic_wavelet_tag)";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Coercing Up Tag} *)

let builder_tag_of_containee_tag tag_spw =
  Tag_v.map_entity 
    Skeleton_symbol_v.skeleton_symbol_of_skeleton_set_fence_periodic_wavelet_symbol 
    tag_spw
;;

(** {6 Coercing Down Tag} *)

let containee_tag_off_builder_tag tag_ske =
  Tag_v.map_entity
    Skeleton_symbol_v.skeleton_set_fence_periodic_wavelet_symbol_off_skeleton_symbol
    tag_ske
;;

(** {6 Builder Tag Datastructures : Building} *)

let building_of_tag tag_spw =
  let tag_ske = builder_tag_of_containee_tag tag_spw in
  Uno_v.make tag_ske
;;

let builder_tag_uno tag_spw =
  building_of_tag tag_spw
;;

let builder_tag_list_of_tag tag_spw =
  let tag_ske = builder_tag_of_containee_tag tag_spw in
  [tag_ske]
;;

let builder_tag_tuple_of_tag tag_spw =
  let bug = building_of_tag tag_spw in
  Tuple_v.tuple_of_uno bug
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_spw =
  Uno_v.make tag_spw
;;

(** {6 Fence list *)

let fence_as_list_of_tag tag_spw =
  let tag_ske = builder_tag_of_containee_tag tag_spw in
  Skeleton_fence_by_skeleton_tag_provider_v.provide tag_ske
;;

let fence_as_tuple_of_tag tag_spw =
  let fen_l = fence_as_list_of_tag tag_spw in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_spw =
  let fen_l = fence_as_list_of_tag tag_spw in
  Tuple_list_v.make fen_l
;;

(** {6 Naming_for_container} *)

let name con_spw =
  Uno_v.name 
    Skeleton_set_fence_periodic_wavelet_tag_v.name
    con_spw
;;

let string_off con_spw =
  Uno_v.name 
    Skeleton_set_fence_periodic_wavelet_tag_v.string_off
    con_spw
;;

let longname con_spw =
  Uno_v.name 
    Skeleton_set_fence_periodic_wavelet_tag_v.longname
    con_spw
;;

let fullname con_spw =
  Uno_v.name 
    Skeleton_set_fence_periodic_wavelet_tag_v.fullname
    con_spw
;;


(* generated by ./do_container_as_uno_fence_bud_0containee_v.sh skeleton_set_fence_periodic_wavelet spw *)
(* using ./template_container_as_uno_fence_bud_0containee_v.ml *)
(* Done on jeudi 5 janvier 2017, 19:38:47 (UTC+0100) *)
