REGISTERS_V_MLI := \
Basicname_databox_n_basicname_database_by_db1pointsdata_context_databox_tag_register_v.mli \
Db1pointsdata_creation_module_name_by_sole_index_register_v.mli \
Db1pointsdata_father_tag_by_db1pointsdata_son_tag_register_v.mli \
Db1pointsdata_set_fence_by_db1pointsdata_tag_register_v.mli \
Db1pointsdata_son_tag_list_by_db1pointsdata_father_tag_register_v.mli \
Db1pointsdata_symbol_by_sole_index_register_v.mli \
Db1pointsdata_symbol_subtree_by_basicname_databox_register_v.mli \
Db1pointsdata_as_set_body_sequence_float_symbol_subtree_list_by_basicname_databox_register_v.mli \
Db1pointsdata_as_set_body_record_vertex_symbol_subtree_list_by_basicname_databox_register_v.mli \
Db1pointsdata_tag_all_list_by_basicname_databox_register_v.mli \
Db1pointsdata_tag_all_list_by_db1pointsdata_context_databox_tag_register_v.mli \
Db1pointsdata_tag_subtree_by_db1pointsdata_tag_register_v.mli \
Db1pointsdata_tag_tree_by_basicname_databox_register_v.mli \
  
CONTEXT_NAME_V_MLI := \
Db1pointsdata_basicname_trio_by_unit_provider_v.mli \
Db1pointsdata_basicname_by_unit_provider_v.mli \
Db1pointsdata_context_domain_name_by_unit_provider_v.mli \
Db1pointsdata_basicname_database_by_unit_provider_v.mli \
 
CONTEXT_TAG_V_MLI := \
Db1pointsdata_context_sector_tag_by_unit_provider_v.mli \
Db1pointsdata_as_context_sector_tag_by_unit_provider_v.mli \
 \
Db1pointsdata_context_domain_tag_by_unit_provider_v.mli \
Db1pointsdata_as_context_domain_tag_by_unit_provider_v.mli \
 \
Db1pointsdata_context_database_tag_by_unit_provider_v.mli \
Db1pointsdata_as_context_database_tag_by_unit_provider_v.mli \
 \
Db1pointsdata_context_databox_tag_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_context_databox_tag_by_basicname_databox_provider_v.mli \
 \
Db1pointsdata_context_databox_sole_index_by_any_sole_index_provider_v.mli \
Db1pointsdata_context_databox_symbol_by_any_sole_index_provider_v.mli \
Db1pointsdata_context_databox_tag_by_any_sole_index_provider_v.mli \
 \
Basicname_databox_by_db1pointsdata_context_databox_tag_provider_v.mli \
Basicname_databox_n_basicname_database_by_db1pointsdata_context_databox_tag_provider_v.mli \
 
CONTEXT_TAG_QUATUOR_V_MLI := \
Db1pointsdata_as_context_tag_quatuor_by_basicname_databox_provider_v.mli \
Db1pointsdata_context_tag_quadruplet_by_basicname_databox_provider_v.mli \

SYMBOL_SUBTREE_FROM_PARSER_V_MLI := \
Db1pointsdata_symbol_subtree_by_basicname_databox_provider_v.mli \
Db1pointsdata_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_v.mli \

TAG_TREE_V_MLI := \
Db1pointsdata_tag_tree_by_basicname_databox_provider_v.mli \
Db1pointsdata_tag_tree_by_db1pointsdata_context_databox_tag_provider_v.mli \
 
INTERFACES_V_MLI := \
Db1pointsdata_tag_all_list_by_basicname_databox_provider_v.mli \
Db1pointsdata_tag_all_list_by_db1pointsdata_context_databox_tag_provider_v.mli \
 
EXTRACTORS_V_MLI := \
Db1pointsdata_symbol_by_sole_index_register_filler_v.mli \
Db1pointsdata_symbol_by_sole_index_provider_v.mli \
Db1pointsdata_any_category_by_sole_index_extractor_v.mli \
Db1pointsdata_son_tag_list_by_db1pointsdata_father_tag_provider_v.mli \
Db1pointsdata_father_tag_by_db1pointsdata_son_tag_provider_v.mli \
Db1pointsdata_tag_subtree_by_db1pointsdata_tag_provider_v.mli \
 
FENCE_V_MLI := \
Db1pointsdata_as_set_body_sequence_float_tag_list_by_db1pointsdata_context_databox_tag_provider_v.mli \
Db1pointsdata_as_set_body_sequence_float_tag_list_by_basicname_databox_provider_v.mli \
 \
Db1pointsdata_set_fence_by_db1pointsdata_tag_provider_v.mli \
 
SYMBOL_SUBTREE_FOR_TRANSLATION_V_MLI := \
Db1pointsdata_as_set_body_cluster_information_symbol_subtree_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_body_cluster_vertex_symbol_subtree_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_body_bundle_coordinates_symbol_subtree_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_body_bundle_figure_symbol_subtree_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_body_record_vertex_symbol_subtree_list_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_body_sequence_float_symbol_subtree_list_by_basicname_databox_provider_v.mli \
 \
Db1pointsdata_as_set_body_record_vertex_symbol_subtree_by_vertex_name_n_databox_name_provider_v.mli \
Db1pointsdata_as_set_body_sequence_float_symbol_subtree_by_vertex_name_n_databox_name_provider_v.mli \
 
SYMBOL_LIST_FOR_TRANSLATION_V_MLI := \
Db1pointsdata_as_set_body_name_vertex_symbol_list_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_fence_basic_numerical_float_symbol_list_by_vertex_name_n_databox_name_provider_v.mli \
 
SYMBOL_FOR_TRANSLATION_V_MLI := \
Db1pointsdata_as_set_fence_token_figure_kind_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_fence_token_coordinates_kind_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_fence_token_coordinates_units_angle_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_as_set_fence_token_coordinates_units_length_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_set_fence_token_figure_kind_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_set_fence_token_coordinates_kind_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_set_fence_token_coordinates_units_angle_symbol_by_basicname_databox_provider_v.mli \
Db1pointsdata_set_fence_token_coordinates_units_length_symbol_by_basicname_databox_provider_v.mli \
 
MEASURE_V_MLI := \
Units_by_db1pointsdata_set_fence_token_coordinates_units_angle_symbol_provider_v.mli \
Units_by_db1pointsdata_set_fence_token_coordinates_units_length_symbol_provider_v.mli \
Float_list_by_db1pointsdata_set_body_sequence_float_tag_provider_v.mli \
Units_tuple_by_db1pointsdata_set_body_sequence_float_tag_provider_v.mli \
Measure_list_by_db1pointsdata_set_body_sequence_float_tag_provider_v.mli \
 
FILES_MLI := \
$(REGISTERS_V_MLI) \
$(SYMBOL_SUBTREE_FROM_PARSER_V_MLI) \
$(CONTEXT_NAME_V_MLI) \
$(CONTEXT_TAG_V_MLI) \
$(CONTEXT_TAG_QUATUOR_V_MLI) \
$(TAG_TREE_V_MLI) \
$(INTERFACES_V_MLI) \
$(EXTRACTORS_V_MLI) \
$(FENCE_V_MLI) \
$(SYMBOL_SUBTREE_FOR_TRANSLATION_V_MLI) \
$(SYMBOL_LIST_FOR_TRANSLATION_V_MLI) \
$(SYMBOL_FOR_TRANSLATION_V_MLI) \
$(MEASURE_V_MLI) \
 