NEEDED_DIRS := \
	$(LOCALINPUTSET_VARIABLES_DIR) \
	$(FIGURESET_ENVELOPES_DIR) \
	$(SKELETONSET_ENVELOPES_DIR) \
	$(PROPERTYSET_ENVELOPES_DIR) \
	$(ELEMENTARYSET_ENVELOPES_DIR) \
	$(PROPERTYSET_INTERDOMAINS_DIR) \
 