INCLUDED_DIRS := \
        $(BASICS_DIR) \
        $(DATASTRUCTURES_DIR) \
	$(CHEMICALSET_SYMBOLS_DIR) \
	$(FIGURESET_SYMBOLS_DIR) \
	$(GENERATORSET_SYMBOLS_DIR) \
	$(MUSICSET_SYMBOLS_DIR) \
	$(DOMAINSET_SYMBOLS_DIR) \
  