(** {3 Db1pointsdata_set_fence_token_coordinates_units_length_symbol_t} *)


(** {6 Typing_for_symbol} *)

type db1pointsdata_set_fence_token_coordinates_units_length_symbol =
  | Db1pointsdata_set_fence_token_coordinates_units_length_angstrom_symbol of Db1pointsdata_set_fence_token_coordinates_units_length_angstrom_symbol_t.db1pointsdata_set_fence_token_coordinates_units_length_angstrom_symbol
  | Db1pointsdata_set_fence_token_coordinates_units_length_bohr_symbol of Db1pointsdata_set_fence_token_coordinates_units_length_bohr_symbol_t.db1pointsdata_set_fence_token_coordinates_units_length_bohr_symbol
  | Db1pointsdata_set_fence_token_coordinates_units_length_meter_symbol of Db1pointsdata_set_fence_token_coordinates_units_length_meter_symbol_t.db1pointsdata_set_fence_token_coordinates_units_length_meter_symbol
  | Db1pointsdata_set_fence_token_coordinates_units_length_nanometer_symbol of Db1pointsdata_set_fence_token_coordinates_units_length_nanometer_symbol_t.db1pointsdata_set_fence_token_coordinates_units_length_nanometer_symbol
;;


(** Db1pointsdata_set_fence_token_coordinates_units_length_symbol_t at 15:8:2 on 31 Oct 2018. created by version v2.5 of generator *)



