(** {3 Figure_set_body_triangle_scalene_container_t} *)


(** {6 Typing_for_container} *)

type figure_set_body_triangle_scalene_container =
  | Figure_set_body_triangle_scalene_acute_container of Figure_set_body_triangle_scalene_acute_container_t.figure_set_body_triangle_scalene_acute_container
  | Figure_set_body_triangle_scalene_obtuse_container of Figure_set_body_triangle_scalene_obtuse_container_t.figure_set_body_triangle_scalene_obtuse_container
  | Figure_set_body_triangle_scalene_right_container of Figure_set_body_triangle_scalene_right_container_t.figure_set_body_triangle_scalene_right_container
;;


(** Figure_set_body_triangle_scalene_container_t at 13:58:13 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh figure_set_body_triangle_scalene *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/figureset/figureset_symbols/Figure_set_body_triangle_scalene_symbol_t.ml *)
(* done on vendredi 2 décembre 2016, 14:43:46 (UTC+0100) *)
