(** {3 Figure_container_t} *)


(** {6 Typing_for_container} *)

type figure_container =
  | Figure_context_container of Figure_context_container_t.figure_context_container
  | Figure_set_container of Figure_set_container_t.figure_set_container
;;


(** Figure_container_t at 13:58:11 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh figure *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/figureset/figureset_symbols/Figure_symbol_t.ml *)
(* done on vendredi 2 décembre 2016, 14:43:46 (UTC+0100) *)
