(** {3 Figure_set_fence_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FFIG:Figure_set_fence_container_v";
   "Needs : FFIG:Figure_set_fence_tag_v";
   "Needs : FFIG:Figure_set_fence_point_container_v";
   "Needs : DFIG:Figure_any_category_by_sole_index_extractor_v";
   "Needs : DFIG:Figure_fence_by_figure_tag_provider_v";
   "Needed-by: ";
   "What-is-it : Up_coercion of Container type as Symbol type up_coercion";
   "What-is-it : it is a Stem container of its own Tag Uno Tag";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name = function
  | Figure_set_fence_container_t.Figure_set_fence_point_container con_fpo ->
      (Figure_set_fence_point_container_v.name con_fpo)
;;

let string_off = function
  | Figure_set_fence_container_t.Figure_set_fence_point_container con_fpo ->
      (Figure_set_fence_point_container_v.string_off con_fpo)
;;

let longname = function
  | Figure_set_fence_container_t.Figure_set_fence_point_container con_fpo ->
      (Figure_set_fence_point_container_v.longname con_fpo)
;;

let fullname = function
  | Figure_set_fence_container_t.Figure_set_fence_point_container con_fpo ->
      (Figure_set_fence_point_container_v.fullname con_fpo)
;;

(** {6 Coercing Tag} *)

(** {9 Coercing Up Tag} *)

let coerce_up_tag tag_ffe =
  Tag_v.map_entity 
    Figure_symbol_v.figure_symbol_of_figure_set_fence_symbol 
    tag_ffe
;;

(** {9 Coercing Down Builder to Containee} *)

let containee_tag_off_builder_tag tag_fig =
  Tag_v.map_entity
    Figure_symbol_v.figure_set_fence_symbol_off_figure_symbol
    tag_fig
;;

(** {9 Coercing Up Containee_up to Builder} *)

let builder_tag_of_containee_tag tag_cnu =
  Tag_v.map_entity 
    Figure_symbol_v.figure_symbol_of_figure_set_fence_symbol
    tag_cnu
;;

(** {6 Builders} *)

(** {9 Builder Tag list} *)

let builder_tag_list_of_tag tag_ffe =
  let tag_bui = builder_tag_of_containee_tag tag_ffe in
  [tag_bui]
;;

(** {9 Builder Tag Tuple} *)

let builder_tag_tuple tag_ffe =
  let tag_bui_l = builder_tag_list_of_tag tag_ffe in
  Tuple_v.tuple_of_list tag_bui_l
;;

(** {9 Building as Builder Tag tuple} *)

let building_of_tag tag_ffe =
  builder_tag_list_of_tag tag_ffe
;;

(** {6 Container} *)

let containee_tag_list_of_tag tag_ffe =
  let tag_bui_l = builder_tag_list_of_tag tag_ffe in
  List.map containee_tag_off_builder_tag tag_bui_l
;;

(** {6 Fence *)

let fence_as_list_of_tag tag_ffe =
  let tag_fig = coerce_up_tag tag_ffe in
  Figure_fence_by_figure_tag_provider_v.provide tag_fig
;;

let fence_as_tuple_of_tag tag_ffe =
  let fen_l = fence_as_list_of_tag tag_ffe in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_ffe =
  let fen_l = fence_as_list_of_tag tag_ffe in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_uno_fence_stem_1sibling_1containee_v.sh figure_set_fence ffe figure_set_fence_point fpo figure_set_fence ffe *)
(* using ./template_container_as_uno_fence_stem_1sibling_1containee_v.ml *)
(* done on vendredi 2 décembre 2016, 14:43:52 (UTC+0100) *)

