(** {3 Figure_set_fence_point_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FFIG:Figure_set_fence_point_container_v";
   "Needs : FFIG:Figure_set_fence_point_tag_v";
   "Needs : DFIG:Figure_any_category_by_sole_index_extractor_v";
   "Needs : DFIG:Figure_fence_by_figure_tag_provider_v";
   "Needed-by: ";
   "Definition : a Builder (for an Entity of a Domain) is a son of its Builder-Subtree";
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a Building is the Datastructure of the Builders of an Entity (Container with Builders)"; 
   "Definition : a Stalk is a type with only one constructor of nothing";
   "Definition : a Bud type is a type with only one constructor of string";
   "Definition : a Stem type has only constructor of string";
   "Definition : a Branch type has only constructors of nothing";
   "Definition : a Trunc type has only constructors of constructor";
   "What-is-it: it is a container of a Fence Bud Type as a Uno of Conee_tag (i.e. Figure_set_fence_point_tag)";
   "What-is-it: its Fence is its Tag";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name con_fpo =
  Uno_v.name 
    Figure_set_fence_point_tag_v.name
    con_fpo
;;

let string_off con_fpo =
  Uno_v.name 
    Figure_set_fence_point_tag_v.string_off
    con_fpo
;;

let longname con_fpo =
  Uno_v.name 
    Figure_set_fence_point_tag_v.longname
    con_fpo
;;

let fullname con_fpo =
  Uno_v.name 
    Figure_set_fence_point_tag_v.fullname
    con_fpo
;;

(** {6 Coercing Up Tag} *)

let builder_tag_of_containee_tag tag_cnn =
  Tag_v.map_entity 
    Figure_symbol_v.figure_symbol_of_figure_set_fence_point_symbol 
    tag_cnn
;;

(** {6 Coercing Down Tag} *)

let containee_tag_off_builder_tag tag_fig =
  Tag_v.map_entity
    Figure_symbol_v.figure_set_fence_point_symbol_off_figure_symbol
    tag_fig
;;

(** {6 Builder Tag Datastructures : Building} *)

let building_of_tag tag_fpo =
  let tag_fig = builder_tag_of_containee_tag tag_fpo in
  Uno_v.make tag_fig
;;

let builder_tag_uno tag_fpo =
  building_of_tag tag_fpo
;;

let builder_tag_list_of_tag tag_fpo =
  let tag_fig = builder_tag_of_containee_tag tag_fpo in
  [tag_fig]
;;

let builder_tag_tuple tag_fpo =
  let bug = building_of_tag tag_fpo in
  Tuple_v.tuple_of_uno bug
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_fpo =
  Uno_v.make tag_fpo
;;

(** {6 Fence list *)

let fence_as_list_of_tag tag_fpo =
  [tag_fpo]
;;

let fence_as_tuple_of_tag tag_fpo =
  let fen_l = fence_as_list_of_tag tag_fpo in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_fpo =
  let fen_l = fence_as_list_of_tag tag_fpo in
  Tuple_list_v.make fen_l
;;


(* generated by ./do_container_as_uno_fence_bud_v.sh figure_set_fence_point fpo *)
(* using ./template_container_as_uno_fence_bud_v.ml *)
(* done on vendredi 2 décembre 2016, 14:43:50 (UTC+0100) *)

