(** {3 Figure_set_container_t} *)


(** {6 Typing_for_container} *)

type figure_set_container =
  | Figure_set_body_container of Figure_set_body_container_t.figure_set_body_container
  | Figure_set_fence_container of Figure_set_fence_container_t.figure_set_fence_container
;;


(** Figure_set_container_t at 13:58:12 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh figure_set *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/figureset/figureset_symbols/Figure_set_symbol_t.ml *)
(* done on vendredi 2 décembre 2016, 14:43:46 (UTC+0100) *)
