(** {3 Figure_context_container_t} *)


(** {6 Typing_for_container} *)

type figure_context_container =
  | Figure_context_database_container of Figure_context_database_container_t.figure_context_database_container
  | Figure_context_databox_container of Figure_context_databox_container_t.figure_context_databox_container
  | Figure_context_domain_container of Figure_context_domain_container_t.figure_context_domain_container
  | Figure_context_sector_container of Figure_context_sector_container_t.figure_context_sector_container
;;


(** Figure_context_container_t at 13:58:11 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh figure_context *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/figureset/figureset_symbols/Figure_context_symbol_t.ml *)
(* done on vendredi 2 décembre 2016, 14:43:46 (UTC+0100) *)
