#!/bin/bash

this=$1
ttt=$2
buldr=$3
bbb=$4
mainb=$5
mbu=$6
bui_1=$7
bui_2=$8
bui_3=$9
datstr=${10}

if [ "${datstr}" == "" ] 
then 
    echo "$0 : datstr (10th argument) is missing"
    exit
fi

dat=`date`
category="container"
suffix="v"

This=`capitalize_first.sh ${this}`
Sibling_1=`capitalize_first.sh ${sibling_1}`
Sibling_2=`capitalize_first.sh ${sibling_2}`
Sibling_3=`capitalize_first.sh ${sibling_3}`
Buldr=`capitalize_first.sh ${buldr}`
Clsur=`capitalize_first.sh ${clsur}`
Datstr=`capitalize_first.sh ${datstr}`

template=`echo "$0" | sed -e 's/do_/template_/' -e 's/\.sh/.ml/'`

module="${this}_${category}_${suffix}"
Module=`capitalize_first.sh ${module}`
file="${module}.ml"
File=`capitalize_first.sh ${file}`
supplement="supplement_${file}"

if [ ! -f ${template} ] 
then 
    echo "file ${template} is missing"
    exit
fi
if [ ! -f ${supplement} ] 
then 
    echo "touch ${supplement}"
    exit
fi

sed -e "s/this/$this/g" -e "s/ttt/$ttt/g" -e "s/This/$This/g" \
    -e "s/buldr/$buldr/g" -e "s/Buldr/$Buldr/g" -e "s/bbb/$bbb/g" \
    -e "s/clsur/$clsur/g" -e "s/Clsur/$Clsur/g" -e "s/ccc/$ccc/g" \
    -e "s/datstr/$datstr/g" -e "s/Datstr/$Datstr/g" \
    -e "s/dta/$dta/g" -e "s/Dta/$Dta/g" \
    -e "s/bui_1/${bui_1}/g" -e "s/bui_2/${bui_2}/g" -e "s/bui_3/${bui_3}/g" \
    -e "s/mainb/$mainb/g" -e "s/Mainb/$Mainb/g"  -e "s/mbu/$mbu/g" \
    -e "s/sibling_1/${sibling_1}/g" -e "s/Sibling_1/${Sibling_1}/g" -e "s/sib_1/${sib_1}/g" \
    -e "s/sibling_2/${sibling_2}/g" -e "s/Sibling_2/${Sibling_2}/g" -e "s/sib_2/${sib_2}/g" \
    -e "s/sibling_3/${sibling_3}/g" -e "s/Sibling_3/${Sibling_3}/g" -e "s/sib_3/${sib_3}/g" \
     ${template} > ${File}

if [ -s ${supplement} ] 
then 
    cat ${supplement} >> ${File}
else
    echo "supplement ${supplement} is empty"
fi

echo "" >> ${File}
echo "(* generate/$0 ${this} ${ttt} ${buldr} ${bbb} ${mainb} ${mbu} ${sib_1} ${sib_2} ${sib_3} ${datstr} *)" >> ${File}
echo "(* using ${template} *)" >> ${File}

if [ -s ${supplement} ] 
then
    echo "(* adding ${supplement} *)" >> ${File} 
fi

echo "(* Done on ${dat} *)" >> ${File}

echo " cat ${File}"
echo " mv ${File} ../"
echo " make $Module.cmo"