# --- basic ---

# fence_bud

do_container_as_uno_fence_bud_t.sh elementary_fence_basic_boolean 
do_container_as_uno_fence_bud_t.sh elementary_fence_basic_float   
do_container_as_uno_fence_bud_t.sh elementary_fence_basic_integer 
do_container_as_uno_fence_bud_t.sh elementary_fence_basic_string  

# fence_trunc

do_container_from_symbol_this_t.sh elementary_fence_basic

# --- color ---

# fence_trunc
do_container_as_uno_fence_bud_t.sh elementary_fence_color 

# --- units ---

# fence_bud

do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_action
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_angle
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_charge
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_energy
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_length
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_mass
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_none
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_temperature
do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_time

do_container_as_uno_fence_bud_t.sh elementary_fence_units_canonical_classical
do_container_as_uno_fence_bud_t.sh elementary_fence_units_canonical_quantum

# fence_trunc

do_container_from_symbol_this_t.sh elementary_fence_units_actual
do_container_from_symbol_this_t.sh elementary_fence_units_canonical
do_container_from_symbol_this_t.sh elementary_fence_units

# --- coordinate ---

# border_bud coordinate

do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_phi elementary_fence_units_actual_angle
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_rho elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_zed elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_polar_rho elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_polar_theta elementary_fence_units_actual_angle
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_spherical_phi elementary_fence_units_actual_angle
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_spherical_rho elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_spherical_theta elementary_fence_units_actual_angle
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_homogeneous_cartesian_x elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_homogeneous_cartesian_y elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_homogeneous_cartesian_z elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_homogeneous_linear_x elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_homogeneous_planar_x elementary_fence_units_actual_length
do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_homogeneous_planar_y elementary_fence_units_actual_length

# border trunc coordinate  

do_container_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_cartesian 
do_container_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_linear
do_container_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_planar

do_container_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_cylindrical
do_container_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_polar
do_container_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_spherical

do_container_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous
do_container_from_symbol_this_t.sh elementary_border_coordinate_homogeneous
do_container_from_symbol_this_t.sh elementary_border_coordinate

# coordinate_tuple body_bud

do_container_as_triplet_body_bud_3containee_t.sh \
elementary_body_coordinate_tuple_homogeneous_cartesian \
elementary_border_coordinate_homogeneous_cartesian_x \
elementary_border_coordinate_homogeneous_cartesian_y \
elementary_border_coordinate_homogeneous_cartesian_z

do_container_as_doublet_body_bud_2containee_t.sh \
elementary_body_coordinate_tuple_homogeneous_planar \
elementary_border_coordinate_homogeneous_planar_x \
elementary_border_coordinate_homogeneous_planar_y

do_container_as_singlet_body_bud_1containee_t.sh \
elementary_body_coordinate_tuple_homogeneous_linear \
elementary_border_coordinate_homogeneous_linear_x

do_container_as_triplet_body_bud_3containee_t.sh \
elementary_body_coordinate_tuple_heterogeneous_cylindrical \
elementary_border_coordinate_heterogeneous_cylindrical_rho \
elementary_border_coordinate_heterogeneous_cylindrical_phi \
elementary_border_coordinate_heterogeneous_cylindrical_zed

do_container_as_triplet_body_bud_3containee_t.sh \
elementary_body_coordinate_tuple_heterogeneous_spherical \
elementary_border_coordinate_heterogeneous_spherical_rho \
elementary_border_coordinate_heterogeneous_spherical_phi \
elementary_border_coordinate_heterogeneous_spherical_theta

do_container_as_doublet_body_bud_2containee_t.sh \
elementary_body_coordinate_tuple_heterogeneous_polar \
elementary_border_coordinate_heterogeneous_polar_rho \
elementary_border_coordinate_heterogeneous_polar_theta
 
# body 

do_container_from_symbol_this_t.sh elementary_body_coordinate_tuple
do_container_from_symbol_this_t.sh elementary_body_coordinate_tuple_heterogeneous
do_container_from_symbol_this_t.sh elementary_body_coordinate_tuple_homogeneous

# context 

do_container_as_list_context_bud_1containee_t.sh elementary_context_domain     elementary_context_database
do_container_as_list_context_bud_1containee_t.sh elementary_context_database   elementary_context_databox

do_container_as_list_context_bud_1containee_t.sh elementary_context_databox_figuredata elementary_body_coordinate_tuple
do_container_as_list_context_bud_1containee_t.sh elementary_context_databox_skeletondata elementary_body_parameter_tuple


# --- parameter ---

# as_nplet_body_bud 
do_container_as_doublet_body_bud_2containee_t.sh \
elementary_body_parameter_tuple_aopef \
elementary_border_parameter_aopef_exponent \
elementary_border_parameter_aopef_coefficient

do_container_as_triplet_body_bud_3containee_t.sh \
elementary_body_parameter_tuple_ecppef \
elementary_border_parameter_ecppef_exponent \
elementary_border_parameter_ecppef_coefficient \
elementary_border_parameter_ecppef_coefficient

# border_bud

do_container_as_uno_border_bud_1containee_t.sh  elementary_border_parameter_aopef_coefficient  elementary_fence_units_actual_length 
do_container_as_uno_border_bud_1containee_t.sh  elementary_border_parameter_aopef_exponent     elementary_fence_units_actual_length 
do_container_as_uno_border_bud_1containee_t.sh  elementary_border_parameter_ecppef_coefficient elementary_fence_units_actual_length 
do_container_as_uno_border_bud_1containee_t.sh  elementary_border_parameter_ecppef_exponent    elementary_fence_units_actual_length  

do_container_from_symbol_this_t.sh elementary_border_parameter_aopef
do_container_from_symbol_this_t.sh elementary_border_parameter_ecppef
do_container_from_symbol_this_t.sh elementary_border_parameter
do_container_from_symbol_this_t.sh elementary_body_parameter_tuple

do_container_from_symbol_this_t.sh elementary_body
do_container_from_symbol_this_t.sh elementary_border
do_container_from_symbol_this_t.sh elementary_fence
do_container_from_symbol_this_t.sh elementary_context
do_container_from_symbol_this_t.sh elementary_context_databox

do_container_from_symbol_this_t.sh elementary

echo " "
echo " mv Elementary_*.ml ../"
echo " "

exit

