(** {3 Db1pointsdata_set_fence_token_coordinates_kind_symbol_t} *)


(** {6 Typing_for_symbol} *)

type db1pointsdata_set_fence_token_coordinates_kind_symbol =
  | Db1pointsdata_set_fence_token_coordinates_kind_cartesian_symbol of Db1pointsdata_set_fence_token_coordinates_kind_cartesian_symbol_t.db1pointsdata_set_fence_token_coordinates_kind_cartesian_symbol
  | Db1pointsdata_set_fence_token_coordinates_kind_cylindrical_symbol of Db1pointsdata_set_fence_token_coordinates_kind_cylindrical_symbol_t.db1pointsdata_set_fence_token_coordinates_kind_cylindrical_symbol
  | Db1pointsdata_set_fence_token_coordinates_kind_linear_symbol of Db1pointsdata_set_fence_token_coordinates_kind_linear_symbol_t.db1pointsdata_set_fence_token_coordinates_kind_linear_symbol
  | Db1pointsdata_set_fence_token_coordinates_kind_planar_symbol of Db1pointsdata_set_fence_token_coordinates_kind_planar_symbol_t.db1pointsdata_set_fence_token_coordinates_kind_planar_symbol
  | Db1pointsdata_set_fence_token_coordinates_kind_polar_symbol of Db1pointsdata_set_fence_token_coordinates_kind_polar_symbol_t.db1pointsdata_set_fence_token_coordinates_kind_polar_symbol
  | Db1pointsdata_set_fence_token_coordinates_kind_spherical_symbol of Db1pointsdata_set_fence_token_coordinates_kind_spherical_symbol_t.db1pointsdata_set_fence_token_coordinates_kind_spherical_symbol
;;


(** Db1pointsdata_set_fence_token_coordinates_kind_symbol_t at 12:44:34 on 4 Jun 2017. created by version v2.4 of generator *)



