(** {3 Db1pointsdata_set_fence_token_coordinates_units_angle_symbol_t} *)


(** {6 Typing_for_symbol} *)

type db1pointsdata_set_fence_token_coordinates_units_angle_symbol =
  | Db1pointsdata_set_fence_token_coordinates_units_angle_degree_symbol of Db1pointsdata_set_fence_token_coordinates_units_angle_degree_symbol_t.db1pointsdata_set_fence_token_coordinates_units_angle_degree_symbol
  | Db1pointsdata_set_fence_token_coordinates_units_angle_noangle_symbol of Db1pointsdata_set_fence_token_coordinates_units_angle_noangle_symbol_t.db1pointsdata_set_fence_token_coordinates_units_angle_noangle_symbol
  | Db1pointsdata_set_fence_token_coordinates_units_angle_radian_symbol of Db1pointsdata_set_fence_token_coordinates_units_angle_radian_symbol_t.db1pointsdata_set_fence_token_coordinates_units_angle_radian_symbol
;;


(** Db1pointsdata_set_fence_token_coordinates_units_angle_symbol_t at 12:44:50 on 4 Jun 2017. created by version v2.4 of generator *)



