DB1POINTSDATA_T_MLI :=  \
       Db1pointsdata_set_fence_token_figure_kind_point_symbol_t.mli \
       Db1pointsdata_set_fence_token_figure_kind_triangle_symbol_t.mli \
       Db1pointsdata_set_fence_token_figure_kind_segment_symbol_t.mli \
      Db1pointsdata_set_fence_token_figure_kind_symbol_t.mli \
     Db1pointsdata_set_fence_token_figure_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_kind_spherical_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_kind_polar_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_kind_planar_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_kind_linear_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_kind_cylindrical_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_kind_cartesian_symbol_t.mli \
      Db1pointsdata_set_fence_token_coordinates_kind_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_length_nanometer_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_length_meter_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_length_bohr_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_length_angstrom_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_units_length_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_angle_radian_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_angle_noangle_symbol_t.mli \
        Db1pointsdata_set_fence_token_coordinates_units_angle_degree_symbol_t.mli \
       Db1pointsdata_set_fence_token_coordinates_units_angle_symbol_t.mli \
      Db1pointsdata_set_fence_token_coordinates_units_symbol_t.mli \
     Db1pointsdata_set_fence_token_coordinates_symbol_t.mli \
    Db1pointsdata_set_fence_token_symbol_t.mli \
     Db1pointsdata_set_fence_keyword_vertex_symbol_t.mli \
     Db1pointsdata_set_fence_keyword_figure_symbol_t.mli \
      Db1pointsdata_set_fence_keyword_coordinates_kind_symbol_t.mli \
       Db1pointsdata_set_fence_keyword_coordinates_units_length_symbol_t.mli \
       Db1pointsdata_set_fence_keyword_coordinates_units_angle_symbol_t.mli \
      Db1pointsdata_set_fence_keyword_coordinates_units_symbol_t.mli \
     Db1pointsdata_set_fence_keyword_coordinates_symbol_t.mli \
    Db1pointsdata_set_fence_keyword_symbol_t.mli \
      Db1pointsdata_set_fence_cell_figure_name_symbol_t.mli \
      Db1pointsdata_set_fence_cell_figure_kind_symbol_t.mli \
     Db1pointsdata_set_fence_cell_figure_symbol_t.mli \
       Db1pointsdata_set_fence_cell_coordinates_units_length_symbol_t.mli \
       Db1pointsdata_set_fence_cell_coordinates_units_angle_symbol_t.mli \
      Db1pointsdata_set_fence_cell_coordinates_units_symbol_t.mli \
      Db1pointsdata_set_fence_cell_coordinates_kind_symbol_t.mli \
     Db1pointsdata_set_fence_cell_coordinates_symbol_t.mli \
    Db1pointsdata_set_fence_cell_symbol_t.mli \
      Db1pointsdata_set_fence_basic_word_uppercase_symbol_t.mli \
      Db1pointsdata_set_fence_basic_word_lowercase_symbol_t.mli \
      Db1pointsdata_set_fence_basic_word_capitalized_symbol_t.mli \
      Db1pointsdata_set_fence_basic_word_anycase_symbol_t.mli \
     Db1pointsdata_set_fence_basic_word_symbol_t.mli \
      Db1pointsdata_set_fence_basic_numerical_integer_symbol_t.mli \
      Db1pointsdata_set_fence_basic_numerical_float_symbol_t.mli \
     Db1pointsdata_set_fence_basic_numerical_symbol_t.mli \
    Db1pointsdata_set_fence_basic_symbol_t.mli \
   Db1pointsdata_set_fence_symbol_t.mli \
     Db1pointsdata_set_body_name_vertex_symbol_t.mli \
    Db1pointsdata_set_body_name_symbol_t.mli \
     Db1pointsdata_set_body_sequence_float_symbol_t.mli \
    Db1pointsdata_set_body_sequence_symbol_t.mli \
     Db1pointsdata_set_body_record_vertex_symbol_t.mli \
    Db1pointsdata_set_body_record_symbol_t.mli \
     Db1pointsdata_set_body_cluster_vertex_symbol_t.mli \
     Db1pointsdata_set_body_cluster_information_symbol_t.mli \
    Db1pointsdata_set_body_cluster_symbol_t.mli \
     Db1pointsdata_set_body_bundle_figure_symbol_t.mli \
     Db1pointsdata_set_body_bundle_coordinates_symbol_t.mli \
    Db1pointsdata_set_body_bundle_symbol_t.mli \
   Db1pointsdata_set_body_symbol_t.mli \
  Db1pointsdata_set_symbol_t.mli \
   Db1pointsdata_context_sector_symbol_t.mli \
   Db1pointsdata_context_domain_symbol_t.mli \
   Db1pointsdata_context_database_symbol_t.mli \
   Db1pointsdata_context_databox_symbol_t.mli \
  Db1pointsdata_context_symbol_t.mli \
 Db1pointsdata_symbol_t.mli \
