include files_db1pointsdata_symbols_mli.mk

SYMBOLS_DB1POINTSDATA_V_MLI := $(subst symbol_t,symbol_v,$(DB1POINTSDATA_T_MLI))
SYMBOLS_DB1POINTSDATA_TV_MLI := $(SYMBOLS_DB1POINTSDATA_T_MLI) $(SYMBOLS_DB1POINTSDATA_V_MLI) 

FILES_MLI := \
$(SYMBOLS_DB1POINTSDATA_TV_MLI) \
