<<<<<<< HEAD
ocamlc -warn-error A -g -I /keep/sources/ocaml_top/setup/frames/general/basics -I /keep/sources/ocaml_top/setup/frames/general/datastructures -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_symbols -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_tags -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_formulas -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_interfaces -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_databases/adb -I /keep/sources/ocaml_top/setup/frames/general/files -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_values -c Do_musicset_symbols_tv.ml

ocamlc -warn-error A -g -I /keep/sources/ocaml_top/setup/frames/general/basics -I /keep/sources/ocaml_top/setup/frames/general/datastructures -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_symbols -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_tags -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_formulas -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_interfaces -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_databases/adb -I /keep/sources/ocaml_top/setup/frames/general/files -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_values -o musicset_generate_symbols_tv.byt unix.cma -cclib -lunix str.cma -cclib -lstr  /keep/sources/ocaml_top/setup/frames/general/basics/basics.cma   /keep/sources/ocaml_top/setup/frames/general/datastructures/datastructures.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_symbols/generatorset_symbols.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_tags/generatorset_tags.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_formulas/generatorset_formulas.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_databases/adb/adb.cma   /keep/sources/ocaml_top/setup/frames/general/files/files.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_values/generatorset_values.cma  Do_musicset_symbols_tv.cmo; 
=======
ocamlc -warn-error A -g -I /keep/sources/ocaml_top/setup/frames/general/basics -I /keep/sources/ocaml_top/setup/frames/general/datastructures -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_symbols -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_tags -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_formulas -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_interfaces -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_databases/adb -I /keep/sources/ocaml_top/setup/frames/general/files -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_values -c do_musicset_symbols_tv.ml

ocamlc -warn-error A -g -I /keep/sources/ocaml_top/setup/frames/general/basics -I /keep/sources/ocaml_top/setup/frames/general/datastructures -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_symbols -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_tags -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_formulas -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_interfaces -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_databases/adb -I /keep/sources/ocaml_top/setup/frames/general/files -I /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_values -o musicset_generate_symbols_tv.byt unix.cma -cclib -lunix str.cma -cclib -lstr  /keep/sources/ocaml_top/setup/frames/general/basics/basics.cma   /keep/sources/ocaml_top/setup/frames/general/datastructures/datastructures.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_symbols/generatorset_symbols.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_tags/generatorset_tags.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_formulas/generatorset_formulas.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_databases/adb/adb.cma   /keep/sources/ocaml_top/setup/frames/general/files/files.cma   /keep/sources/ocaml_top/setup/frames/generatorset/generatorset_values/generatorset_values.cma  do_musicset_symbols_tv.cmo; 
>>>>>>> b2df08b6d54ba28365f4847d83c509aac1a48ea9
