#!/bin/bash

cp $BPRO/Property_context_inputbox_sole_index_by_any_sole_index_provider_v.ml .
cp $BPRO/Property_context_inputbox_name_by_any_sole_index_provider_v.ml .
cp $BPRO/Property_context_inputbox_symbol_by_any_sole_index_provider_v.ml .
cp $BPRO/Property_context_inputbox_tag_by_any_sole_index_provider_v.ml .

modify_strings_and_rename_files.sh  inputbox  databox Property*ml
modify_strings_and_rename_files.sh  property  parameter Property*ml
modify_string.pl _ibo _dbo Property*ml
modify_string.pl BPRO BPAR Property*ml
modify_strings_and_rename_files.sh  Property  Parameter Property*ml

msrf  Parameter_context_databox_name_by_any_sole_index_provider  Databox_name_by_any_sole_index_provider  Parameter_context_databox_name_by_any_sole_index_provider_v.ml *mk

cp $BCOO/Coordinate_father_tag_by_coordinate_son_tag_provider_v.ml Parameter_father_tag_by_parameter_son_tag_provider_v.ml
cp $BCOO/Coordinate_father_tag_by_coordinate_son_tag_register_v.ml Parameter_father_tag_by_parameter_son_tag_register_v.ml

ms coordinate parameter *ml
ms Coordinate Parameter *ml

ms COO PAR *ml

------------------------------

msrf by_databox_name                              by_basicname_databox *ml *mk

msrf "basicname_databox_provider_v.provide nam_" "basicname_databox_provider_v.provide bna_" *ml *mk
 
ms "(nam_pbo, nam_pba, nam_dom, nam_sec)" "(bna_dbo, bna_dba, bna_dom, bna_sec)" *ml
ms "(nam_dba, nam_dom, nam_sec)" "(bna_dba, bna_dom, bna_sec)" *ml
ms "(nam_dbo, nam_dba)" "(bna_dbo, bna_dba)"  *ml
ms "(nam_pbo, nam_pba)" "(bna_dbo, bna_dba)"  *ml
ms "(nam_dom, nam_sec)" "(bna_dom, bna_sec)"  *ml

mw nam_pba  nam_dba *ml
mw bna_pba  bna_dba *ml
mw soi_pba  soi_dba *ml
mw nam_pbo  nam_dbo *ml
mw bna_pbo  bna_dbo *ml
mw soi_pbo  soi_dbo *ml

mw nam_ecs nam_sec *ml
mw ord_ecs ord_sec *ml
mw soi_ecs soi_sec *ml
mw tag_ecs tag_sec *ml


mw ord_ecd ord_dom *ml
mw tag_ecd tag_dom *ml
mw nam_ecd nam_dom *ml

mw sym_ncs  sym_pcs *ml
ms sym_nwc  sym_par *ml
mw sym_ecd  sym_pcd *ml
mw sym_par_ecd  sym_par_pcd *ml
mw tag_par_ecd  tag_par_pcd *ml
mw tag_par_ecs  tag_par_pcs *ml

ms _ele_ _par_ *ml

ms "let nam_sec = Parameter_context_sector_name_by_unit_provider_v.provide ()"  "let bna_sec = Parameter_context_sector_name_by_unit_provider_v.provide ()" *ml

ms "let nam_dom = Parameter_context_domain_name_by_unit_provider_v.provide ()"  "let bna_dom = Parameter_context_domain_name_by_unit_provider_v.provide ()" *ml

ms "let nam_dom = Parameter_basicname_domain_by_unit_provider_v" "let bna_dom = Parameter_basicname_domain_by_unit_provider_v" *ml 

ms "let build nam_" "let build bna_" *ml

ms "let build bna_nbo =" "let build bna_dbo =" *ml

ms "provide nam_" "provide bna_" *ml

ms "by_basicname_sector_provider_v.provide nam_sec" "by_basicname_sector_provider_v.provide bna_sec" *ml
ms "by_basicname_domain_provider_v.provide nam_dom" "by_basicname_domain_provider_v.provide bna_dom" *ml
ms "by_basicname_database_provider_v.provide nam_dba" "by_basicname_database_provider_v.provide bna_dba" *ml
ms "by_basicname_databox_provider_v.provide nam_dbo" "by_basicname_databox_provider_v.provide bna_dbo" *ml

ms "let nam_dba = Parameter_basicname_database_" "let bna_dba = Parameter_basicname_database_" *ml
ms "let nam_dbo = Parameter_basicname_databox_" "let bna_dbo = Parameter_basicname_databox_" *ml

ms "string Duo_t.duo" "Basicname_t.basicname Duo_t.duo" *ml 
ms "Duo_v.name (fun s->s)" "Duo_v.name Basicname_v.name" *ml 
ms "(fun s->s)" "Basicname_v.name" *ml 


ms Domain_name_n_sector_name_by_fullnameofdirectory_provider_v Basicname_duo_by_fullnameofdirectory_provider_v *ml
mscf sector_name basicname_sector  Context_sole_index_by_sector_name_provider_v.ml
msrf Basicname_database_name       Basicname_database *ml *mk
msrf Basicname_databox_name_by     Basicname_databox_by *ml *mk

msrf Database_name_by             Basicname_database_name_by *ml *mk
msrf Databox_name_by              Basicname_databox_name_by *ml *mk
msrf Databox_name_n_database_name Basicname_databox_n_basicname_database *ml *mk
msrf Databox_name_n_database_name_by Basicname_databox_n_basicname_database_by *ml *mk

msrf _context_sector_name_   _context_basicname_sector_ *ml *mk
msrf _context_domain_name_   _context_basicname_domain_ *ml *mk
msrf _context_database_name_ _context_basicname_database_ *ml *mk
msrf _context_databox_name_  _context_basicname_databox_ *ml *mk
msrf _context_name_trio_     _basicname_trio_ *ml *mk
msrf _context_name_quatuor_  _basicname_quatuor_ *ml *mk

msrf Parameter_context_basicname_ Parameter_basicname_ *ml *mk
msrf Context_name_trio_by_fullnameofdirectory  Basicname_trio_by_fullnameofdirectory *ml *mk

ms "let nam_sec = Parameter_basicname_sector_by_unit_provider_v.provide" "let bna_sec = Parameter_basicname_sector_by_unit_provider_v.provide" *ml

ms "by_basicname_sector_provider_v.provide nam_sec" "by_basicname_sector_provider_v.provide bna_sec" *ml

msrf by_parameter_context_name       by_parameter_basicname  *ml *mk
msrf by_parameter_context_name       by_parameter_basicname *ml *mk
msrf by_database_name                 by_basicname_database  *ml *mk
msrf by_databox_name                  by_basicname_databox  *ml *mk
msrf by_databox_name_n_database_name  by_basicname_databox_n_basicname_database  *ml *mk
msrf by_domain_name_n_sector_name     by_basicname_domain_n_basicname_sector  *ml *mk
msrf by_domain_name_provider     by_basicname_domain_provider  *ml *mk
msrf by_sector_name_                  by_basicname_sector_ *ml *mk
msrf   by_basicname_databox_n_database_name_   by_basicname_databox_n_basicname_database_  *ml *mk

msrf _context_basicname_domain _basicname_domain *ml *mk
msrf _context_database_name_by _basicname_database_by *ml *mk
msrf _context_databox_name_by_ _basicname_databox_by_ *ml *mk 
msrf _context_domain_name      _basicname_domain *ml *mk
msrf _context_name_quatuor     _basicname_quatuor *ml *mk
msrf _context_name_quatuor     _basicname_quatuor *ml *mk
msrf _context_sector_name      _basicname_sector *ml *mk
msrf _context_sector_name_by   _basicname_by *ml *mk

msrf _context_name_ _basicname_ *ml *mk
ms Parameter_basicname_databox_by_any_sole_index_provider_v Basicname_databox_by_any_sole_index_provider_v *ml
dlw Parameter_basicname_databox_by_any_sole_index_provider_v *mk
kef Parameter_basicname_databox_by_any_sole_index_provider_v.ml

ms Check_consistency_by_parameter_basicname_quatuor_provider_v Check_consistency_by_basicname_quatuor_provider_v *ml
dlw  Check_consistency_by_parameter_basicname_quatuor_provider_v  *mk
kef  Check_consistency_by_parameter_basicname_quatuor_provider_v.ml

ms Parameter_parser_v.parameter_symbol_tree_root_databox_of_databox_name  Parameter_parser_v.parameter_symbol_tree_root_databox_of_basicname_databox *ml


msrf Parameter_symbol_subtree_by_nwchemdata_context_basicname_databox_provider_v Parameter_symbol_subtree_by_nwchemdata_context_databox_tag_provider_v *ml *mk
