INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(QUANTUM_DIR) \
	$(CONTEXTSET_DIR) \
	$(NWCHEMDATASET_LEXER_DIR) \
	$(NWCHEMDATASET_SYMBOLS_DIR) \
	$(NWCHEMDATASET_PARSER_DIR) \
	$(NWCHEMDATASET_TAGS_DIR) \
	$(NWCHEMDATASET_BUILDER_TREES_DIR) \
	$(SKELETONSET_SYMBOLS_DIR) \
	$(SKELETONSET_TAGS_DIR) \
	$(SKELETONSET_BUILDER_TREES_DIR) \
 