REGISTERS_V_MLI := \
Localinput_lexer_symbol_list_by_basicname_inputbox_register_v.mli \
 
LEXICAL_ANALYSIS_V_MLI := \
Localinput_lexer_lexical_analysis_tools_first_pass_v.mli \
Localinput_lexer_lexical_analysis_tools_second_pass_v.mli \
Localinput_lexer_scanbuf_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_symbol_list_first_pass_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_symbol_list_second_pass_by_basicname_inputbox_provider_v.mli \
 \
Localinput_lexer_symbol_list_by_basicname_inputbox_provider_v.mli \
 
EXTRACTIONS_V_MLI := \
Localinput_lexer_as_command_symbol_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_handle_command_list_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_handle_command_by_basicname_inputbox_n_localinput_lexer_command_symbol_provider_v.mli \
Localinput_lexer_handle_command_define_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_handle_command_print_list_by_basicname_inputbox_provider_v.mli \
 \
Localinput_lexer_as_variable_kind_symbol_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_variable_kind_symbol_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_as_basic_word_capitalized_symbol_n_localinput_lexer_as_variable_kind_symbol_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_basic_word_capitalized_symbol_n_localinput_lexer_variable_kind_symbol_list_by_basicname_inputbox_provider_v.mli \
 \
Variable_name_list_by_basicname_inputbox_provider_v.mli \
Basicname_variable_list_by_basicname_inputbox_provider_v.mli \
Localinput_lexer_handle_command_define_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
Localinput_lexer_handle_command_print_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
Localinput_lexer_as_variable_kind_symbol_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
Localinput_lexer_variable_kind_symbol_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
# Localinput_lexer_handle_variable_kind_list_by_localinput_lexer_handle_command_define_provider_v.mli \
# Localinput_lexer_block_variable_list_by_localinput_lexer_handle_variable_kind_provider_v.mli \
# Localinput_lexer_cell_list_by_localinput_lexer_block_variable_provider_v.mli \
# Variable_name_n_localinput_lexer_as_variable_kind_symbol_list_by_basicname_inputbox_provider_v.mli \
# Variable_name_n_localinput_lexer_variable_kind_symbol_list_by_basicname_inputbox_provider_v.mli \
 
FILES_MLI := \
$(REGISTERS_V_MLI) \
$(LEXICAL_ANALYSIS_V_MLI) \
$(EXTRACTIONS_V_MLI) \
 