INCLUDED_DIRS := \
        $(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(NATURALSET_DATABASES_DIR) \
	$(NATURALSET_SYMBOLS_DIR) \
	$(NATURALSET_TAGS_DIR) \
	$(NATURALSET_INTERFACES_DIR) \
	$(NATURALSET_CONTAINERS_DIR) \
  