FROM_FILES_V_ML := \
Coordinate_cartesian_envelope_by_coordinate_tag_provider_u_any.ml \
Coordinate_cartesian_measure_tuple_by_coordinate_set_body_tuple_tag_provider_u_any.ml \
Coordinate_envelopee_u_any.ml \
Coordinate_envelope_u_any.ml \
Coordinate_set_body_coordinate_tuple_conversions_u_any.ml \
Coordinate_set_body_coordinate_tuple_measure_conversions_u_any.ml \
Coordinate_set_body_tuple_conversions_u_any.ml \
Coordinate_set_body_tuple_homogeneous_measure_canonical_by_coordinate_set_body_tuple_tag_provider_u_any.ml \
Coordinate_set_body_tuple_measure_actual_conversions_u_any.ml \

FROM_FILES_U_ML := \
Coordinate_envelope_u_point_a_rho.ml \
Coordinate_envelope_u_point_a_tuple.ml \
Coordinate_envelope_u_segment_bc.ml \
Coordinate_set_body_tuple_measure_actual_conversions_u_segment_bc.ml \
Coordinate_set_fence_heterogeneous_spherical_rho_envelope_u_point_a.ml \
Coordinate_set_fence_heterogeneous_spherical_rho_envelope_u_segment_s.ml \
Elementary_body_coordinate_tuple_heterogeneous_envelope_u_point_a.ml \
Elementary_body_coordinate_tuple_heterogeneous_envelope_u_segment_s.ml \
Elementary_border_coordinate_heterogeneous_envelope_u_segment_s.ml \
Elementary_border_coordinate_heterogeneous_spherical_phi_envelope_u_point_a.ml \
Elementary_border_coordinate_heterogeneous_spherical_phi_envelope_u_segment_s.ml \
Elementary_coordinate_tuple_heterogeneous_envelope_u_point_a.ml \

UNITARY_TESTS_FILES_ML := \
Coordinate_envelope_u_point_a_rho.ml \
 
