INCLUDED_DIRS := \
        $(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(GENERATORSET_SYMBOLS_DIR) \
	$(GENERATORSET_TAGS_DIR) \
	$(GENERATORSET_DATABASES_ADB_DIR) \
	$(GENERATORSET_INTERFACES_DIR) \
	$(realpath ..) \
 


