MOLECULESET_SYMBOL_ML := \
Category_formula_u_moleculeset.ml \
Entity_proper_formula_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Contentfile_formula_u_moleculeset_symbol_moleculeset.ml \
Item_formula_u_moleculeset_symbol_moleculeset.ml \
Item_formula_u_moleculeset_symbol_moleculeset_typing.ml \
Item_formula_u_moleculeset_symbol_molecule_linear_diatomic_value_alone.ml \
Item_formula_u_moleculeset_symbol_molecule_linear_diatomic_abbreviating.ml \
Item_formula_u_moleculeset_symbol_molecule_linear_diatomic_extracting.ml \
Item_formula_u_moleculeset_symbol_molecule_linear_diatomic_making.ml \
Item_formula_u_moleculeset_symbol_molecule_linear_diatomic_naming.ml \
Item_formula_u_moleculeset_symbol_molecule_linear_diatomic_typing.ml \
Camlparagraph_formula_u_moleculeset_symbol_molecule.ml \
Camlparagraph_formula_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Camlline_formula_u_moleculeset_symbol_moleculeset.ml \

MOLECULESET_FORMULA_ML := \
Entity_proper_formula_u_moleculeset_formula_molecule_linear_diatomic.ml \
Contentfile_formula_u_moleculeset_formula_moleculeset.ml \
Item_formula_u_moleculeset_formula_moleculeset_typing.ml \
Item_formula_u_moleculeset_formula_molecule_linear_diatomic.ml \
Camlparagraph_formula_u_moleculeset_formula_molecule_typing.ml \
Camlparagraph_formula_u_moleculeset_formula_molecule_linear_diatomic.ml \
Camlline_formula_u_moleculeset_formula_molecule_linear_diatomic_typing.ml \
Camlline_formula_u_moleculeset_formula_molecule_linear_diatomic_making.ml \
Camlline_formula_u_moleculeset_formula_molecule_linear_diatomic_naming.ml \
Camlline_formula_u_moleculeset_formula_molecule_linear_diatomic_extracting.ml \

FILES_INACTIVE := \

UNITARY_TESTS_FILES_MOLECULESET_ML := \
$(MOLECULESET_FORMULA_ML) \
# $(MOLECULESET_SYMBOL_ML) \
