CAMLLINE_T_MLI := \
   Camlline_for_tag_trio_symbol_t.mli \
    Camlline_for_tag_duo_current_top_symbol_t.mli \
   Camlline_for_tag_duo_symbol_t.mli \
    Camlline_for_tag_uno_top_symbol_t.mli \
    Camlline_for_tag_uno_camltype_symbol_t.mli \
   Camlline_for_tag_uno_symbol_t.mli \
      Camlline_for_tag_datastructure_function_make_trio_symbol_t.mli \
      Camlline_for_tag_datastructure_function_make_duo_symbol_t.mli \
      Camlline_for_tag_datastructure_function_make_uno_symbol_t.mli \
     Camlline_for_tag_datastructure_function_make_symbol_t.mli \
     Camlline_for_tag_datastructure_function_iter_symbol_t.mli \
    Camlline_for_tag_datastructure_function_symbol_t.mli \
     Camlline_for_tag_datastructure_camltype_duo_symbol_t.mli \
     Camlline_for_tag_datastructure_camltype_uno_symbol_t.mli \
    Camlline_for_tag_datastructure_camltype_symbol_t.mli \
   Camlline_for_tag_datastructure_symbol_t.mli \
  Camlline_for_tag_symbol_t.mli \
    Camlline_for_symbol_uno_current_symbol_t.mli \
     Camlline_for_symbol_uno_son_notleaf_symbol_t.mli \
     Camlline_for_symbol_uno_son_ofstring_symbol_t.mli \
     Camlline_for_symbol_uno_son_bare_symbol_t.mli \
    Camlline_for_symbol_uno_son_symbol_t.mli \
    Camlline_for_symbol_uno_top_symbol_t.mli \
    Camlline_for_symbol_uno_builder_symbol_t.mli \
   Camlline_for_symbol_uno_symbol_t.mli \
     Camlline_for_symbol_duo_son_top_ofstring_symbol_t.mli \
     Camlline_for_symbol_duo_son_top_notleaf_symbol_t.mli \
     Camlline_for_symbol_duo_son_top_bare_symbol_t.mli \
    Camlline_for_symbol_duo_son_top_symbol_t.mli \
    Camlline_for_symbol_duo_current_top_symbol_t.mli \
   Camlline_for_symbol_duo_symbol_t.mli \
  Camlline_for_symbol_symbol_t.mli \
    Camlline_for_formula_uno_top_symbol_t.mli \
    Camlline_for_formula_uno_son_symbol_t.mli \
    Camlline_for_formula_uno_data_symbol_t.mli \
    Camlline_for_formula_uno_main_symbol_t.mli \
    Camlline_for_formula_uno_builder_symbol_t.mli \
   Camlline_for_formula_uno_symbol_t.mli \
    Camlline_for_formula_trio_top_main_builder_symbol_t.mli \
    Camlline_for_formula_trio_top_builder_data_symbol_t.mli \
    Camlline_for_formula_trio_son_top_data_symbol_t.mli \
    Camlline_for_formula_trio_son_top_builder_symbol_t.mli \
   Camlline_for_formula_trio_symbol_t.mli \
    Camlline_for_formula_duo_top_main_symbol_t.mli \
    Camlline_for_formula_duo_top_data_symbol_t.mli \
    Camlline_for_formula_duo_top_builder_symbol_t.mli \
    Camlline_for_formula_duo_son_top_symbol_t.mli \
    Camlline_for_formula_duo_son_main_symbol_t.mli \
    Camlline_for_formula_duo_son_data_symbol_t.mli \
    Camlline_for_formula_duo_son_builder_symbol_t.mli \
    Camlline_for_formula_duo_main_data_symbol_t.mli \
    Camlline_for_formula_duo_main_builder_symbol_t.mli \
    Camlline_for_formula_duo_localset_builder_symbol_t.mli \
    Camlline_for_formula_duo_localset_data_symbol_t.mli \
    Camlline_for_formula_duo_builder_data_symbol_t.mli \
   Camlline_for_formula_duo_symbol_t.mli \
    Camlline_for_formula_datastructure_trio_symbol_t.mli \
    Camlline_for_formula_datastructure_duo_symbol_t.mli \
    Camlline_for_formula_datastructure_uno_symbol_t.mli \
   Camlline_for_formula_datastructure_symbol_t.mli \
  Camlline_for_formula_symbol_t.mli \
    Camlline_for_any_trio_current_son_top_symbol_t.mli \
   Camlline_for_any_trio_symbol_t.mli \
    Camlline_for_any_uno_top_symbol_t.mli \
    Camlline_for_any_uno_son_symbol_t.mli \
     Camlline_for_any_uno_camltype_top_symbol_t.mli \
     Camlline_for_any_uno_camltype_son_ofstring_symbol_t.mli \
     Camlline_for_any_uno_camltype_son_notleaf_symbol_t.mli \
     Camlline_for_any_uno_camltype_son_bare_symbol_t.mli \
    Camlline_for_any_uno_camltype_symbol_t.mli \
    Camlline_for_any_uno_camlfile_symbol_t.mli \
   Camlline_for_any_uno_symbol_t.mli \
    Camlline_for_any_duo_top_main_symbol_t.mli \
    Camlline_for_any_duo_son_top_notleaf_symbol_t.mli \
    Camlline_for_any_duo_son_top_ofstring_symbol_t.mli \
    Camlline_for_any_duo_son_top_bare_symbol_t.mli \
    Camlline_for_any_duo_datastructure_symbol_t.mli \
    Camlline_for_any_duo_current_top_symbol_t.mli \
    Camlline_for_any_duo_current_son_symbol_t.mli \
   Camlline_for_any_duo_symbol_t.mli \
  Camlline_for_any_symbol_t.mli \
   Camlline_constant_pervasive_symbol_t.mli \
   Camlline_constant_function_symbol_t.mli \
  Camlline_constant_symbol_t.mli \
 Camlline_symbol_t.mli \

