GROUP_T_MLI := \
    Group_for_symbol_footer_top_symbol_t.mli \
   Group_for_symbol_footer_symbol_t.mli \
    Group_for_symbol_body_current_son_top_symbol_t.mli \
    Group_for_symbol_body_son_top_symbol_t.mli \
    Group_for_symbol_body_son_symbol_t.mli \
    Group_for_symbol_body_top_symbol_t.mli \
   Group_for_symbol_body_symbol_t.mli \
    Group_for_symbol_header_son_top_symbol_t.mli \
    Group_for_symbol_header_son_symbol_t.mli \
    Group_for_symbol_header_current_top_symbol_t.mli \
    Group_for_symbol_header_current_son_top_symbol_t.mli \
    Group_for_symbol_header_constant_symbol_t.mli \
   Group_for_symbol_header_symbol_t.mli \
  Group_for_symbol_symbol_t.mli \
    Group_for_formula_header_top_main_symbol_t.mli \
    Group_for_formula_header_top_data_symbol_t.mli \
    Group_for_formula_header_top_builder_symbol_t.mli \
    Group_for_formula_header_constant_symbol_t.mli \
   Group_for_formula_header_symbol_t.mli \
     Group_for_formula_body_top_main_symbol_t.mli \
     Group_for_formula_body_top_data_symbol_t.mli \
     Group_for_formula_body_top_builder_data_symbol_t.mli \
     Group_for_formula_body_top_builder_symbol_t.mli \
     Group_for_formula_body_top_alone_symbol_t.mli \
    Group_for_formula_body_top_symbol_t.mli \
     Group_for_formula_body_son_top_main_builder_symbol_t.mli \
     Group_for_formula_body_son_top_main_symbol_t.mli \
     Group_for_formula_body_son_top_data_symbol_t.mli \
     Group_for_formula_body_son_top_builder_symbol_t.mli \
     Group_for_formula_body_son_top_symbol_t.mli \
     Group_for_formula_body_son_builder_symbol_t.mli \
    Group_for_formula_body_son_symbol_t.mli \
    Group_for_formula_body_main_data_symbol_t.mli \
    Group_for_formula_body_main_builder_symbol_t.mli \
    Group_for_formula_body_localset_builder_symbol_t.mli \
    Group_for_formula_body_localset_data_symbol_t.mli \
    Group_for_formula_body_data_alone_symbol_t.mli \
    Group_for_formula_body_builder_data_symbol_t.mli \
    Group_for_formula_body_builder_alone_symbol_t.mli \
   Group_for_formula_body_symbol_t.mli \
  Group_for_formula_symbol_t.mli \
   Group_for_any_footer_symbol_t.mli \
    Group_for_any_body_top_main_symbol_t.mli \
    Group_for_any_body_top_symbol_t.mli \
    Group_for_any_body_son_symbol_t.mli \
   Group_for_any_body_symbol_t.mli \
    Group_for_any_header_top_symbol_t.mli \
    Group_for_any_header_constant_symbol_t.mli \
   Group_for_any_header_symbol_t.mli \
  Group_for_any_symbol_t.mli \
 Group_symbol_t.mli \

