(** {3 Item_for_symbol_symbol_t} *)


(** {6 Typing_for_symbol} *)

type item_for_symbol_symbol =
  | Item_for_symbol_each_grandson_bare_symbol of Item_for_symbol_each_grandson_bare_symbol_t.item_for_symbol_each_grandson_bare_symbol
  | Item_for_symbol_each_grandson_notleaf_symbol of Item_for_symbol_each_grandson_notleaf_symbol_t.item_for_symbol_each_grandson_notleaf_symbol
  | Item_for_symbol_each_grandson_ofstring_symbol of Item_for_symbol_each_grandson_ofstring_symbol_t.item_for_symbol_each_grandson_ofstring_symbol
  | Item_for_symbol_each_topson_bare_symbol of Item_for_symbol_each_topson_bare_symbol_t.item_for_symbol_each_topson_bare_symbol
  | Item_for_symbol_each_topson_notleaf_symbol of Item_for_symbol_each_topson_notleaf_symbol_t.item_for_symbol_each_topson_notleaf_symbol
  | Item_for_symbol_each_topson_ofstring_symbol of Item_for_symbol_each_topson_ofstring_symbol_t.item_for_symbol_each_topson_ofstring_symbol
  | Item_for_symbol_only_top_symbol of Item_for_symbol_only_top_symbol_t.item_for_symbol_only_top_symbol
  | Item_for_symbol_by_group_topsons_symbol of Item_for_symbol_by_group_topsons_symbol_t.item_for_symbol_by_group_topsons_symbol
;;


(** Item_for_symbol_symbol_t at 14:14:19 on 2 Jun 2013. created by version v1.13 of generator *)



