 modify_string.pl define_block               	 block_define                $1
 modify_string.pl operator_cofactor_block    	 block_operator_cofactor     $1
 modify_string.pl print_block                	 block_print                 $1
 modify_string.pl read_block                 	 block_read                  $1
 modify_string.pl set_alternative_block      	 block_set_alternative       $1
 modify_string.pl set_block                  	 block_set                   $1
 modify_string.pl title_block                	 block_title                 $1
 modify_string.pl variable_context_block     	 block_variable_context      $1
 modify_string.pl variable_external_block    	 block_variable_external     $1
 modify_string.pl variable_operator_block    	 block_variable_operator     $1
 modify_string.pl variable_target_block      	 block_variable_target       $1
 modify_string.pl write_block                	 block_write                 $1
