INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(UNITS_DIR) \
	$(FUNCTIONS_DIR) \
	$(INTEGRALS_DIR) \
	$(LINEARALGEBRA_DIR) \
	$(POLYNOMIALS_DIR) \
	$(QUANTUM_DIR) \
	$(GENERATOR_DIR) \
	$(realpath ..) \
 

