NEEDED_DIRS := \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(MISCELLANEOUS_DIR) \
	$(FUNCTIONS_DIR) \
	$(INTEGRALS_DIR) \
	$(POLYNOMIALS_DIR) \
	$(QUANTUM_DIR) \
	$(UNITS_DIR) \
	$(GENERATOR_DIR) \
 


