(** {3 Elementary_container_t} *)


(** {6 Typing_for_container} *)

type elementary_container =
  | Elementary_body_container of Elementary_body_container_t.elementary_body_container
  | Elementary_context_container of Elementary_context_container_t.elementary_context_container
  | Elementary_border_container of Elementary_border_container_t.elementary_border_container
  | Elementary_fence_container of Elementary_fence_container_t.elementary_fence_container
;;


(** Elementary_container_t at 11:52:31 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_symbol_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:47 (UTC+0200) *)
