(** {3 Elementary_fence_basic_container_t} *)


(** {6 Typing_for_container} *)

type elementary_fence_basic_container =
  | Elementary_fence_basic_boolean_container of Elementary_fence_basic_boolean_container_t.elementary_fence_basic_boolean_container
  | Elementary_fence_basic_float_container of Elementary_fence_basic_float_container_t.elementary_fence_basic_float_container
  | Elementary_fence_basic_integer_container of Elementary_fence_basic_integer_container_t.elementary_fence_basic_integer_container
  | Elementary_fence_basic_string_container of Elementary_fence_basic_string_container_t.elementary_fence_basic_string_container
;;


(** Elementary_fence_basic_container_t at 11:53:10 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_fence_basic *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_fence_basic_symbol_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:43 (UTC+0200) *)
