(** {3 Elementary_border_coordinate_heterogeneous_cylindrical_container_t} *)


(** {6 Typing_for_container} *)

type elementary_border_coordinate_heterogeneous_cylindrical_container =
  | Elementary_border_coordinate_heterogeneous_cylindrical_rho_container of Elementary_border_coordinate_heterogeneous_cylindrical_rho_container_t.elementary_border_coordinate_heterogeneous_cylindrical_rho_container
  | Elementary_border_coordinate_heterogeneous_cylindrical_phi_container of Elementary_border_coordinate_heterogeneous_cylindrical_phi_container_t.elementary_border_coordinate_heterogeneous_cylindrical_phi_container
  | Elementary_border_coordinate_heterogeneous_cylindrical_zed_container of Elementary_border_coordinate_heterogeneous_cylindrical_zed_container_t.elementary_border_coordinate_heterogeneous_cylindrical_zed_container
;;


(** Elementary_border_coordinate_heterogeneous_cylindrical_container_t at 11:52:37 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_cylindrical *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_border_coordinate_heterogeneous_cylindrical_symbol_t.ml *)
(* adding supplement_elementary_border_coordinate_heterogeneous_cylindrical_container_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:45 (UTC+0200) *)
