type elementary_fence_units_actual_temperature_container = Elementary_fence_units_actual_temperature_tag_t.elementary_fence_units_actual_temperature_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_temperature *)
(* using ./template_container_as_uno_fence_bud_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:44 (UTC+0200) *)

