(** {3 Elementary_border_parameter_container_t} *)


(** {6 Typing_for_container} *)

type elementary_border_parameter_container =
  | Elementary_border_parameter_aopef_container of Elementary_border_parameter_aopef_container_t.elementary_border_parameter_aopef_container
  | Elementary_border_parameter_ecppef_container of Elementary_border_parameter_ecppef_container_t.elementary_border_parameter_ecppef_container
;;


(** Elementary_border_parameter_container_t at 11:53:3 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_border_parameter *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_border_parameter_symbol_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:46 (UTC+0200) *)
