(** {3 Elementary_fence_container_t} *)


(** {6 Typing_for_container} *)

type elementary_fence_container =
  | Elementary_fence_basic_container of Elementary_fence_basic_container_t.elementary_fence_basic_container
  | Elementary_fence_color_container of Elementary_fence_color_container_t.elementary_fence_color_container
  | Elementary_fence_units_container of Elementary_fence_units_container_t.elementary_fence_units_container
;;


(** Elementary_fence_container_t at 11:53:9 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_fence *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_fence_symbol_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:47 (UTC+0200) *)
