(** {3 Elementary_context_databox_container_t} *)


(** {6 Typing_for_container} *)

type elementary_context_databox_container =
  | Elementary_context_databox_skeletondata_container of Elementary_context_databox_skeletondata_container_t.elementary_context_databox_skeletondata_container
  | Elementary_context_databox_figuredata_container of Elementary_context_databox_figuredata_container_t.elementary_context_databox_figuredata_container
;;


(** Elementary_context_databox_container_t at 11:53:7 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_context_databox *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_context_databox_symbol_t.ml *)
(* adding supplement_elementary_context_databox_container_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:47 (UTC+0200) *)
