type elementary_body_parameter_tuple_aopef_container = (Elementary_border_parameter_aopef_exponent_tag_t.elementary_border_parameter_aopef_exponent_tag, Elementary_border_parameter_aopef_coefficient_tag_t.elementary_border_parameter_aopef_coefficient_tag) Doublet_t.doublet;;

(* generated by ./do_container_as_doublet_body_bud_2containee_t.sh elementary_body_parameter_tuple_aopef elementary_border_parameter_aopef_exponent elementary_border_parameter_aopef_coefficient *)
(* using ./template_container_as_doublet_body_bud_2containee_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:46 (UTC+0200) *)

