type elementary_context_domain_container = Elementary_context_database_tag_t.elementary_context_database_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh elementary_context_domain *)
(* using ./template_container_as_list_context_bud_1containee_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:46 (UTC+0200) *)

