type elementary_body_coordinate_tuple_homogeneous_linear_container = Elementary_border_coordinate_homogeneous_linear_x_tag_t.elementary_border_coordinate_homogeneous_linear_x_tag Singlet_t.singlet;;

(* generated by ./do_container_as_singlet_body_bud_1containee_t.sh elementary_body_coordinate_tuple_homogeneous_linear elementary_border_coordinate_homogeneous_linear_x *)
(* using ./template_container_as_singlet_body_bud_1containee_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:45 (UTC+0200) *)

