type elementary_context_databox_figuredata_container = Elementary_body_coordinate_tuple_tag_t.elementary_body_coordinate_tuple_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh elementary_context_databox_figuredata *)
(* using ./template_container_as_list_context_bud_1containee_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:46 (UTC+0200) *)

