(** {3 Elementary_fence_units_canonical_container_t} *)


(** {6 Typing_for_container} *)

type elementary_fence_units_canonical_container =
  | Elementary_fence_units_canonical_classical_container of Elementary_fence_units_canonical_classical_container_t.elementary_fence_units_canonical_classical_container
  | Elementary_fence_units_canonical_quantum_container of Elementary_fence_units_canonical_quantum_container_t.elementary_fence_units_canonical_quantum_container
;;


(** Elementary_fence_units_canonical_container_t at 11:53:31 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_fence_units_canonical *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_fence_units_canonical_symbol_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:44 (UTC+0200) *)
