(** {3 Elementary_border_coordinate_homogeneous_cartesian_container_t} *)


(** {6 Typing_for_container} *)

type elementary_border_coordinate_homogeneous_cartesian_container =
  | Elementary_border_coordinate_homogeneous_cartesian_x_container of Elementary_border_coordinate_homogeneous_cartesian_x_container_t.elementary_border_coordinate_homogeneous_cartesian_x_container
  | Elementary_border_coordinate_homogeneous_cartesian_y_container of Elementary_border_coordinate_homogeneous_cartesian_y_container_t.elementary_border_coordinate_homogeneous_cartesian_y_container
  | Elementary_border_coordinate_homogeneous_cartesian_z_container of Elementary_border_coordinate_homogeneous_cartesian_z_container_t.elementary_border_coordinate_homogeneous_cartesian_z_container
;;


(** Elementary_border_coordinate_homogeneous_cartesian_container_t at 11:52:50 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_cartesian *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_border_coordinate_homogeneous_cartesian_symbol_t.ml *)
(* adding supplement_elementary_border_coordinate_homogeneous_cartesian_container_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:45 (UTC+0200) *)
