type elementary_border_coordinate_heterogeneous_spherical_theta_container = Elementary_fence_units_actual_angle_tag_t.elementary_fence_units_actual_angle_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_border_bud_1containee_t.sh elementary_border_coordinate_heterogeneous_spherical_theta elementary_fence_units_actual_angle *)
(* using ./template_container_as_uno_border_bud_1containee_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:44 (UTC+0200) *)

