type elementary_fence_color_container = Elementary_fence_color_tag_t.elementary_fence_color_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_t.sh elementary_fence_color *)
(* using ./template_container_as_uno_fence_bud_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:43 (UTC+0200) *)

