type elementary_fence_units_actual_angle_container = Elementary_fence_units_actual_angle_tag_t.elementary_fence_units_actual_angle_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_t.sh elementary_fence_units_actual_angle *)
(* using ./template_container_as_uno_fence_bud_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:43 (UTC+0200) *)

