(** {3 Elementary_body_container_t} *)


(** {6 Typing_for_container} *)

type elementary_body_container =
  | Elementary_body_coordinate_tuple_container of Elementary_body_coordinate_tuple_container_t.elementary_body_coordinate_tuple_container
  | Elementary_body_parameter_tuple_container of Elementary_body_parameter_tuple_container_t.elementary_body_parameter_tuple_container
;;


(** Elementary_body_container_t at 11:52:31 on 9 May 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh elementary_body *)
(* using /keep/sources/ocaml_top/setup/frames/elementaryset/elementaryset_symbols/Elementary_body_symbol_t.ml *)
(* Done on mercredi 11 mai 2016, 10:51:46 (UTC+0200) *)
