# include ../elementaryset_symbols/files_elementary_symbols_mli.mk 
# CONTAINERS_T_MLI := $(subst symbol_t,container_t,$(ELEMENTARY_T_MLI)) 
# CONTAINERS_V_MLI := $(subst container_t,container_v,$(CONTAINERS_T_MLI)) 

CONTAINERS_T_MLI := \
    Elementary_fence_units_actual_none_container_t.mli \
    Elementary_fence_units_actual_time_container_t.mli \
    Elementary_fence_units_actual_temperature_container_t.mli \
    Elementary_fence_units_actual_mass_container_t.mli \
    Elementary_fence_units_actual_length_container_t.mli \
    Elementary_fence_units_actual_energy_container_t.mli \
    Elementary_fence_units_actual_charge_container_t.mli \
    Elementary_fence_units_actual_angle_container_t.mli \
    Elementary_fence_units_actual_action_container_t.mli \
   Elementary_fence_units_actual_container_t.mli \
    Elementary_fence_units_canonical_quantum_container_t.mli \
    Elementary_fence_units_canonical_classical_container_t.mli \
   Elementary_fence_units_canonical_container_t.mli \
   Elementary_fence_color_container_t.mli \
    Elementary_fence_basic_string_container_t.mli \
    Elementary_fence_basic_integer_container_t.mli \
    Elementary_fence_basic_float_container_t.mli \
    Elementary_fence_basic_boolean_container_t.mli \
   Elementary_fence_basic_container_t.mli \
  Elementary_fence_container_t.mli \
     Elementary_border_parameter_ecppef_exponent_container_t.mli \
     Elementary_border_parameter_ecppef_coefficient_container_t.mli \
    Elementary_border_parameter_ecppef_container_t.mli \
     Elementary_border_parameter_aopef_exponent_container_t.mli \
     Elementary_border_parameter_aopef_coefficient_container_t.mli \
    Elementary_border_parameter_aopef_container_t.mli \
   Elementary_border_parameter_container_t.mli \
      Elementary_border_coordinate_homogeneous_planar_y_container_t.mli \
      Elementary_border_coordinate_homogeneous_planar_x_container_t.mli \
     Elementary_border_coordinate_homogeneous_planar_container_t.mli \
      Elementary_border_coordinate_homogeneous_linear_x_container_t.mli \
     Elementary_border_coordinate_homogeneous_linear_container_t.mli \
      Elementary_border_coordinate_homogeneous_cartesian_z_container_t.mli \
      Elementary_border_coordinate_homogeneous_cartesian_y_container_t.mli \
      Elementary_border_coordinate_homogeneous_cartesian_x_container_t.mli \
     Elementary_border_coordinate_homogeneous_cartesian_container_t.mli \
    Elementary_border_coordinate_homogeneous_container_t.mli \
      Elementary_border_coordinate_heterogeneous_spherical_theta_container_t.mli \
      Elementary_border_coordinate_heterogeneous_spherical_phi_container_t.mli \
      Elementary_border_coordinate_heterogeneous_spherical_rho_container_t.mli \
     Elementary_border_coordinate_heterogeneous_spherical_container_t.mli \
      Elementary_border_coordinate_heterogeneous_polar_theta_container_t.mli \
      Elementary_border_coordinate_heterogeneous_polar_rho_container_t.mli \
     Elementary_border_coordinate_heterogeneous_polar_container_t.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_zed_container_t.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_phi_container_t.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_rho_container_t.mli \
     Elementary_border_coordinate_heterogeneous_cylindrical_container_t.mli \
    Elementary_border_coordinate_heterogeneous_container_t.mli \
   Elementary_border_coordinate_container_t.mli \
  Elementary_border_container_t.mli \
   Elementary_context_domain_container_t.mli \
    Elementary_context_databox_figuredata_container_t.mli \
    Elementary_context_databox_skeletondata_container_t.mli \
   Elementary_context_databox_container_t.mli \
   Elementary_context_database_container_t.mli \
  Elementary_context_container_t.mli \
    Elementary_body_parameter_tuple_ecppef_container_t.mli \
    Elementary_body_parameter_tuple_aopef_container_t.mli \
   Elementary_body_parameter_tuple_container_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_planar_container_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_linear_container_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_cartesian_container_t.mli \
    Elementary_body_coordinate_tuple_homogeneous_container_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_spherical_container_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_polar_container_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_cylindrical_container_t.mli \
    Elementary_body_coordinate_tuple_heterogeneous_container_t.mli \
   Elementary_body_coordinate_tuple_container_t.mli \
  Elementary_body_container_t.mli \
 Elementary_container_t.mli \

CONTAINERS_V_MLI := \
    Elementary_fence_basic_string_container_v.mli \
    Elementary_fence_basic_integer_container_v.mli \
    Elementary_fence_basic_float_container_v.mli \
    Elementary_fence_basic_boolean_container_v.mli \
   Elementary_fence_basic_container_v.mli \
      Elementary_fence_units_actual_none_container_v.mli \
      Elementary_fence_units_actual_time_container_v.mli \
      Elementary_fence_units_actual_temperature_container_v.mli \
      Elementary_fence_units_actual_mass_container_v.mli \
      Elementary_fence_units_actual_length_container_v.mli \
      Elementary_fence_units_actual_energy_container_v.mli \
      Elementary_fence_units_actual_charge_container_v.mli \
      Elementary_fence_units_actual_angle_container_v.mli \
      Elementary_fence_units_actual_action_container_v.mli \
      Elementary_fence_units_actual_container_v.mli \
     Elementary_fence_units_canonical_quantum_container_v.mli \
     Elementary_fence_units_canonical_classical_container_v.mli \
    Elementary_fence_units_canonical_container_v.mli \
   Elementary_fence_units_container_v.mli \
   Elementary_fence_color_container_v.mli \
  Elementary_fence_container_v.mli \
      Elementary_border_coordinate_homogeneous_planar_x_container_v.mli \
      Elementary_border_coordinate_homogeneous_planar_y_container_v.mli \
     Elementary_border_coordinate_homogeneous_planar_container_v.mli \
      Elementary_border_coordinate_homogeneous_linear_x_container_v.mli \
     Elementary_border_coordinate_homogeneous_linear_container_v.mli \
      Elementary_border_coordinate_homogeneous_cartesian_z_container_v.mli \
      Elementary_border_coordinate_homogeneous_cartesian_y_container_v.mli \
      Elementary_border_coordinate_homogeneous_cartesian_x_container_v.mli \
     Elementary_border_coordinate_homogeneous_cartesian_container_v.mli \
      Elementary_border_coordinate_heterogeneous_spherical_theta_container_v.mli \
      Elementary_border_coordinate_heterogeneous_spherical_phi_container_v.mli \
      Elementary_border_coordinate_heterogeneous_spherical_rho_container_v.mli \
     Elementary_border_coordinate_heterogeneous_spherical_container_v.mli \
      Elementary_border_coordinate_heterogeneous_polar_theta_container_v.mli \
      Elementary_border_coordinate_heterogeneous_polar_rho_container_v.mli \
     Elementary_border_coordinate_heterogeneous_polar_container_v.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_zed_container_v.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_phi_container_v.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_rho_container_v.mli \
     Elementary_border_coordinate_heterogeneous_cylindrical_container_v.mli \
    Elementary_border_coordinate_homogeneous_container_v.mli \
    Elementary_border_coordinate_heterogeneous_container_v.mli \
   Elementary_border_coordinate_container_v.mli \
      Elementary_border_parameter_ecppef_exponent_container_v.mli \
      Elementary_border_parameter_ecppef_coefficient_container_v.mli \
     Elementary_border_parameter_ecppef_container_v.mli \
      Elementary_border_parameter_aopef_exponent_container_v.mli \
      Elementary_border_parameter_aopef_coefficient_container_v.mli \
     Elementary_border_parameter_aopef_container_v.mli \
   Elementary_border_parameter_container_v.mli \
    Elementary_body_parameter_tuple_ecppef_container_v.mli \
    Elementary_body_parameter_tuple_aopef_container_v.mli \
   Elementary_body_parameter_tuple_container_v.mli \
      Elementary_body_coordinate_tuple_homogeneous_linear_container_v.mli \
      Elementary_body_coordinate_tuple_homogeneous_planar_container_v.mli \
      Elementary_body_coordinate_tuple_homogeneous_cartesian_container_v.mli \
     Elementary_body_coordinate_tuple_homogeneous_container_v.mli \
     Elementary_body_coordinate_tuple_heterogeneous_spherical_container_v.mli \
     Elementary_body_coordinate_tuple_heterogeneous_polar_container_v.mli \
     Elementary_body_coordinate_tuple_heterogeneous_cylindrical_container_v.mli \
    Elementary_body_coordinate_tuple_heterogeneous_container_v.mli \
   Elementary_body_coordinate_tuple_container_v.mli \
   Elementary_context_domain_container_v.mli \
    Elementary_context_databox_figuredata_container_v.mli \
    Elementary_context_databox_skeletondata_container_v.mli \
   Elementary_context_databox_container_v.mli \
   Elementary_context_database_container_v.mli \
  Elementary_border_container_v.mli \
  Elementary_body_container_v.mli \
  Elementary_context_container_v.mli \
 Elementary_container_v.mli \
 
# CONTAINERS_TV_MLI := $(CONTAINERS_T_MLI) $(CONTAINERS_V_MLI)
 
FILES_MLI := \
$(CONTAINERS_T_MLI) \
$(CONTAINERS_V_MLI) \
 