CONTAINERS_T_MLI := \
    Elementary_fence_basic_container_t.mli \
    Elementary_fence_units_container_t.mli \
    Elementary_fence_color_container_t.mli \
  Elementary_fence_container_t.mli \
        Elementary_border_coordinate_elementary_border_coordinate_homogeneous_planar_container_t.mli \
        Elementary_border_coordinate_elementary_border_coordinate_homogeneous_linear_container_t.mli \
        Elementary_border_coordinate_elementary_border_coordinate_homogeneous_cartesian_container_t.mli \
        Elementary_border_coordinate_elementary_border_coordinate_heterogeneous_spherical_container_t.mli \
        Elementary_border_coordinate_elementary_border_coordinate_heterogeneous_polar_container_t.mli \
        Elementary_border_coordinate_elementary_border_coordinate_heterogeneous_cylindrical_container_t.mli \
      Elementary_border_coordinate_heterogeneous_container_t.mli \
      Elementary_border_coordinate_homogeneous_container_t.mli \
    Elementary_border_coordinate_container_t.mli \
       Elementary_border_parameter_ecppef_exponent_container_t.mli \
       Elementary_border_parameter_ecppef_coefficient_container_t.mli \
     Elementary_border_parameter_ecppef_container_t.mli \
       Elementary_border_parameter_aopef_exponent_container_t.mli \
       Elementary_border_parameter_aopef_coefficient_container_t.mli \
     Elementary_border_parameter_aopef_container_t.mli \
   Elementary_border_parameter_container_t.mli \
  Elementary_border_container_t.mli \
     Elementary_body_parameter_tuple_ecppef_container_t.mli \
     Elementary_body_parameter_tuple_aopef_container_t.mli \
   Elementary_body_parameter_tuple_container_t.mli \
     Elementary_body_coordinate_tuple_elementary_border_coordinate_heterogeneous_spherical_container_t.mli \
     Elementary_body_coordinate_tuple_elementary_border_coordinate_heterogeneous_polar_container_t.mli \
     Elementary_body_coordinate_tuple_elementary_border_coordinate_heterogeneous_cylindrical_container_t.mli \
    Elementary_body_coordinate_tuple_heterogeneous_container_t.mli \
     Elementary_body_coordinate_tuple_elementary_border_coordinate_homogeneous_planar_container_t.mli \
     Elementary_body_coordinate_tuple_elementary_border_coordinate_homogeneous_linear_container_t.mli \
     Elementary_body_coordinate_tuple_elementary_border_coordinate_homogeneous_cartesian_container_t.mli \
    Elementary_body_coordinate_tuple_homogeneous_container_t.mli \
   Elementary_body_coordinate_tuple_container_t.mli \
  Elementary_body_container_t.mli \
     Elementary_context_databox_figuredata_container_t.mli \
     Elementary_context_databox_skeletondata_container_t.mli \
   Elementary_context_databox_container_t.mli \
   Elementary_context_database_container_t.mli \
   Elementary_context_domain_container_t.mli \
  Elementary_context_container_t.mli \
 Elementary_container_t.mli \
 
