INCLUDED_DIRS := \
        $(BASICS_DIR) \
        $(DATASTRUCTURES_DIR) \
        $(FILES_DIR) \
        $(COMMONSET_DIR) \
        $(DATABASESET_COMMON_DIR) \
        $(DB1_FIGURE_DIR) \
	$(INPUTSET_COMMON_DIR) \
	$(INPUTSET_LEXER_DIR) \
	$(INPUTSET_SYMBOLS_DIR) \
	$(INPUTSET_TAGS_DIR) \
	$(INPUTSET_PARSER_DIR) \
	$(INPUTSET_BUILDER_TREES_DIR) \
        $(ELEMENTARYSET_SYMBOLS_DIR) \
        $(ELEMENTARYSET_TAGS_DIR) \
        $(ELEMENTARYSET_DATABASES_DIR) \
        $(ELEMENTARYSET_CONTAINERS_DIR) \
  