(** {3 The functionalities for a Mark for a Block_zerotied_zerotied.} *)

let nam_cod = "block_zerotied_zerotied_mark_v.ml";;


(** {6 Aliasing} *)



(** {6 Naming} *)


let name mark_b00 =
  Mark_v.name Block_zerotied_zerotied_symbol_v.name mark_b00
;;


(** {6 Upgrading} *)


let block_zerotied_zerotied_mark_of_block_none_none_ax0_mark mark_nna = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax0_symbol mark_nna
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax0e0_monoatomic_mark mark_nam = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax0e0_monoatomic_symbol mark_nam
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_mark mark_at0 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_symbol mark_at0
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_anion_mark mark_a0a = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_anion_symbol mark_a0a
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_anion_minusone_mark mark_0a1 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_anion_minusone_symbol mark_0a1
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_anion_minustwo_mark mark_0a2 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_anion_minustwo_symbol mark_0a2
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_cation_mark mark_a0c = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_cation_symbol mark_a0c
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_cation_plusone_mark mark_0c1 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_cation_plusone_symbol mark_0c1
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_cation_plustwo_mark mark_0c2 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_cation_plustwo_symbol mark_0c2
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_cation_plusthree_mark mark_0c3 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_cation_plusthree_symbol mark_0c3
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_raregas_mark mark_a0r = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_raregas_symbol mark_a0r
;;

let block_zerotied_zerotied_mark_of_atom_zerotied_halfbridge_mark mark_a0h = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_atom_zerotied_halfbridge_symbol mark_a0h
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax1_mark mark_nna = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax1_symbol mark_nna
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax1en_diatomic_mark mark_nad = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax1en_diatomic_symbol mark_nad
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax2_mark mark_nna = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax2_symbol mark_nna
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax2e0_linear_mark mark_nal = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax2e0_linear_symbol mark_nal
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax2e1_bent_mark mark_nab = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax2e1_bent_symbol mark_nab
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax2e2_bent_mark mark_nab = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax2e2_bent_symbol mark_nab
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax3_mark mark_nna = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax3_symbol mark_nna
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax3e0_trigonalplanar_mark mark_nat = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax3e0_trigonalplanar_symbol mark_nat
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax3e1_trigonalpyramidal_mark mark_nat = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax3e1_trigonalpyramidal_symbol mark_nat
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax4_mark mark_nna = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax4_symbol mark_nna
;;

let block_zerotied_zerotied_mark_of_block_none_none_ax4e1_tetrahedral_mark mark_nat = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_zerotied_zerotied_symbol_of_block_none_none_ax4e1_tetrahedral_symbol mark_nat
;;


(** {6 Abbreviating} *)



(** {6 Making} *)


let make sym_b00 soi_b00 =
  Mark_v.make sym_b00 soi_b00
;;


(** {6 Extracting} *)


let block_none_none_ax0_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax0_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax0e0_monoatomic_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax0e0_monoatomic_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_anion_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_anion_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_anion_minusone_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_anion_minusone_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_anion_minustwo_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_anion_minustwo_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_cation_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_cation_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_cation_plusone_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_cation_plusone_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_cation_plustwo_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_cation_plustwo_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_cation_plusthree_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_cation_plusthree_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_raregas_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_raregas_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let atom_zerotied_halfbridge_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.atom_zerotied_halfbridge_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax1_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax1_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax1en_diatomic_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax1en_diatomic_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax2_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax2_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax2e0_linear_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax2e0_linear_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax2e1_bent_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax2e1_bent_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax2e2_bent_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax2e2_bent_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax3_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax3_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax3e0_trigonalplanar_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax3e0_trigonalplanar_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax3e1_trigonalpyramidal_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax3e1_trigonalpyramidal_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax4_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax4_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let block_none_none_ax4e1_tetrahedral_mark_off_block_zerotied_zerotied_mark mark_b00 = 
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.block_none_none_ax4e1_tetrahedral_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;


(** {6 Querying} *)


let is_block_none_none_ax0_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax0_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax0e0_monoatomic_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax0e0_monoatomic_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_anion_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_anion_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_anion_minusone_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_anion_minusone_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_anion_minustwo_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_anion_minustwo_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_cation_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_cation_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_cation_plusone_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_cation_plusone_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_cation_plustwo_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_cation_plustwo_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_cation_plusthree_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_cation_plusthree_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_raregas_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_raregas_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_atom_zerotied_halfbridge_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_atom_zerotied_halfbridge_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax1_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax1_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax1en_diatomic_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax1en_diatomic_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax2_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax2_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax2e0_linear_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax2e0_linear_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax2e1_bent_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax2e1_bent_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax2e2_bent_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax2e2_bent_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax3_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax3_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax3e0_trigonalplanar_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax3e0_trigonalplanar_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax3e1_trigonalpyramidal_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax3e1_trigonalpyramidal_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax4_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax4_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;

let is_block_none_none_ax4e1_tetrahedral_mark_off_block_zerotied_zerotied_mark mark_b00 =
  Mark_v.map_left Block_zerotied_zerotied_symbol_v.is_block_none_none_ax4e1_tetrahedral_symbol_off_block_zerotied_zerotied_symbol mark_b00
;;


(** created by ./generator block_zerotied_zerotied implementation mark at 15:12 13 Mar 2012. *)



