(** {3 The functionalities for a Mark for a Block_single_single.} *)

let nam_cod = "block_single_single_mark_v.ml";;


(** {6 Aliasing} *)



(** {6 Naming} *)


let name mark_bss =
  Mark_v.name Block_single_single_symbol_v.name mark_bss
;;


(** {6 Upgrading} *)


let block_single_single_mark_of_block_single_single_ax2_mark mark_ssa = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax2_symbol mark_ssa
;;

let block_single_single_mark_of_block_single_single_ax2e0_bent_mark mark_sab = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax2e0_bent_symbol mark_sab
;;

let block_single_single_mark_of_block_single_single_ax2e2_bent_mark mark_sab = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax2e2_bent_symbol mark_sab
;;

let block_single_single_mark_of_block_single_single_ax2e3_linear_mark mark_sal = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax2e3_linear_symbol mark_sal
;;

let block_single_single_mark_of_block_single_single_ax3_mark mark_ssa = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax3_symbol mark_ssa
;;

let block_single_single_mark_of_block_single_single_ax3e0_trigonalplanar_mark mark_sat = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax3e0_trigonalplanar_symbol mark_sat
;;

let block_single_single_mark_of_block_single_single_ax3e1_trigonalpyramidal_mark mark_sat = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax3e1_trigonalpyramidal_symbol mark_sat
;;

let block_single_single_mark_of_block_single_single_ax3e2_tshaped_mark mark_sat = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax3e2_tshaped_symbol mark_sat
;;

let block_single_single_mark_of_block_single_single_ax4_mark mark_ssa = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax4_symbol mark_ssa
;;

let block_single_single_mark_of_block_single_single_ax4e0_tetrahedral_mark mark_sat = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax4e0_tetrahedral_symbol mark_sat
;;

let block_single_single_mark_of_block_single_single_ax4e1_seesaw_mark mark_sas = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_symbol_of_block_single_single_ax4e1_seesaw_symbol mark_sas
;;


(** {6 Abbreviating} *)



(** {6 Making} *)


let make sym_bss soi_bss =
  Mark_v.make sym_bss soi_bss
;;


(** {6 Extracting} *)


let block_single_single_ax2_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax2_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax2e0_bent_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax2e0_bent_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax2e2_bent_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax2e2_bent_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax2e3_linear_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax2e3_linear_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax3_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax3_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax3e0_trigonalplanar_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax3e0_trigonalplanar_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax3e1_trigonalpyramidal_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax3e1_trigonalpyramidal_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax3e2_tshaped_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax3e2_tshaped_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax4_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax4_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax4e0_tetrahedral_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax4e0_tetrahedral_symbol_off_block_single_single_symbol mark_bss
;;

let block_single_single_ax4e1_seesaw_mark_off_block_single_single_mark mark_bss = 
  Mark_v.map_left Block_single_single_symbol_v.block_single_single_ax4e1_seesaw_symbol_off_block_single_single_symbol mark_bss
;;


(** {6 Querying} *)


let is_block_single_single_ax2_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax2_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax2e0_bent_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax2e0_bent_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax2e2_bent_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax2e2_bent_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax2e3_linear_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax2e3_linear_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax3_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax3_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax3e0_trigonalplanar_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax3e0_trigonalplanar_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax3e1_trigonalpyramidal_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax3e1_trigonalpyramidal_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax3e2_tshaped_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax3e2_tshaped_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax4_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax4_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax4e0_tetrahedral_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax4e0_tetrahedral_symbol_off_block_single_single_symbol mark_bss
;;

let is_block_single_single_ax4e1_seesaw_mark_off_block_single_single_mark mark_bss =
  Mark_v.map_left Block_single_single_symbol_v.is_block_single_single_ax4e1_seesaw_symbol_off_block_single_single_symbol mark_bss
;;


(** created by ./generator block_single_single implementation mark at 15:13 13 Mar 2012. *)



