(** {3 The functionalities for a Mark for a Block_onetied_forktied.} *)

let nam_cod = "block_onetied_forktied_mark_v.ml";;


(** {6 Aliasing} *)



(** {6 Naming} *)


let name mark_b1f =
  Mark_v.name Block_onetied_forktied_symbol_v.name mark_b1f
;;


(** {6 Upgrading} *)


let block_onetied_forktied_mark_of_block_onetied_biforktied_mark mark_b1b = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_onetied_biforktied_symbol mark_b1b
;;

let block_onetied_forktied_mark_of_block_single_singlesingle_mark mark_bss = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singlesingle_symbol mark_bss
;;

let block_onetied_forktied_mark_of_block_single_singlesingle_ax3_mark mark_ssa = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singlesingle_ax3_symbol mark_ssa
;;

let block_onetied_forktied_mark_of_block_single_singlesingle_ax3e1_trigonalpyramidal_mark mark_sat = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singlesingle_ax3e1_trigonalpyramidal_symbol mark_sat
;;

let block_onetied_forktied_mark_of_block_single_singledouble_mark mark_bss = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singledouble_symbol mark_bss
;;

let block_onetied_forktied_mark_of_block_single_singledouble_ax3e0_trigonalplanar_mark mark_sat = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singledouble_ax3e0_trigonalplanar_symbol mark_sat
;;

let block_onetied_forktied_mark_of_block_onetied_triforktied_mark mark_b1t = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_onetied_triforktied_symbol mark_b1t
;;

let block_onetied_forktied_mark_of_block_single_singlesinglesingle_mark mark_bss = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singlesinglesingle_symbol mark_bss
;;

let block_onetied_forktied_mark_of_block_single_singlesinglesingle_ax4_mark mark_ssa = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singlesinglesingle_ax4_symbol mark_ssa
;;

let block_onetied_forktied_mark_of_block_single_singlesinglesingle_ax4e1_tetrahedral_mark mark_sat = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_forktied_symbol_of_block_single_singlesinglesingle_ax4e1_tetrahedral_symbol mark_sat
;;


(** {6 Abbreviating} *)



(** {6 Making} *)


let make sym_b1f soi_b1f =
  Mark_v.make sym_b1f soi_b1f
;;


(** {6 Extracting} *)


let block_onetied_biforktied_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_biforktied_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singlesingle_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singlesingle_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singlesingle_ax3_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singlesingle_ax3_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singlesingle_ax3e1_trigonalpyramidal_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singlesingle_ax3e1_trigonalpyramidal_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singledouble_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singledouble_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singledouble_ax3e0_trigonalplanar_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singledouble_ax3e0_trigonalplanar_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_onetied_triforktied_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_onetied_triforktied_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singlesinglesingle_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singlesinglesingle_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singlesinglesingle_ax4_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singlesinglesingle_ax4_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let block_single_singlesinglesingle_ax4e1_tetrahedral_mark_off_block_onetied_forktied_mark mark_b1f = 
  Mark_v.map_left Block_onetied_forktied_symbol_v.block_single_singlesinglesingle_ax4e1_tetrahedral_symbol_off_block_onetied_forktied_symbol mark_b1f
;;


(** {6 Querying} *)


let is_block_onetied_biforktied_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_onetied_biforktied_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singlesingle_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singlesingle_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singlesingle_ax3_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singlesingle_ax3_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singlesingle_ax3e1_trigonalpyramidal_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singlesingle_ax3e1_trigonalpyramidal_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singledouble_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singledouble_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singledouble_ax3e0_trigonalplanar_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singledouble_ax3e0_trigonalplanar_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_onetied_triforktied_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_onetied_triforktied_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singlesinglesingle_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singlesinglesingle_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singlesinglesingle_ax4_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singlesinglesingle_ax4_symbol_off_block_onetied_forktied_symbol mark_b1f
;;

let is_block_single_singlesinglesingle_ax4e1_tetrahedral_mark_off_block_onetied_forktied_mark mark_b1f =
  Mark_v.map_left Block_onetied_forktied_symbol_v.is_block_single_singlesinglesingle_ax4e1_tetrahedral_symbol_off_block_onetied_forktied_symbol mark_b1f
;;


(** created by ./generator block_onetied_forktied implementation mark at 15:12 13 Mar 2012. *)



