FILES_T_MLI :=  \
   segment_onetied_onetied_mark_t.mli \
      block_single_triple_ax2e0_linear_mark_t.mli \
     block_single_triple_ax2_mark_t.mli \
    block_single_triple_mark_t.mli \
      block_single_double_ax3e0_trigonalplanar_mark_t.mli \
     block_single_double_ax3_mark_t.mli \
    block_single_double_mark_t.mli \
     block_single_conjugated_ax3e0_trigonalplanar_mark_t.mli \
    block_single_conjugated_mark_t.mli \
      block_single_single_ax4e1_seesaw_mark_t.mli \
      block_single_single_ax4e0_tetrahedral_mark_t.mli \
     block_single_single_ax4_mark_t.mli \
      block_single_single_ax3e2_tshaped_mark_t.mli \
      block_single_single_ax3e1_trigonalpyramidal_mark_t.mli \
      block_single_single_ax3e0_trigonalplanar_mark_t.mli \
     block_single_single_ax3_mark_t.mli \
      block_single_single_ax2e3_linear_mark_t.mli \
      block_single_single_ax2e2_bent_mark_t.mli \
      block_single_single_ax2e0_bent_mark_t.mli \
     block_single_single_ax2_mark_t.mli \
    block_single_single_mark_t.mli \
   block_onetied_onetied_mark_t.mli \
  segment_buried_mark_t.mli \
   segment_zerotied_onetied_mark_t.mli \
      block_none_triple_ax2e0_linear_mark_t.mli \
     block_none_triple_ax2_mark_t.mli \
    block_none_triple_mark_t.mli \
     block_none_double_ax3e0_trigonalplanar_mark_t.mli \
    block_none_double_mark_t.mli \
     block_none_conjugated_ax3e0_trigonalplanar_mark_t.mli \
    block_none_conjugated_mark_t.mli \
      block_none_single_ax4e1_tetrahedral_mark_t.mli \
     block_none_single_ax4_mark_t.mli \
      block_none_single_ax3e1_trigonalpyramidal_mark_t.mli \
      block_none_single_ax3e0_trigonalplanar_mark_t.mli \
     block_none_single_ax3_mark_t.mli \
      block_none_single_ax1en_diatomic_mark_t.mli \
     block_none_single_ax1_mark_t.mli \
    block_none_single_mark_t.mli \
   block_zerotied_onetied_mark_t.mli \
  segment_head_mark_t.mli \
 segment_mark_t.mli \
 polypeptide_subunit_mark_t.mli \
   polypeptide_mark_t.mli \
  molecule_polymer_mark_t.mli \
   molecule_linear_overpentatomic_mark_t.mli \
   molecule_linear_pentatomic_mark_t.mli \
   molecule_linear_tetratomic_mark_t.mli \
   molecule_linear_triatomic_mark_t.mli \
   molecule_linear_diatomic_mark_t.mli \
      atom_zerotied_halfbridge_mark_t.mli \
      atom_zerotied_raregas_mark_t.mli \
       atom_zerotied_cation_plusthree_mark_t.mli \
       atom_zerotied_cation_plustwo_mark_t.mli \
       atom_zerotied_cation_plusone_mark_t.mli \
      atom_zerotied_cation_mark_t.mli \
       atom_zerotied_anion_minustwo_mark_t.mli \
       atom_zerotied_anion_minusone_mark_t.mli \
      atom_zerotied_anion_mark_t.mli \
     atom_zerotied_mark_t.mli \
    block_none_none_ax0e0_monoatomic_mark_t.mli \
   molecule_linear_monoatomic_mark_t.mli \
  molecule_linear_mark_t.mli \
  molecule_forked_mark_t.mli \
  molecule_dendrimer_mark_t.mli \
  molecule_bridged_mark_t.mli \
 molecule_mark_t.mli \
 mendeleev_mark_t.mli \
  polypeptide_sidegroup_mark_t.mli \
   fragment_leaf_halfbridgetailed_mark_t.mli \
   fragment_onetied_zerotied_mark_t.mli \
  fragment_leaf_mark_t.mli \
 grouping_mark_t.mli \
   fragment_leaf_halfbridgetailed_mark_t.mli \
   fragment_onetied_zerotied_mark_t.mli \
  fragment_leaf_mark_t.mli \
       block_single_singlesinglesingle_ax4e1_tetrahedral_mark_t.mli \
      block_single_singlesinglesingle_ax4_mark_t.mli \
     block_single_singlesinglesingle_mark_t.mli \
    block_onetied_triforktied_mark_t.mli \
      block_single_singledouble_ax3e0_trigonalplanar_mark_t.mli \
     block_single_singledouble_mark_t.mli \
       block_single_singlesingle_ax3e1_trigonalpyramidal_mark_t.mli \
      block_single_singlesingle_ax3_mark_t.mli \
     block_single_singlesingle_mark_t.mli \
    block_onetied_biforktied_mark_t.mli \
   block_onetied_forktied_mark_t.mli \
  fragment_buried_mark_t.mli \
   fragment_head_halfbridged_mark_t.mli \
    fragment_head_triforked_mark_t.mli \
    fragment_head_biforked_mark_t.mli \
   fragment_head_forked_mark_t.mli \
  fragment_head_mark_t.mli \
   fragment_zerotied_zerotied_mark_t.mli \
     block_none_none_ax4e1_tetrahedral_mark_t.mli \
    block_none_none_ax4_mark_t.mli \
     block_none_none_ax3e1_trigonalpyramidal_mark_t.mli \
     block_none_none_ax3e0_trigonalplanar_mark_t.mli \
    block_none_none_ax3_mark_t.mli \
     block_none_none_ax2e2_bent_mark_t.mli \
     block_none_none_ax2e1_bent_mark_t.mli \
     block_none_none_ax2e0_linear_mark_t.mli \
    block_none_none_ax2_mark_t.mli \
     block_none_none_ax1en_diatomic_mark_t.mli \
    block_none_none_ax1_mark_t.mli \
       atom_zerotied_halfbridge_mark_t.mli \
       atom_zerotied_raregas_mark_t.mli \
        atom_zerotied_cation_plusthree_mark_t.mli \
        atom_zerotied_cation_plustwo_mark_t.mli \
        atom_zerotied_cation_plusone_mark_t.mli \
       atom_zerotied_cation_mark_t.mli \
        atom_zerotied_anion_minustwo_mark_t.mli \
        atom_zerotied_anion_minusone_mark_t.mli \
       atom_zerotied_anion_mark_t.mli \
      atom_zerotied_mark_t.mli \
     block_none_none_ax0e0_monoatomic_mark_t.mli \
    block_none_none_ax0_mark_t.mli \
   block_zerotied_zerotied_mark_t.mli \
  fragment_closed_mark_t.mli \
 fragment_mark_t.mli \
 coffer_mark_t.mli \
 cluster_mark_t.mli \
 chain_mark_t.mli \
 bridge_mark_t.mli \
 bond_mark_t.mli \
       block_single_singlesinglesingle_ax4e1_tetrahedral_mark_t.mli \
      block_single_singlesinglesingle_ax4_mark_t.mli \
     block_single_singlesinglesingle_mark_t.mli \
    block_onetied_triforktied_mark_t.mli \
      block_single_singledouble_ax3e0_trigonalplanar_mark_t.mli \
     block_single_singledouble_mark_t.mli \
       block_single_singlesingle_ax3e1_trigonalpyramidal_mark_t.mli \
      block_single_singlesingle_ax3_mark_t.mli \
     block_single_singlesingle_mark_t.mli \
    block_onetied_biforktied_mark_t.mli \
   block_onetied_forktied_mark_t.mli \
      block_single_triple_ax2e0_linear_mark_t.mli \
     block_single_triple_ax2_mark_t.mli \
    block_single_triple_mark_t.mli \
      block_single_double_ax3e0_trigonalplanar_mark_t.mli \
     block_single_double_ax3_mark_t.mli \
    block_single_double_mark_t.mli \
     block_single_conjugated_ax3e0_trigonalplanar_mark_t.mli \
    block_single_conjugated_mark_t.mli \
      block_single_single_ax4e1_seesaw_mark_t.mli \
      block_single_single_ax4e0_tetrahedral_mark_t.mli \
     block_single_single_ax4_mark_t.mli \
      block_single_single_ax3e2_tshaped_mark_t.mli \
      block_single_single_ax3e1_trigonalpyramidal_mark_t.mli \
      block_single_single_ax3e0_trigonalplanar_mark_t.mli \
     block_single_single_ax3_mark_t.mli \
      block_single_single_ax2e3_linear_mark_t.mli \
      block_single_single_ax2e2_bent_mark_t.mli \
      block_single_single_ax2e0_bent_mark_t.mli \
     block_single_single_ax2_mark_t.mli \
    block_single_single_mark_t.mli \
   block_onetied_onetied_mark_t.mli \
  block_onetied_mark_t.mli \
      block_none_triple_ax2e0_linear_mark_t.mli \
     block_none_triple_ax2_mark_t.mli \
    block_none_triple_mark_t.mli \
     block_none_double_ax3e0_trigonalplanar_mark_t.mli \
    block_none_double_mark_t.mli \
     block_none_conjugated_ax3e0_trigonalplanar_mark_t.mli \
    block_none_conjugated_mark_t.mli \
      block_none_single_ax4e1_tetrahedral_mark_t.mli \
     block_none_single_ax4_mark_t.mli \
      block_none_single_ax3e1_trigonalpyramidal_mark_t.mli \
      block_none_single_ax3e0_trigonalplanar_mark_t.mli \
     block_none_single_ax3_mark_t.mli \
      block_none_single_ax1en_diatomic_mark_t.mli \
     block_none_single_ax1_mark_t.mli \
    block_none_single_mark_t.mli \
   block_zerotied_onetied_mark_t.mli \
     block_none_none_ax4e1_tetrahedral_mark_t.mli \
    block_none_none_ax4_mark_t.mli \
     block_none_none_ax3e1_trigonalpyramidal_mark_t.mli \
     block_none_none_ax3e0_trigonalplanar_mark_t.mli \
    block_none_none_ax3_mark_t.mli \
     block_none_none_ax2e2_bent_mark_t.mli \
     block_none_none_ax2e1_bent_mark_t.mli \
     block_none_none_ax2e0_linear_mark_t.mli \
    block_none_none_ax2_mark_t.mli \
     block_none_none_ax1en_diatomic_mark_t.mli \
    block_none_none_ax1_mark_t.mli \
       atom_zerotied_halfbridge_mark_t.mli \
       atom_zerotied_raregas_mark_t.mli \
        atom_zerotied_cation_plusthree_mark_t.mli \
        atom_zerotied_cation_plustwo_mark_t.mli \
        atom_zerotied_cation_plusone_mark_t.mli \
       atom_zerotied_cation_mark_t.mli \
        atom_zerotied_anion_minustwo_mark_t.mli \
        atom_zerotied_anion_minusone_mark_t.mli \
       atom_zerotied_anion_mark_t.mli \
      atom_zerotied_mark_t.mli \
     block_none_none_ax0e0_monoatomic_mark_t.mli \
    block_none_none_ax0_mark_t.mli \
   block_zerotied_zerotied_mark_t.mli \
  block_zerotied_mark_t.mli \
 block_mark_t.mli \
   atom_zerotied_halfbridge_mark_t.mli \
   atom_zerotied_raregas_mark_t.mli \
    atom_zerotied_cation_plusthree_mark_t.mli \
    atom_zerotied_cation_plustwo_mark_t.mli \
    atom_zerotied_cation_plusone_mark_t.mli \
   atom_zerotied_cation_mark_t.mli \
    atom_zerotied_anion_minustwo_mark_t.mli \
    atom_zerotied_anion_minusone_mark_t.mli \
   atom_zerotied_anion_mark_t.mli \
  atom_zerotied_mark_t.mli \
   atom_onetied_triple_mark_t.mli \
   atom_onetied_single_mark_t.mli \
   atom_onetied_double_mark_t.mli \
   atom_onetied_conjugated_mark_t.mli \
  atom_onetied_mark_t.mli \
   atom_core_sixtied_mark_t.mli \
   atom_core_fivetied_mark_t.mli \
   atom_core_fourtied_mark_t.mli \
  atom_core_mark_t.mli \
 atom_mark_t.mli \
chemicalset_mark_t.mli \

FILES_V_MLI := $(subst mark_t,mark_v,$(FILES_T_MLI))

# concatenate
FILES_MLI:= $(FILES_T_MLI) $(FILES_V_MLI) \
#chemicalset_mark_by_sole_index_production_provider_v.mli \

