NEEDED_DIRS := \
	$(FIGURESET_ENVELOPES_DIR) \
	$(SKELETONSET_ENVELOPES_DIR) \
	$(ELEMENTARYSET_ENVELOPES_DIR) \
	$(PROPERTYSET_CONTAINERS_DIR) \
	$(PROPERTYSET_INTERDOMAINS_DIR) \
  
#	$(LOCALINPUTSET_BUILDER_TREES_DIR) \
