type property_operand_body_envelope = Elementary_envelopee_t.elementary_envelopee list;;

(* generated by ./do_envelope_as_list_t.sh property_operand_body *)
(* using template_envelope_as_list_t.ml *)
(* Done on mardi 14 mars 2017, 15:46:10 (UTC+0100) *)
