type property_operator_fence_tounit_envelope = Elementary_envelopee_t.elementary_envelopee list;;

(* generated by ./do_envelope_as_list_t.sh property_operator_fence_tounit *)
(* using template_envelope_as_list_t.ml *)
(* Done on mardi 14 mars 2017, 15:46:14 (UTC+0100) *)
