NEEDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(LOCALINPUTSET_LEXER_DIR) \
	$(LOCALINPUTSET_PARSER_DIR) \
	$(LOCALINPUTSET_BUILDER_TREES_DIR) \
	$(LOCALINPUTSET_VARIABLES_DIR) \
    