FROM_FILES_V_ML := \
Databox_name_n_database_name_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Db1pointsdata_any_category_by_sole_index_extractor_u_any.ml \
Db1pointsdata_as_context_database_tag_by_unit_provider_u_any.ml \
Db1pointsdata_as_context_databox_tag_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_context_domain_tag_by_unit_provider_u_any.ml \
Db1pointsdata_as_context_sector_tag_by_unit_provider_u_any.ml \
Db1pointsdata_as_context_tag_quatuor_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_bundle_coordinates_symbol_subtree_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_bundle_figure_symbol_subtree_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_cluster_information_symbol_subtree_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_cluster_vertex_symbol_subtree_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_name_vertex_symbol_list_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_record_vertex_symbol_subtree_by_vertex_name_n_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_record_vertex_symbol_subtree_list_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_sequence_float_symbol_subtree_by_vertex_name_n_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_sequence_float_symbol_subtree_list_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_sequence_float_tag_list_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_body_sequence_float_tag_list_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Db1pointsdata_as_set_fence_basic_numerical_float_symbol_list_by_vertex_name_n_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_fence_token_coordinates_kind_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_fence_token_coordinates_units_angle_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_fence_token_coordinates_units_length_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_as_set_fence_token_figure_kind_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_context_database_name_by_unit_provider_u_any.ml \
Db1pointsdata_context_database_tag_by_unit_provider_u_any.ml \
Db1pointsdata_context_databox_name_by_any_sole_index_provider_u_any.ml \
Db1pointsdata_context_databox_sole_index_by_any_sole_index_provider_u_any.ml \
Db1pointsdata_context_databox_symbol_by_any_sole_index_provider_u_any.ml \
Db1pointsdata_context_databox_tag_by_any_sole_index_provider_u_any.ml \
Db1pointsdata_context_databox_tag_by_databox_name_provider_u_any.ml \
Db1pointsdata_context_domain_name_by_unit_provider_u_any.ml \
Db1pointsdata_context_domain_tag_by_unit_provider_u_any.ml \
Db1pointsdata_context_name_trio_by_unit_provider_u_any.ml \
Db1pointsdata_context_sector_name_by_unit_provider_u_any.ml \
Db1pointsdata_context_sector_tag_by_unit_provider_u_any.ml \
Db1pointsdata_context_tag_quadruplet_by_databox_name_provider_u_any.ml \
Db1pointsdata_father_tag_by_db1pointsdata_son_tag_provider_u_any.ml \
Db1pointsdata_set_fence_by_db1pointsdata_tag_provider_u_any.ml \
Db1pointsdata_set_fence_token_coordinates_kind_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_set_fence_token_coordinates_units_angle_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_set_fence_token_coordinates_units_length_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_set_fence_token_figure_kind_symbol_by_databox_name_provider_u_any.ml \
Db1pointsdata_son_tag_list_by_db1pointsdata_father_tag_provider_u_any.ml \
Db1pointsdata_symbol_by_sole_index_provider_u_any.ml \
Db1pointsdata_symbol_subtree_by_databox_name_provider_u_any.ml \
Db1pointsdata_symbol_subtree_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Db1pointsdata_tag_all_list_by_databox_name_provider_u_any.ml \
Db1pointsdata_tag_all_list_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Db1pointsdata_tag_subtree_by_db1pointsdata_tag_provider_u_any.ml \
Db1pointsdata_tag_tree_by_databox_name_provider_u_any.ml \
Db1pointsdata_tag_tree_by_db1pointsdata_context_databox_tag_provider_u_any.ml \
Float_list_by_db1pointsdata_set_body_sequence_float_tag_provider_u_any.ml \
Measure_list_by_db1pointsdata_set_body_sequence_float_tag_provider_u_any.ml \
Units_by_db1pointsdata_set_fence_token_coordinates_units_angle_symbol_provider_u_any.ml \
Units_by_db1pointsdata_set_fence_token_coordinates_units_length_symbol_provider_u_any.ml \
Units_tuple_by_db1pointsdata_set_body_sequence_float_tag_provider_u_any.ml \

FROM_FILES_U_ML := \
Db1pointsdata_as_set_body_cluster_vertex_symbol_subtree_by_databox_name_provider_u_segment_BC.ml \
Db1pointsdata_as_set_body_record_vertex_symbol_subtree_by_vertex_name_n_databox_name_provider_u_segment_BC.ml \
Db1pointsdata_context_databox_tag_by_databox_name_provider_u_Point_a.ml \
Db1pointsdata_context_databox_tag_by_databox_name_provider_u_segment_BC.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
$(FROM_FILES_U_ML) \

