#!/bin/bash

# The sub-directories where we run a configure script.
SUB_DIRECTORIES="generatorset_databases generatorset_formulas generatorset_interfaces generatorset_symbols generatorset_tags generatorset_values "

# The directory where we just configure .depend and .depend-rebuild.
CURRENT_AND_TEST=". unitary_tests"

# created by /code/sources/ocaml_top/setup/utilities/do_configure_local_no_sub_directory.sh > configure_local
