NEEDED_DIRS := \
	$(GENERATORSET_SYMBOLS_DIR) \
	$(GENERATORSET_TAGS_DIR) \
	$(GENERATORSET_DATABASES_DIR) \
	$(GENERATORSET_INTERFACES_DIR) \
	$(GENERATORSET_FORMULAS_DIR) \
	$(GENERATORSET_VALUES_DIR) \
  