INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(LOCALINPUTSET_LEXER_DIR) \
	$(LOCALINPUTSET_LEXICAL_ANALYSIS_DIR) \
	$(LOCALINPUTSET_SYMBOLS_DIR) \
	$(LOCALINPUTSET_PARSER_DIR) \
