FROM_FILES_V_ML := \
Property_container_u_any.ml \
Property_context_container_u_any.ml \
Property_context_domain_container_u_any.ml \
Property_context_inputbase_container_u_any.ml \
Property_context_inputbox_container_u_any.ml \
Property_context_sector_container_u_any.ml \
Property_set_body_command_container_u_any.ml \
Property_set_body_command_debug_container_u_any.ml \
Property_set_body_command_set_container_u_any.ml \
Property_set_body_command_title_container_u_any.ml \
Property_set_body_command_trace_container_u_any.ml \
Property_set_body_container_u_any.ml \
Property_set_body_operand_container_u_any.ml \
Property_set_body_operand_target_calculated_container_u_any.ml \
Property_set_body_operand_target_container_u_any.ml \
Property_set_body_operand_target_created_container_u_any.ml \
Property_set_body_operand_target_measured_container_u_any.ml \
Property_set_body_target_implicit_container_u_any.ml \
Property_set_body_target_implicit_tounit_container_u_any.ml \
Property_set_fence_container_u_any.ml \
Property_set_fence_operand_external_container_u_any.ml \
Property_set_fence_operator_container_u_any.ml \
Property_set_fence_operator_creation_container_u_any.ml \
Property_set_fence_operator_creation_tobasic_container_u_any.ml \
Property_set_fence_operator_creation_toentity_container_u_any.ml \
Property_set_fence_operator_creation_tomeasure_container_u_any.ml \
Property_set_fence_operator_tounit_container_u_any.ml \
Property_set_fence_operator_tounit_print_container_u_any.ml \
Property_set_fence_operator_tounit_write_container_u_any.ml \

FROM_FILES_U_ML := \
Property_operand_target_created_container_u_point_homothety_debug.ml \
Property_operand_target_created_container_u_point_homothety_n_translation_debug.ml \
Property_tag_list_by_input_fullnameoffile_provider_u_coordinate_tuple_print_debug.ml \
Property_target_implicit_unit_container_u_coordinate_tuple_print_debug.ml \
Property_target_implicit_unit_container_u_elementary_body_parameter_tuple_aopef_hes11_print_debug.ml \
Property_target_implicit_unit_container_u_point_homothety_debug.ml \
Property_target_implicit_unit_container_u_point_print_debug.ml \
Property_target_measured_container_u_vector_length_debug.ml \
Property_target_measured_value_u_vector_length_debug.ml \
Property_target_unit_container_u_coordinate_tuple_print_debug.ml \
Property_target_unit_container_u_point_homothety_debug.ml \
Property_target_unit_container_u_point_print_debug.ml \
Property_unit_container_u_coordinate_tuple_print_debug.ml \
Son_operator_tag_list_by_father_operator_tag_provider_u_coordinate_tuple_print_debug.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
$(FROM_FILES_U_ML) \

