INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(INPUTSET_COMMON_DIR) \
	$(INPUTSET_LEXER_DIR) \
	$(INPUTSET_SYMBOLS_DIR) \
	$(INPUTSET_TAGS_DIR) \
	$(INPUTSET_PARSER_DIR) \
	$(INPUTSET_BUILDER_TREES_DIR) \
	$(PROPERTYSET_SYMBOLS_DIR) \
	$(PROPERTYSET_TAGS_DIR) \
	$(PROPERTYSET_BUILDER_TREES_DIR) \
	$(PROPERTYSET_CONTAINERS_DIR) \
