FILES_T_MLI :=  \
Singlet_t.mli \
Either_or_t.mli \
Multiplicity_t.mli \
Doublet_t.mli \
Pair_t.mli \
Uno_t.mli \
Duo_t.mli \
Triplet_t.mli \
Trio_t.mli \
Quadruplet_t.mli \
Quintuplet_t.mli \
Quintet_t.mli \
Quatuor_t.mli \
Sequential_index_t.mli \
List_t.mli \
Doublet_list_t.mli \
Triplet_list_t.mli \
Quadruplet_list_t.mli \
Duo_list_t.mli \
Trio_list_t.mli \
Tie_t.mli \
Bond_t.mli \
Tree_t.mli \
Tree_edge_t.mli \
Tree_bunch_t.mli \
Doublet_tree_t.mli \
Indexed_tree_t.mli \
Bridge_t.mli \
Twig_t.mli \
Brunk_t.mli \
Chunk_t.mli \
Tree_leafed_t.mli \
Tree_leafed_bunch_t.mli \
Capped_tree_t.mli \
Tree_leafed_capped_t.mli \
Indexed_tree_leafed_t.mli \
Capped_indexed_tree_leafed_t.mli \
Tree_footed_capped_t.mli \
Capped_list_t.mli \
Booted_list_t.mli \
Booted_twig_t.mli \
Capped_booted_list_t.mli \
Capped_booted_twig_t.mli \
Capped_doublet_list_t.mli \
Doubletcapped_doublet_list_t.mli \
Cappedoption_list_t.mli \
Cappedoption_booted_list_t.mli \
Marker_t.mli \
Trail_t.mli \
Sextuplet_t.mli \
Sextuor_t.mli \
Septuplet_t.mli \
Octuplet_t.mli \
Nonuplet_t.mli \
Decuplet_t.mli \
Repeated_list_t.mli \
Booted_repeated_list_t.mli \
Axe_notation_t.mli \
Vsepr_index_t.mli \
Entity_index_t.mli \
Sole_index_t.mli \
Sole_indexed_tree_t.mli \
Tag_t.mli \
Mark_t.mli \
Extended_t.mli \
Extended_by_t.mli \
Singlet_formula_t.mli \
List_doublet_t.mli \
Float_tag_t.mli \
Float_positive_tag_t.mli \
String_tag_t.mli \

FILES_V_MLI:=$(subst _t.mli,_v.mli,$(FILES_T_MLI))

FILES_MLI:= \
$(FILES_T_MLI) \
$(FILES_V_MLI) \
Stack_v.mli \
Version_v.mli \
Tuple_t.mli \
Tuple_v.mli \
Tuple_list_t.mli \
Tuple_list_v.mli \
Float_tuple_t.mli \
Float_tuple_v.mli \
Float_list_t.mli \
Float_list_v.mli \
Float_tuple_list_t.mli \
Float_tuple_list_v.mli \
Tools_parser_v.mli \
Option_v.mli \
 