# --- basic ---

# fence_bud

do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_boolean readee_basic_boolean
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_float   readee_basic_float
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_integer readee_basic_integer
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_basic_string  readee_basic_string

# fence_trunc

do_belt_from_symbol_this_t.sh            elementary_fence_basic

# --- color ---

# fence_trunc
do_belt_as_uno_fence_bud_t.sh elementary_fence_color 

# --- units ---

# fence_bud

do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_action  measure_actual_action
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_angle   measure_actual_angle
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_charge  measure_actual_charge
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_energy  measure_actual_energy
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_length  measure_actual_length
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_mass    measure_actual_mass
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_none    measure_actual_none
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_temperature measure_actual_temperature
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_actual_time    measure_actual_time

do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_canonical_classical  measure_canonical_classical
do_belt_as_doublet_fence_bud_2beltee_t.sh elementary_fence_units_canonical_quantum  measure_canonical_quantum

# fence_trunc

do_belt_from_symbol_this_t.sh elementary_fence_units_canonical
do_belt_from_symbol_this_t.sh elementary_fence_units_actual
do_belt_from_symbol_this_t.sh elementary_fence_units

# --- coordinate ---

# border_bud coordinate

do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_homogeneous_cartesian_x measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_homogeneous_cartesian_y measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_homogeneous_cartesian_z measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_homogeneous_linear_x measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_homogeneous_planar_x measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_homogeneous_planar_y measure_actual_length

do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_phi measure_actual_angle
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_rho measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_cylindrical_zed measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_polar_rho measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_polar_theta measure_actual_angle
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_spherical_phi measure_actual_angle
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_spherical_rho measure_actual_length
do_belt_as_doublet_border_bud_2beltee_t.sh elementary_border_coordinate_heterogeneous_spherical_theta measure_actual_angle

# border trunc coordinate  

do_belt_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_cartesian 
do_belt_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_linear
do_belt_from_symbol_this_t.sh elementary_border_coordinate_homogeneous_planar

do_belt_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_cylindrical
do_belt_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_polar
do_belt_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous_spherical

do_belt_from_symbol_this_t.sh elementary_border_coordinate_heterogeneous
do_belt_from_symbol_this_t.sh elementary_border_coordinate_homogeneous
do_belt_from_symbol_this_t.sh elementary_border_coordinate

# border_bud

do_belt_as_doublet_border_bud_2beltee_t.sh  elementary_border_parameter_aopef_coefficient  measure_actual_length

do_belt_as_doublet_border_bud_2beltee_t.sh  elementary_border_parameter_aopef_exponent     measure_actual_length

do_belt_as_doublet_border_bud_2beltee_t.sh  elementary_border_parameter_ecppef_coefficient measure_actual_length

do_belt_as_doublet_border_bud_2beltee_t.sh  elementary_border_parameter_ecppef_exponent    measure_actual_length

do_belt_from_symbol_this_t.sh elementary_border_parameter_aopef
do_belt_from_symbol_this_t.sh elementary_border_parameter_ecppef
do_belt_from_symbol_this_t.sh elementary_border_parameter

do_belt_from_symbol_this_t.sh elementary_border
do_belt_from_symbol_this_t.sh elementary_fence

echo " "
echo " mv Elementary_*.ml ../"
echo " "

exit


