#!/bin/bash

this=$1
ttt=$2
sibling_1=$3
sib_1=$4
sibling_2=$5
sib_2=$6
sibling_3=$7
sib_3=$8
sibling_4=$9
sib_4=${10}
sibling_5=${11}
sib_5=${12}
sibling_6=${13}
sib_6=${14}
sibling_7=${15}
sib_7=${16}
sibling_8=${17}
sib_8=${18}
sibling_9=${19}
sib_9=${20}

if [ "${sib_9}" == "" ] 
then 
    echo "$0 : sib_9 (20th argument) is missing"
    exit
fi

cnn=$ttt
conee_1=$this
Conee_1=`capitalize_first.sh ${conee_1}`


dat=`date`
category=`echo $0 |cut -d"_" -f2`

gresuf=`echo "$0"| grep -c _v.sh`
if [ "$gresuf" == "1" ]
then suffix="v" 
else suffix="t"
fi

mainb=`echo ${buldr} | cut -d"_" -f1` 
maint=`echo ${this} | cut -d"_" -f1` 

case ${maint} in
    chemical ) mmm="che";;
    database ) mmm="dba";;
    elementary ) mmm="ele";;
    figure ) mmm="fig";;
    input ) mmm="inp";;
    operator ) mmm="ope";;
    primitive ) mmm="pri";;
    prototype ) mmm="prt";;
    *) echo "";echo -n "Error: in script $0 : unknown maint >${maint}<";echo"";exit;;
esac
MMM=`echo $mmm | tr a-z A-Z`

Mainb=`capitalize_first.sh ${mainb}`
Maint=`capitalize_first.sh ${maint}`

This=`capitalize_first.sh ${this}`
Sibling_1=`capitalize_first.sh ${sibling_1}`
Sibling_2=`capitalize_first.sh ${sibling_2}`
Sibling_3=`capitalize_first.sh ${sibling_3}`
Sibling_4=`capitalize_first.sh ${sibling_4}`
Sibling_5=`capitalize_first.sh ${sibling_5}`
Sibling_6=`capitalize_first.sh ${sibling_6}`
Sibling_7=`capitalize_first.sh ${sibling_7}`
Sibling_8=`capitalize_first.sh ${sibling_8}`
Sibling_9=`capitalize_first.sh ${sibling_9}`
Buldr=`capitalize_first.sh ${buldr}`
Deepfn=`capitalize_first.sh ${deepfn}`
Fnc=`capitalize_first.sh ${fnc}`
Clsur=`capitalize_first.sh ${clsur}`
Datstr=`capitalize_first.sh ${datstr}`
Dta=`capitalize_first.sh ${dta}`

template=`echo "$0" | sed -e 's/do_/template_/' -e 's/\.sh/.ml/'`

module="${this}_${category}_${suffix}"
Module=`capitalize_first.sh ${module}`
file="${module}.ml"
File=`capitalize_first.sh ${file}`
supplement="supplement_${file}"

if [ ! -f ${template} ] 
then 
    echo ""
    echo "file ${template} is missing"
    echo ""
    exit
fi

if [ ! -f ${supplement} ] 
then 
    echo ""
    echo " touch ${supplement}"
    echo ""
    exit
fi

sed -e "s/this/$this/g" -e "s/ttt/$ttt/g" -e "s/This/$This/g" \
    -e "s/mainb/${mainb}/g" -e "s/Mainb/${Mainb}/g" \
    -e "s/maint/${maint}/g" -e "s/Maint/${Maint}/g" -e "s/mmm/${mmm}/g" -e "s/MMM/${MMM}/g" \
    -e "s/buldr/$buldr/g" -e "s/Buldr/$Buldr/g" -e "s/bbb/$bbb/g" \
    -e "s/clsur/$clsur/g" -e "s/Clsur/$Clsur/g" -e "s/ccc/$ccc/g" \
    -e "s/conee_1/$conee_1/g" -e "s/Conee_1/$Conee_1/g" -e "s/cnn/$cnn/g" \
    -e "s/sibling_1/${sibling_1}/g" -e "s/Sibling_1/${Sibling_1}/g" -e "s/sib_1/${sib_1}/g" \
    -e "s/sibling_2/${sibling_2}/g" -e "s/Sibling_2/${Sibling_2}/g" -e "s/sib_2/${sib_2}/g" \
    -e "s/sibling_3/${sibling_3}/g" -e "s/Sibling_3/${Sibling_3}/g" -e "s/sib_3/${sib_3}/g" \
    -e "s/sibling_4/${sibling_4}/g" -e "s/Sibling_4/${Sibling_4}/g" -e "s/sib_4/${sib_4}/g" \
    -e "s/sibling_5/${sibling_5}/g" -e "s/Sibling_5/${Sibling_5}/g" -e "s/sib_5/${sib_5}/g" \
    -e "s/sibling_6/${sibling_6}/g" -e "s/Sibling_6/${Sibling_6}/g" -e "s/sib_6/${sib_6}/g" \
    -e "s/sibling_7/${sibling_7}/g" -e "s/Sibling_7/${Sibling_7}/g" -e "s/sib_7/${sib_7}/g" \
    -e "s/sibling_8/${sibling_8}/g" -e "s/Sibling_8/${Sibling_8}/g" -e "s/sib_8/${sib_8}/g" \
    -e "s/sibling_9/${sibling_9}/g" -e "s/Sibling_9/${Sibling_9}/g" -e "s/sib_9/${sib_9}/g" \
    -e "s/datstr/$datstr/g" -e "s/Datstr/$Datstr/g" \
    -e "s/fnc/$fnc/g" -e "s/Fnc/$Fnc/g" \
    -e "s/deepfn/$deepfn/g" -e "s/Deepfn/$Deepfn/g" \
    -e "s/dta/$dta/g" -e "s/Dta/$Dta/g" \
    -e "s/bui_1/${bui_1}/g" \
    -e "s/bui_2/${bui_2}/g" \
    -e "s/bui_3/${bui_3}/g" \
    -e "s/bui_6/${bui_4}/g" \
    -e "s/iii_1/${iii_1}/g" \
    -e "s/iii_2/${iii_2}/g" \
    -e "s/iii_3/${iii_3}/g" \
    -e "s/iii_4/${iii_4}/g" \
     ${template} > ${File}

if [ -s ${supplement} ] 
then 
    cat ${supplement} >> ${File}
else
    echo "supplement ${supplement} is empty"
fi

echo "" >> ${File}
echo "(* generated by $0 ${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9} ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} *)" >> ${File}
echo "(* using ${template} *)" >> ${File}

if [ -s ${supplement} ] 
then
    echo "(* adding ${supplement} *)" >> ${File} 
fi

echo "(* Done on ${dat} *)" >> ${File}

echo " cat ${File}"
echo " mv ${File} ../"
echo " make $Module.cmo"
echo "" >> ${File}


