#!/bin/bash

this=$1
This=`capitalize_first.sh ${this}`

dat=`date`
category=`echo $0 |cut -d"_" -f2`

gresuf=`echo "$0"| grep -c _v.sh`
if [ "$gresuf" == "1" ]
then suffix="v" 
else suffix="t"
fi

module="${this}_${category}_${suffix}"
Module=`capitalize_first.sh ${module}`
file="${module}.ml"
File=`capitalize_first.sh ${file}`
supplement="supplement_${file}"

case ${category} in
    container ) oldcat="formulas";;
    envelope ) oldcat="values";;
    *) oldcat=${category}
esac

SYMBOLS_DIR=`pwd | sed -e "s#_${oldcat}/generator#_symbols#"`
if [ ! -e ${SYMBOLS_DIR} ]
then
    echo "$0 : Error : Symbols directory must exist"
    echo ""
    exit
fi

file_symbol="${this}_symbol_${suffix}.ml"
File_symbol=`capitalize_first.sh ${file_symbol}`
template=${SYMBOLS_DIR}/${File_symbol}

if [ ! -f ${template} ] 
then 
    echo "file ${template} is missing"
    exit
fi

sed -e "s/symbol/${category}/g" ${template} > ${File}

if [ -f ${supplement} ] 
then 
    cat ${supplement} >> ${File} 
fi

echo "" >> ${File}
echo "(* generated by $0 ${this} *)" >> ${File}
echo "(* using ${template} *)" >> ${File}

if [ -f ${supplement} ] 
then
    echo "(* adding ${supplement} *)" >> ${File} 
fi

echo "(* Done on ${dat} *)" >> ${File}

echo " cat ${This}_${category}_${suffix}.ml"
echo " mv ${This}_${category}_${suffix}.ml ../"
echo " make ${This}_${category}_${suffix}.cmo"