FROM_FILES_V_ML := \
Coordinate_envelopee_u_any.ml \
Coordinate_envelope_u_any.ml \
Measure_by_coordinate_set_fence_tag_provider_u_any.ml \
Measure_list_by_coordinate_set_body_tuple_tag_provider_u_any.ml \
Readee_by_coordinate_set_fence_tag_provider_u_any.ml \
Readee_list_by_coordinate_set_body_tuple_tag_provider_u_any.ml \

FROM_FILES_U_ML := \
Coordinate_envelope_u_point_a_rho.ml \
Coordinate_envelope_u_point_a_tuple.ml \
Coordinate_envelope_u_segment_bc.ml \
Coordinate_set_fence_heterogeneous_spherical_rho_envelope_u_point_a.ml \
Coordinate_set_fence_heterogeneous_spherical_rho_envelope_u_segment_s.ml \
Elementary_body_coordinate_tuple_heterogeneous_envelope_u_point_a.ml \
Elementary_body_coordinate_tuple_heterogeneous_envelope_u_segment_s.ml \
Elementary_border_coordinate_heterogeneous_envelope_u_segment_s.ml \
Elementary_border_coordinate_heterogeneous_spherical_phi_envelope_u_point_a.ml \
Elementary_border_coordinate_heterogeneous_spherical_phi_envelope_u_segment_s.ml \
Elementary_coordinate_tuple_heterogeneous_envelope_u_point_a.ml \
Nwchemdata_set_body_node_aoset_numericalvalues_tag_by_coordinate_set_body_tuple_heterogeneous_tag_provider_u_point_a.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
$(FROM_FILES_U_ML) \

