(** {3 Elementary_body_coordinate_tuple_heterogeneous_symbol_t} *)


(** {6 Typing_for_symbol} *)

type elementary_body_coordinate_tuple_heterogeneous_symbol =
  | Elementary_body_coordinate_tuple_heterogeneous_cylindrical_symbol of Elementary_body_coordinate_tuple_heterogeneous_cylindrical_symbol_t.elementary_body_coordinate_tuple_heterogeneous_cylindrical_symbol
  | Elementary_body_coordinate_tuple_heterogeneous_polar_symbol of Elementary_body_coordinate_tuple_heterogeneous_polar_symbol_t.elementary_body_coordinate_tuple_heterogeneous_polar_symbol
  | Elementary_body_coordinate_tuple_heterogeneous_spherical_symbol of Elementary_body_coordinate_tuple_heterogeneous_spherical_symbol_t.elementary_body_coordinate_tuple_heterogeneous_spherical_symbol
;;


(** Elementary_body_coordinate_tuple_heterogeneous_symbol_t at 11:52:31 on 9 May 2016. created by version v2.4 of generator *)



