(** {3 Elementary_border_coordinate_heterogeneous_spherical_symbol_t} *)


(** {6 Typing_for_symbol} *)

type elementary_border_coordinate_heterogeneous_spherical_symbol =
  | Elementary_border_coordinate_heterogeneous_spherical_rho_symbol of Elementary_border_coordinate_heterogeneous_spherical_rho_symbol_t.elementary_border_coordinate_heterogeneous_spherical_rho_symbol
  | Elementary_border_coordinate_heterogeneous_spherical_phi_symbol of Elementary_border_coordinate_heterogeneous_spherical_phi_symbol_t.elementary_border_coordinate_heterogeneous_spherical_phi_symbol
  | Elementary_border_coordinate_heterogeneous_spherical_theta_symbol of Elementary_border_coordinate_heterogeneous_spherical_theta_symbol_t.elementary_border_coordinate_heterogeneous_spherical_theta_symbol
;;


(** Elementary_border_coordinate_heterogeneous_spherical_symbol_t at 11:52:44 on 9 May 2016. created by version v2.4 of generator *)



