ELEMENTARY_T_MLI :=  \
     Elementary_fence_units_canonical_quantum_symbol_t.mli \
     Elementary_fence_units_canonical_classical_symbol_t.mli \
    Elementary_fence_units_canonical_symbol_t.mli \
     Elementary_fence_units_actual_none_symbol_t.mli \
     Elementary_fence_units_actual_time_symbol_t.mli \
     Elementary_fence_units_actual_temperature_symbol_t.mli \
     Elementary_fence_units_actual_mass_symbol_t.mli \
     Elementary_fence_units_actual_length_symbol_t.mli \
     Elementary_fence_units_actual_energy_symbol_t.mli \
     Elementary_fence_units_actual_charge_symbol_t.mli \
     Elementary_fence_units_actual_angle_symbol_t.mli \
     Elementary_fence_units_actual_action_symbol_t.mli \
    Elementary_fence_units_actual_symbol_t.mli \
   Elementary_fence_units_symbol_t.mli \
   Elementary_fence_color_symbol_t.mli \
    Elementary_fence_basic_string_symbol_t.mli \
    Elementary_fence_basic_integer_symbol_t.mli \
    Elementary_fence_basic_float_symbol_t.mli \
    Elementary_fence_basic_boolean_symbol_t.mli \
   Elementary_fence_basic_symbol_t.mli \
  Elementary_fence_symbol_t.mli \
     Elementary_border_parameter_ecppef_exponent_symbol_t.mli \
     Elementary_border_parameter_ecppef_coefficient_symbol_t.mli \
    Elementary_border_parameter_ecppef_symbol_t.mli \
     Elementary_border_parameter_aopef_exponent_symbol_t.mli \
     Elementary_border_parameter_aopef_coefficient_symbol_t.mli \
    Elementary_border_parameter_aopef_symbol_t.mli \
   Elementary_border_parameter_symbol_t.mli \
      Elementary_border_coordinate_homogeneous_planar_y_symbol_t.mli \
      Elementary_border_coordinate_homogeneous_planar_x_symbol_t.mli \
     Elementary_border_coordinate_homogeneous_planar_symbol_t.mli \
      Elementary_border_coordinate_homogeneous_linear_x_symbol_t.mli \
     Elementary_border_coordinate_homogeneous_linear_symbol_t.mli \
      Elementary_border_coordinate_homogeneous_cartesian_z_symbol_t.mli \
      Elementary_border_coordinate_homogeneous_cartesian_y_symbol_t.mli \
      Elementary_border_coordinate_homogeneous_cartesian_x_symbol_t.mli \
     Elementary_border_coordinate_homogeneous_cartesian_symbol_t.mli \
    Elementary_border_coordinate_homogeneous_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_spherical_theta_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_spherical_phi_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_spherical_rho_symbol_t.mli \
     Elementary_border_coordinate_heterogeneous_spherical_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_polar_theta_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_polar_rho_symbol_t.mli \
     Elementary_border_coordinate_heterogeneous_polar_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_zed_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_phi_symbol_t.mli \
      Elementary_border_coordinate_heterogeneous_cylindrical_rho_symbol_t.mli \
     Elementary_border_coordinate_heterogeneous_cylindrical_symbol_t.mli \
    Elementary_border_coordinate_heterogeneous_symbol_t.mli \
   Elementary_border_coordinate_symbol_t.mli \
  Elementary_border_symbol_t.mli \
   Elementary_context_domain_symbol_t.mli \
    Elementary_context_databox_figuredata_symbol_t.mli \
    Elementary_context_databox_skeletondata_symbol_t.mli \
   Elementary_context_databox_symbol_t.mli \
   Elementary_context_database_symbol_t.mli \
  Elementary_context_symbol_t.mli \
    Elementary_body_parameter_tuple_ecppef_symbol_t.mli \
    Elementary_body_parameter_tuple_aopef_symbol_t.mli \
   Elementary_body_parameter_tuple_symbol_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_planar_symbol_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_linear_symbol_t.mli \
     Elementary_body_coordinate_tuple_homogeneous_cartesian_symbol_t.mli \
    Elementary_body_coordinate_tuple_homogeneous_symbol_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_spherical_symbol_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_polar_symbol_t.mli \
     Elementary_body_coordinate_tuple_heterogeneous_cylindrical_symbol_t.mli \
    Elementary_body_coordinate_tuple_heterogeneous_symbol_t.mli \
   Elementary_body_coordinate_tuple_symbol_t.mli \
  Elementary_body_symbol_t.mli \
 Elementary_symbol_t.mli \
