type parameter_context_databox_container = Parameter_set_body_tuple_tag_t.parameter_set_body_tuple_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh parameter_context_databox parameter_set_body_tuple *)
(* using template_container_as_list_context_bud_1containee_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:46 (UTC+0100) *)

