(** {3 Parameter_set_fence_container_t} *)


(** {6 Typing_for_container} *)

type parameter_set_fence_container =
  | Parameter_set_fence_aopef_container of Parameter_set_fence_aopef_container_t.parameter_set_fence_aopef_container
  | Parameter_set_fence_ecppef_container of Parameter_set_fence_ecppef_container_t.parameter_set_fence_ecppef_container
;;


(** Parameter_set_fence_container_t at 16:28:53 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh parameter_set_fence *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/parameterset/parameterset_symbols/Parameter_set_fence_symbol_t.ml *)
(* adding supplement_parameter_set_fence_container_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:47 (UTC+0100) *)
