type parameter_context_database_container = Parameter_context_databox_tag_t.parameter_context_databox_tag list;;

(* generated by ./do_container_as_list_context_bud_1containee_t.sh parameter_context_database parameter_context_databox *)
(* using template_container_as_list_context_bud_1containee_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:46 (UTC+0100) *)

