type parameter_set_body_tuple_aopef_container = (Parameter_set_fence_aopef_exponent_tag_t.parameter_set_fence_aopef_exponent_tag, Parameter_set_fence_aopef_coefficient_tag_t.parameter_set_fence_aopef_coefficient_tag) Doublet_t.doublet;;

(* generated by ./do_container_as_doublet_body_bud_2containee_t.sh parameter_set_body_tuple_aopef parameter_set_fence_aopef_exponent parameter_set_fence_aopef_coefficient *)
(* using template_container_as_doublet_body_bud_2containee_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:46 (UTC+0100) *)

