(** {3 Parameter_set_body_container_t} *)


(** {6 Typing_for_container} *)

type parameter_set_body_container =
  | Parameter_set_body_tuple_container of Parameter_set_body_tuple_container_t.parameter_set_body_tuple_container
;;


(** Parameter_set_body_container_t at 16:28:52 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh parameter_set_body *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/parameterset/parameterset_symbols/Parameter_set_body_symbol_t.ml *)
(* adding supplement_parameter_set_body_container_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:46 (UTC+0100) *)
