(** {3 Parameter_context_container_t} *)


(** {6 Typing_for_container} *)

type parameter_context_container =
  | Parameter_context_database_container of Parameter_context_database_container_t.parameter_context_database_container
  | Parameter_context_databox_container of Parameter_context_databox_container_t.parameter_context_databox_container
  | Parameter_context_domain_container of Parameter_context_domain_container_t.parameter_context_domain_container
  | Parameter_context_sector_container of Parameter_context_sector_container_t.parameter_context_sector_container
;;


(** Parameter_context_container_t at 16:28:52 on 2 Dec 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh parameter_context *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/parameterset/parameterset_symbols/Parameter_context_symbol_t.ml *)
(* adding supplement_parameter_context_container_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:46 (UTC+0100) *)
