type parameter_set_fence_aopef_exponent_container = Parameter_set_fence_aopef_exponent_tag_t.parameter_set_fence_aopef_exponent_tag Uno_t.uno;;

(* generated by ./do_container_as_uno_fence_bud_1containee_t.sh parameter_set_fence_aopef_exponent  *)
(* using template_container_as_uno_fence_bud_1containee_t.ml *)
(* Done on samedi 3 décembre 2016, 10:13:45 (UTC+0100) *)

