(** {3 Parameter_set_fence_ecppef_exponent_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FPAR:Parameter_set_fence_ecppef_exponent_container_v";
   "Needs : ";
   "Needed-by: ";
   "Definition : a Building is the same Datastructure as a Container but filled with Builders"; 
   "Definition : a Containee is a Builder expressed in the lowest subtype compatible with the Datastructure of the Container";
   "Definition : a Container is the Datastructure of the Containee of an Entity";
   "Definition : a Containee is an element of the Datastructure of the Container of an Entity";
   "Definition : a fence Container contains an Uno of its Tag";
   "Definition : a non-fence Bud Container is a Datastructure of Containee Tag";
   "Definition : a Bud is a type with only one constructor of string";
   "What-is-it : it is a container of a Fence Bud type i.e. itself Tag Uno";
   "Author : François Colonna 30 novembre 2016 at 18:21:24+01:00";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name con_pee =
  Uno_v.name 
    Parameter_set_fence_ecppef_exponent_tag_v.name
    con_pee
;;

let string_off con_pee =
  Uno_v.name 
    Parameter_set_fence_ecppef_exponent_tag_v.string_off
    con_pee
;;

let longname con_pee =
  Uno_v.name 
    Parameter_set_fence_ecppef_exponent_tag_v.longname
    con_pee
;;

let fullname con_pee =
  Uno_v.name 
    Parameter_set_fence_ecppef_exponent_tag_v.fullname
    con_pee
;;

(** {6 Coercing Up Parameter_set_fence_ecppef_exponent Tag} *)

let coerce_up_tag tag_pee =
  Parameter_set_fence_ecppef_exponent_tag_v.parameter_tag_of_parameter_set_fence_ecppef_exponent_tag
    tag_pee
;;

(** {6 Coercing Down Parameter Tag to Parameter_set_fence_ecppef_exponent Tag} *)

let coerce_down_tag tag_par =
  Parameter_set_fence_ecppef_exponent_tag_v.parameter_set_fence_ecppef_exponent_tag_off_parameter_tag
    tag_par
;;

(** {6 Builder Tag list : itself list for a fence entity} *)

let builder_tag_list_of_tag tag_pee =
  let tag_par = coerce_up_tag tag_pee in
  [tag_par]
;;

(** {6 Builder Tag Datastructure} *)

let builder_tag_uno_of_tag tag_pee =
  let tag_par = coerce_up_tag tag_pee in
  Uno_v.make tag_par
;;

(** {6 Builder Tag tuple} *)

let builder_tag_tuple_of_tag tag_pee =
  let tag_bui_u = builder_tag_uno_of_tag tag_pee in
  Tuple_v.tuple_of_uno tag_bui_u
;;

(** {6 Building as Builder Tag uno} *)

let building_of_tag tag_pee =
  builder_tag_uno_of_tag tag_pee
;;

(** {6 Coercing Up Containee Tag} *)

let builder_tag_of_containee_tag tag_con =
  coerce_up_tag tag_con
;;

(** {6 Coercing Down Containee} *)

let containee_tag_off_builder_tag tag_par =
  Tag_v.map_entity
    Parameter_symbol_v.parameter_set_fence_ecppef_exponent_symbol_off_parameter_symbol
    tag_par
;;

(** {6 Container_of_tag : Containee Datastructure} *)

let container_of_tag tag_pee =
  let bug = building_of_tag tag_pee in
  Uno_v.map (* Coerce Down *)
    containee_tag_off_builder_tag
    bug
;;

(** {6 Coercing Down Builder Tag to Containee Tag} *)

let containee_tag_off_builder_tag tag_bui =
  coerce_down_tag tag_bui
;;

(** {6 Containee Tag Datastructures} *)

let containee_tag_uno_of_tag tag_pee =
  container_of_tag tag_pee
;;

let containee_tag_tuple_of_tag tag_pee =
  let tag_cne_u = containee_tag_uno_of_tag tag_pee in
  Tuple_v.tuple_of_uno tag_cne_u
;;

(** {6 Fence *)

let fence_as_list_of_tag tag_pee =
  let tag_par = coerce_up_tag tag_pee in
  [tag_par]
;;

let fence_as_uno_of_tag tag_pee =
  let fen_pee = fence_as_list_of_tag tag_pee in
  Uno_v.uno_of_list fen_pee
;;

let fence_as_tuple_of_tag tag_pee =
  let fen_l = fence_as_list_of_tag tag_pee in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_pee =
  let fen_l = fence_as_list_of_tag tag_pee in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_uno_fence_bud_1containee_v.sh parameter_set_fence_ecppef_exponent pee *)
(* using template_container_as_uno_fence_bud_1containee_v.ml *)
(* Done on mercredi 14 décembre 2016, 16:07:04 (UTC+0100) *)

