(** {3 Parameter_container_v} *)

(** {6 Documenting_for_container} *)

let documentation () = 
  [
   "Current : FPAR:Parameter_container_v";
   "Needs : FPAR:Parameter_set_fence_tag_v";
   "Needs : FPAR:Parameter_context_container_v";
   "Needs : FPAR:Parameter_set_container_v";
   "Needs : BPAR:Parameter_fence_by_parameter_tag_provider_v";
   "Needed-by: ";
   "What-is-it : Up_coercion of Container type as Symbol type up_coercion";
   "What-is-it : it is a Trunc container of Context sub-Types and thus a List of its Parameter_set_fence Tag";
 ]
;;

let nam_mod = Management_v.current_module_name (documentation ());;

(** {6 Naming_for_container} *)

let name = function
  | Parameter_container_t.Parameter_context_container con_pco ->
      (Parameter_context_container_v.name con_pco)
        
  | Parameter_container_t.Parameter_set_container con_pse ->
      (Parameter_set_container_v.name con_pse)
;;

let string_off = function
  | Parameter_container_t.Parameter_context_container con_pco ->
      (Parameter_context_container_v.string_off con_pco)
        
  | Parameter_container_t.Parameter_set_container con_pse ->
      (Parameter_set_container_v.string_off con_pse)
;;

let longname = function
  | Parameter_container_t.Parameter_context_container con_pco ->
      (Parameter_context_container_v.longname con_pco)
        
  | Parameter_container_t.Parameter_set_container con_pse ->
      (Parameter_set_container_v.longname con_pse)
;;

let fullname = function
  | Parameter_container_t.Parameter_context_container con_pco ->
      (Parameter_context_container_v.fullname con_pco)
        
  | Parameter_container_t.Parameter_set_container con_pse ->
      (Parameter_set_container_v.fullname con_pse)
;;

(** {6 Coercing Tag} *)

(** {9 Coercing Up Tag} *)

let coerce_up_tag tag_par =
    tag_par
;;

(** {9 Coercing Down Builder to Containee} *)

let containee_up_tag_off_builder_tag tag_par =
    tag_par
;;

(** {9 Coercing Up Containee_up to Builder} *)

let builder_tag_of_containee_up_tag tag_cnu =
    tag_cnu
;;

(** {6 Builders} *)

(** {9 Builder Tag list} *)

let builder_tag_list_of_tag tag_par =
  let (sym_par, soi_par) = tag_par in
  match sym_par with
  | Parameter_symbol_t.Parameter_context_symbol sym_pco ->
      let tag_pco = Tag_v.make sym_pco soi_par in
      Parameter_context_container_v.builder_tag_list_of_tag tag_pco

  | Parameter_symbol_t.Parameter_set_symbol sym_pse ->
      let tag_pse = Tag_v.make sym_pse soi_par in
      Parameter_set_container_v.builder_tag_list_of_tag tag_pse
;;

(** {9 Builder Tag Tuple} *)

let builder_tag_tuple_of_tag tag_par =
  let tag_bui_l = builder_tag_list_of_tag tag_par in
  Tuple_v.tuple_of_list tag_bui_l
;;

(** {9 Building as Builder Tag tuple} *)

let building_of_tag tag_par =
  builder_tag_list_of_tag tag_par
;;

(** {6 Container} *)

let containee_up_tag_list tag_par =
  let tag_bui_l = builder_tag_list_of_tag tag_par in
  List.map containee_up_tag_off_builder_tag tag_bui_l
;;

(** {6 Fence *)

let fence_as_list_of_tag tag_par =
  let tag_par = coerce_up_tag tag_par in
  Parameter_fence_by_parameter_tag_provider_v.provide tag_par
;;

let fence_as_tuple_of_tag tag_par =
  let fen_l = fence_as_list_of_tag tag_par in
  Tuple_v.tuple_of_list fen_l
;;

let fence_as_tuple_list_of_tag tag_par =
  let fen_l = fence_as_list_of_tag tag_par in
  Tuple_list_v.make fen_l
;;

(* generated by ./do_container_as_list_top_trunc_2sibling_1containee_v.sh parameter par parameter_context pco parameter_set pse parameter_set_fence *)
(* using template_container_as_list_top_trunc_2sibling_1containee_v.ml *)
(* Done on mercredi 14 décembre 2016, 16:07:06 (UTC+0100) *)

