(** {3 Parameter_body_container_t} *)


(** {6 Typing_for_container} *)

type parameter_body_container =
  | Parameter_body_tuple_container of Parameter_body_tuple_container_t.parameter_body_tuple_container
;;


(** Parameter_body_container_t at 8:49:50 on 24 Nov 2016. created by version v2.4 of generator *)




(* generated by ./do_container_from_symbol_this_t.sh parameter_body *)
(* using /home/colonna/sources/ocaml_top/setup/frames/internalsector/parameterset/parameterset_symbols/Parameter_body_symbol_t.ml *)
(* adding supplement_parameter_body_container_t.ml *)
(* Done on samedi 3 décembre 2016, 09:48:02 (UTC+0100) *)
