UNITARY_TESTS_FILES_ML := \
Nwchemdata_lexer_lexical_analysis_u_try_ecp.ml \
Nwchemdata_lexer_lexical_analysis_u_any.ml \
# Nwchemdata_lexer_lexical_analysis_u_LANL2DZ_debug.ml \
# Nwchemdata_lexer_lexical_analysis_u_6_31GSS_debug.ml \
# Nwchemdata_lexer_symbol_reverse_list_by_database_fullnameoffile_provider_u_LANL2DZ_debug.ml \
 