REGISTERS_V_MLI := \
Basicname_databox_n_basicname_database_by_skeleton_context_databox_tag_register_v.mli \
Parameter_set_body_tuple_string_off_by_skeleton_set_fence_tag_register_v.mli \
Skeleton_bridge_by_skeleton_set_fence_tag_register_v.mli \
Skeleton_creation_module_name_by_sole_index_register_v.mli \
Skeleton_fence_by_skeleton_tag_register_v.mli \
Skeleton_set_fence_tag_list_by_skeleton_tag_register_v.mli \
Skeleton_son_tag_list_by_skeleton_father_tag_register_v.mli \
Skeleton_symbol_by_sole_index_register_v.mli \
Skeleton_tag_all_list_by_basicname_databox_n_basicname_database_register_v.mli \
Skeleton_tag_all_list_by_skeleton_context_databox_tag_register_v.mli \
Skeleton_tag_subtree_by_skeleton_tag_register_v.mli \
Skeleton_tag_tree_by_basicname_databox_n_basicname_database_register_v.mli \
Skeleton_tag_tree_by_skeleton_context_databox_tag_register_v.mli \
  
CONTEXT_NAME_BY_UNIT_V_MLI := \
Skeleton_basicname_sector_by_unit_provider_v.mli \
Skeleton_basicname_domain_by_unit_provider_v.mli \
 
CONTEXT_TAG_BY_UNIT_V_MLI := \
Skeleton_context_sector_tag_by_unit_provider_v.mli \
Skeleton_as_context_sector_tag_by_unit_provider_v.mli \
 \
Skeleton_context_domain_tag_by_unit_provider_v.mli \
Skeleton_as_context_domain_tag_by_unit_provider_v.mli \
 
BASICNAME_QUATUOR_V_MLI := \
Skeleton_basicname_quatuor_by_basicname_databox_n_basicname_database_provider_v.mli \
 
CONTEXT_TAG_BY_DATABOX_NAME_N_DATABASE_NAME_V_MLI := \
Skeleton_context_database_tag_by_basicname_database_provider_v.mli \
Skeleton_as_context_database_tag_by_basicname_database_provider_v.mli \
 \
Skeleton_context_databox_tag_by_basicname_databox_n_basicname_database_provider_v.mli \
Skeleton_as_context_databox_tag_by_basicname_databox_n_basicname_database_provider_v.mli \
 \
Skeleton_context_tag_quadruplet_by_basicname_databox_n_basicname_database_provider_v.mli \
Skeleton_as_context_tag_quatuor_by_basicname_databox_n_basicname_database_provider_v.mli \
 \
Basicname_database_by_skeleton_context_databox_tag_provider_v.mli \
Basicname_databox_n_basicname_database_by_skeleton_context_databox_tag_provider_v.mli \
 \
Skeleton_context_databox_sole_index_by_any_sole_index_provider_v.mli \
Skeleton_basicname_databox_by_any_sole_index_provider_v.mli \
Skeleton_context_databox_symbol_by_any_sole_index_provider_v.mli \
Skeleton_context_databox_tag_by_any_sole_index_provider_v.mli \
 
TRANSLATION_FROM_NWCHEMDATA_V_MLI := \
Skeleton_symbol_from_nwchemdata_tag_translations_v.mli \
# Skeleton_symbol_from_nwchemdata_basicname_databox_translations_v.mli \
   
SYMBOL_SUBTREE_BY_CONTEXT_NAME_V_MLI := \
Skeleton_symbol_subtree_by_basicname_databox_n_basicname_database_provider_v.mli \
  
TAG_TREE_V_MLI := \
Skeleton_tag_tree_by_basicname_databox_n_basicname_database_provider_v.mli \
Skeleton_tag_tree_by_skeleton_context_databox_tag_provider_v.mli \
 
INTERFACES_V_MLI := \
Skeleton_tag_all_list_by_basicname_databox_n_basicname_database_provider_v.mli \
Skeleton_tag_all_list_by_skeleton_context_databox_tag_provider_v.mli \
 
EXTRACTORS_V_MLI := \
Skeleton_symbol_by_sole_index_register_filler_v.mli \
Skeleton_symbol_by_sole_index_provider_v.mli \
Skeleton_any_category_by_sole_index_extractor_v.mli \
Skeleton_son_tag_list_by_skeleton_father_tag_provider_v.mli \
Skeleton_tag_subtree_by_skeleton_tag_provider_v.mli \
Skeleton_name_by_skeleton_set_fence_tag_provider_v.mli \
Basicname_skeleton_by_skeleton_set_fence_tag_provider_v.mli \
 
FENCE_V_MLI := \
Skeleton_fence_by_skeleton_tag_provider_v.mli \
Skeleton_set_fence_tag_list_by_skeleton_tag_provider_v.mli \
 
BRIDGE_V_MLI := \
Parameter_set_body_tuple_string_off_by_skeleton_set_fence_tag_provider_v.mli \
Skeleton_bridge_by_skeleton_set_fence_tag_provider_v.mli \
 
FILES_MLI := \
$(REGISTERS_V_MLI) \
$(CONTEXT_NAME_BY_UNIT_V_MLI) \
$(CONTEXT_TAG_BY_UNIT_V_MLI) \
$(BASICNAME_QUATUOR_V_MLI) \
$(CONTEXT_TAG_BY_DATABOX_NAME_N_DATABASE_NAME_V_MLI) \
$(TRANSLATION_FROM_NWCHEMDATA_V_MLI) \
$(SYMBOL_SUBTREE_BY_CONTEXT_NAME_V_MLI) \
$(TAG_TREE_V_MLI) \
$(INTERFACES_V_MLI) \
$(EXTRACTORS_V_MLI) \
$(FENCE_V_MLI) \
$(BRIDGE_V_MLI) \
 