MUSIC_T_MLI :=  \
    Tag_id3v2_4_specific_symbol_t.mli \
    Tag_id3v2_3_specific_symbol_t.mli \
   Tag_id3v2_specific_symbol_t.mli \
    Tag_id3v2_base_multiple_symbol_t.mli \
    Tag_id3v2_base_unique_symbol_t.mli \
   Tag_id3v2_base_symbol_t.mli \
  Tag_id3v2_symbol_t.mli \
   Tag_id3v1_227_symbol_t.mli \
   Tag_id3v1_128_symbol_t.mli \
  Tag_id3v1_symbol_t.mli \
 Tag_id3_symbol_t.mli \
 Mp3_layout_tag_symbol_t.mli \
  Mp3_header_tag_symbol_t.mli \
   Mp3_header_field_elevenbits_symbol_t.mli \
   Mp3_header_field_fourbits_symbol_t.mli \
   Mp3_header_field_twobits_symbol_t.mli \
    Version_symbol_t.mli \
   Mp3_header_field_onebit_symbol_t.mli \
  Mp3_header_field_symbol_t.mli \
 Mp3_header_symbol_t.mli \
  Mp3_file_id3v2_symbol_t.mli \
  Mp3_file_id3v1_symbol_t.mli \
 Mp3_file_symbol_t.mli \
 Mp3_elementary_stream_symbol_t.mli \
 Mp3_frame_symbol_t.mli \
 Mp3_data_symbol_t.mli \
Music_symbol_t.mli \
