INCLUDED_DIRS = \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_CONTAINERS_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(ELEMENTARYSET_SYMBOLS_DIR) \
	$(ELEMENTARYSET_TAGS_DIR) \
	$(ELEMENTARYSET_BUILDER_TREES_DIR) \
	$(ELEMENTARYSET_CONTAINERS_DIR) \
	$(FIGURESET_SYMBOLS_DIR) \
	$(FIGURESET_TAGS_DIR) \
	$(FIGURESET_BUILDER_TREES_DIR) \
	$(FIGURESET_CONTAINERS_DIR) \
  


