FROM_FILES_V_ML := \
Parameter_set_body_container_u_any.ml \
Parameter_set_body_tuple_aopef_container_u_any.ml \
Parameter_set_body_tuple_container_u_any.ml \
Parameter_set_body_tuple_ecppef_container_u_any.ml \
Parameter_container_u_any.ml \
Parameter_context_container_u_any.ml \
Parameter_context_database_container_u_any.ml \
Parameter_context_databox_container_u_any.ml \
Parameter_context_domain_container_u_any.ml \
Parameter_context_sector_container_u_any.ml \
Parameter_set_fence_aopef_coefficient_container_u_any.ml \
Parameter_set_fence_aopef_container_u_any.ml \
Parameter_set_fence_aopef_exponent_container_u_any.ml \
Parameter_set_fence_container_u_any.ml \
Parameter_set_fence_ecppef_coefficient_container_u_any.ml \
Parameter_set_fence_ecppef_container_u_any.ml \
Parameter_set_fence_ecppef_exponent_container_u_any.ml \

FROM_FILES_U_ML := \
Elementary_body_parameter_tuple_aopef_container_u_test_ao_debug.ml \
Elementary_body_parameter_tuple_container_u_test_ao_debug.ml \
Elementary_border_coordinate_homogeneous_cartesian_x_container_u_segment_s_debug.ml \
Elementary_border_parameter_aopef_coefficient_container_u_test_ao_debug.ml \
Elementary_border_parameter_aopef_container_u_test_ao_debug.ml \
Elementary_border_parameter_container_u_test_ao_debug.ml \
Elementary_context_container_u_db1_debug.ml \
Elementary_context_container_u_debug.ml \
Elementary_context_container_u_lanl2dz_debug.ml \
Elementary_coordinate_cartesian_container_u_debug.ml \
Elementary_coordinate_formula_u_debug.ml \
Elementary_coordinate_heterogeneous_container_u_debug.ml \
Elementary_coordinate_homogeneous_container_u_debug.ml \
Elementary_coordinate_tuple_cartesian_container_u_debug.ml \
Elementary_coordinate_tuple_cylindrical_container_u_debug.ml \
Elementary_coordinate_tuple_cylindrical_formula_u_debug.ml \
Elementary_coordinate_tuple_heterogeneous_container_u_debug.ml \
Elementary_coordinate_tuple_homogeneous_container_u_debug.ml \
Elementary_coordinate_tuple_polar_container_u_debug.ml \
Elementary_coordinate_tuple_spherical_container_u_debug.ml \
Elementary_fence_basic_container_u_test_ao_debug.ml \
Elementary_fence_container_u_test_ao_debug.ml \
Elementary_fence_units_container_u_test_ao_debug.ml \
Elementary_fence_units_length_container_u_test_ao_debug.ml \
Elementary_parameter_aopef_container_u_lanl2dz_debug.ml \
Elementary_parameter_tuple_aopef_container_u_cc_pvtz_debug.ml \
Elementary_symbol_tree_by_coordinate_tuple_spherical_symbol_builder_u_debug.ml \
Elementary_tag_tree_by_coordinate_tuple_spherical_tag_provider_u_debug.ml \
Elementary_units_container_u_debug.ml \
Elementary_units_formula_u_debug.ml \
Measure_u_debug.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
$(FROM_FILES_U_ML) \

