LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(QUANTUM_DIR) \
	$(UNITS_DIR) \
	$(CONTEXTSET_DIR) \
	$(NWCHEMDATASET_SYMBOLS_DIR) \
	$(NWCHEMDATASET_TAGS_DIR) \
	$(NWCHEMDATASET_LEXER_DIR) \
	$(NWCHEMDATASET_PARSER_DIR) \
	$(NWCHEMDATASET_BUILDER_TREES_DIR) \
	$(PARAMETERSET_SYMBOLS_DIR) \
	$(PARAMETERSET_TAGS_DIR) \
	$(PARAMETERSET_BUILDER_TREES_DIR) \
	$(PARAMETERSET_CONTAINERS_DIR) \
  


