INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(QUANTUM_DIR) \
	$(UNITS_DIR) \
	$(MEASURE_DIR) \
	$(READEE_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_LEXER_DIR) \
	$(DB1POINTSDATASET_PARSER_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(COORDINATESET_SYMBOLS_DIR) \
	$(COORDINATESET_TAGS_DIR) \
	$(COORDINATESET_BUILDER_TREES_DIR) \
	$(COORDINATESET_CONTAINERS_DIR) \
	$(COORDINATESET_READEES_DIR) \
	$(COORDINATESET_ENVELOPES_DIR) \
  


