NEEDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
        $(GENERATORSET_SYMBOLS_DIR) \
        $(GENERATORSET_DATABASES_DIR) \
        $(GENERATORSET_DATABASES_ADB_DIR) \
	$(realpath ..) \
    