FILES_MUSICSET_SYMBOL_ML := \
entity_properlist_by_category_tag_provider_u_musicset_symbol.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_musicset_symbol_musicset.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_musicset_symbol_mp3_header_field.ml \
usagefile_symbol_list_by_contentfile_quatup_provider_u_musicset_symbol_mp3_header_field.ml \
entity_symbol_constructor_tree_by_domain_symbol_provider_u_musicset_symbol.ml \
entity_symbol_constructor_subtree_list_by_domain_symbol_provider_u_musicset_symbol.ml \
entity_symbol_constructor_subtree_by_entity_tritup_provider_u_musicset_symbol_musicset.ml \
entity_symbol_constructor_subtree_by_entity_tritup_provider_u_musicset_symbol_mp3_header_field.ml \
entity_current_symbol_by_camlparagraph_septup_provider_u_musicset_symbol_musicset_typing.ml \
entity_current_symbol_by_camlparagraph_septup_provider_u_musicset_symbol_mp3_header_field_onebit_abbreviating.ml \
entity_current_symbol_by_camlparagraph_septup_provider_u_musicset_symbol_mp3_header_field_onebit_typing.ml \
entity_symbol_path_list_by_item_sextup_provider_u_musicset_symbol_musicset_upgrading.ml \
entity_symbol_path_list_by_item_sextup_provider_u_musicset_symbol_mp3_header_field_onebit_upgrading.ml \
entity_symbol_path_list_by_item_sextup_provider_u_musicset_symbol_mp3_header_field_upgrading.ml \
entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_musicset_symbol_musicset_upgrading.ml \
entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_musicset_symbol_mp3_header_field_onebit.ml \
entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_musicset_symbol_mp3_header_field_onebit_abbreviating.ml \
camlparagraph_for_symbol_let_match_proformula_u_musicset_symbol_musicset_naming.ml \
camlparagraph_for_symbol_let_match_proformula_u_musicset_symbol_musicset_making.ml \
camlparagraph_for_symbol_let_match_proformula_u_musicset_symbol_mp3_header_field_making.ml \
camlparagraph_for_symbol_let_match_proformula_u_musicset_symbol_mp3_header_field_onebit_making.ml \
camlparagraph_for_symbol_let_match_proformula_u_musicset_symbol_coordinate_making.ml \
camlparagraph_symbol_list_by_item_sextup_provider_u_musicset_symbol_musicset.ml \
 \
entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_musicset_symbol_mp3_header_field_onebit_abbreviating.ml \
entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_musicset_symbol_mp3_header_field_onebit_typing.ml \
camlline_symbol_list_by_camlparagraph_septup_provider_u_musicset_symbol_mp3_header_field_onebit_typing.ml \
entity_symbol_list_by_camlline_octtup_provider_u_musicset_symbol_musicset_abbreviating.ml \
entity_symbol_list_by_camlline_octtup_provider_u_musicset_symbol_musicset_typing.ml \
entity_symbol_list_by_camlline_octtup_provider_u_musicset_symbol_mp3_header_field_onebit_abbreviating.ml \
entity_symbol_list_by_camlline_octtup_provider_u_musicset_symbol_mp3_header_field_onebit_typing.ml \

FILES_MUSICSET_FORMULA_ML := \
Item_symbol_list_by_usagefile_quitup_provider_u_musicset_formula_mp3_header_field_onebit.ml \
Camlparagraph_for_formula_let_function_proformula_u_musicset_formula_musicset_making.ml \
Camlparagraph_for_formula_let_function_proformula_u_musicset_formula_mp3_header_field_onebit_making.ml \
Camlparagraph_symbol_list_by_item_sextup_provider_u_musicset_formula_musicset_making.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_musicset_formula_musicset.ml \
Entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_musicset_formula_musicset_making.ml \
Entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_musicset_formula_musicset_typing.ml \
Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_musicset_formula_musicset_typing.ml \
Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_musicset_formula_musicset_making.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_musicset_formula_mp3_header_field_onebit_making.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_musicset_formula_mp3_header_field_onebit_typing.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_musicset_formula_musicset_making.ml \

FILES_INACTIVE := \
translating_item_symbol_entity_symbol_path_doublet_to_camlparagraph_symbol_u_musicset_symbol_musicset.ml \

UNITARY_TESTS_FILES_MUSICSET_ML := \
b$(FILES_MUSICSET_FORMULA_ML) \
# $(FILES_MUSICSET_SYMBOL_ML) \
# $(FILES_CONSTRUCTOR_MUSICSET_ML) \
# $(FILES_CONSTRUCTOR_MUSICSET_SYMBOL_ML) \
# $(FILES_BUILDER_MUSICSET_ML) \
# $(FILES_BUILDER_MUSICSET_FORMULA_ML) \
