FILES_GENERATORSET_ML := \
Entity_fictive_nullary_symbol_entity_main_symbol_doublet_list_by_domain_symbol_provider_u_generatorset.ml \
Entity_fictive_nullary_symbol_entity_stem_symbol_doublet_list_by_domain_symbol_provider_u_generatorset.ml \

FILES_GENERATORSET_SYMBOL_ML := \
Entity_proper_symbol_list_by_domain_symbol_provider_u_generatorset_symbol_item.ml \
Usagefile_implementation_interface_u_generatorset_symbol_item.ml \
Usagefile_implementation_interface_u_generatorset_symbol_item_gather_both_topsons_for_symbol.ml \
Camlline_constant_function_interface_u_generatorset_symbol_item.ml \
Camlparagraph_for_symbol_let_argument_interface_u_generatorset_symbol_item.ml \
Category_interface_u_generatorset_symbol_item.ml \
Contentfile_interface_u_generatorset_symbol_item.ml \
Domainset_interface_u_generatorset_symbol_item.ml \
Entity_proper_interface_u_generatorset_symbol_item.ml \
Entity_symbol_constructor_tree_by_domain_symbol_provider_u_generatorset_symbol.ml \
Entity_symbol_path_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_generatorset_symbol_item.ml \
Group_for_symbol_header_constant_interface_u_generatorset_symbol_item.ml \
Item_all_topsons_for_symbol_interface_u_generatorset_symbol_item.ml \
Section_for_symbol_header_constant_interface_u_generatorset_symbol_item.ml \
# Camlline_test_interface_u_generatorset_symbol_item_type_alone.ml \
# Camlline_test_interface_u_generatorset_symbol_item_value_alone.ml \
 
# Camlline_uno_camltype_interface_u_generatorset_symbol_item.ml \
# Entity_symbol_stem_main_set_trio_by_entity_tritup_provider_u_generatorset_symbol_item_only_top_for_any.ml \
 

# Contentfile_symbol_list_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
# Contentfile_symbol_list_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
# Usagefile_symbol_list_by_contentfile_quatup_provider_u_generatorset_symbol_item.ml \
# Item_symbol_list_by_usagefile_quitup_provider_u_generatorset_symbol_item_only_top_for_any_equilateral.ml \
# Entity_symbol_stem_main_set_trio_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
#   \
# Entity_topson_symbol_list_by_item_all_topsons_sextup_provider_u_generatorset_symbol_item.ml \
# Entity_grandson_symbol_list_by_item_each_grandson_leaf_sextup_provider_u_generatorset_symbol_item.ml \
# Entity_grandson_symbol_list_by_item_each_grandson_notleaf_sextup_provider_u_generatorset_symbol_item.ml \
# Entity_topson_symbol_list_by_item_each_topson_leaf_sextup_provider_u_generatorset_symbol_item.ml \
# Entity_topson_symbol_list_by_item_each_topson_notleaf_sextup_provider_u_generatorset_symbol_item.ml \
# Entity_topson_symbol_list_by_item_each_topson_leaf_sextup_provider_u_generatorset_symbol_item_only_top_for_any.ml \
# Entity_topson_symbol_list_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
# Entity_topson_leaf_symbol_list_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
# Entity_topson_notleaf_symbol_list_by_entity_tritup_provider_u_generatorset_symbol_item.ml \
#   \
# Camlparagraph_symbol_by_item_all_topsons_making_sextup_provider_u_generatorset_symbol_item.ml \
#   \
# Camlparagraph_symbol_by_item_each_grandson_leaf_abbreviating_grandson_sextup_provider_u_generatorset_symbol_item.ml \
# Camlparagraph_symbol_by_item_each_grandson_notleaf_grandson_sextup_provider_u_generatorset_symbol_item.ml \
# Camlparagraph_symbol_by_item_each_topson_leaf_abbreviating_topson_sextup_provider_u_generatorset_symbol_item.ml \
# Camlparagraph_symbol_by_item_each_topson_leaf_abbreviating_topson_sextup_provider_u_generatorset_symbol_item_only_top_for_any.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_abbreviating.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_extracting.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_making.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_naming.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_typing.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_upgrading.ml \
#  \
# Camlparagraph_symbol_list_by_item_all_topson_iterating_sextup_provider_u_generatorset_formula_generatorset.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_documenting.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_making.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_typing.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_upgrading.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_only_top_for_any_typing.ml \
#  \
# Entity_symbol_constructor_subtree_list_by_domain_symbol_provider_u_generatorset_symbol.ml \
#  \
# Camlparagraph_for_any_function_proformula_u_generatorset_symbol_item_documenting.ml \
#  \
# Camlparagraph_for_symbol_let_argument_proformula_u_generatorset_symbol_coordinate_making.ml \
# Camlparagraph_for_symbol_let_argument_proformula_u_generatorset_symbol_item_making.ml \
# Camlparagraph_for_symbol_let_argument_proformula_u_generatorset_symbol_item_only_top_for_any_making.ml \
# Camlparagraph_for_symbol_let_argument_proformula_u_generatorset_symbol_item_making.ml \
# Camlparagraph_for_symbol_let_match_proformula_u_generatorset_symbol_item_naming.ml \
#  \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_symbol_item_abbreviating.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_symbol_item_heading.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_symbol_item_making.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_symbol_item_typing.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_symbol_item_upgrading.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_symbol_item_typing.ml \
#   \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_abbreviating.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_making.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_upgrading.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_only_top_for_any_making.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_only_top_for_any_typing.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_only_top_for_any_upgrading.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_making.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_typing.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_symbol_item_upgrading.ml \
#  \
# Entity_symbol_list_by_camlline_octtup_provider_u_generatorset_symbol_item_abbreviating_grandson.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_generatorset_symbol_item_abbreviating_topson.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_generatorset_symbol_item_typing.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_generatorset_symbol_item_only_top_for_any_abbreviating.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_generatorset_symbol_item_only_top_for_any_typing.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_only_top_for_any_abbreviating.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_generatorset_symbol_item_only_top_for_any_typing.ml \
# Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_generatorset_symbol_item.ml \
# Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_generatorset_symbol_item.ml \
# Entity_symbol_constructor_subtree_list_by_domain_symbol_provider_u_generatorset_symbol.ml \
#  \
 
# FILES_GENERATORSET_BUILDER_ML := \
# Entity_external_datastructure_symbol_by_entity_fictive_nullary_tritup_provider_u_generatorset_symbol_item_only_top_for_any.ml \
# Entity_external_datastructure_symbol_list_by_entity_tritup_provider_u_generatorset_formula_item.ml \
# Entity_external_datastructure_arity_by_entity_tritup_provider_u_generatorset_formula_item.ml \
# Entity_symbol_builder_subtree_by_entity_fictive_nullary_tritup_provider_u_generatorset_formula_vector.ml \
 
# Entity_external_datastructure_symbol_entity_fictive_symbol_list_by_entity_fictive_nullary_tritup_provider_u_generatorset_formula_item_only_top_for_any_equilateral.ml \
# Translating_trail_of_tag_u_generatorset_symbol_item_only_top_for_any.ml \
# Translating_entity_fictive_symbol_of_builder_basename_u_generatorset_symbol_item_only_top_for_any.ml \

FILES_GENERATORSET_TAG_ML := \
Camlline_symbol_list_by_camlparagraph_septup_provider_u_generatorset_tag_item_only_top_for_any_making.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_generatorset_tag_generatorset.ml \
Usagefile_symbol_list_by_contentfile_quatup_provider_u_generatorset_tag_item.ml \
Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_tag_item_only_top_for_any_making.ml \
Entity_current_symbol_list_by_item_sextup_provider_u_generatorset_tag_item_only_top_for_any_typing.ml \
Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_tag_generatorset_making.ml \
Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_generatorset_tag_generatorset_typing.ml \
Camlparagraph_symbol_list_by_item_sextup_provider_u_generatorset_tag_generatorset_abbreviating.ml \
Camlparagraph_symbol_list_by_item_sextup_provider_u_generatorset_tag_generatorset_typing.ml \
Camlparagraph_for_tag_type_proformula_u_generatorset_tag_generatorset_typing.ml \

FILES_INACTIVE := \
Translating_item_symbol_entity_symbol_path_doublet_to_camlparagraph_symbol_u_generatorset_symbol_item.ml \

UNITARY_TESTS_FILES_GENERATORSET_ML := \
$(FILES_GENERATORSET_SYMBOL_ML) \
# $(FILES_GENERATORSET_FORMULA_ML) \
# $(FILES_GENERATORSET_BUILDER_ML) \
# $(FILES_GENERATORSET_TAG_ML) \
# $(FILES_GENERATORSET_ML) \

 
