FILES_GENERAL_MOLECULESET_SYMBOL_ML := \
Contentfile_symbol_list_by_entity_tritup_provider_u_moleculeset_symbol_moleculeset.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_moleculeset_symbol_molecule.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
 \
Usagefile_symbol_list_by_contentfile_quatup_provider_u_moleculeset_symbol_moleculeset.ml \
 \
Item_symbol_list_by_usagefile_quitup_provider_u_moleculeset_symbol_moleculeset.ml \
 \
Entity_symbol_from_string_u_moleculeset_symbol_moleculeset.ml \
Entity_symbol_constructor_tree_by_domain_symbol_provider_u_moleculeset_symbol.ml \
Entity_symbol_constructor_subtree_by_domain_symbol_provider_u_moleculeset_symbol.ml \
  \
Entity_properlist_by_domain_symbol_provider_u_moleculeset_symbol.ml \
  \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_moleculeset_symbol_molecule.ml \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
  \
Entity_symbol_path_constructor_subtree_by_entity_tritup_provider_u_moleculeset_symbol_molecule.ml \
  \
entity_symbol_path_item_symbol_doublet_to_camlparagraph_symbol_u_moleculeset_symbol_moleculeset.ml \
Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_moleculeset_symbol_moleculeset.ml \
Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_moleculeset_symbol_moleculeset_typing.ml \
Entity_current_symbol_list_by_item_sextup_provider_u_moleculeset_symbol_moleculeset.ml \
Entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_moleculeset_symbol_moleculeset.ml \
Entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_moleculeset_symbol_moleculeset.ml \

FILES_FOR_ANY_MLI:= \
  camlparagraph_endmarked_let_argument_function_proformula_for_any_u_moleculeset.ml \
  camlparagraph_endmarked_let_argument_proformula_for_any_u_moleculeset.ml \
  camlparagraph_endmarked_let_function_proformula_for_any_u_moleculeset.ml \
 entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_any_u_moleculeset.ml \

FILES_FOR_TAG_MLI:= \
  camlparagraph_endmarked_let_argument_function_proformula_for_tag_u_moleculeset.ml \
  camlparagraph_endmarked_let_argument_proformula_for_tag_u_moleculeset.ml \
  camlparagraph_endmarked_let_function_proformula_for_tag_u_moleculeset.ml \
 entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_tag_u_moleculeset.ml \

FILES_FOR_SYMBOL_MLI:= \
  camlparagraph_endmarked_let_argument_function_proformula_for_symbol_u_moleculeset.ml \
  camlparagraph_endmarked_let_argument_proformula_for_symbol_u_moleculeset.ml \
  camlparagraph_for_symbol_let_match_proformula_u_moleculeset.ml \
 entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_symbol_u_moleculeset.ml \

FILES_FOR_FORMULA_MLI:= \
entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_moleculeset.ml \

CAMLLINE_MOLECULESET_SYMBOL_ML := \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_symbol.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_symbol_molecule.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_symbol_moleculeset.ml \
  \
camlparagraph_symbol_list_by_item_sextup_provider_u_moleculeset_symbol.ml \
  \
camlline_symbol_list_by_camlparagraph_septup_provider_u_moleculeset_symbol.ml \
  \
Entity_symbol_list_by_camlline_octtup_provider_u_moleculeset_symbol_molecule_linear_diatomic.ml \
Entity_symbol_list_by_camlline_octtup_provider_u_moleculeset_symbol_moleculeset.ml \
 \
Camlparagraph_for_symbol_let_match_proformula_u_moleculeset_symbol_moleculeset.ml \

FILES_GENERAL_MOLECULESET_FORMULA_ML := \
Contentfile_symbol_list_by_entity_tritup_provider_u_moleculeset_formula_moleculeset.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_moleculeset_formula_molecule_linear_diatomic.ml \
entity_trail_constructor_tree_by_Category_trail_provider_u_moleculeset_formula.ml \
Entity_basename_constructor_tree_by_domain_trail_provider_u_moleculeset_formula.ml \
entity_symbol_constructor_tree_by_Category_trail_provider_u_moleculeset_formula.ml \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_moleculeset_formula_molecule.ml \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_moleculeset_formula_molecule_linear_diatomic.ml \
Entity_symbol_path_constructor_subtree_by_entity_tritup_provider_u_moleculeset_formula.ml \
Entity_current_symbol_list_by_item_sextup_provider_u_moleculeset_formula_molecule_linear_diatomic.ml \
Entity_symbol_path_list_camlparagraph_symbol_doublet_list_by_item_sextup_provider_u_moleculeset_formula.ml \
Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_moleculeset_formula_molecule_linear_diatomic.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_formula_molecule_linear_diatomic.ml \
Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_moleculeset_formula_moleculeset_typing.ml \
Entity_symbol_list_by_camlline_octtup_provider_u_moleculeset_formula_molecule_linear_diatomic_typing.ml \
Entity_symbol_list_by_camlline_octtup_provider_u_moleculeset_formula.ml \
Translating_item_symbol_entity_symbol_path_doublet_to_camlparagraph_symbol_u_moleculeset_formula_moleculeset.ml \

FILES_INACTIVE := \

UNITARY_TESTS_FILES_MOLECULESET_ML := \
$(FILES_GENERAL_MOLECULESET_SYMBOL_ML) \
# $(FILES_FOR_ANY_MLI) \
# $(FILES_FOR_SYMBOL_MLI) \
# $(FILES_FOR_TAG_MLI) \
# $(FILES_FOR_FORMULA_MLI) \
# $(FILES_GENERAL_MOLECULESET_FORMULA_ML) \
