TRANSLATING_ML := \
Translating_trail_of_symbol_u_naturalset_symbol.ml \
Translating_entity_symbol_of_entity_basename_u_naturalset_symbol.ml \
Entity_fictive_nullary_symbol_by_constructor_leaf_trail_provider_u_naturalset.ml \
Entity_proper_symbol_by_constructor_notleaf_trail_provider_u_naturalset.ml \
 
TREE_ML := \
Entity_builder_symbol_tree_by_entity_proper_tritup_provider_u_naturalset.ml \
Entity_symbol_constructor_tree_by_domain_symbol_provider_u_naturalset_symbol.ml \
Entity_inconstructortree_symbol_list_by_domain_symbol_provider_u_naturalset_symbol.ml \
Entity_constructor_inner_symbol_list_by_domain_symbol_provider_u_naturalset_symbol.ml \
Entity_symbol_path_by_entity_tritup_provider_u_naturalset_symbol_point.ml \

NULL := \
Entity_fictive_nullary_symbol_entity_main_symbol_doublet_list_by_domain_symbol_provider_u_naturalset.ml \
 
# ENTITY_LEAF_LIST_ML := \
# Entity_leaf_symbol_list_by_entity_proper_tritup_provider_u_naturalset.ml \
 
# ENTITY_PROPER_LIST_ML := \
# Entity_proper_symbol_list_by_domain_symbol_provider_u_naturalset.ml \
  
TOPSON_BY_ENTITY_TRITUP_ML := \
Entity_topson_symbol_list_by_entity_tritup_provider_u_naturalset_symbol_naturalset.ml \
Entity_topson_leaf_symbol_list_by_entity_tritup_provider_u_naturalset_symbol.ml \
Entity_topson_notleaf_symbol_list_by_entity_tritup_provider_u_naturalset_symbol_naturalset.ml \
 
# Entity_topson_symbol_list_by_item_each_topson_leaf_sextup_provider_u_naturalset_symbol_naturalset.ml \
# Entity_topson_symbol_list_by_item_each_topson_notleaf_sextup_provider_u_naturalset_symbol_naturalset.ml \
# Entity_topson_symbol_list_by_item_each_topson_leaf_sextup_provider_u_naturalset_symbol_triangle_isoceles.ml \
# Entity_topson_symbol_list_by_item_all_topsons_sextup_provider_u_naturalset_symbol_naturalset.ml \

# BUILDER_LIST_ML := \
# Entity_builder_base_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_list.ml \
# Entity_builder_basic_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_list.ml \
# Entity_builder_symbol_once_list_by_entity_proper_tritup_provider_u_naturalset_list.ml \
# Entity_builder_symbol_tree_by_entity_proper_tritup_provider_u_naturalset_list.ml \

PROFORMULA_ML := \
Entity_builder_proper_topson_symbol_list_by_entity_proper_tritup_provider_u_naturalset_list.ml \
Entity_builder_leaf_symbol_list_by_entity_proper_tritup_provider_u_naturalset_list.ml \
Kind_symbol_list_by_category_symbol_provider_u_naturalset.ml \
Contentfile_symbol_list_by_entity_proper_tritup_provider_u_naturalset.ml \
Contentfile_interface_u_naturalset.ml \
Entity_interface_u_naturalset.ml \
Category_interface_u_naturalset.ml \
Domainset_interface_u_naturalset.ml \
 
PROVIDER_ML := \
$(TREE_ML) \
$(TOPSON_BY_ENTITY_TRITUP_ML) \
$(GRANDSON_BY_ENTITY_TRITUP_ML) \
# $(TRANSLATING_ML) \
# $(BUILDER_LIST_ML) \
# $(ENTITY_LEAF_LIST_ML) \
# $(ENTITY_PROPER_LIST_ML) \
 

# FILES_NATURALSET_FORMULA_LIST_ML := \
# Entity_builder_basic_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_formula_point_list.ml \
# Entity_builder_base_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_formula_coordinate_list.ml \
# Entity_builder_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_formula_coordinate_list.ml \
# Entity_main_symbol_by_entity_tritup_provider_u_naturalset.ml \
 
FILES_NATURALSET_FORMULA_ML := \
Item_symbol_list_by_usagefile_quitup_provider_u_naturalset_formula_triangle_isoceles.ml \
Item_symbol_list_by_usagefile_quitup_provider_u_naturalset_formula_coordinate_polar.ml \
 \
# Entity_builder_base_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_formula_point.ml \
#  \
# Entity_external_datastructure_symbol_list_by_entity_tritup_provider_u_naturalset_formula_triangle.ml \
# Entity_external_datastructure_symbol_list_by_entity_tritup_provider_u_naturalset_formula_vector.ml \
# Entity_external_datastructure_arity_by_entity_tritup_provider_u_naturalset_formula_triangle.ml \
# Entity_external_datastructure_arity_by_entity_tritup_provider_u_naturalset_formula_vector.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_x_iterating.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_formula_x_iterating.ml \
#   \
# Entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_naturalset_formula_x_typing.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_x_typing.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_x_making.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_x_naming.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_vector_making.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_point_making.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_polar_rho_making.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_point_naming.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_triangle_isoceles_equilateral_typing.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_naturalset_formula_triangle_isoceles_typing.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_naturalset_formula_triangle_isoceles_equilateral_typing.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_formula_triangle_isoceles_naming.ml \
#  \
# Camlparagraph_for_formula_let_entity_fictive_nullary_proformula_u_naturalset_formula_triangle_isoceles_equilateral_making.ml \
# Camlparagraph_for_formula_let_entity_fictive_nullary_proformula_u_naturalset_formula_triangle_isoceles_equilateral_naming.ml \
#  \
# Camlparagraph_for_formula_let_entity_proper_proformula_u_naturalset_formula_triangle_isoceles_making.ml \
# Camlparagraph_for_formula_let_entity_proper_proformula_u_naturalset_formula_triangle_isoceles_naming.ml \
# Contentfile_symbol_list_by_entity_tritup_provider_u_naturalset_formula_naturalset.ml \
#   \
# Entity_current_symbol_list_by_item_all_topsons_sextup_provider_u_naturalset_formula_triangle_isoceles_equilateral.ml \
# Entity_current_symbol_list_by_item_only_top_sextup_provider_u_naturalset_formula_triangle_isoceles_equilateral.ml \
# Entity_current_symbol_list_by_item_only_top_sextup_provider_u_naturalset_formula_triangle_isoceles.ml \
#  \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_naturalset_formula_naturalset_making.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_naturalset_formula_triangle_isoceles_making.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_naturalset_formula_naturalset_making.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_for_camlparagraph_formula_u_naturalset_formula_naturalset_typing.ml \
#   \
# Entity_formula_constructor_tree_by_domain_symbol_provider_u_naturalset.ml \
# ?? Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_naturalset_formula_naturalset_making.ml \
# ?? Entity_current_symbol_uno_by_camlparagraph_septup_provider_u_naturalset_formula_naturalset_typing.ml \

FILES_NATURALSET_SYMBOL_ML := \
Entity_symbol_constructor_tree_by_domain_symbol_provider_u_naturalset_symbol.ml \
Entity_symbol_path_by_entity_tritup_provider_u_naturalset_symbol_point.ml \
Entity_symbol_path_by_entity_tritup_provider_u_naturalset_symbol_triangle.ml \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_naturalset_symbol_triangle.ml \
Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_naturalset_symbol_point.ml \
 \
Contentfile_interface_u_naturalset_symbol_naturalset.ml \
Entity_interface_u_naturalset_symbol_naturalset.ml \
Category_interface_u_naturalset_symbol_naturalset.ml \
Domainset_interface_u_naturalset_symbol_naturalset.ml \
# Camlparagraph_for_symbol_let_argument_interface_u_naturalset_symbol_naturalset.ml \
# Group_for_symbol_header_constant_interface_u_naturalset_symbol_naturalset.ml \
# Camlline_constant_function_interface_u_naturalset_symbol_naturalset.ml \
# Section_for_symbol_header_constant_interface_u_naturalset_symbol_naturalset.ml \
# Usagefile_implementation_interface_u_naturalset_symbol_naturalset.ml \
# Camlline_test_interface_u_naturalset_symbol_naturalset_type_alone.ml \
# Camlline_test_interface_u_naturalset_symbol_naturalset_value_alone.ml \
 
# Camlline_uno_camltype_interface_u_naturalset_symbol_naturalset.ml \
# Entity_symbol_stem_main_set_trio_by_entity_tritup_provider_u_naturalset_symbol_triangle_isoceles.ml \
 

# Contentfile_symbol_list_by_entity_tritup_provider_u_naturalset_symbol_naturalset.ml \
# Contentfile_symbol_list_by_entity_tritup_provider_u_naturalset_symbol_triangle.ml \
# Usagefile_symbol_list_by_contentfile_quatup_provider_u_naturalset_symbol_triangle.ml \
# Item_symbol_list_by_usagefile_quitup_provider_u_naturalset_symbol_triangle_isoceles_equilateral.ml \
# Entity_symbol_stem_main_set_trio_by_entity_tritup_provider_u_naturalset_symbol_triangle.ml \
#   \
# Entity_grandson_symbol_list_by_item_each_grandson_leaf_sextup_provider_u_naturalset_symbol_naturalset.ml \
# Entity_grandson_symbol_list_by_item_each_grandson_notleaf_sextup_provider_u_naturalset_symbol_naturalset.ml \
#   \
# Camlparagraph_symbol_by_item_all_topsons_making_sextup_provider_u_naturalset_symbol_naturalset.ml \
#   \
# Camlparagraph_symbol_by_item_each_grandson_leaf_abbreviating_grandson_sextup_provider_u_naturalset_symbol_naturalset.ml \
# Camlparagraph_symbol_by_item_each_grandson_notleaf_grandson_sextup_provider_u_naturalset_symbol_naturalset.ml \
# Camlparagraph_symbol_by_item_each_topson_leaf_abbreviating_topson_sextup_provider_u_naturalset_symbol_naturalset.ml \
# Camlparagraph_symbol_by_item_each_topson_leaf_abbreviating_topson_sextup_provider_u_naturalset_symbol_triangle_isoceles.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_naturalset_abbreviating.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_naturalset_extracting.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_naturalset_making.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_naturalset_naming.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_naturalset_typing.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_naturalset_upgrading.ml \
#  \
# Camlparagraph_symbol_list_by_item_all_topson_iterating_sextup_provider_u_naturalset_formula_naturalset.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_documenting.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_making.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_typing.ml \
# Camlparagraph_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_upgrading.ml \
# Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_symbol_triangle_isoceles_typing.ml \
#  \
# Entity_symbol_constructor_subtree_list_by_domain_symbol_provider_u_naturalset_symbol.ml \
#  \
# Camlparagraph_for_any_function_proformula_u_naturalset_symbol_naturalset_documenting.ml \
#  \
# Camlparagraph_for_symbol_let_argument_proformula_u_naturalset_symbol_coordinate_making.ml \
# Camlparagraph_for_symbol_let_argument_proformula_u_naturalset_symbol_naturalset_making.ml \
# Camlparagraph_for_symbol_let_argument_proformula_u_naturalset_symbol_triangle_isoceles_making.ml \
# Camlparagraph_for_symbol_let_argument_proformula_u_naturalset_symbol_triangle_making.ml \
# Camlparagraph_for_symbol_let_match_proformula_u_naturalset_symbol_naturalset_naming.ml \
#  \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_abbreviating.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_heading.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_making.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_typing.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_upgrading.ml \
# Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_symbol_triangle_typing.ml \
#   \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_abbreviating.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_making.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_naturalset_upgrading.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_triangle_isoceles_making.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_triangle_isoceles_typing.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_triangle_isoceles_upgrading.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_triangle_making.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_triangle_typing.ml \
# Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_symbol_triangle_upgrading.ml \
#  \
# Entity_symbol_list_by_camlline_octtup_provider_u_naturalset_symbol_naturalset_abbreviating_grandson.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_naturalset_symbol_naturalset_abbreviating_topson.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_naturalset_symbol_naturalset_typing.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_naturalset_symbol_triangle_isoceles_abbreviating.ml \
# Entity_symbol_list_by_camlline_octtup_provider_u_naturalset_symbol_triangle_isoceles_typing.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_naturalset_symbol_triangle_isoceles_abbreviating.ml \
# Entity_symbol_list_camlline_symbol_doublet_list_by_camlparagraph_septup_provider_u_naturalset_symbol_triangle_isoceles_typing.ml \
# Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_naturalset_symbol_naturalset.ml \
# Entity_symbol_constructor_subtree_by_entity_proper_tritup_provider_u_naturalset_symbol_triangle.ml \
# Entity_symbol_constructor_subtree_list_by_domain_symbol_provider_u_naturalset_symbol.ml \
#  \
 
FILES_NATURALSET_BUILDER_ML := \
Entity_leaf_symbol_list_by_entity_proper_tritup_provider_u_naturalset.ml \
Entity_builder_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset.ml \
Entity_builder_symbol_once_list_by_entity_proper_tritup_provider_u_naturalset.ml \
Entity_builder_symbol_tree_by_entity_proper_tritup_provider_u_naturalset.ml \
# Entity_external_datastructure_symbol_by_entity_fictive_nullary_tritup_provider_u_naturalset_symbol_triangle_isoceles.ml \
# Entity_external_datastructure_symbol_list_by_entity_tritup_provider_u_naturalset_formula_triangle.ml \
# Entity_external_datastructure_arity_by_entity_tritup_provider_u_naturalset_formula_triangle.ml \
# Entity_symbol_builder_subtree_by_entity_fictive_nullary_tritup_provider_u_naturalset_formula_vector.ml \
# Entity_external_datastructure_symbol_entity_fictive_symbol_list_by_entity_fictive_nullary_tritup_provider_u_naturalset_formula_triangle_isoceles_equilateral.ml \
# Translating_trail_of_tag_u_naturalset_symbol_triangle_isoceles.ml \
# Translating_entity_fictive_symbol_of_builder_basename_u_naturalset_symbol_triangle_isoceles.ml \

FILES_NATURALSET_TAG_ML := \
Camlline_symbol_list_by_camlparagraph_septup_provider_u_naturalset_tag_triangle_isoceles_making.ml \
Contentfile_symbol_list_by_entity_tritup_provider_u_naturalset_tag_naturalset.ml \
Usagefile_symbol_list_by_contentfile_quatup_provider_u_naturalset_tag_triangle.ml \
Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_tag_triangle_isoceles_making.ml \
Entity_current_symbol_list_by_item_sextup_provider_u_naturalset_tag_triangle_isoceles_typing.ml \
Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_tag_naturalset_making.ml \
Entity_current_symbol_camlparagraph_tag_doublet_list_by_item_sextup_provider_u_naturalset_tag_naturalset_typing.ml \
Camlparagraph_symbol_list_by_item_sextup_provider_u_naturalset_tag_naturalset_abbreviating.ml \
Camlparagraph_symbol_list_by_item_sextup_provider_u_naturalset_tag_naturalset_typing.ml \
Camlparagraph_for_tag_type_proformula_u_naturalset_tag_naturalset_typing.ml \

FILES_INACTIVE := \
Translating_item_symbol_entity_symbol_path_doublet_to_camlparagraph_symbol_u_naturalset_symbol_naturalset.ml \

UNITARY_TESTS_FILES_NATURALSET_ML := \
$(PROVIDER_ML) \
# $(FILES_NATURALSET_BUILDER_ML) \
# $(PROFORMULA_ML) \
# $(FILES_NATURALSET_FORMULA_LIST_ML) \
# $(FILES_NATURALSET_FORMULA_ML) \
# $(FILES_NATURALSET_ML) \
# $(FILES_NATURALSET_SYMBOL_ML) \
# $(FILES_NATURALSET_TAG_ML) \


 
