FROM_FILES_V_ML := \
Databox_name_n_database_name_by_nwchemdata_context_databox_tag_provider_u_any.ml \
Databox_name_n_database_name_by_nwchemdata_context_databox_tag_register_u_any.ml \
Nwchemdata_any_category_by_sole_index_extractor_u_any.ml \
Nwchemdata_as_body_bundle_coordinates_symbol_subtree_by_databox_name_provider_u_any.ml \
Nwchemdata_as_body_bundle_figure_symbol_subtree_by_databox_name_provider_u_any.ml \
Nwchemdata_as_body_cluster_information_tag_subtree_by_databox_name_provider_u_any.ml \
Nwchemdata_as_body_cluster_vertex_symbol_subtree_by_databox_name_provider_u_any.ml \
Nwchemdata_as_context_database_tag_by_unit_provider_u_any.ml \
Nwchemdata_as_context_databox_tag_by_databox_name_provider_u_any.ml \
Nwchemdata_as_context_domain_tag_by_unit_provider_u_any.ml \
Nwchemdata_as_context_sector_tag_by_unit_provider_u_any.ml \
Nwchemdata_as_context_tag_quatuor_by_databox_name_provider_u_any.ml \
Nwchemdata_as_set_body_node_aoset_numericalvalues_tag_list_by_databox_name_provider_u_any.ml \
Nwchemdata_as_set_body_node_aoset_numericalvalues_tag_list_by_nwchemdata_context_databox_tag_provider_u_any.ml \
Nwchemdata_as_set_body_node_aoset_numericalvalues_tag_subtree_list_by_databox_name_provider_u_any.ml \
Nwchemdata_context_database_name_by_unit_provider_u_any.ml \
Nwchemdata_context_database_tag_by_unit_provider_u_any.ml \
Nwchemdata_context_databox_name_by_any_sole_index_provider_u_any.ml \
Nwchemdata_context_databox_sole_index_by_any_sole_index_provider_u_any.ml \
Nwchemdata_context_databox_symbol_by_any_sole_index_provider_u_any.ml \
Nwchemdata_context_databox_tag_by_any_sole_index_provider_u_any.ml \
Nwchemdata_context_databox_tag_by_databox_name_provider_u_any.ml \
Nwchemdata_context_domain_name_by_unit_provider_u_any.ml \
Nwchemdata_context_domain_tag_by_unit_provider_u_any.ml \
Nwchemdata_context_name_trio_by_unit_provider_u_any.ml \
Nwchemdata_context_sector_name_by_unit_provider_u_any.ml \
Nwchemdata_context_sector_tag_by_unit_provider_u_any.ml \
Nwchemdata_context_tag_quadruplet_by_databox_name_provider_u_any.ml \
Nwchemdata_creation_module_name_by_sole_index_register_u_any.ml \
Nwchemdata_set_body_node_aoset_numericalvalues_string_off_list_by_databox_name_provider_u_any.ml \
Nwchemdata_set_body_node_aoset_numericalvalues_string_off_list_by_nwchemdata_context_databox_tag_provider_u_any.ml \
Nwchemdata_set_fence_by_nwchemdata_tag_provider_u_any.ml \
Nwchemdata_set_fence_by_nwchemdata_tag_register_u_any.ml \
Nwchemdata_son_tag_list_by_nwchemdata_father_tag_provider_u_any.ml \
Nwchemdata_son_tag_list_by_nwchemdata_father_tag_register_u_any.ml \
Nwchemdata_symbol_by_sole_index_provider_u_any.ml \
Nwchemdata_symbol_by_sole_index_register_filler_u_any.ml \
Nwchemdata_symbol_by_sole_index_register_u_any.ml \
Nwchemdata_symbol_subtree_by_databox_name_provider_u_any.ml \
Nwchemdata_symbol_subtree_by_databox_name_register_u_any.ml \
Nwchemdata_symbol_subtree_by_nwchemdata_context_databox_tag_provider_u_any.ml \
Nwchemdata_tag_all_list_by_databox_name_provider_u_any.ml \
Nwchemdata_tag_all_list_by_databox_name_register_u_any.ml \
Nwchemdata_tag_all_list_by_nwchemdata_context_databox_tag_provider_u_any.ml \
Nwchemdata_tag_all_list_by_nwchemdata_context_databox_tag_register_u_any.ml \
Nwchemdata_tag_subtree_by_nwchemdata_tag_provider_u_any.ml \
Nwchemdata_tag_subtree_by_nwchemdata_tag_register_u_any.ml \
Nwchemdata_tag_tree_by_databox_name_provider_u_any.ml \
Nwchemdata_tag_tree_by_databox_name_register_u_any.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_any.ml \

FROM_FILES_U_ML := \
Database_fullnameofdirectory_by_nwchemdata_context_database_tag_provider_u_lanl2dz.ml \
Nwchemdata_context_database_name_by_unit_provider_u_lanl2dz.ml \
Nwchemdata_context_domain_name_by_unit_provider_u_lanl2dz.ml \
Nwchemdata_datafile_name_by_unit_provider_u_lanl2dz.ml \
Nwchemdata_domaindata_name_by_unit_provider_u_lanl2dz.ml \
Nwchemdata_son_tag_list_by_nwchemdata_father_tag_provider_u_lanl2dz_analysis_list.ml \
Nwchemdata_symbol_subtree_by_nwchemdata_context_databox_tag_provider_u_lanl2dz.ml \
Nwchemdata_tag_all_list_by_nwchemdata_context_databox_tag_provider_u_lanl2dz.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_cc_pvtz_analysis_tree.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_cc_pvtz.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_lanl2dz_analysis_list.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_lanl2dz_analysis.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_lanl2dz_analysis_tree.ml \
Nwchemdata_tag_tree_by_nwchemdata_context_databox_tag_provider_u_lanl2dz.ml \

UNITARY_TESTS_FILES_ML := \
$(FROM_FILES_V_ML) \
# $(FROM_FILES_U_ML) \

