INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(LOCALINPUTSET_LEXER_DIR) \
	$(LOCALINPUTSET_SYMBOLS_DIR) \
	$(LOCALINPUTSET_TAGS_DIR) \
	$(LOCALINPUTSET_PARSER_DIR) \
	$(LOCALINPUTSET_BUILDER_TREES_DIR) \
	$(LOCALINPUTSET_VARIABLES_DIR) \
	$(PROPERTYSET_SYMBOLS_DIR) \
	$(PROPERTYSET_TAGS_DIR) \
	$(PROPERTYSET_BUILDER_TREES_DIR) \
 