#!/bin/bash
# The directory where we run a configure script.
SUB_DIRECTORIES="pdbdata_symbols pdbdata_tags pdbdata_buildertree"

# The directory where we just configure .depend and .depend-rebuild.
CURRENT_AND_TEST=". unitary_tests"
