modify_string.pl Afs_t Atom_fieldpdb_symbol_t *.ml
modify_string.pl Ard_t Atom_recordpdb_data_t *.ml
modify_string.pl Ard_v Atom_recordpdb_data_v *.ml
modify_string.pl Ard_v Atom_recordpdb_data_v *.ml
modify_string.pl Ark_v Atom_recordpdb_keypdb_v *.ml
modify_string.pl Arm_v Atom_recordpdb_markerpdb_v *.ml
modify_string.pl Arsf_v Atom_recordpdb_symbol_formula_v *.ml
modify_string.pl Cdps_t Coordinate_clusterpdb_symbol_t *.ml
modify_string.pl Cpd_v Clusterpdb_data_v *.ml
modify_string.pl Cpk_v Clusterpdb_keypdb_v *.ml
modify_string.pl Cps_t Clusterpdb_symbol_t *.ml
modify_string.pl Cps_v Clusterpdb_symbol_v *.ml
modify_string.pl Epd_v Entrypdb_data_v *.ml
modify_string.pl Eps_t Entrypdb_symbol_t *.ml
modify_string.pl Eps_v Entrypdb_symbol_v *.ml
modify_string.pl Epv_v Entrypdb_value_v *.ml
modify_string.pl Esfc_v Entrypdb_symbol_formula_constrained_pdb_v *.ml
modify_string.pl Esf_v Entrypdb_symbol_formula_v *.ml
modify_string.pl Fio_v Fileio_v *.ml
modify_string.pl Fln_v Filename_p *.ml
modify_string.pl Hfs_t Header_fieldpdb_symbol_t *.ml
modify_string.pl Hrd_t Header_recordpdb_data_t *.ml
modify_string.pl Hrd_v Header_recordpdb_data_v *.ml
modify_string.pl Hrsf_v Header_recordpdb_symbol_formula_v *.ml
modify_string.pl Lst_v List_v *.ml
modify_string.pl Mps_v Moleculepdb_symbol_v *.ml
modify_string.pl Ord_p Ordinal_p *.ml
modify_string.pl Ppd_v Packpdb_data_v *.ml
modify_string.pl Ppk_v Packpdb_keypdb_v *.ml
modify_string.pl Ppm_v Packpdb_markerpdb_v *.ml
modify_string.pl Pps_t Packpdb_symbol_t *.ml
modify_string.pl Pps_v Packpdb_symbol_v *.ml
modify_string.pl Psp_v Protein_sequencepdb_v *.ml
modify_string.pl Rpd_v Residue_packpdb_data_v *.ml
modify_string.pl Rpk_v Residue_packpdb_keypdb_v *.ml
modify_string.pl Rpm_v Residue_packpdb_markerpdb_v *.ml
modify_string.pl Rps_t Recordpdb_symbol_t *.ml
modify_string.pl Rps_v Recordpdb_symbol_v *.ml
modify_string.pl Rss_v Residuepdb_symbol_v *.ml
modify_string.pl Sfs_t Seqres_fieldpdb_symbol_t *.ml
modify_string.pl Sqpd_v Seqres_packpdb_data_v *.ml
modify_string.pl Srd_t Seqres_recordpdb_data_t *.ml
modify_string.pl Srd_v Seqres_recordpdb_data_v *.ml
modify_string.pl Srsf_v Seqres_recordpdb_symbol_formula_v *.ml
modify_string.pl Tkp_v Tokenpdb_v *.ml
