CONTEXT_U_ML := \
Figure_as_context_domain_tag_by_unit_provider_u_any.ml \
Figure_context_domain_tag_by_unit_provider_u_any.ml \
\
Figure_as_context_database_tag_by_database_name_provider_u_any.ml \
Figure_context_database_tag_by_database_name_provider_u_any.ml \
 \
Figure_as_context_database_tag_by_parameters_general_provider_u_any.ml \
Figure_context_database_tag_by_parameters_general_provider_u_any.ml \
 \
Figure_as_context_databox_tag_by_database_name_n_databox_name_provider_u_any.ml \
Figure_as_context_databox_tag_by_parameters_general_provider_u_any.ml \
 \
Figure_context_databox_tag_by_database_name_n_databox_name_provider_u_any.ml \
Figure_context_databox_tag_by_parameters_general_provider_u_any.ml \
 \
Database_name_n_databox_name_by_figure_context_databox_tag_provider_u_point_a.ml \
 
CONTEXT_TAGS_TUPLE_U_ML := \
Figure_as_context_tag_trio_by_database_name_n_databox_name_provider_u_point_a.ml \
Figure_context_tag_triplet_by_database_name_n_databox_name_provider_u_point_a.ml \
 
TRANSLATORS_TO_DB1FIGURE_U_ML := \
Db1figure_context_databox_tag_by_database_name_n_databox_name_provider_u_point_a.ml \
Db1figure_context_databox_tag_by_figure_context_databox_tag_provider_u_point_a.ml \
 
TRANSLATORS_FROM_DB1FIGURE_U_ML := \
Figure_symbol_from_db1figure_tag_translations_u_point_a.ml \
Figure_as_field_symbol_subtree_by_database_name_n_databox_name_provider_u_point_a.ml \
Figure_as_field_symbol_subtree_by_database_name_n_databox_name_provider_u_segment_s.ml \
Figure_as_field_symbol_subtree_from_db1figure_as_body_cluster_vertex_tag_subtree_translator_u_point_a.ml \
 
SUBTREES_U_ML := \
Figure_symbol_subtree_root_databox_by_database_name_n_databox_name_provider_u_point_a.ml \
Figure_symbol_subtree_root_databox_by_database_name_n_databox_name_provider_u_segment_s.ml \
# Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_point_a.ml \
# Figure_symbol_subtree_by_db1figure_figure_context_databox_tag_provider_u_point_a.ml \
# Figure_symbol_subtree_by_db1figure_figure_context_databox_tag_provider_u_segment_s.ml \
# Figure_symbol_subtree_root_databox_by_database_name_n_databox_name_provider_u_any.ml \
# Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_segment_s_cpu.ml \

TREES_U_ML := \
Figure_tag_tree_by_database_name_n_databox_name_provider_u_point_a.ml \
Figure_tag_tree_by_database_name_n_databox_name_provider_u_segment_s.ml \
# Figure_tag_tree_by_figure_context_databox_tag_provider_u_any.ml \
# Figure_tag_tree_by_figure_context_databox_tag_provider_u_segment_s_analysis.ml \
# Figure_tag_tree_by_parameters_general_provider_u_any.ml \
# Figure_tag_all_list_by_figure_context_databox_tag_provider_u_any.ml \
# Figure_tag_all_list_by_parameters_general_provider_u_any.ml \
# Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_point_a.ml \
# Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_triangle_isoright.ml \
# Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_segment_s.ml \
# Figure_symbol_subtree_by_figure_context_databox_tag_provider_u_point_a_trace.ml \
   
EXTRACTORS_U_ML := \
Figure_any_category_by_sole_index_extractor_u_segment_s.ml \
Son_figure_tag_list_by_father_figure_tag_provider_u_segment_s.ml \
Figure_tag_subtree_by_figure_tag_provider_u_any.ml \
  
INTERFACES_U_ML := \
Figure_tag_all_list_by_database_name_n_databox_name_provider_u_point_a.ml \
Figure_tag_all_list_by_figure_context_databox_tag_provider_u_point_a.ml \
 
FENCE_U_ML := \
Figure_fence_point_tag_list_by_figure_tag_provider_u_segment_s.ml \

UNITARY_TESTS_FILES_ML := \
Figure_tag_tree_by_database_name_n_databox_name_provider_u_point_a.ml \
# $(CONTEXT_TAGS_TUPLE_V_MLI) \
# $(SUBTREES_U_ML) \
# $(TREES_U_ML) \
# $(FENCE_U_ML) \
# $(EXTRACTORS_U_ML) \
#$(CONTEXT_U_ML) \
 
# Figure_point_tag_fence_by_figure_tag_provider_u.ml \
# Figure_symbol_by_target_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_dependency_list_by_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_dependency_list_by_input_variable_name_provider_u_point_print.ml \
# Figure_symbol_dependency_list_by_input_variable_name_provider_u_segment_length.ml \
# Figure_symbol_dependency_list_list_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_from_database_db1_database_tag_translator_u_any.ml \
# Figure_symbol_in_database_by_external_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_subtree_by_external_input_variable_name_provider_u_point_homothety.ml \
# Figure_symbol_subtree_by_external_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_subtree_by_input_fullnameoffile_provider_u_point_homothety.ml \
# Figure_symbol_subtree_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_subtree_by_input_fullnameoffile_provider_u_point_print.ml \
# Figure_symbol_subtree_by_input_variable_name_provider_u_point_homothety.ml \
# Figure_symbol_subtree_by_target_input_variable_name_provider_u_point_homothety.ml \
# Figure_symbol_subtree_by_target_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_symbol_tree_by_database_db1_database_tag_provider_u_any.ml \
# Figure_symbol_tree_by_database_db1_database_tag_provider_u_point_print.ml \
# Figure_symbol_tree_by_database_name_provider_u_point_homothety.ml \
# Figure_tag_all_list_by_database_name_provider_u_point_homothety_n_translation.ml \
# Figure_tag_all_list_by_figure_createdby_tag_provider_u_point_homothety_n_translation.ml \
# Figure_tag_all_list_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
# Figure_tag_by_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_tag_by_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_tag_by_input_variable_name_provider_u_point_print.ml \
# Figure_tag_in_database_by_external_input_variable_name_provider_u_point_homothety.ml \
# Figure_tag_in_database_by_external_input_variable_name_provider_u_point_homothety_n_translation.ml \
# Figure_tag_tree_by_database_name_provider_u_point_homothety.ml \
# Figure_tag_tree_by_figure_createdby_tag_provider_u_point_homothety.ml \
# Figure_tag_tree_by_figure_createdby_tag_provider_u_point_homothety_n_translation.ml \
# Figure_tag_tree_by_input_fullnameoffile_provider_u_point_homothety.ml \
# Figure_tag_tree_by_input_fullnameoffile_provider_u_point_homothety_n_translation.ml \
# Figure_tag_tree_by_input_variable_name_provider_u_point_homothety.ml \

# Figure_tag_subtree_by_figure_database_tag_provider_u_any.ml \
# Figure_tag_tree_by_figure_database_tag_provider_u_any.ml \
# Figure_tag_all_list_by_figure_database_tag_provider_u_any.ml \
 
