LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1FIGURE_LEXER_DIR) \
	$(DB1FIGURE_SYMBOLS_DIR) \
	$(DB1FIGURE_PARSER_DIR) \
	$(DB1FIGURE_TAGS_DIR) \
	$(DB1FIGURE_BUILDER_TREES_DIR) \
	$(ELEMENTARYSET_SYMBOLS_DIR) \
	$(ELEMENTARYSET_TAGS_DIR) \
	$(ELEMENTARYSET_DATABASES_DIR) \
	$(FIGURESET_SYMBOLS_DIR) \
	$(FIGURESET_TAGS_DIR) \
	$(FIGURESET_DATABASES_DIR) \
 