#!/bin/bash

# The sub-directories where we run a configure script.
SUB_DIRECTORIES="chemicalset_databases chemicalset_formulas chemicalset_interfaces chemicalset_marks chemicalset_symbols chemicalset_tags chemicalset_values "

# The directory where we just configure .depend and .depend-rebuild.
CURRENT_AND_TEST=". unitary_tests"

# created by /code/sources/ocaml_top/setup/utilities/do_configure_local_for_any_set.sh > configure_local
