LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(QUANTUM_DIR) \
	$(CONTEXTSET_DIR) \
	$(DB1POINTSDATASET_LEXER_DIR) \
	$(DB1POINTSDATASET_SYMBOLS_DIR) \
	$(DB1POINTSDATASET_PARSER_DIR) \
	$(DB1POINTSDATASET_TAGS_DIR) \
	$(DB1POINTSDATASET_BUILDER_TREES_DIR) \
	$(NWCHEMDATASET_SYMBOLS_DIR) \
	$(NWCHEMDATASET_TAGS_DIR) \
	$(NWCHEMDATASET_LEXER_DIR) \
	$(NWCHEMDATASET_PARSER_DIR) \
	$(NWCHEMDATASET_BUILDER_TREES_DIR) \
	$(ELEMENTARYSET_SYMBOLS_DIR) \
	$(ELEMENTARYSET_TAGS_DIR) \
	$(ELEMENTARYSET_BUILDER_TREES_DIR) \
   