INCLUDED_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FIGURESET_SYMBOLS_DIR) \
	$(FIGURESET_TAGS_DIR) \
	$(FIGURESET_CONTAINERS_DIR) \
	$(FIGURESET_INTERFACES_DIR) \
        $(FIGURESET_DATABASES_DIR) \
        $(FIGURESET_INTERFACES_DIR) \
        $(FIGURESET_VALUES_DIR) \
        $(FIGURESET_PROPERTIES_DIR) \
 


