REGISTERS_V_MLI := \
Localinput_set_fence_variable_kind_symbol_by_basicname_variable_n_basicname_inputbox_register_v.mli \
Localinput_set_fence_variable_name_symbol_by_basicname_variable_n_basicname_inputbox_register_v.mli \
  
PARSER_TOOLS_V_MLI := \
Localinput_parser_tools_v.mli \
 
LOCALINPUT_FENCE_VARIABLE_V_MLI := \
Localinput_set_fence_variable_kind_symbol_by_localinput_lexer_variable_kind_symbol_provider_v.mli \
Localinput_as_set_fence_variable_kind_symbol_by_localinput_lexer_variable_kind_symbol_provider_v.mli \
Localinput_set_fence_variable_name_symbol_by_localinput_lexer_variable_kind_symbol_provider_v.mli \
Localinput_set_fence_variable_name_symbol_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
Localinput_set_fence_variable_kind_symbol_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
Localinput_as_set_fence_variable_name_symbol_by_basicname_variable_n_basicname_inputbox_provider_v.mli \
# Localinput_parser_variable_name_tools_v.mli \
# Localinput_parser_structure_v.mli \
  
PARSER_V_MLI := \
Localinput_parser_cell_leaf_by_localinput_lexeme_cell_doublet_provider_v.mli \
Localinput_parser_cell_leaf_n_remainder_lexeme_sublist_by_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_end_leaf_n_remainder_lexeme_sublist_by_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_variable_name_leaf_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_variable_name_entity_implicit_leaf_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
 \
Localinput_parser_list_variable_name_external_subtree_n_remainder_lexeme_sublist_by_variable_name_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_list_variable_type_subtree_n_remainder_lexeme_sublist_by_variable_name_n_localinput_lexeme_rightlist_provider_v.mli \
 \
Localinput_parser_box_units_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_box_type_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
 \
Localinput_parser_block_cofactor_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_handle_cofactor_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
 \
Localinput_parser_block_print_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_block_variable_kind_subtree_n_localinput_symbol_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_handle_variable_kind_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
 \
Localinput_parser_block_define_subtree_n_remainder_lexeme_sublist_by_basicname_inputbox_n_localinput_lexeme_rightlist_provider_v.mli \
Localinput_parser_handle_command_subtree_by_basicname_inputbox_n_localinput_lexer_command_symbol_provider_v.mli \
 \
Localinput_parser_tree_by_basicname_inputbox_provider_v.mli \
 
FILES_MLI := \
$(REGISTERS_V_MLI) \
$(PARSER_TOOLS_V_MLI) \
$(LOCALINPUT_FENCE_VARIABLE_V_MLI) \
$(PARSER_V_MLI) \
 
# Localinput_parser_cell_leaf_n_localinput_lexer_remainder_by_localinput_lexer_cell_headed_list_provider_v.mli \
# Localinput_parser_block_variable_subtree_n_localinput_lexer_remainder_by_variable_kind_localinput_lexer_block_variable_headed_list_provider_v.mli \
# Localinput_parser_handle_command_define_subtree_by_localinput_lexer_handle_command_define_provider_v.mli \
# Localinput_parser_handle_command_subtree_list_by_basicname_inputbox_n_localinput_lexeme_sublist_provider_v.mli \
