(** {6 Typing} *)

type camlline_for_symbol_uno_son_value =
  | Camlline_for_symbol_uno_son_bare_value of Camlline_for_symbol_uno_son_bare_value_t.camlline_for_symbol_uno_son_bare_value
  | Camlline_for_symbol_uno_son_ofstring_value of Camlline_for_symbol_uno_son_ofstring_value_t.camlline_for_symbol_uno_son_ofstring_value
  | Camlline_for_symbol_uno_son_notleaf_value of Camlline_for_symbol_uno_son_notleaf_value_t.camlline_for_symbol_uno_son_notleaf_value
;;
