
type camlline_constant_value = 
  | Camlline_constant_function_value of Camlline_constant_function_value_t.camlline_constant_function_value
  | Camlline_constant_pervasive_value of Camlline_constant_pervasive_value_t.camlline_constant_pervasive_value
;;
