type camlline_for_tag_datastructure_camltype_value =
  | Camlline_for_tag_datastructure_camltype_uno_value of Camlline_for_tag_datastructure_camltype_uno_value_t.camlline_for_tag_datastructure_camltype_uno_value
  | Camlline_for_tag_datastructure_camltype_duo_value of Camlline_for_tag_datastructure_camltype_duo_value_t.camlline_for_tag_datastructure_camltype_duo_value
;;
