type camlline_for_formula_trio_value =
  | Camlline_for_formula_trio_son_top_builder_value of Camlline_for_formula_trio_son_top_builder_value_t.camlline_for_formula_trio_son_top_builder_value
  | Camlline_for_formula_trio_son_top_data_value of Camlline_for_formula_trio_son_top_data_value_t.camlline_for_formula_trio_son_top_data_value
  | Camlline_for_formula_trio_top_builder_data_value of Camlline_for_formula_trio_top_builder_data_value_t.camlline_for_formula_trio_top_builder_data_value
  | Camlline_for_formula_trio_top_main_builder_value of Camlline_for_formula_trio_top_main_builder_value_t.camlline_for_formula_trio_top_main_builder_value
;;

