type camlline_for_tag_datastructure_value =
  | Camlline_for_tag_datastructure_camltype_value of Camlline_for_tag_datastructure_camltype_value_t.camlline_for_tag_datastructure_camltype_value
  | Camlline_for_tag_datastructure_function_value of Camlline_for_tag_datastructure_function_value_t.camlline_for_tag_datastructure_function_value
;;

