type camlline_for_tag_datastructure_function_make_value =
  | Camlline_for_tag_datastructure_function_make_uno_value of Camlline_for_tag_datastructure_function_make_uno_value_t.camlline_for_tag_datastructure_function_make_uno_value
  | Camlline_for_tag_datastructure_function_make_duo_value of Camlline_for_tag_datastructure_function_make_duo_value_t.camlline_for_tag_datastructure_function_make_duo_value
  | Camlline_for_tag_datastructure_function_make_trio_value of Camlline_for_tag_datastructure_function_make_trio_value_t.camlline_for_tag_datastructure_function_make_trio_value
;;

