type camlline_for_formula_uno_value =
  | Camlline_for_formula_uno_builder_value of Camlline_for_formula_uno_builder_value_t.camlline_for_formula_uno_builder_value
  | Camlline_for_formula_uno_data_value of Camlline_for_formula_uno_data_value_t.camlline_for_formula_uno_data_value
  | Camlline_for_formula_uno_main_value of Camlline_for_formula_uno_main_value_t.camlline_for_formula_uno_main_value
  | Camlline_for_formula_uno_son_value of Camlline_for_formula_uno_son_value_t.camlline_for_formula_uno_son_value
  | Camlline_for_formula_uno_top_value of Camlline_for_formula_uno_top_value_t.camlline_for_formula_uno_top_value
;;
