
type camlline_for_tag_datastructure_function_value =
  | Camlline_for_tag_datastructure_function_iter_value of Camlline_for_tag_datastructure_function_iter_value_t.camlline_for_tag_datastructure_function_iter_value
  | Camlline_for_tag_datastructure_function_make_value of Camlline_for_tag_datastructure_function_make_value_t.camlline_for_tag_datastructure_function_make_value
  | Camlline_for_tag_datastructure_function_name of string
;;
