type camlparagraph_for_symbol_let_value =
  | Camlparagraph_for_symbol_let_argument_value of Camlparagraph_for_symbol_let_argument_value_t.camlparagraph_for_symbol_let_argument_value
  | Camlparagraph_for_symbol_let_abbreviate_value of Camlparagraph_for_symbol_let_abbreviate_value_t.camlparagraph_for_symbol_let_abbreviate_value
  | Camlparagraph_for_symbol_let_match_value of Camlparagraph_for_symbol_let_match_value_t.camlparagraph_for_symbol_let_match_value
  | Camlparagraph_for_symbol_let_mixed_value of Camlparagraph_for_symbol_let_mixed_value_t.camlparagraph_for_symbol_let_mixed_value
;;
