type camlline_for_formula_duo_value =
  | Camlline_for_formula_duo_builder_data_value of Camlline_for_formula_duo_builder_data_value_t.camlline_for_formula_duo_builder_data_value
  | Camlline_for_formula_duo_localset_builder_value of Camlline_for_formula_duo_localset_builder_value_t.camlline_for_formula_duo_localset_builder_value
  | Camlline_for_formula_duo_localset_data_value of Camlline_for_formula_duo_localset_data_value_t.camlline_for_formula_duo_localset_data_value
  | Camlline_for_formula_duo_main_builder_value of Camlline_for_formula_duo_main_builder_value_t.camlline_for_formula_duo_main_builder_value
  | Camlline_for_formula_duo_main_data_value of Camlline_for_formula_duo_main_data_value_t.camlline_for_formula_duo_main_data_value
  | Camlline_for_formula_duo_son_builder_value of Camlline_for_formula_duo_son_builder_value_t.camlline_for_formula_duo_son_builder_value
  | Camlline_for_formula_duo_son_data_value of Camlline_for_formula_duo_son_data_value_t.camlline_for_formula_duo_son_data_value
  | Camlline_for_formula_duo_son_main_value of Camlline_for_formula_duo_son_main_value_t.camlline_for_formula_duo_son_main_value
  | Camlline_for_formula_duo_son_top_value of Camlline_for_formula_duo_son_top_value_t.camlline_for_formula_duo_son_top_value
  | Camlline_for_formula_duo_top_builder_value of Camlline_for_formula_duo_top_builder_value_t.camlline_for_formula_duo_top_builder_value
  | Camlline_for_formula_duo_top_data_value of Camlline_for_formula_duo_top_data_value_t.camlline_for_formula_duo_top_data_value
  | Camlline_for_formula_duo_top_main_value of Camlline_for_formula_duo_top_main_value_t.camlline_for_formula_duo_top_main_value
;;
