type camlline_for_formula_datastructure_value =
  | Camlline_for_formula_datastructure_uno_value of Camlline_for_formula_datastructure_uno_value_t.camlline_for_formula_datastructure_uno_value
  | Camlline_for_formula_datastructure_duo_value of Camlline_for_formula_datastructure_duo_value_t.camlline_for_formula_datastructure_duo_value
  | Camlline_for_formula_datastructure_trio_value of Camlline_for_formula_datastructure_trio_value_t.camlline_for_formula_datastructure_trio_value
;;


