type camlline_constant_function_value =
  | Let_count_equal_zero of string
  | Let_count_increment_in of string
  | Let_documentation_unit_equal of string
  | Let_longname_equal_function of string
  | Let_make_argument_equal_function of string
  | Let_make_equal_function of string
  | Let_make_equal_tag_vdot_make_double_semicolon of string
  | Let_make_nam_s_equal of string
  | Let_make_of_topson_bare_nam_equal of string
  | Let_make_of_topson_notleaf_nam_s_equal of string
  | Let_make_of_topson_ofstring_nam_s_equal of string
  | Let_map_equal_function of string
  | Let_nam_cod_equal of string
  | Let_nam_low_equal_string_lowercase_nam_in of string
  | Let_name_equal_function of string
  | Let_name_of_topson_bare_equal_function of string
  | Let_name_of_topson_notleaf_equal_function of string
  | Let_name_of_topson_ofstring_equal_function of string
  | Let_print_ppf_equal_function of string
  | Let_print_ppf_str_equal of string
  | Let_string_off_equal_function of string
  | Let_string_off_of_topson_bare_equal_function of string
  | Let_string_off_of_topson_notleaf_equal_function of string
  | Let_string_off_of_topson_ofstring_equal_function of string
  | Let_symbol_of_formula_equal_function of string
  | Match_nam_low_with of string
  | Pipe_print_fatal_error_make_4_lines of string
  | Pipe_underscore_arrow of string
  | Pipe_underscore_arrow_false of string
  | Pipe_underscore_arrow_true of string
  | Double_quote_example of string
  | Double_quote_how_is_it_done of string
  | Double_quote_needed of string
  | Double_quote_needs of string
  | Double_quote_what_is_it of string
  | Map of string
  | Sole_index_vdot_son_sole_index_list_of_int_of_length_of_sole_index of string
  | Try_make_of_topson_bare_nam of string
  | Try_make_of_topson_notleaf_nam_s of string
  | Try_make_of_topson_ofstring_nam_s of string
;;
