CAMLLINE_T_MLI := \
   Camlline_for_tag_trio_value_t.mli \
    Camlline_for_tag_duo_current_top_value_t.mli \
   Camlline_for_tag_duo_value_t.mli \
    Camlline_for_tag_uno_top_value_t.mli \
    Camlline_for_tag_uno_camltype_value_t.mli \
   Camlline_for_tag_uno_value_t.mli \
      Camlline_for_tag_datastructure_function_make_trio_value_t.mli \
      Camlline_for_tag_datastructure_function_make_duo_value_t.mli \
      Camlline_for_tag_datastructure_function_make_uno_value_t.mli \
     Camlline_for_tag_datastructure_function_make_value_t.mli \
     Camlline_for_tag_datastructure_function_iter_value_t.mli \
    Camlline_for_tag_datastructure_function_value_t.mli \
     Camlline_for_tag_datastructure_camltype_duo_value_t.mli \
     Camlline_for_tag_datastructure_camltype_uno_value_t.mli \
    Camlline_for_tag_datastructure_camltype_value_t.mli \
   Camlline_for_tag_datastructure_value_t.mli \
  Camlline_for_tag_value_t.mli \
    Camlline_for_symbol_uno_current_value_t.mli \
     Camlline_for_symbol_uno_son_notleaf_value_t.mli \
     Camlline_for_symbol_uno_son_ofstring_value_t.mli \
     Camlline_for_symbol_uno_son_bare_value_t.mli \
    Camlline_for_symbol_uno_son_value_t.mli \
    Camlline_for_symbol_uno_top_value_t.mli \
    Camlline_for_symbol_uno_builder_value_t.mli \
   Camlline_for_symbol_uno_value_t.mli \
     Camlline_for_symbol_duo_son_top_ofstring_value_t.mli \
     Camlline_for_symbol_duo_son_top_notleaf_value_t.mli \
     Camlline_for_symbol_duo_son_top_bare_value_t.mli \
    Camlline_for_symbol_duo_son_top_value_t.mli \
    Camlline_for_symbol_duo_current_top_value_t.mli \
   Camlline_for_symbol_duo_value_t.mli \
  Camlline_for_symbol_value_t.mli \
    Camlline_for_formula_uno_top_value_t.mli \
    Camlline_for_formula_uno_son_value_t.mli \
    Camlline_for_formula_uno_data_value_t.mli \
    Camlline_for_formula_uno_main_value_t.mli \
    Camlline_for_formula_uno_builder_value_t.mli \
   Camlline_for_formula_uno_value_t.mli \
    Camlline_for_formula_trio_top_main_builder_value_t.mli \
    Camlline_for_formula_trio_top_builder_data_value_t.mli \
    Camlline_for_formula_trio_son_top_data_value_t.mli \
    Camlline_for_formula_trio_son_top_builder_value_t.mli \
   Camlline_for_formula_trio_value_t.mli \
    Camlline_for_formula_duo_top_main_value_t.mli \
    Camlline_for_formula_duo_top_data_value_t.mli \
    Camlline_for_formula_duo_top_builder_value_t.mli \
    Camlline_for_formula_duo_son_top_value_t.mli \
    Camlline_for_formula_duo_son_main_value_t.mli \
    Camlline_for_formula_duo_son_data_value_t.mli \
    Camlline_for_formula_duo_son_builder_value_t.mli \
    Camlline_for_formula_duo_main_data_value_t.mli \
    Camlline_for_formula_duo_main_builder_value_t.mli \
    Camlline_for_formula_duo_localset_builder_value_t.mli \
    Camlline_for_formula_duo_localset_data_value_t.mli \
    Camlline_for_formula_duo_builder_data_value_t.mli \
   Camlline_for_formula_duo_value_t.mli \
    Camlline_for_formula_datastructure_trio_value_t.mli \
    Camlline_for_formula_datastructure_duo_value_t.mli \
    Camlline_for_formula_datastructure_uno_value_t.mli \
   Camlline_for_formula_datastructure_value_t.mli \
  Camlline_for_formula_value_t.mli \
    Camlline_for_any_trio_current_son_top_value_t.mli \
   Camlline_for_any_trio_value_t.mli \
    Camlline_for_any_uno_top_value_t.mli \
    Camlline_for_any_uno_son_value_t.mli \
     Camlline_for_any_uno_camltype_top_value_t.mli \
     Camlline_for_any_uno_camltype_son_ofstring_value_t.mli \
     Camlline_for_any_uno_camltype_son_notleaf_value_t.mli \
     Camlline_for_any_uno_camltype_son_bare_value_t.mli \
    Camlline_for_any_uno_camltype_value_t.mli \
    Camlline_for_any_uno_camlfile_value_t.mli \
   Camlline_for_any_uno_value_t.mli \
    Camlline_for_any_duo_top_main_value_t.mli \
    Camlline_for_any_duo_son_top_notleaf_value_t.mli \
    Camlline_for_any_duo_son_top_ofstring_value_t.mli \
    Camlline_for_any_duo_son_top_bare_value_t.mli \
    Camlline_for_any_duo_datastructure_value_t.mli \
    Camlline_for_any_duo_current_top_value_t.mli \
    Camlline_for_any_duo_current_son_value_t.mli \
   Camlline_for_any_duo_value_t.mli \
  Camlline_for_any_value_t.mli \
   Camlline_constant_pervasive_value_t.mli \
   Camlline_constant_function_value_t.mli \
  Camlline_constant_value_t.mli \
 Camlline_value_t.mli \

