SECTION_T_MLI := \
    Section_for_symbol_footer_top_value_t.mli \
   Section_for_symbol_footer_value_t.mli \
    Section_for_symbol_body_top_value_t.mli \
    Section_for_symbol_body_son_top_value_t.mli \
     Section_for_symbol_body_son_ofstring_value_t.mli \
     Section_for_symbol_body_son_bare_value_t.mli \
    Section_for_symbol_body_son_value_t.mli \
    Section_for_symbol_body_current_son_top_value_t.mli \
   Section_for_symbol_body_value_t.mli \
    Section_for_symbol_header_son_top_value_t.mli \
    Section_for_symbol_header_son_value_t.mli \
    Section_for_symbol_header_current_top_value_t.mli \
    Section_for_symbol_header_current_son_top_value_t.mli \
    Section_for_symbol_header_constant_value_t.mli \
   Section_for_symbol_header_value_t.mli \
  Section_for_symbol_value_t.mli \
    Section_for_formula_header_top_main_value_t.mli \
    Section_for_formula_header_top_data_value_t.mli \
    Section_for_formula_header_top_builder_value_t.mli \
    Section_for_formula_header_constant_value_t.mli \
   Section_for_formula_header_value_t.mli \
    Section_for_formula_body_top_main_data_value_t.mli \
    Section_for_formula_body_top_main_builder_value_t.mli \
    Section_for_formula_body_top_data_value_t.mli \
    Section_for_formula_body_top_builder_data_value_t.mli \
    Section_for_formula_body_top_builder_value_t.mli \
    Section_for_formula_body_top_value_t.mli \
    Section_for_formula_body_son_top_main_builder_value_t.mli \
    Section_for_formula_body_son_top_main_value_t.mli \
    Section_for_formula_body_son_top_data_value_t.mli \
    Section_for_formula_body_son_top_builder_value_t.mli \
    Section_for_formula_body_son_top_value_t.mli \
    Section_for_formula_body_son_builder_value_t.mli \
    Section_for_formula_body_localset_builder_value_t.mli \
    Section_for_formula_body_localset_data_value_t.mli \
    Section_for_formula_body_builder_data_value_t.mli \
   Section_for_formula_body_value_t.mli \
  Section_for_formula_value_t.mli \
   Section_for_any_footer_value_t.mli \
    Section_for_any_header_top_value_t.mli \
    Section_for_any_header_constant_value_t.mli \
   Section_for_any_header_value_t.mli \
    Section_for_any_body_top_main_value_t.mli \
    Section_for_any_body_top_value_t.mli \
    Section_for_any_body_son_value_t.mli \
   Section_for_any_body_value_t.mli \
  Section_for_any_value_t.mli \
 Section_value_t.mli \

