type group_for_formula_body_son_top_builder_value =
  | Builder_tag_list_topson_pattern_bare_for_formula of Camlline_value_t.camlline_value list
  | Builder_tag_list_topson_pattern_notleaf_for_formula of Camlline_value_t.camlline_value list
  | Builder_tag_list_topson_pattern_ofstring_for_formula of Camlline_value_t.camlline_value list
;;
