type group_for_formula_value =
  | Group_for_formula_body_value of Group_for_formula_body_value_t.group_for_formula_body_value
  | Group_for_formula_header_value of Group_for_formula_header_value_t.group_for_formula_header_value
;;
