type group_for_formula_header_value =
  | Group_for_formula_header_constant_value of Group_for_formula_header_constant_value_t.group_for_formula_header_constant_value
  | Group_for_formula_header_top_builder_value of Group_for_formula_header_top_builder_value_t.group_for_formula_header_top_builder_value
  | Group_for_formula_header_top_data_value of Group_for_formula_header_top_data_value_t.group_for_formula_header_top_data_value
  | Group_for_formula_header_top_main_value of Group_for_formula_header_top_main_value_t.group_for_formula_header_top_main_value
;;

