type group_for_formula_body_son_value =
  | Group_for_formula_body_son_builder_value of Group_for_formula_body_son_builder_value_t.group_for_formula_body_son_builder_value
  | Group_for_formula_body_son_top_value of Group_for_formula_body_son_top_value_t.group_for_formula_body_son_top_value
  | Group_for_formula_body_son_top_builder_value of Group_for_formula_body_son_top_builder_value_t.group_for_formula_body_son_top_builder_value

  | Group_for_formula_body_son_top_data_value of Group_for_formula_body_son_top_data_value_t.group_for_formula_body_son_top_data_value

  | Group_for_formula_body_son_top_main_value of Group_for_formula_body_son_top_main_value_t.group_for_formula_body_son_top_main_value
  | Group_for_formula_body_son_top_main_builder_value of Group_for_formula_body_son_top_main_builder_value_t.group_for_formula_body_son_top_main_builder_value
;;
