type group_for_formula_body_top_value =
  | Group_for_formula_body_top_alone_value of Group_for_formula_body_top_alone_value_t.group_for_formula_body_top_alone_value
  | Group_for_formula_body_top_builder_value of Group_for_formula_body_top_builder_value_t.group_for_formula_body_top_builder_value
  | Group_for_formula_body_top_builder_data_value of Group_for_formula_body_top_builder_data_value_t.group_for_formula_body_top_builder_data_value
  | Group_for_formula_body_top_data_value of Group_for_formula_body_top_data_value_t.group_for_formula_body_top_data_value
  | Group_for_formula_body_top_main_value of Group_for_formula_body_top_main_value_t.group_for_formula_body_top_main_value
;;

