type group_for_formula_body_value =
  | Group_for_formula_body_builder_alone_value of Group_for_formula_body_builder_alone_value_t.group_for_formula_body_builder_alone_value
  | Group_for_formula_body_builder_data_value of Group_for_formula_body_builder_data_value_t.group_for_formula_body_builder_data_value
  | Group_for_formula_body_data_alone_value of Group_for_formula_body_data_alone_value_t.group_for_formula_body_data_alone_value
  | Group_for_formula_body_localset_builder_value of Group_for_formula_body_localset_builder_value_t.group_for_formula_body_localset_builder_value
  | Group_for_formula_body_localset_data_value of Group_for_formula_body_localset_data_value_t.group_for_formula_body_localset_data_value
  | Group_for_formula_body_main_builder_value of Group_for_formula_body_main_builder_value_t.group_for_formula_body_main_builder_value
  | Group_for_formula_body_main_data_value of Group_for_formula_body_main_data_value_t.group_for_formula_body_main_data_value
  | Group_for_formula_body_son_value of Group_for_formula_body_son_value_t.group_for_formula_body_son_value
  | Group_for_formula_body_top_value of Group_for_formula_body_top_value_t.group_for_formula_body_top_value
;;

