type item_for_formula_value =
  | Item_for_formula_by_group_topsons_value of Item_for_formula_by_group_topsons_value_t.item_for_formula_by_group_topsons_value
  | Item_for_formula_only_top_value of Item_for_formula_only_top_value_t.item_for_formula_only_top_value
;;
