type section_for_formula_body_value =
  | Section_for_formula_body_builder_data_value of Section_for_formula_body_builder_data_value_t.section_for_formula_body_builder_data_value
  | Section_for_formula_body_localset_builder_value of Section_for_formula_body_localset_builder_value_t.section_for_formula_body_localset_builder_value
  | Section_for_formula_body_localset_data_value of Section_for_formula_body_localset_data_value_t.section_for_formula_body_localset_data_value
  | Section_for_formula_body_son_builder_value of Section_for_formula_body_son_builder_value_t.section_for_formula_body_son_builder_value
  | Section_for_formula_body_son_top_value of Section_for_formula_body_son_top_value_t.section_for_formula_body_son_top_value
  | Section_for_formula_body_son_top_builder_value of Section_for_formula_body_son_top_builder_value_t.section_for_formula_body_son_top_builder_value
  | Section_for_formula_body_son_top_data_value of Section_for_formula_body_son_top_data_value_t.section_for_formula_body_son_top_data_value
  | Section_for_formula_body_son_top_main_value of Section_for_formula_body_son_top_main_value_t.section_for_formula_body_son_top_main_value
  | Section_for_formula_body_son_top_main_builder_value of Section_for_formula_body_son_top_main_builder_value_t.section_for_formula_body_son_top_main_builder_value
  | Section_for_formula_body_top_builder_value of Section_for_formula_body_top_builder_value_t.section_for_formula_body_top_builder_value
  | Section_for_formula_body_top_builder_data_value of Section_for_formula_body_top_builder_data_value_t.section_for_formula_body_top_builder_data_value
  | Section_for_formula_body_top_data_value of Section_for_formula_body_top_data_value_t.section_for_formula_body_top_data_value
  | Section_for_formula_body_top_main_builder_value of Section_for_formula_body_top_main_builder_value_t.section_for_formula_body_top_main_builder_value
  | Section_for_formula_body_top_main_data_value of Section_for_formula_body_top_main_data_value_t.section_for_formula_body_top_main_data_value
  | Section_for_formula_body_top_value of Section_for_formula_body_top_value_t.section_for_formula_body_top_value
;;


