
type section_for_formula_header_value =
  | Section_for_formula_header_constant_value of Section_for_formula_header_constant_value_t.section_for_formula_header_constant_value
  | Section_for_formula_header_top_builder_value of Section_for_formula_header_top_builder_value_t.section_for_formula_header_top_builder_value
  | Section_for_formula_header_top_data_value of Section_for_formula_header_top_data_value_t.section_for_formula_header_top_data_value
  | Section_for_formula_header_top_main_value of Section_for_formula_header_top_main_value_t.section_for_formula_header_top_main_value
;;

