FROM_FILES_V_ML := \
Parameter_tag_by_input_fullnameoffile_n_input_fence_variable_name_entity_string_off_provider_u_any.ml \
Property_application_envelope_u_any.ml \
Property_applications_u_any.ml \
Property_envelope_u_any.ml \
Property_operand_body_envelope_u_any.ml \
Property_operand_body_target_calculated_envelope_u_any.ml \
Property_operand_body_target_created_envelope_u_any.ml \
Property_operand_body_target_envelope_u_any.ml \
Property_operand_body_target_measured_envelope_u_any.ml \
Property_operand_fence_external_envelope_u_any.ml \
Property_operator_fence_creation_envelope_u_any.ml \

FROM_FILES_U_ML := \
Measure_tools_u_skeleton_fence_centered_aopef_hes11_print.ml \
Operator_symbol_by_input_fence_variable_name_entity_string_off_provider_u_skeleton_fence_centered_aopef_hes11_copy.ml \
Operator_tag_by_input_fence_variable_name_entity_string_off_provider_u_skeleton_fence_centered_aopef_hes11_copy.ml \
Property_set_body_operand_external_envelope_by_property_operand_external_tag_provider_u_skeleton_fence_centered_aopef_hes11_print.ml \
Property_set_body_operand_external_envelope_u_skeleton_fence_centered_aopef_hes11_copy.ml \
Property_set_body_operand_external_envelope_u_skeleton_fence_centered_aopef_hes11_print.ml \
Property_set_body_operand_external_value_by_property_operand_external_tag_provider_u_skeleton_fence_centered_aopef_hes11_print.ml \
Property_set_body_operand_target_created_envelope_u_point_homothety.ml \
Property_set_body_operand_target_created_envelope_u_point_homothety_n_translation.ml \
Property_set_body_operand_target_created_envelope_u_point_translation.ml \
Property_set_body_operand_target_created_envelope_u_point_translation_s.ml \
Property_set_body_operand_target_created_envelope_u_skeleton_fence_centered_aopef_hes11_copy.ml \
Property_set_body_operand_target_measured_envelope_u_segment_length.ml \
Property_set_body_operand_target_measured_envelope_u_triangle_perimeter.ml \
Property_set_body_target_implicit_unit_envelope_u_coordinate_tuple_print.ml \
Property_set_body_target_implicit_unit_envelope_u_parameter_tuple_print.ml \
Property_set_body_target_implicit_unit_envelope_u_point_homothety.ml \
Property_set_body_target_implicit_unit_envelope_u_point_print.ml \
Property_tag_list_by_input_fullnameoffile_provider_u_coordinate_tuple_print.ml \
Property_unit_envelope_u_coordinate_tuple_print.ml \
Skeleton_tag_by_input_fence_variable_name_entity_string_off_provider_u_skeleton_fence_centered_aopef_hes11_copy.ml \

UNITARY_TESTS_FILES_ML := \
test.ml
