NWCHEMDATA_T_MLI :=  \
    Nwchemdata_set_fence_string_symbol_t.mli \
     Nwchemdata_set_fence_integer_nonnegative_symbol_t.mli \
     Nwchemdata_set_fence_integer_negative_symbol_t.mli \
     Nwchemdata_set_fence_integer_positive_symbol_t.mli \
    Nwchemdata_set_fence_integer_symbol_t.mli \
     Nwchemdata_set_fence_float_nonnegative_symbol_t.mli \
     Nwchemdata_set_fence_float_negative_symbol_t.mli \
     Nwchemdata_set_fence_float_positive_symbol_t.mli \
    Nwchemdata_set_fence_float_symbol_t.mli \
   Nwchemdata_set_fence_symbol_t.mli \
     Nwchemdata_set_body_variable_version_symbol_t.mli \
      Nwchemdata_set_body_variable_shellname_relativistic_symbol_t.mli \
      Nwchemdata_set_body_variable_shellname_usual_symbol_t.mli \
      Nwchemdata_set_body_variable_shellname_extended_symbol_t.mli \
     Nwchemdata_set_body_variable_shellname_symbol_t.mli \
     Nwchemdata_set_body_variable_radialfunction_symbol_t.mli \
     Nwchemdata_set_body_variable_name_symbol_t.mli \
     Nwchemdata_set_body_variable_mendeleievsymbol_symbol_t.mli \
      Nwchemdata_set_body_variable_localname_ecpset_symbol_t.mli \
      Nwchemdata_set_body_variable_localname_dataname_symbol_t.mli \
     Nwchemdata_set_body_variable_localname_symbol_t.mli \
      Nwchemdata_set_body_variable_generalcontraction_shellset_symbol_t.mli \
      Nwchemdata_set_body_variable_generalcontraction_coefficientcolumn_symbol_t.mli \
     Nwchemdata_set_body_variable_generalcontraction_symbol_t.mli \
     Nwchemdata_set_body_variable_exponent_n_coefficient_symbol_t.mli \
     Nwchemdata_set_body_variable_exponent_symbol_t.mli \
     Nwchemdata_set_body_variable_dummy_center_symbol_t.mli \
     Nwchemdata_set_body_variable_databox_name_symbol_t.mli \
     Nwchemdata_set_body_variable_coefficient_symbol_t.mli \
     Nwchemdata_set_body_variable_centername_symbol_t.mli \
      Nwchemdata_set_body_variable_aos_at_c_n_symbol_t.mli \
      Nwchemdata_set_body_variable_aos_at_c_symbol_t.mli \
     Nwchemdata_set_body_variable_aos_symbol_t.mli \
      Nwchemdata_set_body_variable_ao_single_symbol_t.mli \
      Nwchemdata_set_body_variable_ao_contracted_symbol_t.mli \
     Nwchemdata_set_body_variable_ao_symbol_t.mli \
     Nwchemdata_set_body_variable_angularmomentum_symbol_t.mli \
      Nwchemdata_set_body_variable_angularfunction_spherical_symbol_t.mli \
      Nwchemdata_set_body_variable_angularfunction_cartesian_symbol_t.mli \
     Nwchemdata_set_body_variable_angularfunction_symbol_t.mli \
    Nwchemdata_set_body_variable_symbol_t.mli \
      Nwchemdata_set_body_node_shell_expansion_symbol_t.mli \
      Nwchemdata_set_body_node_shell_contraction_symbol_t.mli \
     Nwchemdata_set_body_node_shell_symbol_t.mli \
     Nwchemdata_set_body_node_positiveinteger_n_shellname_symbol_t.mli \
     Nwchemdata_set_body_node_hash_databox_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_oneshell_block_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_onecenter_block_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_numericalvalues_block_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_numericalvalues_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_electronnumber_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_definition_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_block_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_anyshell_block_symbol_t.mli \
      Nwchemdata_set_body_node_ecpset_anycenter_block_symbol_t.mli \
     Nwchemdata_set_body_node_ecpset_symbol_t.mli \
     Nwchemdata_set_body_node_ecpbasis_block_symbol_t.mli \
     Nwchemdata_set_body_node_datanamefile_symbol_t.mli \
     Nwchemdata_set_body_node_comment_reference_block_symbol_t.mli \
     Nwchemdata_set_body_node_comment_block_symbol_t.mli \
     Nwchemdata_set_body_node_center_n_shellname_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_oneshell_block_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_onecenter_block_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_numericalvalues_block_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_numericalvalues_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_definition_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_center_contraction_scheme_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_center_contraction_image_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_block_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_anyshell_block_symbol_t.mli \
      Nwchemdata_set_body_node_aoset_anycenter_block_symbol_t.mli \
     Nwchemdata_set_body_node_aoset_symbol_t.mli \
     Nwchemdata_set_body_node_aocomment_block_symbol_t.mli \
     Nwchemdata_set_body_node_aobasis_block_symbol_t.mli \
    Nwchemdata_set_body_node_symbol_t.mli \
    Nwchemdata_set_body_keyword_symbol_t.mli \
    Nwchemdata_set_body_directive_symbol_t.mli \
   Nwchemdata_set_body_symbol_t.mli \
  Nwchemdata_set_symbol_t.mli \
   Nwchemdata_context_sector_symbol_t.mli \
   Nwchemdata_context_domain_symbol_t.mli \
   Nwchemdata_context_database_symbol_t.mli \
   Nwchemdata_context_databox_symbol_t.mli \
  Nwchemdata_context_symbol_t.mli \
   Nwchemdata_comment_reference_symbol_t.mli \
   Nwchemdata_comment_journalreference_symbol_t.mli \
   Nwchemdata_comment_header_symbol_t.mli \
    Nwchemdata_comment_elementline_many_symbol_t.mli \
    Nwchemdata_comment_elementline_one_symbol_t.mli \
   Nwchemdata_comment_elementline_symbol_t.mli \
   Nwchemdata_comment_dashedline_symbol_t.mli \
   Nwchemdata_comment_dashed_symbol_t.mli \
   Nwchemdata_comment_aoemsl_symbol_t.mli \
    Nwchemdata_comment_authorname_many_symbol_t.mli \
    Nwchemdata_comment_authorname_two_symbol_t.mli \
    Nwchemdata_comment_authorname_one_symbol_t.mli \
   Nwchemdata_comment_authorname_symbol_t.mli \
  Nwchemdata_comment_symbol_t.mli \
 Nwchemdata_symbol_t.mli \
