(** {3 Nwchemdata_set_body_node_symbol_t} *)


(** {6 Typing_for_symbol} *)

type nwchemdata_set_body_node_symbol =
  | Nwchemdata_set_body_node_aobasis_block_symbol of Nwchemdata_set_body_node_aobasis_block_symbol_t.nwchemdata_set_body_node_aobasis_block_symbol
  | Nwchemdata_set_body_node_aocomment_block_symbol of Nwchemdata_set_body_node_aocomment_block_symbol_t.nwchemdata_set_body_node_aocomment_block_symbol
  | Nwchemdata_set_body_node_aoset_symbol of Nwchemdata_set_body_node_aoset_symbol_t.nwchemdata_set_body_node_aoset_symbol
  | Nwchemdata_set_body_node_center_n_shellname_symbol of Nwchemdata_set_body_node_center_n_shellname_symbol_t.nwchemdata_set_body_node_center_n_shellname_symbol
  | Nwchemdata_set_body_node_comment_block_symbol of Nwchemdata_set_body_node_comment_block_symbol_t.nwchemdata_set_body_node_comment_block_symbol
  | Nwchemdata_set_body_node_comment_reference_block_symbol of Nwchemdata_set_body_node_comment_reference_block_symbol_t.nwchemdata_set_body_node_comment_reference_block_symbol
  | Nwchemdata_set_body_node_datanamefile_symbol of Nwchemdata_set_body_node_datanamefile_symbol_t.nwchemdata_set_body_node_datanamefile_symbol
  | Nwchemdata_set_body_node_ecpbasis_block_symbol of Nwchemdata_set_body_node_ecpbasis_block_symbol_t.nwchemdata_set_body_node_ecpbasis_block_symbol
  | Nwchemdata_set_body_node_ecpset_symbol of Nwchemdata_set_body_node_ecpset_symbol_t.nwchemdata_set_body_node_ecpset_symbol
  | Nwchemdata_set_body_node_hash_databox_symbol of Nwchemdata_set_body_node_hash_databox_symbol_t.nwchemdata_set_body_node_hash_databox_symbol
  | Nwchemdata_set_body_node_positiveinteger_n_shellname_symbol of Nwchemdata_set_body_node_positiveinteger_n_shellname_symbol_t.nwchemdata_set_body_node_positiveinteger_n_shellname_symbol
  | Nwchemdata_set_body_node_shell_symbol of Nwchemdata_set_body_node_shell_symbol_t.nwchemdata_set_body_node_shell_symbol
;;


(** Nwchemdata_set_body_node_symbol_t at 17:57:47 on 4 Dec 2016. created by version v2.4 of generator *)



