(** {3 Nwchemdata_set_body_node_ecpset_symbol_t} *)


(** {6 Typing_for_symbol} *)

type nwchemdata_set_body_node_ecpset_symbol =
  | Nwchemdata_set_body_node_ecpset_anycenter_block_symbol of Nwchemdata_set_body_node_ecpset_anycenter_block_symbol_t.nwchemdata_set_body_node_ecpset_anycenter_block_symbol
  | Nwchemdata_set_body_node_ecpset_anyshell_block_symbol of Nwchemdata_set_body_node_ecpset_anyshell_block_symbol_t.nwchemdata_set_body_node_ecpset_anyshell_block_symbol
  | Nwchemdata_set_body_node_ecpset_block_symbol of Nwchemdata_set_body_node_ecpset_block_symbol_t.nwchemdata_set_body_node_ecpset_block_symbol
  | Nwchemdata_set_body_node_ecpset_definition_symbol of Nwchemdata_set_body_node_ecpset_definition_symbol_t.nwchemdata_set_body_node_ecpset_definition_symbol
  | Nwchemdata_set_body_node_ecpset_electronnumber_symbol of Nwchemdata_set_body_node_ecpset_electronnumber_symbol_t.nwchemdata_set_body_node_ecpset_electronnumber_symbol
  | Nwchemdata_set_body_node_ecpset_numericalvalues_symbol of Nwchemdata_set_body_node_ecpset_numericalvalues_symbol_t.nwchemdata_set_body_node_ecpset_numericalvalues_symbol
  | Nwchemdata_set_body_node_ecpset_numericalvalues_block_symbol of Nwchemdata_set_body_node_ecpset_numericalvalues_block_symbol_t.nwchemdata_set_body_node_ecpset_numericalvalues_block_symbol
  | Nwchemdata_set_body_node_ecpset_onecenter_block_symbol of Nwchemdata_set_body_node_ecpset_onecenter_block_symbol_t.nwchemdata_set_body_node_ecpset_onecenter_block_symbol
  | Nwchemdata_set_body_node_ecpset_oneshell_block_symbol of Nwchemdata_set_body_node_ecpset_oneshell_block_symbol_t.nwchemdata_set_body_node_ecpset_oneshell_block_symbol
;;


(** Nwchemdata_set_body_node_ecpset_symbol_t at 17:58:33 on 4 Dec 2016. created by version v2.4 of generator *)



