(** {3 Nwchemdata_set_body_variable_symbol_t} *)


(** {6 Typing_for_symbol} *)

type nwchemdata_set_body_variable_symbol =
  | Nwchemdata_set_body_variable_angularfunction_symbol of Nwchemdata_set_body_variable_angularfunction_symbol_t.nwchemdata_set_body_variable_angularfunction_symbol
  | Nwchemdata_set_body_variable_angularmomentum_symbol of Nwchemdata_set_body_variable_angularmomentum_symbol_t.nwchemdata_set_body_variable_angularmomentum_symbol
  | Nwchemdata_set_body_variable_ao_symbol of Nwchemdata_set_body_variable_ao_symbol_t.nwchemdata_set_body_variable_ao_symbol
  | Nwchemdata_set_body_variable_aos_symbol of Nwchemdata_set_body_variable_aos_symbol_t.nwchemdata_set_body_variable_aos_symbol
  | Nwchemdata_set_body_variable_centername_symbol of Nwchemdata_set_body_variable_centername_symbol_t.nwchemdata_set_body_variable_centername_symbol
  | Nwchemdata_set_body_variable_coefficient_symbol of Nwchemdata_set_body_variable_coefficient_symbol_t.nwchemdata_set_body_variable_coefficient_symbol
  | Nwchemdata_set_body_variable_databox_name_symbol of Nwchemdata_set_body_variable_databox_name_symbol_t.nwchemdata_set_body_variable_databox_name_symbol
  | Nwchemdata_set_body_variable_dummy_center_symbol of Nwchemdata_set_body_variable_dummy_center_symbol_t.nwchemdata_set_body_variable_dummy_center_symbol
  | Nwchemdata_set_body_variable_exponent_symbol of Nwchemdata_set_body_variable_exponent_symbol_t.nwchemdata_set_body_variable_exponent_symbol
  | Nwchemdata_set_body_variable_exponent_n_coefficient_symbol of Nwchemdata_set_body_variable_exponent_n_coefficient_symbol_t.nwchemdata_set_body_variable_exponent_n_coefficient_symbol
  | Nwchemdata_set_body_variable_generalcontraction_symbol of Nwchemdata_set_body_variable_generalcontraction_symbol_t.nwchemdata_set_body_variable_generalcontraction_symbol
  | Nwchemdata_set_body_variable_localname_symbol of Nwchemdata_set_body_variable_localname_symbol_t.nwchemdata_set_body_variable_localname_symbol
  | Nwchemdata_set_body_variable_mendeleievsymbol_symbol of Nwchemdata_set_body_variable_mendeleievsymbol_symbol_t.nwchemdata_set_body_variable_mendeleievsymbol_symbol
  | Nwchemdata_set_body_variable_name_symbol of Nwchemdata_set_body_variable_name_symbol_t.nwchemdata_set_body_variable_name_symbol
  | Nwchemdata_set_body_variable_radialfunction_symbol of Nwchemdata_set_body_variable_radialfunction_symbol_t.nwchemdata_set_body_variable_radialfunction_symbol
  | Nwchemdata_set_body_variable_shellname_symbol of Nwchemdata_set_body_variable_shellname_symbol_t.nwchemdata_set_body_variable_shellname_symbol
  | Nwchemdata_set_body_variable_version_symbol of Nwchemdata_set_body_variable_version_symbol_t.nwchemdata_set_body_variable_version_symbol
;;


(** Nwchemdata_set_body_variable_symbol_t at 17:59:37 on 4 Dec 2016. created by version v2.4 of generator *)



