(** {3 Nwchemdata_set_body_node_aoset_symbol_t} *)


(** {6 Typing_for_symbol} *)

type nwchemdata_set_body_node_aoset_symbol =
  | Nwchemdata_set_body_node_aoset_anycenter_block_symbol of Nwchemdata_set_body_node_aoset_anycenter_block_symbol_t.nwchemdata_set_body_node_aoset_anycenter_block_symbol
  | Nwchemdata_set_body_node_aoset_anyshell_block_symbol of Nwchemdata_set_body_node_aoset_anyshell_block_symbol_t.nwchemdata_set_body_node_aoset_anyshell_block_symbol
  | Nwchemdata_set_body_node_aoset_block_symbol of Nwchemdata_set_body_node_aoset_block_symbol_t.nwchemdata_set_body_node_aoset_block_symbol
  | Nwchemdata_set_body_node_aoset_center_contraction_image_symbol of Nwchemdata_set_body_node_aoset_center_contraction_image_symbol_t.nwchemdata_set_body_node_aoset_center_contraction_image_symbol
  | Nwchemdata_set_body_node_aoset_center_contraction_scheme_symbol of Nwchemdata_set_body_node_aoset_center_contraction_scheme_symbol_t.nwchemdata_set_body_node_aoset_center_contraction_scheme_symbol
  | Nwchemdata_set_body_node_aoset_definition_symbol of Nwchemdata_set_body_node_aoset_definition_symbol_t.nwchemdata_set_body_node_aoset_definition_symbol
  | Nwchemdata_set_body_node_aoset_numericalvalues_symbol of Nwchemdata_set_body_node_aoset_numericalvalues_symbol_t.nwchemdata_set_body_node_aoset_numericalvalues_symbol
  | Nwchemdata_set_body_node_aoset_numericalvalues_block_symbol of Nwchemdata_set_body_node_aoset_numericalvalues_block_symbol_t.nwchemdata_set_body_node_aoset_numericalvalues_block_symbol
  | Nwchemdata_set_body_node_aoset_onecenter_block_symbol of Nwchemdata_set_body_node_aoset_onecenter_block_symbol_t.nwchemdata_set_body_node_aoset_onecenter_block_symbol
  | Nwchemdata_set_body_node_aoset_oneshell_block_symbol of Nwchemdata_set_body_node_aoset_oneshell_block_symbol_t.nwchemdata_set_body_node_aoset_oneshell_block_symbol
;;


(** Nwchemdata_set_body_node_aoset_symbol_t at 17:57:53 on 4 Dec 2016. created by version v2.4 of generator *)



