MUSIC_T_MLI :=  \
    Tag_id3v2_4_specific_tag_t.mli \
    Tag_id3v2_3_specific_tag_t.mli \
   Tag_id3v2_specific_tag_t.mli \
    Tag_id3v2_base_multiple_tag_t.mli \
    Tag_id3v2_base_unique_tag_t.mli \
   Tag_id3v2_base_tag_t.mli \
  Tag_id3v2_tag_t.mli \
   Tag_id3v1_227_tag_t.mli \
   Tag_id3v1_128_tag_t.mli \
  Tag_id3v1_tag_t.mli \
 Tag_id3_tag_t.mli \
 Mp3_layout_tag_tag_t.mli \
  Mp3_header_tag_tag_t.mli \
   Mp3_header_field_elevenbits_tag_t.mli \
   Mp3_header_field_fourbits_tag_t.mli \
   Mp3_header_field_twobits_tag_t.mli \
    Version_tag_t.mli \
   Mp3_header_field_onebit_tag_t.mli \
  Mp3_header_field_tag_t.mli \
 Mp3_header_tag_t.mli \
  Mp3_file_id3v2_tag_t.mli \
  Mp3_file_id3v1_tag_t.mli \
 Mp3_file_tag_t.mli \
 Mp3_elementary_stream_tag_t.mli \
 Mp3_frame_tag_t.mli \
 Mp3_data_tag_t.mli \
Music_tag_t.mli \
