(** {3 Skeleton_set_body_centered_aopefset_symbol_t} *)


(** {6 Typing_for_symbol} *)

type skeleton_set_body_centered_aopefset_symbol =
  | Skeleton_set_body_centered_aopefset_onecenter_symbol of Skeleton_set_body_centered_aopefset_onecenter_symbol_t.skeleton_set_body_centered_aopefset_onecenter_symbol
  | Skeleton_set_body_centered_aopefset_anycenter_symbol of Skeleton_set_body_centered_aopefset_anycenter_symbol_t.skeleton_set_body_centered_aopefset_anycenter_symbol
  | Skeleton_set_body_centered_aopefset_shellsymmetry_symbol of Skeleton_set_body_centered_aopefset_shellsymmetry_symbol_t.skeleton_set_body_centered_aopefset_shellsymmetry_symbol
  | Skeleton_set_body_centered_aopefset_shellordinal_symbol of Skeleton_set_body_centered_aopefset_shellordinal_symbol_t.skeleton_set_body_centered_aopefset_shellordinal_symbol
;;


(** Skeleton_set_body_centered_aopefset_symbol_t at 14:13:13 on 5 Jan 2017. created by version v2.4 of generator *)



