MUSIC_T_MLI :=  \
    Tag_id3v2_4_specific_formula_t.mli \
    Tag_id3v2_3_specific_formula_t.mli \
   Tag_id3v2_specific_formula_t.mli \
    Tag_id3v2_base_multiple_formula_t.mli \
    Tag_id3v2_base_unique_formula_t.mli \
   Tag_id3v2_base_formula_t.mli \
  Tag_id3v2_formula_t.mli \
   Tag_id3v1_227_formula_t.mli \
   Tag_id3v1_128_formula_t.mli \
  Tag_id3v1_formula_t.mli \
 Tag_id3_formula_t.mli \
 Mp3_layout_tag_formula_t.mli \
  Mp3_header_tag_formula_t.mli \
   Mp3_header_field_elevenbits_formula_t.mli \
   Mp3_header_field_fourbits_formula_t.mli \
   Mp3_header_field_twobits_formula_t.mli \
    Version_formula_t.mli \
   Mp3_header_field_onebit_formula_t.mli \
  Mp3_header_field_formula_t.mli \
 Mp3_header_formula_t.mli \
  Mp3_file_id3v2_formula_t.mli \
  Mp3_file_id3v1_formula_t.mli \
 Mp3_file_formula_t.mli \
 Mp3_elementary_stream_formula_t.mli \
 Mp3_frame_formula_t.mli \
 Mp3_data_formula_t.mli \
Music_formula_t.mli \
