WAVEFUNCTION_T_MLI :=  \
   Wavefunction_closure_spin_symbol_t.mli \
    Wavefunction_closure_spatial_orbital_numerical_symbol_t.mli \
    Wavefunction_closure_spatial_orbital_so_symbol_t.mli \
    Wavefunction_closure_spatial_orbital_mo_symbol_t.mli \
   Wavefunction_closure_spatial_orbital_symbol_t.mli \
   Wavefunction_closure_jastrow_factor_symbol_t.mli \
   Wavefunction_closure_coefficient_symbol_t.mli \
  Wavefunction_closure_symbol_t.mli \
   Wavefunction_context_domain_symbol_t.mli \
   Wavefunction_context_createdby_symbol_t.mli \
  Wavefunction_context_symbol_t.mli \
    Wavefunction_body_total_orbital_symbol_t.mli \
    Wavefunction_body_total_manye_symbol_t.mli \
   Wavefunction_body_total_symbol_t.mli \
    Wavefunction_body_spatial_manye_fragment_symbol_t.mli \
     Wavefunction_body_spatial_manye_determinant_bare_symbol_t.mli \
    Wavefunction_body_spatial_manye_determinant_symbol_t.mli \
   Wavefunction_body_spatial_manye_symbol_t.mli \
  Wavefunction_body_symbol_t.mli \
 Wavefunction_symbol_t.mli \
