modify_string.pl Aas_t Molecule_aminoacid_symbol_t *.ml
modify_string.pl Aas_v Molecule_aminoacid_symbol_v *.ml
modify_string.pl Als_v Polypeptide_subunit_symbol_v *.ml
modify_string.pl Brl_v Booted_repeated_list_v *.ml
modify_string.pl Bxs_t Box_symbol_t *.ml
modify_string.pl Csp_v Chain_sequencepdb_v *.ml
modify_string.pl Dbs_t Database_symbol_t *.ml
modify_string.pl Dbs_t Database_symbol_t *.ml
modify_string.pl Dbt_v Doublet_v *.ml
modify_string.pl Eps_t Entrypdb_symbol_t *.ml
modify_string.pl Eps_v Entrypdb_symbol_v *.ml
modify_string.pl Esp_v Entrypdb_symbol_provider_v *.ml
modify_string.pl Lst_v List_v *.ml
modify_string.pl Maos_v Molecule_aminoacid_olc_symbol_v *.ml
modify_string.pl Mas_t Molecule_aminoacid_symbol_t *.ml
modify_string.pl Mas_v Molecule_aminoacid_symbol_v *.ml
modify_string.pl Pls_t Polypeptide_symbol_t *.ml
modify_string.pl Pls_v Polypeptide_symbol_v *.ml
modify_string.pl Prs_t Protein_symbol_t *.ml
modify_string.pl Prs_v Protein_symbol_v *.ml
modify_string.pl Pspp_v Polypeptide_sequence_provider_from_pdb_v *.ml
modify_string.pl Psp_v Polypeptide_sequence_provider_v *.ml
modify_string.pl Psp_v Protein_sequencepdb_v *.ml
modify_string.pl Psq_t Polypeptide_sequence_t *.ml
modify_string.pl Reg_t Register_t *.ml
modify_string.pl Reg_v Register_v *.ml
modify_string.pl Rps_v Residuepdb_symbol_v *.ml
