LIBRARIES_DIRS := \
	$(BASICS_DIR) \
	$(DATASTRUCTURES_DIR) \
	$(FILES_DIR) \
	$(COMMONSET_DIR) \
	$(QUANTUM_DIR) \
	$(CONTEXTSET_DIR) \
	$(NWCHEM_LEXER_DIR) \
	$(NWCHEM_SYMBOLS_DIR) \
	$(NWCHEM_PARSER_DIR) \
	$(NWCHEM_TAGS_DIR) \
	$(NWCHEM_BUILDER_TREES_DIR) \
	$(DB1FIGURE_LEXER_DIR) \
	$(DB1FIGURE_SYMBOLS_DIR) \
	$(DB1FIGURE_PARSER_DIR) \
	$(DB1FIGURE_TAGS_DIR) \
	$(DB1FIGURE_BUILDER_TREES_DIR) \
	$(ELEMENTARYSET_SYMBOLS_DIR) \
	$(ELEMENTARYSET_TAGS_DIR) \
	$(ELEMENTARYSET_DATABASES_DIR) \
	$(SKELETONSET_SYMBOLS_DIR) \
	$(SKELETONSET_TAGS_DIR) \
	$(SKELETONSET_DATABASES_DIR) \
 